import { registerFilesystemHandlers } from "./filesystem";
import { registerInlineCompletionHandlers } from "./inline-completion";
import { registerAtelierConnectorHandlers } from "./atelier-connector";
import { registerBrowserHandlers } from "./browser";
import { registerCraneConnectorHandlers } from "./crane-connector";
import { registerDiagnosticsHandlers } from "./diagnostics";
import { registerJiraConnectorHandlers } from "./jira-connector";
import { registerLocalMcpHandlers } from "./local-mcp";
import { registerEslintHandlers } from "./eslint";
import { registerMartinSyncHandlers } from "./martin-sync";
import { registerLspHandlers } from "./lsp";
import { registerMetricsHandlers } from "./metrics";
import { registerAgentRunHandlers } from "./agent-runs";
import { registerWakeUpHandlers } from "./wake-ups";
import { registerAgentHandlers } from "./agents";
import { registerNotificationHandlers } from "./notifications";
import { registerPersistenceHandlers } from "./persistence";
import { registerRepositoryMemoryHandlers } from "./repository-memory";
import { registerProviderHandlers } from "./provider";
import { registerProviderAccountHandlers } from "./provider-accounts";
import { registerApiConnectionHandlers } from "./api-connections";
import { registerProviderAccountIdentityHandlers } from "./provider-account-identity";
import { registerProviderAccountSetupHandlers } from "./provider-account-setup";
import { registerRunHandlers } from "./runs";
import { registerAutomationHandlers } from "./automations";
import { registerScmHandlers } from "./scm";
import { registerSecretHandlers } from "./secrets";
import { registerSkillsHandlers } from "./skills";
import { registerStorageHandlers } from "./storage";
import { registerTerminalHandlers } from "./terminal";
import { registerTaskControlHandlers } from "./task-control";
import { registerToolingHandlers } from "./tooling";
import { registerTrackerIssuesHandlers } from "./tracker-issues";
import { registerWindowHandlers } from "./window";
import { registerWorkspaceScriptHandlers } from "./workspace-scripts";

export function registerHandlers() {
  registerWindowHandlers();
  registerDiagnosticsHandlers();
  registerProviderHandlers();
  registerProviderAccountHandlers();
  registerApiConnectionHandlers();
  registerProviderAccountIdentityHandlers();
  registerProviderAccountSetupHandlers();
  registerRunHandlers();
  registerAutomationHandlers();
  registerAgentRunHandlers();
  registerWakeUpHandlers();
  registerAgentHandlers();
  registerPersistenceHandlers();
  registerRepositoryMemoryHandlers();
  registerTerminalHandlers();
  registerTaskControlHandlers();
  registerToolingHandlers();
  registerWorkspaceScriptHandlers();
  registerScmHandlers();
  registerFilesystemHandlers();
  registerSkillsHandlers();
  registerLspHandlers();
  registerEslintHandlers();
  registerInlineCompletionHandlers();
  registerMetricsHandlers();
  registerStorageHandlers();
  registerNotificationHandlers();
  registerLocalMcpHandlers();
  registerAtelierConnectorHandlers();
  registerCraneConnectorHandlers();
  registerMartinSyncHandlers();
  registerJiraConnectorHandlers();
  registerTrackerIssuesHandlers();
  registerBrowserHandlers();
  registerSecretHandlers();
}
