import { registerFilesystemHandlers } from "./filesystem";
import { registerInlineCompletionHandlers } from "./inline-completion";
import { registerAtelierConnectorHandlers } from "./atelier-connector";
import { registerBrowserHandlers } from "./browser";
import { registerCraneConnectorHandlers } from "./crane-connector";
import { registerDiagnosticsHandlers } from "./diagnostics";
import { registerLocalMcpHandlers } from "./local-mcp";
import { registerEslintHandlers } from "./eslint";
import { registerMartinSyncHandlers } from "./martin-sync";
import { registerLspHandlers } from "./lsp";
import { registerMetricsHandlers } from "./metrics";
import { registerNotificationHandlers } from "./notifications";
import { registerPersistenceHandlers } from "./persistence";
import { registerProviderHandlers } from "./provider";
import { registerRunHandlers } from "./runs";
import { registerRoutineHandlers } from "./routines";
import { registerScmHandlers } from "./scm";
import { registerSecretHandlers } from "./secrets";
import { registerSkillsHandlers } from "./skills";
import { registerTerminalHandlers } from "./terminal";
import { registerTaskControlHandlers } from "./task-control";
import { registerToolingHandlers } from "./tooling";
import { registerWindowHandlers } from "./window";
import { registerWorkspaceScriptHandlers } from "./workspace-scripts";

export function registerHandlers() {
  registerWindowHandlers();
  registerDiagnosticsHandlers();
  registerProviderHandlers();
  registerRunHandlers();
  registerRoutineHandlers();
  registerPersistenceHandlers();
  registerTerminalHandlers();
  registerTaskControlHandlers();
  registerToolingHandlers();
  registerWorkspaceScriptHandlers();
  registerScmHandlers();
  registerFilesystemHandlers();
  registerSkillsHandlers();
  registerLspHandlers();
  registerEslintHandlers();
  registerInlineCompletionHandlers();
  registerMetricsHandlers();
  registerNotificationHandlers();
  registerLocalMcpHandlers();
  registerAtelierConnectorHandlers();
  registerCraneConnectorHandlers();
  registerMartinSyncHandlers();
  registerBrowserHandlers();
  registerSecretHandlers();
}
