import * as stylex from "@stylexjs/stylex";
import { vars } from "../ads/tokens/tokens.stylex";

/**
 * Projects view and project home. Existing ADS tokens only. The home is one
 * reading column: header, coordinator, lanes (Needs you, Running, Done), then
 * Memory, Library and Settings.
 */
export const projectStyles = stylex.create({
  body: {
    position: "relative",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr)",
    flex: "1 1 auto",
    minHeight: 0,
    borderTopWidth: vars["--ads-border-width-hairline"],
    borderTopStyle: "solid",
    borderTopColor: vars["--ads-color-border-subtle"],
  },
  bodyList: { gridTemplateColumns: "minmax(15rem, 18rem) minmax(0, 1fr)" },
  bodyDock: { gridTemplateColumns: "minmax(0, 1fr) minmax(20rem, 24rem)" },
  bodyListDock: { gridTemplateColumns: "minmax(14rem, 16rem) minmax(0, 1fr) minmax(20rem, 24rem)" },
  dockColumn: { minHeight: 0, minWidth: 0 },
  dockOverlay: {
    position: "absolute",
    insetBlock: 0,
    insetInlineEnd: 0,
    width: "min(24rem, 100%)",
    zIndex: 2,
    boxShadow: vars["--ads-elevation-modal"],
  },
  master: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minHeight: 0,
    overflowY: "auto",
    padding: vars["--ads-space-12"],
    borderInlineEndWidth: vars["--ads-border-width-hairline"],
    borderInlineEndStyle: "solid",
    borderInlineEndColor: vars["--ads-color-border-subtle"],
  },
  card: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    gap: vars["--ads-space-4"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-8"],
    borderRadius: vars["--ads-radius-control"],
    textAlign: "start",
    color: vars["--ads-color-text"],
    backgroundColor: { default: "transparent", ":hover": vars["--ads-color-overlay-hover"] },
    cursor: "pointer",
  },
  cardActive: {
    backgroundColor: { default: vars["--ads-color-selection-fill"], ":hover": vars["--ads-color-selection-fill"] },
  },
  cardTitleRow: { display: "flex", alignItems: "center", gap: vars["--ads-space-8"], minWidth: 0 },
  cardTitle: {
    flex: "1 1 auto",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  masterLabel: {
    margin: 0,
    paddingTop: vars["--ads-space-16"],
    paddingBottom: vars["--ads-space-4"],
    paddingInline: vars["--ads-space-8"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
    color: vars["--ads-color-text-subtle"],
  },
  cardMeta: { fontSize: vars["--ads-font-size-caption"], color: vars["--ads-color-text-muted"] },
  needsCount: {
    flex: "0 0 auto",
    minWidth: 18,
    height: 18,
    paddingInline: 5,
    borderRadius: vars["--ads-radius-full"],
    backgroundColor: vars["--ads-color-warning-soft"],
    color: vars["--ads-color-warning-text"],
    fontSize: vars["--ads-font-size-micro"],
    fontWeight: vars["--ads-font-weight-medium"],
    lineHeight: "18px",
    textAlign: "center",
    fontVariantNumeric: "tabular-nums",
  },
  scroll: { flex: "1 1 auto", minHeight: 0, overflowY: "auto" },
  /** Replaces the project list below the width that shows it. */
  picker: {
    display: "block",
    padding: vars["--ads-space-12"],
    borderBlockEndWidth: vars["--ads-border-width-hairline"],
    borderBlockEndStyle: "solid",
    borderBlockEndColor: vars["--ads-color-border-subtle"],
  },
  home: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-24"],
    width: "100%",
    maxWidth: "56rem",
    marginInline: "auto",
    paddingInline: vars["--ads-space-24"],
    paddingTop: vars["--ads-space-20"],
    paddingBottom: vars["--ads-space-32"],
  },
  heading: { display: "flex", alignItems: "flex-start", gap: vars["--ads-space-12"], minWidth: 0 },
  headingText: { display: "flex", flexDirection: "column", gap: vars["--ads-space-4"], flex: "1 1 auto", minWidth: 0 },
  titleRow: { display: "flex", alignItems: "center", gap: vars["--ads-space-8"], minWidth: 0 },
  title: {
    margin: 0,
    fontSize: vars["--ads-font-size-title"],
    lineHeight: vars["--ads-line-height-title"],
    fontWeight: vars["--ads-font-weight-semibold"],
    color: vars["--ads-color-text"],
    overflowWrap: "anywhere",
  },
  goal: {
    margin: 0,
    fontSize: vars["--ads-font-size-body"],
    lineHeight: vars["--ads-line-height-relaxed"],
    color: vars["--ads-color-text-muted"],
    overflowWrap: "anywhere",
  },
  stats: { display: "flex", flexWrap: "wrap", gap: vars["--ads-space-8"], marginTop: vars["--ads-space-4"] },
  stat: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    height: 24,
    paddingInline: vars["--ads-space-8"],
    borderRadius: vars["--ads-radius-full"],
    backgroundColor: vars["--ads-color-canvas-subtle"],
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text-muted"],
    fontVariantNumeric: "tabular-nums",
  },
  statAttention: { backgroundColor: vars["--ads-color-warning-soft"], color: vars["--ads-color-warning-text"] },
  colorInherit: { color: "inherit" },
  statQuiet: { backgroundColor: "transparent", paddingInline: vars["--ads-space-4"] },
  statStrong: { color: vars["--ads-color-text"], fontWeight: vars["--ads-font-weight-medium"] },
  headingActions: { flex: "0 0 auto", display: "flex", alignItems: "center", gap: vars["--ads-space-4"] },
  coordinator: {
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr) auto",
    alignItems: "start",
    columnGap: vars["--ads-space-12"],
    padding: vars["--ads-space-16"],
    borderRadius: vars["--ads-radius-panel"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface"],
  },
  coordinatorActions: { display: "flex", alignItems: "center", gap: vars["--ads-space-4"] },
  coordinatorText: { display: "flex", flexDirection: "column", gap: vars["--ads-space-4"], minWidth: 0 },
  coordinatorQuote: {
    margin: 0,
    fontSize: vars["--ads-font-size-body"],
    lineHeight: vars["--ads-line-height-relaxed"],
    color: vars["--ads-color-text"],
    overflowWrap: "anywhere",
  },
  coordinatorEmpty: { color: vars["--ads-color-text-muted"] },
  coordinatorMeta: { fontSize: vars["--ads-font-size-caption"], color: vars["--ads-color-text-subtle"] },
  lane: { display: "flex", flexDirection: "column", gap: vars["--ads-space-8"], minWidth: 0 },
  laneHeader: { display: "flex", alignItems: "baseline", gap: vars["--ads-space-8"] },
  laneTitle: {
    margin: 0,
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
    letterSpacing: "0.02em",
    textTransform: "uppercase",
    color: vars["--ads-color-text-subtle"],
  },
  laneCount: { fontSize: vars["--ads-font-size-caption"], color: vars["--ads-color-text-subtle"], fontVariantNumeric: "tabular-nums" },
  rows: {
    display: "flex",
    flexDirection: "column",
    margin: 0,
    padding: 0,
    listStyle: "none",
    containerType: "inline-size",
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-panel"],
    backgroundColor: vars["--ads-color-surface"],
    overflow: "hidden",
  },
  /*
   * Every list row shares one grid — mark, text, stage track, actions — so the
   * tracks and buttons line up down the page, across lanes. Narrow lists drop
   * the track.
   */
  row: {
    display: "grid",
    gridTemplateColumns: {
      default: "20px minmax(0, 1fr) 7.5rem 7rem",
      "@container (max-width: 34rem)": "20px minmax(0, 1fr) auto",
    },
    alignItems: "center",
    columnGap: vars["--ads-space-12"],
    minHeight: 56,
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
    borderTopWidth: { default: vars["--ads-border-width-hairline"], ":first-child": 0 },
    borderTopStyle: "solid",
    borderTopColor: vars["--ads-color-border-subtle"],
  },
  /** Memory and library rows: no track column. */
  rowCompact: { gridTemplateColumns: "20px minmax(0, 1fr) auto", minHeight: 52 },
  linkItem: {
    borderTopWidth: { default: vars["--ads-border-width-hairline"], ":first-child": 0 },
    borderTopStyle: "solid",
    borderTopColor: vars["--ads-color-border-subtle"],
  },
  rowLink: {
    color: "inherit",
    textDecoration: "none",
    backgroundColor: { default: "transparent", ":hover": vars["--ads-color-overlay-hover"] },
  },
  rowMark: { display: "flex", justifyContent: "center" },
  rowText: { display: "flex", flexDirection: "column", gap: 2, minWidth: 0 },
  rowTitle: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
    color: vars["--ads-color-text"],
  },
  rowMeta: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text-muted"],
  },
  rowWaiting: { color: vars["--ads-color-warning-text"] },
  rowAttention: { color: vars["--ads-color-danger-text"] },
  rowActions: { display: "flex", alignItems: "center", gap: vars["--ads-space-4"], justifyContent: "flex-end" },
  /** A proposal has no track yet; its two buttons take the track's column too. */
  rowActionsWide: { gridColumn: { default: "3 / 5", "@container (max-width: 34rem)": "3 / 4" } },
  rowTrack: {
    display: { default: "flex", "@container (max-width: 34rem)": "none" },
    alignItems: "center",
    gap: 2,
    minWidth: 0,
  },
  miniSegment: { flex: "1 1 0", height: 4, borderRadius: vars["--ads-radius-full"], backgroundColor: vars["--ads-color-border"] },
  segDone: { backgroundColor: vars["--ads-color-success"] },
  segActive: { backgroundColor: vars["--ads-color-accent"] },
  segWaiting: { backgroundColor: vars["--ads-color-warning"] },
  segAttention: { backgroundColor: vars["--ads-color-danger"] },
  emptyLane: {
    margin: 0,
    paddingBlock: vars["--ads-space-12"],
    paddingInline: vars["--ads-space-16"],
    borderRadius: vars["--ads-radius-panel"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "dashed",
    borderColor: vars["--ads-color-border"],
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text-muted"],
  },
  tabLabel: { display: "inline-flex", alignItems: "center", gap: 6 },
  tabCount: { color: vars["--ads-color-text-subtle"], fontVariantNumeric: "tabular-nums" },
  tabDot: { width: 6, height: 6, borderRadius: vars["--ads-radius-full"], backgroundColor: vars["--ads-color-warning"] },
  tabPanel: { paddingTop: vars["--ads-space-12"] },
  memoryText: {
    fontSize: vars["--ads-font-size-body"],
    lineHeight: vars["--ads-line-height-normal"],
    color: vars["--ads-color-text"],
    overflowWrap: "anywhere",
  },
  settingRow: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "center",
    columnGap: vars["--ads-space-16"],
    minHeight: 56,
    paddingBlock: vars["--ads-space-12"],
    paddingInline: vars["--ads-space-16"],
    borderTopWidth: { default: vars["--ads-border-width-hairline"], ":first-child": 0 },
    borderTopStyle: "solid",
    borderTopColor: vars["--ads-color-border-subtle"],
  },
  tabStack: { display: "flex", flexDirection: "column", gap: vars["--ads-space-12"] },
  triggerRow: { gridTemplateColumns: "20px minmax(0, 1fr) auto", alignItems: "start", columnGap: vars["--ads-space-12"] },
  triggerIcon: { display: "flex", justifyContent: "center", paddingTop: 3, color: vars["--ads-color-text-subtle"] },
  triggerField: { display: "block", marginTop: vars["--ads-space-8"], maxWidth: "26rem" },
  triggerSelect: { display: "block", width: "12rem" },
  settingHint: { fontSize: vars["--ads-font-size-caption"], lineHeight: vars["--ads-line-height-normal"], color: vars["--ads-color-text-muted"] },
  settingLabel: { fontSize: vars["--ads-font-size-caption"], fontWeight: vars["--ads-font-weight-medium"], color: vars["--ads-color-text"] },
  settingValue: { display: "flex", flexDirection: "column", alignItems: "flex-start", gap: 6, margin: 0 },
  hint: { margin: 0, fontSize: vars["--ads-font-size-caption"], lineHeight: vars["--ads-line-height-normal"], color: vars["--ads-color-text-subtle"] },
  error: { margin: 0, fontSize: vars["--ads-font-size-caption"], color: vars["--ads-color-danger-text"] },
  icon: { width: 14, height: 14, flex: "0 0 auto" },
  iconMuted: { color: vars["--ads-color-text-subtle"] },
  toneDone: { color: vars["--ads-color-success-text"] },
  toneActive: { color: vars["--ads-color-accent"] },
  toneWaiting: { color: vars["--ads-color-warning-text"] },
  toneAttention: { color: vars["--ads-color-danger-text"] },
  empty: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-20"],
    maxWidth: "46rem",
    marginInline: "auto",
    paddingInline: vars["--ads-space-24"],
    paddingTop: "max(2rem, 8vh)",
    paddingBottom: vars["--ads-space-32"],
  },
  emptyIntro: { display: "flex", flexDirection: "column", alignItems: "flex-start", gap: vars["--ads-space-12"] },
  emptyTitle: { margin: 0, fontSize: vars["--ads-font-size-title"], fontWeight: vars["--ads-font-weight-semibold"] },
  emptyText: { margin: 0, fontSize: vars["--ads-font-size-body"], lineHeight: vars["--ads-line-height-relaxed"], color: vars["--ads-color-text-muted"] },
  steps: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(12rem, 1fr))", gap: vars["--ads-space-12"], margin: 0, padding: 0, listStyle: "none" },
  step: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-8"],
    padding: vars["--ads-space-16"],
    borderRadius: vars["--ads-radius-panel"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface"],
  },
  stepNumber: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 22,
    height: 22,
    borderRadius: vars["--ads-radius-full"],
    backgroundColor: vars["--ads-color-accent-soft"],
    color: vars["--ads-color-accent"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
    fontVariantNumeric: "tabular-nums",
  },
  stepTitle: { fontSize: vars["--ads-font-size-body"], fontWeight: vars["--ads-font-weight-medium"] },
  stepText: { fontSize: vars["--ads-font-size-caption"], lineHeight: vars["--ads-line-height-normal"], color: vars["--ads-color-text-muted"] },
  dialogBody: { display: "flex", flexDirection: "column", gap: vars["--ads-space-16"] },
  field: { display: "flex", flexDirection: "column", alignItems: "flex-start", gap: 6 },
  fieldLabel: {
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
    lineHeight: vars["--ads-line-height-normal"],
    color: vars["--ads-color-text"],
  },
  optionRow: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "center",
    columnGap: vars["--ads-space-16"],
    padding: vars["--ads-space-12"],
    borderRadius: vars["--ads-radius-control"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
  },
});
