import * as stylex from "@stylexjs/stylex";
import { vars } from "@/components/ads/tokens/tokens.stylex";

export const hooksTabStyles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space12,
  },
  intro: {
    display: "flex",
    minWidth: 0,
    flexDirection: "column",
    gap: vars.space4,
  },
  introTitle: {
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightSemibold,
    color: vars.colorText,
  },
  introDescription: {
    fontSize: vars.fontSizeCaption,
    color: vars.colorTextMuted,
  },
  emptyState: {
    borderWidth: vars.borderWidthHairline,
    borderStyle: "dashed",
    borderColor: vars.colorBorder,
    backgroundColor: vars.colorSurfaceTint,
  },
  emptyIcon: {
    width: 16,
    height: 16,
  },
  grid: {
    display: "grid",
    gap: vars.space12,
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 64rem)": "1fr 1fr",
    },
  },
  // ── HookTriggerCard ──
  card: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    borderRadius: vars.radiusPanel,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: vars.colorBorder,
    backgroundColor: vars.colorSurface,
    padding: vars.space12,
  },
  cardHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: vars.space8,
  },
  cardHeaderText: {
    display: "flex",
    minWidth: 0,
    flex: 1,
    flexDirection: "column",
    gap: 2,
  },
  cardTitle: {
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    color: vars.colorText,
  },
  cardDescription: {
    fontSize: vars.fontSizeCaption,
    color: vars.colorTextMuted,
  },
  countBadge: {
    borderRadius: vars.radiusFull,
    paddingInline: vars.space8,
    paddingBlock: 0,
    fontSize: vars.fontSizeMicro,
  },
  emptyLinks: {
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "dashed",
    borderColor: vars.colorBorder,
    backgroundColor: vars.colorSurfaceTint,
    paddingInline: vars.space12,
    paddingBlock: 10,
    fontSize: vars.fontSizeCaption,
    color: vars.colorTextMuted,
  },
  linkList: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space4,
  },
  linkRow: {
    display: "flex",
    alignItems: "center",
    gap: vars.space8,
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: vars.colorBorder,
    backgroundColor: vars.colorSurfaceTint,
    paddingInline: 10,
    paddingBlock: vars.space4,
  },
  linkBody: {
    minWidth: 0,
    flex: 1,
  },
  linkTitleRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: vars.space4,
  },
  candidateLabel: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
    color: vars.colorText,
  },
  kindBadge: {
    borderRadius: vars.radiusMark,
    paddingInline: vars.space8,
    paddingBlock: 0,
    fontSize: vars.fontSizeMicro,
  },
  idBadge: {
    borderRadius: vars.radiusMark,
    paddingInline: vars.space8,
    paddingBlock: 0,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeMicro,
  },
  blockingGroup: {
    display: "flex",
    alignItems: "center",
    gap: vars.space4,
  },
  blockingLabel: {
    fontSize: vars.fontSizeMicro,
    color: vars.colorTextMuted,
  },
  removeButton: {
    color: {
      default: vars.colorTextMuted,
      ":hover": vars.colorDangerText,
    },
  },
  icon: {
    width: 14,
    height: 14,
  },
  assignTrigger: {
    height: 28,
    width: "100%",
    justifyContent: "center",
    gap: vars.space4,
  },
  popoverContent: {
    width: 288,
    padding: vars.space8,
  },
  popoverEmpty: {
    paddingInline: vars.space8,
    paddingBlock: vars.space12,
    textAlign: "center",
    fontSize: vars.fontSizeCaption,
    color: vars.colorTextMuted,
  },
  popoverList: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space4,
  },
  popoverHeading: {
    paddingInline: vars.space8,
    paddingTop: vars.space4,
    paddingBottom: vars.space4,
    fontSize: vars.fontSizeMicro,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    color: vars.colorTextMuted,
  },
  candidateButton: {
    display: "flex",
    width: "100%",
    alignItems: "center",
    gap: vars.space8,
    borderRadius: vars.radiusControl,
    paddingInline: vars.space8,
    paddingBlock: vars.space4,
    textAlign: "left",
    backgroundColor: {
      default: "transparent",
      ":hover": vars.colorOverlayHover,
    },
  },
  candidateDescription: {
    marginTop: 2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: vars.fontSizeMicro,
    color: vars.colorTextMuted,
  },
  candidateAddIcon: {
    width: 14,
    height: 14,
    color: vars.colorTextMuted,
  },
  // ── Unresolved refs ──
  unresolved: {
    borderRadius: vars.radiusPanel,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: vars.colorWarningBorder,
    backgroundColor: vars.colorWarningSoft,
    paddingInline: vars.space12,
    paddingBlock: 10,
    fontSize: vars.fontSizeCaption,
    color: vars.colorWarningText,
  },
  unresolvedHeader: {
    display: "flex",
    alignItems: "center",
    gap: vars.space8,
    fontWeight: vars.fontWeightMedium,
  },
  unresolvedList: {
    marginTop: vars.space8,
    display: "flex",
    flexWrap: "wrap",
    gap: vars.space8,
  },
  unresolvedBadge: {
    borderRadius: vars.radiusMark,
    paddingInline: vars.space8,
    paddingBlock: 0,
  },
});
