import * as stylex from "@stylexjs/stylex";
import { vars } from "@/components/ads/tokens/tokens.stylex";

const spin = stylex.keyframes({
  from: { transform: "rotate(0deg)" },
  to: { transform: "rotate(360deg)" },
});

export const managerStyles = stylex.create({
  loadingMuted: {
    paddingInline: vars.space4,
    paddingBlock: vars.space16,
    fontSize: vars.fontSizeCaption,
    color: vars.colorTextMuted,
  },
  emptyState: {
    borderWidth: vars.borderWidthHairline,
    borderStyle: "dashed",
    borderColor: vars.colorBorder,
    backgroundColor: vars.colorSurfaceTint,
  },
  emptyIcon: {
    width: 16,
    height: 16,
  },
  root: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space16,
  },
  header: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: vars.space12,
  },
  titleBlock: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space4,
  },
  titleRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: vars.space8,
  },
  titleText: {
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightSemibold,
    color: vars.colorText,
  },
  statusBadge: {
    borderRadius: vars.radiusFull,
    paddingInline: vars.space8,
    paddingBlock: 0,
    fontSize: vars.fontSizeMicro,
  },
  subtitle: {
    fontSize: vars.fontSizeCaption,
    lineHeight: "1.25rem",
    color: vars.colorTextMuted,
  },
  headerActions: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: vars.space4,
  },
  toolbarButton: {
    height: 36,
    paddingInline: vars.space12,
  },
  spinnerIcon: {
    marginRight: vars.space4,
    width: 14,
    height: 14,
  },
  spinnerIconAnimated: {
    marginRight: vars.space4,
    width: 14,
    height: 14,
    animationName: {
      default: null,
      "@media (prefers-reduced-motion: no-preference)": spin,
    },
    animationDuration: "1s",
    animationTimingFunction: "linear",
    animationIterationCount: "infinite",
  },
  scopeGrid: {
    display: "grid",
    gap: vars.space12,
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 64rem)": "minmax(0, 280px) 1fr",
    },
  },
  scopeLabel: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space4,
  },
  scopeLabelText: {
    display: "inline-flex",
    alignItems: "center",
    gap: vars.space4,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
    color: vars.colorText,
  },
  helpTrigger: {
    display: "inline-flex",
    width: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
    color: vars.colorTextMuted,
    background: "none",
    borderStyle: "none",
    padding: 0,
    cursor: "pointer",
  },
  helpIcon: {
    width: 14,
    height: 14,
  },
  tooltipContent: {
    maxWidth: "20rem",
    fontSize: vars.fontSizeCaption,
  },
  triggerFull: {
    width: "100%",
  },
  scopeInfo: {
    borderRadius: vars.radiusPanel,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: vars.colorBorder,
    backgroundColor: vars.colorSurfaceTint,
    paddingInline: vars.space12,
    paddingBlock: 10,
  },
  scopeInfoTitle: {
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
    color: vars.colorText,
  },
  scopeInfoPath: {
    marginTop: vars.space4,
    overflowWrap: "anywhere",
    fontSize: vars.fontSizeMicro,
    lineHeight: "1.25rem",
    color: vars.colorTextMuted,
  },
  errorBox: {
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: vars.colorDangerBorder,
    backgroundColor: vars.colorDangerSoft,
    paddingInline: vars.space12,
    paddingBlock: vars.space8,
    fontSize: vars.fontSizeCaption,
    color: vars.colorDangerText,
  },
  tabsRoot: {
    display: "grid",
    alignItems: "start",
    gap: vars.space20,
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 64rem)": "13rem minmax(0, 1fr)",
    },
  },
  tabsList: {
    position: "sticky",
    top: "5rem",
    width: "100%",
    alignItems: "stretch",
    justifyContent: "flex-start",
    gap: vars.space4,
    borderRadius: vars.radiusFrame,
    backgroundColor: vars.colorSurfaceTint,
    padding: vars.space4,
  },
  tab: {
    height: 44,
    width: "100%",
    justifyContent: "flex-start",
    gap: vars.space4,
    paddingInline: vars.space12,
  },
  tabBadge: {
    borderRadius: vars.radiusFull,
    paddingInline: vars.space4,
    paddingBlock: 0,
    fontSize: vars.fontSizeMicro,
  },
  tabPanel: {
    marginTop: 0,
  },
  footer: {
    position: "sticky",
    bottom: 0,
    zIndex: vars.zIndexPanel,
    marginInline: `calc(-1 * ${vars.space8})`,
    marginTop: vars.space20,
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: vars.space12,
    borderTopWidth: vars.borderWidthHairline,
    borderTopStyle: "solid",
    borderTopColor: vars.colorBorder,
    backgroundColor: vars.colorCanvas,
    paddingInline: vars.space8,
    paddingBlock: vars.space12,
  },
  footerStatus: {
    minWidth: 0,
  },
  footerStatusTitle: {
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
    color: vars.colorText,
  },
  footerStatusDetail: {
    marginTop: 2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: vars.fontSizeMicro,
    color: vars.colorTextMuted,
  },
  footerActions: {
    display: "flex",
    alignItems: "center",
    gap: vars.space4,
  },
  fullWidthButton: {
    width: "100%",
  },
});
