import * as stylex from "@stylexjs/stylex";
import { vars } from "@/components/ads/tokens/tokens.stylex";

export const hooksTabStyles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-12"],
  },
  intro: {
    display: "flex",
    minWidth: 0,
    flexDirection: "column",
    gap: vars["--ads-space-4"],
  },
  introTitle: {
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-semibold"],
    color: vars["--ads-color-text"],
  },
  introDescription: {
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text-muted"],
  },
  emptyState: {
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "dashed",
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface-tint"],
  },
  emptyIcon: {
    width: 16,
    height: 16,
  },
  grid: {
    display: "grid",
    gap: vars["--ads-space-12"],
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 64rem)": "1fr 1fr",
    },
  },
  // ── HookTriggerCard ──
  card: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    borderRadius: vars["--ads-radius-panel"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface"],
    padding: vars["--ads-space-12"],
  },
  cardHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: vars["--ads-space-8"],
  },
  cardHeaderText: {
    display: "flex",
    minWidth: 0,
    flex: 1,
    flexDirection: "column",
    gap: 2,
  },
  cardTitle: {
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
    color: vars["--ads-color-text"],
  },
  cardDescription: {
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text-muted"],
  },
  countBadge: {
    borderRadius: vars["--ads-radius-full"],
    paddingInline: vars["--ads-space-8"],
    paddingBlock: 0,
    fontSize: vars["--ads-font-size-micro"],
  },
  emptyLinks: {
    borderRadius: vars["--ads-radius-control"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "dashed",
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface-tint"],
    paddingInline: vars["--ads-space-12"],
    paddingBlock: 10,
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text-muted"],
  },
  linkList: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-4"],
  },
  linkRow: {
    display: "flex",
    alignItems: "center",
    gap: vars["--ads-space-8"],
    borderRadius: vars["--ads-radius-control"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface-tint"],
    paddingInline: 10,
    paddingBlock: vars["--ads-space-4"],
  },
  linkBody: {
    minWidth: 0,
    flex: 1,
  },
  linkTitleRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: vars["--ads-space-4"],
  },
  candidateLabel: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
    color: vars["--ads-color-text"],
  },
  kindBadge: {
    borderRadius: vars["--ads-radius-mark"],
    paddingInline: vars["--ads-space-8"],
    paddingBlock: 0,
    fontSize: vars["--ads-font-size-micro"],
  },
  idBadge: {
    borderRadius: vars["--ads-radius-mark"],
    paddingInline: vars["--ads-space-8"],
    paddingBlock: 0,
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-micro"],
  },
  blockingGroup: {
    display: "flex",
    alignItems: "center",
    gap: vars["--ads-space-4"],
  },
  blockingLabel: {
    fontSize: vars["--ads-font-size-micro"],
    color: vars["--ads-color-text-muted"],
  },
  removeButton: {
    color: {
      default: vars["--ads-color-text-muted"],
      ":hover": vars["--ads-color-danger-text"],
    },
  },
  icon: {
    width: 14,
    height: 14,
  },
  assignTrigger: {
    height: 28,
    width: "100%",
    justifyContent: "center",
    gap: vars["--ads-space-4"],
  },
  popoverContent: {
    width: 288,
    padding: vars["--ads-space-8"],
  },
  popoverEmpty: {
    paddingInline: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-12"],
    textAlign: "center",
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text-muted"],
  },
  popoverList: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-4"],
  },
  popoverHeading: {
    paddingInline: vars["--ads-space-8"],
    paddingTop: vars["--ads-space-4"],
    paddingBottom: vars["--ads-space-4"],
    fontSize: vars["--ads-font-size-micro"],
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    color: vars["--ads-color-text-muted"],
  },
  candidateButton: {
    display: "flex",
    width: "100%",
    alignItems: "center",
    gap: vars["--ads-space-8"],
    borderRadius: vars["--ads-radius-control"],
    paddingInline: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-4"],
    textAlign: "left",
    backgroundColor: {
      default: "transparent",
      ":hover": vars["--ads-color-overlay-hover"],
    },
  },
  candidateDescription: {
    marginTop: 2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: vars["--ads-font-size-micro"],
    color: vars["--ads-color-text-muted"],
  },
  candidateAddIcon: {
    width: 14,
    height: 14,
    color: vars["--ads-color-text-muted"],
  },
  // ── Unresolved refs ──
  unresolved: {
    borderRadius: vars["--ads-radius-panel"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-warning-border"],
    backgroundColor: vars["--ads-color-warning-soft"],
    paddingInline: vars["--ads-space-12"],
    paddingBlock: 10,
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-warning-text"],
  },
  unresolvedHeader: {
    display: "flex",
    alignItems: "center",
    gap: vars["--ads-space-8"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  unresolvedList: {
    marginTop: vars["--ads-space-8"],
    display: "flex",
    flexWrap: "wrap",
    gap: vars["--ads-space-8"],
  },
  unresolvedBadge: {
    borderRadius: vars["--ads-radius-mark"],
    paddingInline: vars["--ads-space-8"],
    paddingBlock: 0,
  },
});
