import * as stylex from "@stylexjs/stylex";
import { vars } from "@/components/ads/tokens/tokens.stylex";

const spin = stylex.keyframes({
  from: { transform: "rotate(0deg)" },
  to: { transform: "rotate(360deg)" },
});

export const managerStyles = stylex.create({
  loadingMuted: {
    paddingInline: vars["--ads-space-4"],
    paddingBlock: vars["--ads-space-16"],
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text-muted"],
  },
  emptyState: {
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "dashed",
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface-tint"],
  },
  emptyIcon: {
    width: 16,
    height: 16,
  },
  root: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-16"],
  },
  header: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: vars["--ads-space-12"],
  },
  titleBlock: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-4"],
  },
  titleRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: vars["--ads-space-8"],
  },
  titleText: {
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-semibold"],
    color: vars["--ads-color-text"],
  },
  statusBadge: {
    borderRadius: vars["--ads-radius-full"],
    paddingInline: vars["--ads-space-8"],
    paddingBlock: 0,
    fontSize: vars["--ads-font-size-micro"],
  },
  subtitle: {
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: "1.25rem",
    color: vars["--ads-color-text-muted"],
  },
  headerActions: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: vars["--ads-space-4"],
  },
  toolbarButton: {
    height: 36,
    paddingInline: vars["--ads-space-12"],
  },
  spinnerIcon: {
    marginRight: vars["--ads-space-4"],
    width: 14,
    height: 14,
  },
  spinnerIconAnimated: {
    marginRight: vars["--ads-space-4"],
    width: 14,
    height: 14,
    animationName: {
      default: null,
      "@media (prefers-reduced-motion: no-preference)": spin,
    },
    animationDuration: "1s",
    animationTimingFunction: "linear",
    animationIterationCount: "infinite",
  },
  scopeGrid: {
    display: "grid",
    gap: vars["--ads-space-12"],
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 64rem)": "minmax(0, 280px) 1fr",
    },
  },
  scopeLabel: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-4"],
  },
  scopeLabelText: {
    display: "inline-flex",
    alignItems: "center",
    gap: vars["--ads-space-4"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
    color: vars["--ads-color-text"],
  },
  helpTrigger: {
    display: "inline-flex",
    width: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
    color: vars["--ads-color-text-muted"],
    background: "none",
    borderStyle: "none",
    padding: 0,
    cursor: "pointer",
  },
  helpIcon: {
    width: 14,
    height: 14,
  },
  tooltipContent: {
    maxWidth: "20rem",
    fontSize: vars["--ads-font-size-caption"],
  },
  triggerFull: {
    width: "100%",
  },
  scopeInfo: {
    borderRadius: vars["--ads-radius-panel"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface-tint"],
    paddingInline: vars["--ads-space-12"],
    paddingBlock: 10,
  },
  scopeInfoTitle: {
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
    color: vars["--ads-color-text"],
  },
  scopeInfoPath: {
    marginTop: vars["--ads-space-4"],
    overflowWrap: "anywhere",
    fontSize: vars["--ads-font-size-micro"],
    lineHeight: "1.25rem",
    color: vars["--ads-color-text-muted"],
  },
  errorBox: {
    borderRadius: vars["--ads-radius-control"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-danger-border"],
    backgroundColor: vars["--ads-color-danger-soft"],
    paddingInline: vars["--ads-space-12"],
    paddingBlock: vars["--ads-space-8"],
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-danger-text"],
  },
  tabsRoot: {
    display: "grid",
    alignItems: "start",
    gap: vars["--ads-space-20"],
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 64rem)": "13rem minmax(0, 1fr)",
    },
  },
  tabsList: {
    position: "sticky",
    top: "5rem",
    width: "100%",
    alignItems: "stretch",
    justifyContent: "flex-start",
    gap: vars["--ads-space-4"],
    borderRadius: vars["--ads-radius-frame"],
    backgroundColor: vars["--ads-color-surface-tint"],
    padding: vars["--ads-space-4"],
  },
  tab: {
    height: 44,
    width: "100%",
    justifyContent: "flex-start",
    gap: vars["--ads-space-4"],
    paddingInline: vars["--ads-space-12"],
  },
  tabBadge: {
    borderRadius: vars["--ads-radius-full"],
    paddingInline: vars["--ads-space-4"],
    paddingBlock: 0,
    fontSize: vars["--ads-font-size-micro"],
  },
  tabPanel: {
    marginTop: 0,
  },
  footer: {
    position: "sticky",
    bottom: 0,
    zIndex: vars["--ads-z-index-panel"],
    marginInline: `calc(-1 * ${vars["--ads-space-8"]})`,
    marginTop: vars["--ads-space-20"],
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: vars["--ads-space-12"],
    borderTopWidth: vars["--ads-border-width-hairline"],
    borderTopStyle: "solid",
    borderTopColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-canvas"],
    paddingInline: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-12"],
  },
  footerStatus: {
    minWidth: 0,
  },
  footerStatusTitle: {
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
    color: vars["--ads-color-text"],
  },
  footerStatusDetail: {
    marginTop: 2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: vars["--ads-font-size-micro"],
    color: vars["--ads-color-text-muted"],
  },
  footerActions: {
    display: "flex",
    alignItems: "center",
    gap: vars["--ads-space-4"],
  },
  fullWidthButton: {
    width: "100%",
  },
});
