import * as stylex from "@stylexjs/stylex";

import { vars } from "../../ads/tokens/tokens.stylex";

/** Layout ownership for the Tasks surface. Component primitives keep their own states. */
export const taskLayoutStyles = stylex.create({
  surface: {
    backgroundColor: vars["--ads-color-canvas"],
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    overflow: "hidden",
    position: "relative",
  },
  content: {
    display: "flex",
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
    position: "relative",
  },
  listPane: {
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    "@media (max-width: 48rem)": { display: "none" },
  },
  listPaneVisible: { "@media (max-width: 48rem)": { display: "block" } },
  listColumn: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
  },
  listBody: { flex: 1, minHeight: 0 },
  truncationNotice: {
    borderTopColor: vars["--ads-color-border"],
    borderTopStyle: "solid",
    borderTopWidth: 1,
    color: vars["--ads-color-text-muted"],
    flexShrink: 0,
    fontSize: vars["--ads-font-size-caption"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-16"],
  },
  header: {
    alignItems: "center",
    backgroundColor: vars["--ads-color-canvas"],
    borderBottomColor: vars["--ads-color-border"],
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flexShrink: 0,
    gap: vars["--ads-space-16"],
    justifyContent: "space-between",
    minHeight: "4.5rem",
    paddingBlock: vars["--ads-space-12"],
    paddingInline: vars["--ads-space-20"],
  },
  headerLead: { minWidth: 0 },
  headerTitleRow: {
    alignItems: "center",
    display: "flex",
    gap: vars["--ads-space-8"],
    minWidth: 0,
  },
  headerIcon: {
    color: vars["--ads-color-text-muted"],
    flexShrink: 0,
    height: 18,
    width: 18,
  },
  headerTitle: {
    color: vars["--ads-color-text"],
    fontFamily: vars["--ads-font-sans"],
    fontSize: vars["--ads-font-size-lead"],
    fontWeight: vars["--ads-font-weight-semibold"],
    letterSpacing: "-0.01em",
    lineHeight: vars["--ads-line-height-normal"],
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerStatus: {
    alignItems: "center",
    color: vars["--ads-color-text-muted"],
    display: "flex",
    flexWrap: "wrap",
    fontSize: vars["--ads-font-size-caption"],
    gap: vars["--ads-space-4"],
    marginTop: vars["--ads-space-4"],
  },
  headerSource: {
    alignItems: "center",
    display: "inline-flex",
    gap: vars["--ads-space-4"],
  },
  headerSourceName: {
    color: vars["--ads-color-text"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  headerStale: {
    backgroundColor: vars["--ads-color-warning-soft"],
    borderColor: vars["--ads-color-warning-border"],
    borderRadius: vars["--ads-radius-full"],
    borderStyle: "solid",
    borderWidth: 1,
    color: vars["--ads-color-warning-text"],
    paddingInline: vars["--ads-space-8"],
  },
  headerPartial: {
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-full"],
    borderStyle: "solid",
    borderWidth: 1,
    paddingInline: vars["--ads-space-8"],
  },
  headerActions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: vars["--ads-space-8"],
  },
  headerAction: { height: 32, padding: 0, width: 32 },
  icon16: { height: 16, width: 16 },
  spinner: {
    animationName: {
      default: stylex.keyframes({
        from: { transform: "rotate(0deg)" },
        to: { transform: "rotate(360deg)" },
      }),
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    animationDuration: "1s",
    animationIterationCount: "infinite",
    animationTimingFunction: "linear",
  },
  toolbar: {
    backgroundColor: "color-mix(in oklch, var(--background) 85%, transparent)",
    borderBottomColor: vars["--ads-color-border"],
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    gap: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-16"],
  },
  toolbarRow: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: vars["--ads-space-8"],
  },
  tabList: {
    alignItems: "center",
    backgroundColor: vars["--ads-color-surface-tint"],
    borderRadius: vars["--ads-radius-control"],
    display: "flex",
    gap: 2,
    padding: 2,
  },
  activeTab: {
    backgroundColor: vars["--ads-color-surface"],
    borderColor: vars["--ads-color-border"],
    boxShadow: vars["--ads-elevation-raised"],
  },
  tab: {
    fontSize: vars["--ads-font-size-caption"],
    gap: vars["--ads-space-8"],
    height: 32,
    paddingInline: vars["--ads-space-8"],
  },
  search: { marginInlineStart: "auto", position: "relative" },
  searchIcon: {
    color: vars["--ads-color-text-muted"],
    height: 16,
    left: 10,
    pointerEvents: "none",
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    width: 16,
  },
  searchInput: {
    fontSize: vars["--ads-font-size-caption"],
    height: 32,
    paddingInlineStart: "2rem",
    width: "16rem",
  },
  toolbarActions: {
    alignItems: "center",
    display: "flex",
    gap: vars["--ads-space-8"],
    marginInlineStart: "auto",
  },
  segmented: {
    alignItems: "center",
    backgroundColor: vars["--ads-color-surface-tint"],
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    padding: 2,
  },
  selectSmall: { fontSize: vars["--ads-font-size-caption"], height: 32 },
  selectMedium: { fontSize: vars["--ads-font-size-caption"], height: 32, width: "10rem" },
  selectShort: { fontSize: vars["--ads-font-size-caption"], height: 32, width: "9rem" },
  // The columns row. `scrollbarColor` opts out of overlay scrollbars and the
  // inline-end fade turns a clipped column into "the row continues here":
  // without either, a board wider than the pane reads as if it ended.
  board: {
    display: "flex",
    gap: vars["--ads-space-12"],
    height: "100%",
    maskImage: `linear-gradient(to right, black calc(100% - ${vars["--ads-space-16"]}), transparent)`,
    minHeight: 0,
    overflowX: "auto",
    overflowY: "hidden",
    paddingBlock: vars["--ads-space-12"],
    paddingInline: vars["--ads-space-16"],
    scrollbarColor: `${vars["--ads-color-scrollbar-thumb"]} transparent`,
    scrollbarWidth: "thin",
  },
  boardColumn: { minBlockSize: 0 },
  boardTitle: {
    alignItems: "center",
    display: "inline-flex",
    gap: vars["--ads-space-8"],
  },
  boardItems: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: vars["--ads-space-8"],
    minHeight: 0,
    overflowY: "auto",
    scrollbarColor: `${vars["--ads-color-scrollbar-thumb"]} transparent`,
    scrollbarWidth: "thin",
  },
  // An empty column still has to look like a column. Left blank it collapsed to
  // a bare header and read as a rendering fault rather than "nothing here".
  boardColumnEmpty: {
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "dashed",
    borderWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-text-subtle"],
    fontSize: vars["--ads-font-size-caption"],
    paddingBlock: vars["--ads-space-16"],
    paddingInline: vars["--ads-space-8"],
    textAlign: "center",
  },
  boardCard: {
    backgroundColor: vars["--ads-color-surface-raised"],
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-panel"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    boxShadow: vars["--ads-elevation-raised"],
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
    textAlign: "start",
    width: "100%",
    // Neutral on hover; the accent wash is reserved for the selected card, so
    // a pointer resting on the board does not look like a second selection.
    ":hover": { borderColor: vars["--ads-color-border-strong"] },
  },
  boardCardSelected: {
    backgroundColor: vars["--ads-color-selection-fill"],
    borderColor: { default: vars["--ads-color-accent"], ":hover": vars["--ads-color-accent"] },
  },
  boardSkeletonCard: {
    backgroundColor: vars["--ads-color-surface-raised"],
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-panel"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    boxShadow: vars["--ads-elevation-raised"],
    display: "grid",
    gap: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
  },
  boardSkeletonFooter: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
  },
  boardCardTop: {
    alignItems: "center",
    display: "flex",
    gap: vars["--ads-space-8"],
    justifyContent: "space-between",
  },
  boardCardKeyGroup: {
    alignItems: "center",
    display: "flex",
    gap: vars["--ads-space-8"],
    minWidth: 0,
  },
  boardCardKey: {
    color: vars["--ads-color-text-muted"],
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-tight"],
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  // Three lines, then an ellipsis. `overflowWrap` is what keeps a title that is
  // one long unbroken token — a URL, a branch name — inside the card.
  boardCardTitle: {
    color: vars["--ads-color-text"],
    display: "-webkit-box",
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
    lineHeight: vars["--ads-line-height-lead"],
    overflow: "hidden",
    overflowWrap: "anywhere",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 3,
  },
  boardCardFinished: {
    color: vars["--ads-color-text-muted"],
    textDecorationLine: "line-through",
  },
  boardCardFooter: {
    alignItems: "center",
    display: "flex",
    gap: vars["--ads-space-8"],
    justifyContent: "space-between",
  },
  boardCardTrailing: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: vars["--ads-space-4"],
  },
  boardDue: {
    fontSize: vars["--ads-font-size-caption"],
    fontVariantNumeric: "tabular-nums",
    whiteSpace: "nowrap",
  },
  boardLabels: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: vars["--ads-space-4"],
    minWidth: 0,
  },
  boardLabel: {
    alignItems: "center",
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-full"],
    borderStyle: "solid",
    borderWidth: 1,
    color: vars["--ads-color-text-muted"],
    display: "inline-flex",
    fontSize: vars["--ads-font-size-caption"],
    gap: vars["--ads-space-4"],
    maxWidth: "7rem",
    overflow: "hidden",
    paddingBlock: 2,
    paddingInline: vars["--ads-space-8"],
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  labelDot: {
    borderRadius: vars["--ads-radius-full"],
    flexShrink: 0,
    height: 6,
    width: 6,
  },
  boardAvatar: {
    alignItems: "center",
    backgroundColor: vars["--ads-color-surface-tint"],
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-full"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-text-muted"],
    display: "flex",
    flexShrink: 0,
    fontSize: vars["--ads-font-size-micro"],
    fontWeight: vars["--ads-font-weight-medium"],
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  list: { height: "100%", overflowY: "auto" },
  listGroup: { position: "sticky", top: 0, zIndex: 10 },
  listHeader: {
    alignItems: "center",
    backdropFilter: "blur(4px)",
    backgroundColor: "color-mix(in oklch, var(--background) 95%, transparent)",
    borderBottomColor: vars["--ads-color-border"],
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    color: vars["--ads-color-text-muted"],
    display: "flex",
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-semibold"],
    gap: vars["--ads-space-8"],
    letterSpacing: "0.08em",
    lineHeight: vars["--ads-line-height-tight"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-16"],
    textAlign: "start",
    textTransform: "uppercase",
    width: "100%",
    ":hover": { color: vars["--ads-color-text"] },
  },
  listCount: {
    color: vars["--ads-color-text-muted"],
    fontVariantNumeric: "tabular-nums",
    fontWeight: vars["--ads-font-weight-regular"],
  },
  peek: {
    backgroundColor: vars["--ads-color-canvas"],
    color: vars["--ads-color-text"],
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    minHeight: 0,
    transitionDuration: {
      default: vars["--ads-motion-duration-normal"],
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionProperty: "transform, opacity, visibility, margin",
    transitionTimingFunction: "ease-out",
    "@media (max-width: 48rem)": {
      borderLeftWidth: 0,
      inset: 0,
      position: "absolute",
      width: "100%",
      zIndex: 20,
    },
  },
  peekSplit: {
    borderLeftColor: vars["--ads-color-border"],
    borderLeftStyle: "solid",
    borderLeftWidth: 1,
    flexShrink: 0,
    position: "relative",
    width: "var(--stave-peek-width)",
  },
  peekParent: {
    borderLeftColor: vars["--ads-color-border"],
    borderLeftStyle: "solid",
    borderLeftWidth: 1,
    boxShadow: vars["--ads-elevation-overlay"],
    insetBlock: 0,
    insetInlineEnd: 0,
    position: "absolute",
    width: "min(var(--stave-peek-width), 100%)",
    zIndex: 20,
  },
  peekClosedSplit: {
    marginInlineEnd: "calc(-1 * var(--stave-peek-width))",
    opacity: 0,
    pointerEvents: "none",
    transform: "translateX(100%)",
    visibility: "hidden",
  },
  peekClosedParent: {
    opacity: 0,
    pointerEvents: "none",
    transform: "translateX(110%)",
    visibility: "hidden",
  },
  peekOpen: { transform: "translateX(0)" },
  peekResize: {
    cursor: "col-resize",
    insetBlock: 0,
    insetInlineStart: 0,
    position: "absolute",
    transform: "translateX(-50%)",
    width: 12,
    zIndex: 10,
    "@media (max-width: 48rem)": { display: "none" },
  },
  peekHeader: {
    alignItems: "center",
    borderBottomColor: vars["--ads-color-border"],
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flexShrink: 0,
    gap: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-4"],
    paddingInline: vars["--ads-space-8"],
  },
  peekNavigation: { display: "flex", flexDirection: "column", flexShrink: 0 },
  peekTitle: {
    color: vars["--ads-color-text-muted"],
    flex: 1,
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-caption"],
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  peekActions: { alignItems: "center", display: "flex", flexShrink: 0, gap: 2 },
  peekBody: { minHeight: 0, overflow: "hidden" },
  meta: { display: "flex", flexDirection: "column", gap: vars["--ads-space-12"] },
  metaGrid: {
    columnGap: vars["--ads-space-16"],
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    rowGap: "0.625rem",
  },
  metaField: { minWidth: 0 },
  metaLabel: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-micro"],
    letterSpacing: "0.12em",
    lineHeight: vars["--ads-line-height-tight"],
    textTransform: "uppercase",
  },
  metaValue: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
    marginTop: 2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  metaInline: {
    alignItems: "center",
    display: "inline-flex",
    gap: vars["--ads-space-4"],
  },
  metaLabels: { display: "flex", flexWrap: "wrap", gap: vars["--ads-space-4"] },
  metaLabelChip: {
    alignItems: "center",
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-full"],
    borderStyle: "solid",
    borderWidth: 1,
    color: vars["--ads-color-text-muted"],
    display: "inline-flex",
    fontSize: vars["--ads-font-size-micro"],
    gap: vars["--ads-space-4"],
    lineHeight: vars["--ads-line-height-tight"],
    paddingBlock: 1,
    paddingInline: vars["--ads-space-8"],
  },
  detailRoot: {
    backgroundColor: vars["--ads-color-canvas"],
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    overflow: "hidden",
  },
  detailStandalone: {
    backgroundColor: vars["--ads-color-surface-tint"],
    borderLeftColor: vars["--ads-color-border"],
    borderLeftStyle: "solid",
    borderLeftWidth: 1,
  },
  detailHeader: {
    borderBottomColor: vars["--ads-color-border"],
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    gap: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-12"],
    paddingInline: vars["--ads-space-16"],
  },
  detailKey: {
    alignItems: "center",
    color: vars["--ads-color-text-muted"],
    display: "flex",
    fontSize: vars["--ads-font-size-caption"],
    gap: vars["--ads-space-8"],
  },
  detailKeyText: { fontFamily: vars["--ads-font-mono"] },
  detailTitle: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-lead"],
    fontWeight: vars["--ads-font-weight-semibold"],
    lineHeight: vars["--ads-line-height-lead"],
  },
  detailActions: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: vars["--ads-space-8"],
  },
  detailAction: {
    fontSize: vars["--ads-font-size-caption"],
    gap: vars["--ads-space-8"],
    height: 32,
  },
  detailMenuAction: {
    fontSize: vars["--ads-font-size-caption"],
    height: 32,
    paddingInline: vars["--ads-space-8"],
  },
  detailBody: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: vars["--ads-space-16"],
    minHeight: 0,
    overflowY: "auto",
    paddingBlock: vars["--ads-space-12"],
    paddingInline: vars["--ads-space-16"],
  },
  detailLink: {
    alignItems: "center",
    backgroundColor: vars["--ads-color-surface-tint"],
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-panel"],
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    gap: vars["--ads-space-8"],
    padding: "0.625rem",
    textAlign: "start",
    width: "100%",
    ":hover": { backgroundColor: vars["--ads-color-accent-soft"] },
  },
  detailLinkCopy: { flex: 1, minWidth: 0 },
  detailLinkTitle: {
    color: vars["--ads-color-text"],
    display: "block",
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
    lineHeight: vars["--ads-line-height-tight"],
  },
  detailLinkSubtitle: {
    color: vars["--ads-color-text-muted"],
    display: "block",
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-tight"],
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  detailSection: { display: "flex", flexDirection: "column", gap: vars["--ads-space-8"] },
  detailSectionTitle: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-micro"],
    letterSpacing: "0.12em",
    lineHeight: vars["--ads-line-height-tight"],
    textTransform: "uppercase",
  },
  detailMuted: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
  },
  detailSkeletons: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-8"],
  },
  detailSkeletonFull: { height: 12, width: "100%" },
  detailSkeletonEleven: { height: 12, width: "91.666667%" },
  detailSkeletonEight: { height: 12, width: "66.666667%" },
  detailComments: {
    borderTopColor: vars["--ads-color-border"],
    borderTopStyle: "solid",
    borderTopWidth: 1,
  },
  detailAccordionTrigger: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
    paddingBlock: vars["--ads-space-8"],
  },
  detailAccordionContent: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-8"],
    paddingBlockEnd: vars["--ads-space-8"],
  },
  detailComment: { display: "flex", flexDirection: "column", gap: 2 },
  detailCommentMeta: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-tight"],
  },
  detailCommentBody: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
    whiteSpace: "pre-wrap",
  },
  kickoffContent: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: vars["--ads-space-20"],
    minHeight: 0,
    overflowY: "auto",
    paddingBlock: vars["--ads-space-16"],
    paddingInline: vars["--ads-space-20"],
  },
  kickoffSheet: {
    gap: 0,
    padding: 0,
    width: "100%",
    "@media (min-width: 40rem)": { maxWidth: "36rem" },
  },
  kickoffHeader: {
    borderBottomColor: vars["--ads-color-border"],
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    flexShrink: 0,
    paddingBlockEnd: vars["--ads-space-16"],
    paddingBlockStart: vars["--ads-space-20"],
    paddingInlineEnd: "3rem",
    paddingInlineStart: vars["--ads-space-20"],
  },
  kickoffTicket: {
    backgroundColor: vars["--ads-color-surface-tint"],
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-panel"],
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-8"],
    padding: vars["--ads-space-12"],
  },
  kickoffTicketHeader: {
    alignItems: "flex-start",
    display: "flex",
    gap: vars["--ads-space-12"],
    justifyContent: "space-between",
  },
  kickoffTicketCopy: { minWidth: 0 },
  kickoffTicketTitle: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-semibold"],
    lineHeight: vars["--ads-line-height-normal"],
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  kickoffTicketMeta: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-micro"],
    lineHeight: vars["--ads-line-height-tight"],
    marginTop: 2,
  },
  kickoffSourceButton: {
    fontSize: vars["--ads-font-size-micro"],
    gap: vars["--ads-space-8"],
    height: 28,
  },
  kickoffWarning: {
    backgroundColor: vars["--ads-color-warning-soft"],
    borderColor: vars["--ads-color-warning-border"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: 1,
    color: vars["--ads-color-warning-text"],
    fontSize: vars["--ads-font-size-micro"],
    lineHeight: vars["--ads-line-height-tight"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-8"],
  },
  kickoffSection: { display: "grid", gap: vars["--ads-space-8"] },
  kickoffSectionHeading: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-semibold"],
    lineHeight: vars["--ads-line-height-normal"],
  },
  kickoffHeadingRow: {
    alignItems: "center",
    display: "flex",
    gap: vars["--ads-space-8"],
    justifyContent: "space-between",
  },
  kickoffTextArea: {
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
  },
  kickoffHint: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
  },
  kickoffModeList: {
    alignItems: "center",
    backgroundColor: vars["--ads-color-surface-tint"],
    borderRadius: vars["--ads-radius-control"],
    display: "flex",
    gap: 2,
    padding: 2,
  },
  kickoffMode: { flex: 1, fontSize: vars["--ads-font-size-micro"], height: 28 },
  kickoffModeActive: {
    backgroundColor: vars["--ads-color-surface"],
    borderColor: vars["--ads-color-border"],
  },
  kickoffReset: { gap: vars["--ads-space-4"] },
  icon14: { height: 14, width: 14 },
  icon12: { height: 12, width: 12 },
  kickoffCrane: {
    alignItems: "flex-start",
    backgroundColor: vars["--ads-color-surface-tint"],
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-panel"],
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    gap: vars["--ads-space-12"],
    justifyContent: "space-between",
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
  },
  kickoffNotice: {
    alignItems: "flex-start",
    backgroundColor: vars["--ads-color-surface-tint"],
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-panel"],
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    gap: vars["--ads-space-12"],
    padding: vars["--ads-space-12"],
  },
  kickoffFooter: {
    alignItems: "center",
    backgroundColor: vars["--ads-color-surface-tint"],
    borderTopColor: vars["--ads-color-border"],
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "flex",
    flexDirection: "row",
    flexShrink: 0,
    paddingBlock: vars["--ads-space-12"],
    paddingInline: vars["--ads-space-20"],
  },
  kickoffFooterHint: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
    marginInlineEnd: "auto",
  },
});
