import * as stylex from "@stylexjs/stylex";
import { focusRing } from "../../ads/recipes/focus-ring";
import { transition } from "../../ads/recipes/transition";
import { vars } from "../../ads/tokens/tokens.stylex";

export const taskRowStyles = stylex.create({
  row: {
    display: "flex",
    alignItems: "center",
    gap: vars.space12,
    cursor: "default",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: vars.colorBorder,
    paddingInline: vars.space16,
    paddingBlock: 10,
    fontSize: vars.fontSizeBody,
    backgroundColor: {
      default: "transparent",
      ":hover": vars.colorSurfaceTint,
      ":focus-visible": vars.colorSurfaceTint,
    },
  },
  selected: { backgroundColor: vars.colorSelectionFill },
  foreground: { color: vars.colorText },
  muted: { color: vars.colorTextMuted },
  danger: { color: vars.colorDangerText },
  warning: { color: vars.colorWarningText },
  transparent: { color: "transparent" },
  visible: { opacity: 1 },
  hidden: { opacity: 0 },
  sourceIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    width: 20,
    height: 20,
    color: vars.colorTextMuted,
  },
  icon15: { width: 15, height: 15 },
  key: {
    flexShrink: 0,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightNormal,
    color: vars.colorTextMuted,
  },
  priority: { flexShrink: 0, width: 16, height: 16 },
  title: {
    minWidth: 0,
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: vars.fontSizeBody,
  },
  finished: { color: vars.colorTextMuted, textDecorationLine: "line-through" },
  inlineParent: {
    display: "inline",
    width: 14,
    height: 14,
    marginInlineEnd: vars.space4,
    color: vars.colorTextMuted,
  },
  label: {
    display: { default: "none", "@media (min-width: 64rem)": "inline-flex" },
    alignItems: "center",
    gap: vars.space4,
    flexShrink: 0,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusFull,
    paddingInline: vars.space8,
    paddingBlock: 2,
    fontSize: vars.fontSizeCaption,
    color: vars.colorTextMuted,
  },
  labelDot: { width: 8, height: 8, borderRadius: vars.radiusFull },
  hiddenCount: {
    display: { default: "none", "@media (min-width: 64rem)": "inline" },
    flexShrink: 0,
    fontSize: vars.fontSizeCaption,
    color: vars.colorTextMuted,
  },
  external: {
    display: { default: "none", "@media (min-width: 48rem)": "inline-flex" },
    alignItems: "center",
    gap: vars.space4,
    flexShrink: 0,
    fontSize: vars.fontSizeCaption,
    color: vars.colorTextMuted,
  },
  link: {
    display: "flex",
    alignItems: "center",
    gap: vars.space4,
    flexShrink: 0,
    borderRadius: vars.radiusFull,
    paddingInline: vars.space8,
    paddingBlock: 2,
    fontSize: vars.fontSizeCaption,
  },
  linkIcon: { width: 12, height: 12 },
  status: { flexShrink: 0, fontSize: vars.fontSizeCaption },
  effort: {
    display: { default: "none", "@media (min-width: 40rem)": "inline" },
    width: 24,
    flexShrink: 0,
    textAlign: "right",
    fontSize: vars.fontSizeCaption,
    fontVariantNumeric: "tabular-nums",
    color: vars.colorTextMuted,
  },
  due: {
    width: "4.5rem",
    flexShrink: 0,
    textAlign: "right",
    fontSize: vars.fontSizeCaption,
  },
  assignee: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 24,
    height: 24,
    flexShrink: 0,
    borderRadius: vars.radiusFull,
    backgroundColor: vars.colorSurfaceTint,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightSemibold,
    color: vars.colorTextMuted,
  },
  sourceStrip: {
    display: "flex",
    alignItems: "center",
    gap: vars.space8,
    flexShrink: 0,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: vars.colorBorder,
    paddingInline: vars.space16,
    paddingBlock: vars.space8,
    fontSize: vars.fontSizeCaption,
  },
  sourceRow: {
    display: "flex",
    alignItems: "center",
    gap: vars.space8,
    fontSize: vars.fontSizeCaption,
  },
  sourceStripError: {
    color: vars.colorDangerText,
    backgroundColor: vars.colorDangerSoft,
    borderBottomColor: vars.colorDangerBorder,
  },
  sourceStripQuiet: {
    color: vars.colorTextMuted,
    backgroundColor: vars.colorSurfaceTint,
  },
  stripText: { minWidth: 0, flex: 1 },
  stripLabel: { fontWeight: vars.fontWeightMedium, color: vars.colorText },
  emptyFull: { height: "100%" },
  summaryList: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space8,
    marginBottom: vars.space12,
    textAlign: "left",
    fontSize: vars.fontSizeBody,
  },
  summaryItem: { display: "flex", gap: vars.space8 },
  summarySource: {
    width: "3.5rem",
    flexShrink: 0,
    fontWeight: vars.fontWeightMedium,
    color: vars.colorText,
  },
  summaryDetail: { color: vars.colorTextMuted },
  summaryHeadline: { color: vars.colorText },
  emptyActions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: vars.space8,
  },
  spin: {
    animationName: stylex.keyframes({
      from: { transform: "rotate(0deg)" },
      to: { transform: "rotate(360deg)" },
    }),
    animationDuration: "1s",
    animationPlayState: {
      default: "running",
      "@media (prefers-reduced-motion: reduce)": "paused",
    },
    animationIterationCount: "infinite",
    animationTimingFunction: "linear",
  },
  buttonIcon: { width: 14, height: 14 },
  filterTrigger: {
    height: 32,
    gap: 6,
    paddingInline: 10,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightNormal,
  },
  filterActive: {
    borderColor: vars.colorBorder,
    backgroundColor: vars.colorSurface,
  },
  filterSummary: {
    maxWidth: "7rem",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: vars.colorText,
  },
  filterChevron: { width: 14, height: 14, color: vars.colorTextMuted },
  filterPopup: { width: "14rem", padding: 0 },
  commandItem: {
    fontSize: vars.fontSizeBody,
    lineHeight: vars.lineHeightNormal,
  },
  commandCheck: { width: 14, height: 14 },
  commandOption: {
    minWidth: 0,
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  optionCount: {
    fontSize: vars.fontSizeCaption,
    fontVariantNumeric: "tabular-nums",
    color: vars.colorTextMuted,
  },
});

export const taskRowFocus = focusRing.ring;
export const taskRowTransition = transition.colors;
