import * as stylex from "@stylexjs/stylex";

import { vars } from "../../ads/tokens/tokens.stylex";

/** Layout ownership for the Tasks surface. Component primitives keep their own states. */
export const taskLayoutStyles = stylex.create({
  surface: {
    backgroundColor: vars.colorCanvas,
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    overflow: "hidden",
    position: "relative",
  },
  content: {
    display: "flex",
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
    position: "relative",
  },
  listPane: {
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    "@media (max-width: 48rem)": { display: "none" },
  },
  listPaneVisible: { "@media (max-width: 48rem)": { display: "block" } },
  listColumn: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
  },
  listBody: { flex: 1, minHeight: 0 },
  truncationNotice: {
    borderTopColor: vars.colorBorder,
    borderTopStyle: "solid",
    borderTopWidth: 1,
    color: vars.colorTextMuted,
    flexShrink: 0,
    fontSize: vars.fontSizeCaption,
    paddingBlock: vars.space8,
    paddingInline: vars.space16,
  },
  header: {
    alignItems: "center",
    backgroundColor: vars.colorCanvas,
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flexShrink: 0,
    gap: vars.space16,
    justifyContent: "space-between",
    minHeight: "4.5rem",
    paddingBlock: vars.space12,
    paddingInline: vars.space20,
  },
  headerLead: { minWidth: 0 },
  headerTitleRow: {
    alignItems: "center",
    display: "flex",
    gap: vars.space8,
    minWidth: 0,
  },
  headerIcon: { color: vars.colorAccent, flexShrink: 0, height: 18, width: 18 },
  headerTitle: {
    color: vars.colorText,
    fontFamily: vars.fontSans,
    fontSize: vars.fontSizeLead,
    fontWeight: vars.fontWeightSemibold,
    letterSpacing: "-0.01em",
    lineHeight: vars.lineHeightNormal,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerStatus: {
    alignItems: "center",
    color: vars.colorTextMuted,
    display: "flex",
    flexWrap: "wrap",
    fontSize: vars.fontSizeCaption,
    gap: vars.space4,
    marginTop: vars.space4,
  },
  headerSource: {
    alignItems: "center",
    display: "inline-flex",
    gap: vars.space4,
  },
  headerSourceName: {
    color: vars.colorText,
    fontWeight: vars.fontWeightMedium,
  },
  headerStale: {
    backgroundColor: vars.colorWarningSoft,
    borderColor: vars.colorWarningBorder,
    borderRadius: vars.radiusFull,
    borderStyle: "solid",
    borderWidth: 1,
    color: vars.colorWarningText,
    paddingInline: vars.space8,
  },
  headerPartial: {
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusFull,
    borderStyle: "solid",
    borderWidth: 1,
    paddingInline: vars.space8,
  },
  headerActions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: vars.space8,
  },
  headerAction: { height: 32, padding: 0, width: 32 },
  icon16: { height: 16, width: 16 },
  spinner: {
    animationName: stylex.keyframes({
      from: { transform: "rotate(0deg)" },
      to: { transform: "rotate(360deg)" },
    }),
    animationDuration: "1s",
    animationIterationCount: "infinite",
    animationTimingFunction: "linear",
  },
  toolbar: {
    backgroundColor: "color-mix(in oklch, var(--background) 85%, transparent)",
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    gap: vars.space8,
    paddingBlock: vars.space8,
    paddingInline: vars.space16,
  },
  toolbarRow: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: vars.space8,
  },
  tabList: {
    alignItems: "center",
    backgroundColor: vars.colorSurfaceTint,
    borderRadius: vars.radiusControl,
    display: "flex",
    gap: 2,
    padding: 2,
  },
  activeTab: {
    backgroundColor: vars.colorSurface,
    borderColor: vars.colorBorder,
    boxShadow: vars.elevationRaised,
  },
  tab: {
    fontSize: vars.fontSizeCaption,
    gap: vars.space8,
    height: 32,
    paddingInline: vars.space8,
  },
  search: { marginInlineStart: "auto", position: "relative" },
  searchIcon: {
    color: vars.colorTextMuted,
    height: 16,
    left: 10,
    pointerEvents: "none",
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    width: 16,
  },
  searchInput: {
    fontSize: vars.fontSizeCaption,
    height: 32,
    paddingInlineStart: "2rem",
    width: "16rem",
  },
  toolbarActions: {
    alignItems: "center",
    display: "flex",
    gap: vars.space8,
    marginInlineStart: "auto",
  },
  segmented: {
    alignItems: "center",
    backgroundColor: vars.colorSurfaceTint,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    padding: 2,
  },
  selectSmall: { fontSize: vars.fontSizeCaption, height: 32 },
  selectMedium: { fontSize: vars.fontSizeCaption, height: 32, width: "10rem" },
  selectShort: { fontSize: vars.fontSizeCaption, height: 32, width: "9rem" },
  board: {
    display: "flex",
    gap: vars.space12,
    height: "100%",
    minHeight: 0,
    overflowX: "auto",
    overflowY: "hidden",
    paddingBlock: vars.space12,
    paddingInline: vars.space16,
    scrollbarWidth: "thin",
  },
  boardColumn: {
    backgroundColor: vars.colorSurfaceTint,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    width: "17rem",
  },
  boardHeader: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: vars.space8,
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
  },
  boardTitle: {
    color: vars.colorText,
    flex: 1,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  boardItems: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: vars.space8,
    minHeight: 0,
    overflowY: "auto",
    paddingBlockEnd: vars.space8,
    paddingInline: vars.space8,
  },
  boardCard: {
    backgroundColor: vars.colorSurface,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    flexDirection: "column",
    gap: vars.space8,
    paddingBlock: "0.625rem",
    paddingInline: vars.space12,
    textAlign: "start",
    transitionProperty: "background-color, border-color",
    transitionDuration: vars.motionDurationFast,
    width: "100%",
    ":hover": { backgroundColor: vars.colorAccentSoft },
  },
  boardCardSelected: {
    backgroundColor: vars.colorAccentSoft,
    borderColor: vars.colorAccent,
  },
  boardCardTop: {
    alignItems: "center",
    display: "flex",
    gap: vars.space8,
    justifyContent: "space-between",
  },
  boardCardKeyGroup: {
    alignItems: "center",
    display: "flex",
    gap: vars.space8,
    minWidth: 0,
  },
  boardCardKey: {
    color: vars.colorTextMuted,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightTight,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  boardCardTitle: {
    color: vars.colorText,
    display: "-webkit-box",
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    lineHeight: vars.lineHeightLead,
    overflow: "hidden",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 3,
  },
  boardCardFooter: {
    alignItems: "center",
    display: "flex",
    gap: vars.space8,
    justifyContent: "space-between",
  },
  boardLabels: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: vars.space4,
    minWidth: 0,
  },
  boardLabel: {
    alignItems: "center",
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusFull,
    borderStyle: "solid",
    borderWidth: 1,
    color: vars.colorTextMuted,
    display: "inline-flex",
    fontSize: vars.fontSizeCaption,
    gap: vars.space4,
    maxWidth: "7rem",
    overflow: "hidden",
    paddingBlock: 2,
    paddingInline: vars.space8,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  labelDot: {
    borderRadius: vars.radiusFull,
    flexShrink: 0,
    height: 6,
    width: 6,
  },
  boardAvatar: {
    alignItems: "center",
    backgroundColor: vars.colorSurfaceTint,
    borderRadius: vars.radiusFull,
    color: vars.colorTextMuted,
    display: "flex",
    flexShrink: 0,
    fontSize: "11px",
    fontWeight: vars.fontWeightMedium,
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  list: { height: "100%", overflowY: "auto" },
  listGroup: { position: "sticky", top: 0, zIndex: 10 },
  listHeader: {
    alignItems: "center",
    backdropFilter: "blur(4px)",
    backgroundColor: "color-mix(in oklch, var(--background) 95%, transparent)",
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    color: vars.colorTextMuted,
    display: "flex",
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightSemibold,
    gap: vars.space8,
    letterSpacing: "0.08em",
    lineHeight: vars.lineHeightTight,
    paddingBlock: vars.space8,
    paddingInline: vars.space16,
    textAlign: "start",
    textTransform: "uppercase",
    width: "100%",
    ":hover": { color: vars.colorText },
  },
  listCount: {
    color: vars.colorTextMuted,
    fontVariantNumeric: "tabular-nums",
    fontWeight: vars.fontWeightRegular,
  },
  peek: {
    backgroundColor: vars.colorCanvas,
    color: vars.colorText,
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    minHeight: 0,
    transitionDuration: {
      default: vars.motionDurationNormal,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionProperty: "transform, opacity, visibility, margin",
    transitionTimingFunction: "ease-out",
    "@media (max-width: 48rem)": {
      borderLeftWidth: 0,
      inset: 0,
      position: "absolute",
      width: "100%",
      zIndex: 20,
    },
  },
  peekSplit: {
    borderLeftColor: vars.colorBorder,
    borderLeftStyle: "solid",
    borderLeftWidth: 1,
    flexShrink: 0,
    position: "relative",
    width: "var(--stave-peek-width)",
  },
  peekParent: {
    borderLeftColor: vars.colorBorder,
    borderLeftStyle: "solid",
    borderLeftWidth: 1,
    boxShadow: vars.elevationOverlay,
    insetBlock: 0,
    insetInlineEnd: 0,
    position: "absolute",
    width: "min(var(--stave-peek-width), 100%)",
    zIndex: 20,
  },
  peekClosedSplit: {
    marginInlineEnd: "calc(-1 * var(--stave-peek-width))",
    opacity: 0,
    pointerEvents: "none",
    transform: "translateX(100%)",
    visibility: "hidden",
  },
  peekClosedParent: {
    opacity: 0,
    pointerEvents: "none",
    transform: "translateX(110%)",
    visibility: "hidden",
  },
  peekOpen: { transform: "translateX(0)" },
  peekResize: {
    cursor: "col-resize",
    insetBlock: 0,
    insetInlineStart: 0,
    position: "absolute",
    transform: "translateX(-50%)",
    width: 12,
    zIndex: 10,
    "@media (max-width: 48rem)": { display: "none" },
  },
  peekHeader: {
    alignItems: "center",
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flexShrink: 0,
    gap: vars.space8,
    paddingBlock: vars.space4,
    paddingInline: vars.space8,
  },
  peekNavigation: { display: "flex", flexDirection: "column", flexShrink: 0 },
  peekTitle: {
    color: vars.colorTextMuted,
    flex: 1,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeCaption,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  peekActions: { alignItems: "center", display: "flex", flexShrink: 0, gap: 2 },
  peekBody: { minHeight: 0, overflow: "hidden" },
  meta: { display: "flex", flexDirection: "column", gap: vars.space12 },
  metaGrid: {
    columnGap: vars.space16,
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    rowGap: "0.625rem",
  },
  metaField: { minWidth: 0 },
  metaLabel: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeMicro,
    letterSpacing: "0.12em",
    lineHeight: vars.lineHeightTight,
    textTransform: "uppercase",
  },
  metaValue: {
    color: vars.colorText,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightNormal,
    marginTop: 2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  metaInline: {
    alignItems: "center",
    display: "inline-flex",
    gap: vars.space4,
  },
  metaLabels: { display: "flex", flexWrap: "wrap", gap: vars.space4 },
  metaLabelChip: {
    alignItems: "center",
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusFull,
    borderStyle: "solid",
    borderWidth: 1,
    color: vars.colorTextMuted,
    display: "inline-flex",
    fontSize: vars.fontSizeMicro,
    gap: vars.space4,
    lineHeight: vars.lineHeightTight,
    paddingBlock: 1,
    paddingInline: vars.space8,
  },
  detailRoot: {
    backgroundColor: vars.colorCanvas,
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    overflow: "hidden",
  },
  detailStandalone: {
    backgroundColor: vars.colorSurfaceTint,
    borderLeftColor: vars.colorBorder,
    borderLeftStyle: "solid",
    borderLeftWidth: 1,
  },
  detailHeader: {
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    gap: vars.space8,
    paddingBlock: vars.space12,
    paddingInline: vars.space16,
  },
  detailKey: {
    alignItems: "center",
    color: vars.colorTextMuted,
    display: "flex",
    fontSize: vars.fontSizeCaption,
    gap: vars.space8,
  },
  detailKeyText: { fontFamily: vars.fontMono },
  detailTitle: {
    color: vars.colorText,
    fontSize: vars.fontSizeLead,
    fontWeight: vars.fontWeightSemibold,
    lineHeight: vars.lineHeightLead,
  },
  detailActions: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: vars.space8,
  },
  detailAction: {
    fontSize: vars.fontSizeCaption,
    gap: vars.space8,
    height: 32,
  },
  detailMenuAction: {
    fontSize: vars.fontSizeCaption,
    height: 32,
    paddingInline: vars.space8,
  },
  detailBody: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: vars.space16,
    minHeight: 0,
    overflowY: "auto",
    paddingBlock: vars.space12,
    paddingInline: vars.space16,
  },
  detailLink: {
    alignItems: "center",
    backgroundColor: vars.colorSurfaceTint,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    gap: vars.space8,
    padding: "0.625rem",
    textAlign: "start",
    width: "100%",
    ":hover": { backgroundColor: vars.colorAccentSoft },
  },
  detailLinkCopy: { flex: 1, minWidth: 0 },
  detailLinkTitle: {
    color: vars.colorText,
    display: "block",
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
    lineHeight: vars.lineHeightTight,
  },
  detailLinkSubtitle: {
    color: vars.colorTextMuted,
    display: "block",
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightTight,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  detailSection: { display: "flex", flexDirection: "column", gap: vars.space8 },
  detailSectionTitle: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeMicro,
    letterSpacing: "0.12em",
    lineHeight: vars.lineHeightTight,
    textTransform: "uppercase",
  },
  detailMuted: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightNormal,
  },
  detailSkeletons: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space8,
  },
  detailSkeletonFull: { height: 12, width: "100%" },
  detailSkeletonEleven: { height: 12, width: "91.666667%" },
  detailSkeletonEight: { height: 12, width: "66.666667%" },
  detailComments: {
    borderTopColor: vars.colorBorder,
    borderTopStyle: "solid",
    borderTopWidth: 1,
  },
  detailAccordionTrigger: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
    paddingBlock: vars.space8,
  },
  detailAccordionContent: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space8,
    paddingBlockEnd: vars.space8,
  },
  detailComment: { display: "flex", flexDirection: "column", gap: 2 },
  detailCommentMeta: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightTight,
  },
  detailCommentBody: {
    color: vars.colorText,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightNormal,
    whiteSpace: "pre-wrap",
  },
  kickoffContent: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: vars.space20,
    minHeight: 0,
    overflowY: "auto",
    paddingBlock: vars.space16,
    paddingInline: vars.space20,
  },
  kickoffSheet: {
    gap: 0,
    padding: 0,
    width: "100%",
    "@media (min-width: 40rem)": { maxWidth: "36rem" },
  },
  kickoffHeader: {
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    flexShrink: 0,
    paddingBlockEnd: vars.space16,
    paddingBlockStart: vars.space20,
    paddingInlineEnd: "3rem",
    paddingInlineStart: vars.space20,
  },
  kickoffTicket: {
    backgroundColor: vars.colorSurfaceTint,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    flexDirection: "column",
    gap: vars.space8,
    padding: vars.space12,
  },
  kickoffTicketHeader: {
    alignItems: "flex-start",
    display: "flex",
    gap: vars.space12,
    justifyContent: "space-between",
  },
  kickoffTicketCopy: { minWidth: 0 },
  kickoffTicketTitle: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightSemibold,
    lineHeight: vars.lineHeightNormal,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  kickoffTicketMeta: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeMicro,
    lineHeight: vars.lineHeightTight,
    marginTop: 2,
  },
  kickoffSourceButton: {
    fontSize: vars.fontSizeMicro,
    gap: vars.space8,
    height: 28,
  },
  kickoffWarning: {
    backgroundColor: vars.colorWarningSoft,
    borderColor: vars.colorWarningBorder,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: 1,
    color: vars.colorWarningText,
    fontSize: vars.fontSizeMicro,
    lineHeight: vars.lineHeightTight,
    paddingBlock: vars.space8,
    paddingInline: vars.space8,
  },
  kickoffSection: { display: "grid", gap: vars.space8 },
  kickoffSectionHeading: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightSemibold,
    lineHeight: vars.lineHeightNormal,
  },
  kickoffHeadingRow: {
    alignItems: "center",
    display: "flex",
    gap: vars.space8,
    justifyContent: "space-between",
  },
  kickoffTextArea: {
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightNormal,
  },
  kickoffHint: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightNormal,
  },
  kickoffModeList: {
    alignItems: "center",
    backgroundColor: vars.colorSurfaceTint,
    borderRadius: vars.radiusControl,
    display: "flex",
    gap: 2,
    padding: 2,
  },
  kickoffMode: { flex: 1, fontSize: vars.fontSizeMicro, height: 28 },
  kickoffModeActive: {
    backgroundColor: vars.colorSurface,
    borderColor: vars.colorBorder,
  },
  kickoffReset: { gap: vars.space4 },
  icon14: { height: 14, width: 14 },
  icon12: { height: 12, width: 12 },
  kickoffCrane: {
    alignItems: "flex-start",
    backgroundColor: vars.colorSurfaceTint,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    gap: vars.space12,
    justifyContent: "space-between",
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
  },
  kickoffNotice: {
    alignItems: "flex-start",
    backgroundColor: vars.colorSurfaceTint,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    gap: vars.space12,
    padding: vars.space12,
  },
  kickoffFooter: {
    alignItems: "center",
    backgroundColor: vars.colorSurfaceTint,
    borderTopColor: vars.colorBorder,
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "flex",
    flexDirection: "row",
    flexShrink: 0,
    paddingBlock: vars.space12,
    paddingInline: vars.space20,
  },
  kickoffFooterHint: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightNormal,
    marginInlineEnd: "auto",
  },
});
