import * as stylex from "@stylexjs/stylex";

import { vars } from "../tokens/tokens.stylex";

const breathe = stylex.keyframes({
  "0%, 100%": { opacity: 0.34, transform: "scale(0.66)" },
  "48%": { opacity: 1, transform: "scale(1)" },
});
const compile = stylex.keyframes({
  "0%, 100%": { opacity: 0.56, transform: "scaleX(0.68)" },
  "50%": { opacity: 1, transform: "scaleX(1)" },
});
const route = stylex.keyframes({
  "0%": { opacity: 0, transform: "translateX(0)" },
  "16%, 84%": { opacity: 1 },
  "100%": { opacity: 0, transform: "translateX(450%)" },
});
const vision = stylex.keyframes({
  "0%, 100%": { opacity: 0.42, transform: "rotate(0deg) scale(0.72)" },
  "50%": { opacity: 1, transform: "rotate(180deg) scale(1)" },
});
const syncForward = stylex.keyframes({
  from: { opacity: 0.36, transform: "translateX(0)" },
  "45%, 55%": { opacity: 1 },
  to: { opacity: 0.36, transform: "translateX(280%)" },
});
const persist = stylex.keyframes({
  "0%, 100%": { opacity: 0.32, transform: "translateY(-1px)" },
  "44%": { opacity: 1, transform: "translateY(1px)" },
});

const loopAnimation = {
  animationDuration: vars.motionDurationLoop,
  animationFillMode: "both",
  animationIterationCount: "infinite",
  animationTimingFunction: vars.motionEaseInOut,
} as const;

export const extendedLoaderStyles = stylex.create({
  mark: {
    blockSize: "100%",
    inlineSize: "100%",
    position: "relative",
  },
  cascadeDot: {
    ...loopAnimation,
    animationName: {
      default: breathe,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    backgroundColor: "currentColor",
    blockSize: "22%",
    borderRadius: vars.radiusMark,
    inlineSize: "22%",
    opacity: {
      default: null,
      "@media (prefers-reduced-motion: reduce)": 0.64,
    },
    position: "absolute",
  },
  cascade1: { insetBlockStart: "15%", insetInlineStart: "10%" },
  cascade2: { insetBlockStart: "32%", insetInlineStart: "30%" },
  cascade3: { insetBlockStart: "49%", insetInlineStart: "50%" },
  cascade4: { insetBlockStart: "66%", insetInlineStart: "70%" },
  decode: {
    alignContent: "center",
    display: "grid",
    gap: "10%",
    gridTemplateColumns: "repeat(2, 30%)",
    justifyContent: "center",
  },
  decodeCell: {
    ...loopAnimation,
    animationName: {
      default: breathe,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    aspectRatio: "1",
    backgroundColor: "currentColor",
    borderRadius: vars.radiusMark,
    opacity: {
      default: null,
      "@media (prefers-reduced-motion: reduce)": 0.64,
    },
  },
  compile: {
    position: "relative",
  },
  compileBar: {
    ...loopAnimation,
    animationName: {
      default: compile,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    backgroundColor: "currentColor",
    blockSize: "12%",
    borderRadius: vars.radiusFull,
    inlineSize: "76%",
    insetInlineStart: "12%",
    opacity: {
      default: null,
      "@media (prefers-reduced-motion: reduce)": 0.64,
    },
    position: "absolute",
    transformOrigin: "left center",
  },
  compileTop: { insetBlockStart: "25%" },
  compileMiddle: {
    inlineSize: "58%",
    insetBlockStart: "44%",
    insetInlineStart: "21%",
  },
  compileBottom: { insetBlockStart: "63%" },
  routeRail: {
    backgroundColor: "currentColor",
    blockSize: "8%",
    borderRadius: vars.radiusFull,
    inlineSize: "72%",
    insetBlockStart: "46%",
    insetInlineStart: "14%",
    opacity: 0.22,
    position: "absolute",
  },
  routeNode: {
    backgroundColor: "currentColor",
    blockSize: "22%",
    borderColor: "currentColor",
    borderRadius: vars.radiusFull,
    borderStyle: "solid",
    borderWidth: vars.ringWidthSm,
    boxSizing: "border-box",
    inlineSize: "22%",
    insetBlockStart: "39%",
    position: "absolute",
  },
  routeStart: { insetInlineStart: "10%", opacity: 0.42 },
  routeMiddle: { insetInlineStart: "39%", opacity: 0.42 },
  routeEnd: { insetInlineEnd: "10%", opacity: 0.42 },
  routeRunner: {
    ...loopAnimation,
    animationName: {
      default: route,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    animationTimingFunction: vars.motionEaseStandard,
    backgroundColor: "currentColor",
    blockSize: "22%",
    borderRadius: vars.radiusFull,
    inlineSize: "14%",
    insetBlockStart: "39%",
    insetInlineStart: "12%",
    position: "absolute",
  },
  handoffNode: {
    ...loopAnimation,
    animationName: {
      default: breathe,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    backgroundColor: "currentColor",
    blockSize: "24%",
    borderRadius: vars.radiusFull,
    inlineSize: "24%",
    insetBlockStart: "38%",
    opacity: {
      default: null,
      "@media (prefers-reduced-motion: reduce)": 0.64,
    },
    position: "absolute",
  },
  handoff1: { insetInlineStart: "8%" },
  handoff2: { insetInlineStart: "38%" },
  handoff3: { insetInlineEnd: "8%" },
  visionFrame: {
    borderColor: "currentColor",
    borderRadius: vars.radiusMark,
    borderStyle: "solid",
    borderWidth: vars.ringWidthSm,
    insetBlock: "10%",
    insetInline: "10%",
    opacity: 0.3,
    position: "absolute",
  },
  visionIris: {
    ...loopAnimation,
    animationDuration: vars.motionDurationLoopSlow,
    animationName: {
      default: vision,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    borderBlockColor: "currentColor",
    borderInlineColor: "transparent",
    borderRadius: vars.radiusFull,
    borderStyle: "solid",
    borderWidth: vars.ringWidthMd,
    insetBlock: "24%",
    insetInline: "24%",
    position: "absolute",
  },
  visionFocus: {
    backgroundColor: "currentColor",
    blockSize: "18%",
    borderRadius: vars.radiusFull,
    inlineSize: "18%",
    insetBlockStart: "41%",
    insetInlineStart: "41%",
    position: "absolute",
  },
  exploreCenter: {
    backgroundColor: "currentColor",
    blockSize: "22%",
    borderRadius: vars.radiusFull,
    inlineSize: "22%",
    insetBlockStart: "39%",
    insetInlineStart: "39%",
    position: "absolute",
  },
  exploreBranch: {
    backgroundColor: "currentColor",
    blockSize: "6%",
    inlineSize: "28%",
    insetBlockStart: "47%",
    insetInlineStart: "50%",
    opacity: 0.24,
    position: "absolute",
    transformOrigin: "left center",
  },
  exploreBranch1: { transform: "rotate(-55deg)" },
  exploreBranch2: { transform: "rotate(0deg)" },
  exploreBranch3: { transform: "rotate(55deg)" },
  exploreLeaf: {
    ...loopAnimation,
    animationName: {
      default: breathe,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    backgroundColor: "currentColor",
    blockSize: "20%",
    borderRadius: vars.radiusFull,
    inlineSize: "20%",
    opacity: {
      default: null,
      "@media (prefers-reduced-motion: reduce)": 0.64,
    },
    position: "absolute",
  },
  exploreLeaf1: { insetBlockStart: "8%", insetInlineEnd: "8%" },
  exploreLeaf2: { insetBlockStart: "40%", insetInlineEnd: "8%" },
  exploreLeaf3: { insetBlockEnd: "8%", insetInlineEnd: "8%" },
  syncRail: {
    backgroundColor: "currentColor",
    blockSize: "8%",
    borderRadius: vars.radiusFull,
    inlineSize: "72%",
    insetInlineStart: "14%",
    opacity: 0.2,
    position: "absolute",
  },
  syncRailTop: { insetBlockStart: "30%" },
  syncRailBottom: { insetBlockEnd: "30%" },
  syncRunner: {
    ...loopAnimation,
    animationName: {
      default: syncForward,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    backgroundColor: "currentColor",
    blockSize: "18%",
    borderRadius: vars.radiusFull,
    inlineSize: "18%",
    insetInlineStart: "16%",
    position: "absolute",
  },
  syncRunnerTop: { insetBlockStart: "25%" },
  syncRunnerBottom: {
    animationDirection: "reverse",
    insetBlockEnd: "25%",
  },
  verifyFrame: {
    borderColor: "currentColor",
    borderRadius: vars.radiusMark,
    borderStyle: "solid",
    borderWidth: vars.ringWidthSm,
    insetBlock: "20%",
    insetInline: "20%",
    opacity: 0.22,
    position: "absolute",
  },
  verifyPoint: {
    ...loopAnimation,
    animationName: {
      default: breathe,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    backgroundColor: "currentColor",
    blockSize: "20%",
    borderRadius: vars.radiusFull,
    inlineSize: "20%",
    opacity: {
      default: null,
      "@media (prefers-reduced-motion: reduce)": 0.64,
    },
    position: "absolute",
  },
  verify1: { insetBlockStart: "10%", insetInlineStart: "10%" },
  verify2: { insetBlockStart: "10%", insetInlineEnd: "10%" },
  verify3: { insetBlockEnd: "10%", insetInlineEnd: "10%" },
  verify4: { insetBlockEnd: "10%", insetInlineStart: "10%" },
  persistLayer: {
    ...loopAnimation,
    animationName: {
      default: persist,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    backgroundColor: "currentColor",
    blockSize: "16%",
    borderRadius: vars.radiusMark,
    inlineSize: "72%",
    insetInlineStart: "14%",
    opacity: {
      default: null,
      "@media (prefers-reduced-motion: reduce)": 0.64,
    },
    position: "absolute",
  },
  persist1: { insetBlockStart: "18%" },
  persist2: { insetBlockStart: "42%" },
  persist3: { insetBlockStart: "66%" },
  phase0: { animationDelay: "0ms" },
  phase1: { animationDelay: "120ms" },
  phase2: { animationDelay: "240ms" },
  phase3: { animationDelay: "360ms" },
});
