import * as stylex from "@stylexjs/stylex";

import { vars } from "../../ads/tokens/tokens.stylex";

export const standaloneCliStyles = stylex.create({
  /** Popup sizing: the terminal wants the room, bounded by the positioner. */
  popoverEmpty: { gap: 0, padding: 0, width: "min(34rem, 92vw)" },
  popoverTerminal: {
    gap: 0,
    height: "min(40rem, var(--available-height, 100vh))",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    padding: 0,
    width: "min(60rem, 92vw)",
  },

  panel: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    width: "100%",
  },
  panelHeader: {
    alignItems: "center",
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    display: "flex",
    flexShrink: 0,
    gap: vars.space12,
    justifyContent: "space-between",
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
  },
  panelHeaderLead: {
    alignItems: "center",
    display: "flex",
    gap: vars.space12,
    minWidth: 0,
  },
  folderLabel: {
    color: vars.colorTextMuted,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeCaption,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  closeButton: {
    blockSize: 28,
    color: { default: vars.colorTextMuted, ":hover": vars.colorText },
    flexShrink: 0,
    inlineSize: 28,
    padding: 0,
  },
  emptyState: {
    alignItems: "flex-start",
    display: "flex",
    flexDirection: "column",
    gap: vars.space12,
    paddingBlock: vars.space24,
    paddingInline: vars.space16,
  },
  emptyStateText: { color: vars.colorTextMuted, fontSize: vars.fontSizeBody },

  tabBar: { alignItems: "center", display: "flex", gap: vars.space4 },
  tab: {
    blockSize: 28,
    color: { default: vars.colorTextMuted, ":hover": vars.colorText },
    fontSize: vars.fontSizeCaption,
    gap: vars.space8,
    paddingInline: vars.space8,
  },
  tabActive: {
    backgroundColor: vars.colorSelectionFill,
    color: vars.colorText,
  },
  tabIcon: { blockSize: 14, inlineSize: 14 },

  terminalColumn: {
    display: "flex",
    flexDirection: "column",
    flexGrow: 1,
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
  },
  terminalHeader: {
    alignItems: "center",
    backgroundColor: vars.colorSurface,
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    display: "flex",
    flexShrink: 0,
    gap: vars.space8,
    justifyContent: "flex-end",
    paddingBlock: 6,
    paddingInline: vars.space12,
  },
  restartButton: {
    backgroundColor: vars.colorSurface,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusMark,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    color: { default: vars.colorTextMuted, ":hover": vars.colorText },
    fontSize: vars.fontSizeMicro,
    paddingBlock: vars.space4,
    paddingInline: vars.space8,
  },
  statusBanner: {
    alignItems: "center",
    backgroundColor: vars.colorSurface,
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    color: vars.colorDanger,
    display: "flex",
    fontSize: vars.fontSizeCaption,
    gap: vars.space12,
    insetInline: 0,
    justifyContent: "space-between",
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
    position: "absolute",
    top: 0,
    zIndex: 20,
  },
  statusText: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  statusAction: {
    borderRadius: vars.radiusMark,
    color: { default: vars.colorTextMuted, ":hover": vars.colorText },
    flexShrink: 0,
    fontSize: vars.fontSizeMicro,
    paddingBlock: vars.space4,
    paddingInline: vars.space8,
  },
  exitedBanner: {
    backgroundColor: vars.colorSurface,
    borderTopColor: vars.colorBorder,
    borderTopStyle: "solid",
    borderTopWidth: vars.borderWidthHairline,
    bottom: 0,
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    insetInline: 0,
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
    position: "absolute",
    zIndex: 20,
  },
  bootOverlay: {
    alignItems: "center",
    backgroundColor: "var(--terminal)",
    display: "flex",
    inset: 0,
    justifyContent: "center",
    position: "absolute",
    zIndex: 10,
  },
  bootLabel: {
    alignItems: "center",
    color: vars.colorTextMuted,
    display: "flex",
    fontSize: vars.fontSizeBody,
    gap: vars.space8,
  },
});
