import * as stylex from "@stylexjs/stylex";

import { vars } from "../../ads/tokens/tokens.stylex";

export const standaloneCliStyles = stylex.create({
  /** Popup sizing: the terminal wants the room, bounded by the positioner. */
  popoverEmpty: { gap: 0, padding: 0, width: "min(34rem, 92vw)" },
  popoverTerminal: {
    gap: 0,
    height: "min(40rem, var(--available-height, 100vh))",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    padding: 0,
    width: "min(60rem, 92vw)",
  },

  panel: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    width: "100%",
  },
  panelHeader: {
    alignItems: "center",
    borderBottomColor: vars["--ads-color-border"],
    borderBottomStyle: "solid",
    borderBottomWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    flexShrink: 0,
    gap: vars["--ads-space-12"],
    justifyContent: "space-between",
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
  },
  panelHeaderLead: {
    alignItems: "center",
    display: "flex",
    gap: vars["--ads-space-12"],
    minWidth: 0,
  },
  folderLabel: {
    color: vars["--ads-color-text-muted"],
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-caption"],
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  closeButton: {
    blockSize: 28,
    color: { default: vars["--ads-color-text-muted"], ":hover": vars["--ads-color-text"] },
    flexShrink: 0,
    inlineSize: 28,
    padding: 0,
  },
  emptyState: {
    alignItems: "flex-start",
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-12"],
    paddingBlock: vars["--ads-space-24"],
    paddingInline: vars["--ads-space-16"],
  },
  emptyStateText: { color: vars["--ads-color-text-muted"], fontSize: vars["--ads-font-size-body"] },

  tabBar: { alignItems: "center", display: "flex", gap: vars["--ads-space-4"] },
  tab: {
    blockSize: 28,
    color: { default: vars["--ads-color-text-muted"], ":hover": vars["--ads-color-text"] },
    fontSize: vars["--ads-font-size-caption"],
    gap: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-8"],
  },
  tabActive: {
    backgroundColor: vars["--ads-color-selection-fill"],
    color: vars["--ads-color-text"],
  },
  tabIcon: { blockSize: 14, inlineSize: 14 },

  terminalColumn: {
    display: "flex",
    flexDirection: "column",
    flexGrow: 1,
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
  },
  terminalHeader: {
    alignItems: "center",
    backgroundColor: vars["--ads-color-surface"],
    borderBottomColor: vars["--ads-color-border"],
    borderBottomStyle: "solid",
    borderBottomWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    flexShrink: 0,
    gap: vars["--ads-space-8"],
    justifyContent: "flex-end",
    paddingBlock: 6,
    paddingInline: vars["--ads-space-12"],
  },
  restartButton: {
    backgroundColor: vars["--ads-color-surface"],
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-mark"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    color: { default: vars["--ads-color-text-muted"], ":hover": vars["--ads-color-text"] },
    fontSize: vars["--ads-font-size-micro"],
    paddingBlock: vars["--ads-space-4"],
    paddingInline: vars["--ads-space-8"],
  },
  statusBanner: {
    alignItems: "center",
    backgroundColor: vars["--ads-color-surface"],
    borderBottomColor: vars["--ads-color-border"],
    borderBottomStyle: "solid",
    borderBottomWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-danger"],
    display: "flex",
    fontSize: vars["--ads-font-size-caption"],
    gap: vars["--ads-space-12"],
    insetInline: 0,
    justifyContent: "space-between",
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
    position: "absolute",
    top: 0,
    zIndex: 20,
  },
  statusText: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  statusAction: {
    borderRadius: vars["--ads-radius-mark"],
    color: { default: vars["--ads-color-text-muted"], ":hover": vars["--ads-color-text"] },
    flexShrink: 0,
    fontSize: vars["--ads-font-size-micro"],
    paddingBlock: vars["--ads-space-4"],
    paddingInline: vars["--ads-space-8"],
  },
  exitedBanner: {
    backgroundColor: vars["--ads-color-surface"],
    borderTopColor: vars["--ads-color-border"],
    borderTopStyle: "solid",
    borderTopWidth: vars["--ads-border-width-hairline"],
    bottom: 0,
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    insetInline: 0,
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
    position: "absolute",
    zIndex: 20,
  },
  bootOverlay: {
    alignItems: "center",
    backgroundColor: "var(--terminal)",
    display: "flex",
    inset: 0,
    justifyContent: "center",
    position: "absolute",
    zIndex: 10,
  },
  bootLabel: {
    alignItems: "center",
    color: vars["--ads-color-text-muted"],
    display: "flex",
    fontSize: vars["--ads-font-size-body"],
    gap: vars["--ads-space-8"],
  },
});
