import * as stylex from "@stylexjs/stylex";

import { vars } from "@/components/ads/tokens/tokens.stylex";

export const chatPanelFileBlocksStyles = stylex.create({
  changeCountBase: {
    flexShrink: 0,
    fontSize: "0.875em",
    fontWeight: vars["--ads-font-weight-medium"],
    fontVariantNumeric: "tabular-nums",
  },
  changeCountAdded: { color: vars["--ads-color-diff-added-text"] },
  changeCountRemoved: { color: vars["--ads-color-diff-removed-text"] },
  card: { gap: 0, overflow: "hidden", padding: 0 },
  cardHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: vars["--ads-space-12"],
    borderBottomWidth: vars["--ads-border-width-hairline"],
    borderBottomStyle: "solid",
    borderBottomColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface-tint"],
    paddingInline: vars["--ads-space-12"],
    paddingBlock: vars["--ads-space-8"],
  },
  cardHeaderInfo: {
    display: "flex",
    minWidth: 0,
    flexWrap: "wrap",
    alignItems: "center",
    columnGap: vars["--ads-space-8"],
    rowGap: vars["--ads-space-4"],
  },
  headerTitleSmall: { fontSize: "0.875em", fontWeight: vars["--ads-font-weight-medium"] },
  headerTitleBody: {
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  shrink0: { flexShrink: 0 },
  divideList: {
    display: "flex",
    flexDirection: "column",
  },
  rowWrapper: {
    borderTopWidth: vars["--ads-border-width-hairline"],
    borderTopStyle: "solid",
    borderTopColor: vars["--ads-color-border"],
  },
  rowWrapperFirst: { borderTopWidth: 0 },
  rowButton: {
    display: "flex",
    width: "100%",
    alignItems: "center",
    gap: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
    paddingBlock: vars["--ads-space-8"],
    textAlign: "left",
    backgroundColor: {
      default: "transparent",
      ":hover": vars["--ads-color-overlay-hover"],
    },
  },
  filePath: {
    minWidth: 0,
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontWeight: vars["--ads-font-weight-medium"],
  },
  pendingDot: {
    width: 8,
    height: 8,
    flexShrink: 0,
    borderRadius: vars["--ads-radius-full"],
    backgroundColor: vars["--ads-color-warning"],
  },
  chevron: {
    width: 16,
    height: 16,
    flexShrink: 0,
    color: vars["--ads-color-text-muted"],
  },
  expandedBody: {
    borderTopWidth: vars["--ads-border-width-hairline"],
    borderTopStyle: "solid",
    borderTopColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface"],
  },
  diffScroll: { overflowX: "auto" },
  inlineDiff: { borderRadius: 0, borderWidth: 0 },
  diffLoading: {
    paddingInline: vars["--ads-space-12"],
    paddingBlock: vars["--ads-space-8"],
    fontSize: "0.875em",
    color: vars["--ads-color-text-muted"],
  },
  actionBar: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: vars["--ads-space-8"],
    borderTopWidth: vars["--ads-border-width-hairline"],
    borderTopStyle: "solid",
    borderTopColor: vars["--ads-color-border"],
    paddingInline: vars["--ads-space-12"],
    paddingBlock: vars["--ads-space-8"],
  },
  staticFileRow: {
    display: "flex",
    alignItems: "center",
    gap: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
    paddingBlock: vars["--ads-space-8"],
    borderTopWidth: vars["--ads-border-width-hairline"],
    borderTopStyle: "solid",
    borderTopColor: vars["--ads-color-border"],
  },
  staticFileRowFirst: { borderTopWidth: 0 },
  codeBlock: {
    margin: 0,
    borderRadius: 0,
    borderWidth: 0,
    borderBottomWidth: vars["--ads-border-width-hairline"],
    borderBottomStyle: "solid",
    borderBottomColor: vars["--ads-color-border"],
  },
  codeBlockHeader: { borderBottomColor: vars["--ads-color-border"] },
  instruction: {
    borderTopWidth: vars["--ads-border-width-hairline"],
    borderTopStyle: "solid",
    borderTopColor: vars["--ads-color-border"],
    paddingInline: vars["--ads-space-12"],
    paddingBlock: vars["--ads-space-8"],
    fontSize: "0.875em",
    color: vars["--ads-color-text-muted"],
  },
  imageGrid: {
    display: "flex",
    flexWrap: "wrap",
    gap: vars["--ads-space-8"],
  },
  imageCard: {
    overflow: "hidden",
    borderRadius: vars["--ads-radius-control"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
  },
  image: {
    maxHeight: "12rem",
    cursor: "zoom-in",
    objectFit: "contain",
  },
  imageLabel: {
    borderTopWidth: vars["--ads-border-width-hairline"],
    borderTopStyle: "solid",
    borderTopColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface-tint"],
    paddingInline: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-4"],
    fontSize: "0.75em",
    color: vars["--ads-color-text-muted"],
  },
});
