import * as stylex from "@stylexjs/stylex";

import { vars } from "@/components/ads/tokens/tokens.stylex";

export const chatPanelFileBlocksStyles = stylex.create({
  changeCountBase: {
    flexShrink: 0,
    fontSize: "0.875em",
    fontWeight: vars.fontWeightMedium,
    fontVariantNumeric: "tabular-nums",
  },
  changeCountAdded: { color: vars.colorSuccess },
  changeCountRemoved: { color: vars.colorDanger },
  card: { gap: 0, overflow: "hidden", padding: 0 },
  cardHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: vars.space12,
    borderBottomWidth: vars.borderWidthHairline,
    borderBottomStyle: "solid",
    borderBottomColor: vars.colorBorder,
    backgroundColor: vars.colorSurfaceTint,
    paddingInline: vars.space12,
    paddingBlock: vars.space8,
  },
  cardHeaderInfo: {
    display: "flex",
    minWidth: 0,
    flexWrap: "wrap",
    alignItems: "center",
    columnGap: vars.space8,
    rowGap: vars.space4,
  },
  headerTitleSmall: { fontSize: "0.875em", fontWeight: vars.fontWeightMedium },
  headerTitleBody: {
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
  },
  shrink0: { flexShrink: 0 },
  divideList: {
    display: "flex",
    flexDirection: "column",
  },
  rowWrapper: {
    borderTopWidth: vars.borderWidthHairline,
    borderTopStyle: "solid",
    borderTopColor: vars.colorBorder,
  },
  rowWrapperFirst: { borderTopWidth: 0 },
  rowButton: {
    display: "flex",
    width: "100%",
    alignItems: "center",
    gap: vars.space8,
    paddingInline: vars.space12,
    paddingBlock: vars.space8,
    textAlign: "left",
    backgroundColor: {
      default: "transparent",
      ":hover": vars.colorOverlayHover,
    },
  },
  filePath: {
    minWidth: 0,
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontWeight: vars.fontWeightMedium,
  },
  pendingDot: {
    width: 8,
    height: 8,
    flexShrink: 0,
    borderRadius: vars.radiusFull,
    backgroundColor: vars.colorWarning,
  },
  chevron: {
    width: 16,
    height: 16,
    flexShrink: 0,
    color: vars.colorTextMuted,
  },
  expandedBody: {
    borderTopWidth: vars.borderWidthHairline,
    borderTopStyle: "solid",
    borderTopColor: vars.colorBorder,
    backgroundColor: vars.colorSurface,
  },
  diffScroll: { overflowX: "auto" },
  diffLoading: {
    paddingInline: vars.space12,
    paddingBlock: vars.space8,
    fontSize: "0.875em",
    color: vars.colorTextMuted,
  },
  actionBar: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: vars.space8,
    borderTopWidth: vars.borderWidthHairline,
    borderTopStyle: "solid",
    borderTopColor: vars.colorBorder,
    paddingInline: vars.space12,
    paddingBlock: vars.space8,
  },
  staticFileRow: {
    display: "flex",
    alignItems: "center",
    gap: vars.space8,
    paddingInline: vars.space12,
    paddingBlock: vars.space8,
    borderTopWidth: vars.borderWidthHairline,
    borderTopStyle: "solid",
    borderTopColor: vars.colorBorder,
  },
  staticFileRowFirst: { borderTopWidth: 0 },
  codeBlock: {
    margin: 0,
    borderRadius: 0,
    borderWidth: 0,
    borderBottomWidth: vars.borderWidthHairline,
    borderBottomStyle: "solid",
    borderBottomColor: vars.colorBorder,
  },
  codeBlockHeader: { borderBottomColor: vars.colorBorder },
  instruction: {
    borderTopWidth: vars.borderWidthHairline,
    borderTopStyle: "solid",
    borderTopColor: vars.colorBorder,
    paddingInline: vars.space12,
    paddingBlock: vars.space8,
    fontSize: "0.875em",
    color: vars.colorTextMuted,
  },
  imageGrid: {
    display: "flex",
    flexWrap: "wrap",
    gap: vars.space8,
  },
  imageCard: {
    overflow: "hidden",
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: vars.colorBorder,
  },
  image: {
    maxHeight: "12rem",
    cursor: "zoom-in",
    objectFit: "contain",
  },
  imageLabel: {
    borderTopWidth: vars.borderWidthHairline,
    borderTopStyle: "solid",
    borderTopColor: vars.colorBorder,
    backgroundColor: vars.colorSurfaceTint,
    paddingInline: vars.space8,
    paddingBlock: vars.space4,
    fontSize: "0.75em",
    color: vars.colorTextMuted,
  },
});
