import * as stylex from "@stylexjs/stylex";
import { vars } from "@/components/ads/tokens/tokens.stylex";

export const usageStyles = stylex.create({
  scroll: { flex: "1 1 auto", blockSize: "100%", minBlockSize: 0, minInlineSize: 0, overflowY: "auto", backgroundColor: vars["--ads-color-canvas"] },
  page: { display: "flex", flexDirection: "column", gap: vars["--ads-space-24"], maxInlineSize: "76rem", marginInline: "auto",
    paddingBlock: vars["--ads-space-24"], paddingInline: { default: vars["--ads-space-24"], "@media (max-width: 700px)": vars["--ads-space-12"] } },
  header: { display: "flex", flexWrap: "wrap", alignItems: "start", justifyContent: "space-between", gap: vars["--ads-space-12"] },
  headerCopy: { flex: "1 1 200px" },
  control: { flexShrink: 0 },
  title: { margin: 0, fontSize: vars["--ads-font-size-heading"], fontWeight: vars["--ads-font-weight-semibold"], color: vars["--ads-color-text"] },
  heading: { margin: 0, fontSize: vars["--ads-font-size-lead"], fontWeight: vars["--ads-font-weight-medium"], color: vars["--ads-color-text"] },
  note: { margin: 0, color: vars["--ads-color-text-muted"], fontSize: vars["--ads-font-size-caption"], lineHeight: vars["--ads-line-height-normal"] },
  stack: { display: "flex", flexDirection: "column", gap: vars["--ads-space-8"], minInlineSize: 0 },
  section: { display: "flex", flexDirection: "column", gap: vars["--ads-space-12"], minInlineSize: 0 },
  viewTabs: { alignSelf: "start", maxInlineSize: "100%" },
  row: { display: "flex", alignItems: "center", gap: vars["--ads-space-8"], flexWrap: "wrap" },
  filters: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 180px), 1fr))", gap: vars["--ads-space-12"], alignItems: "end" },
  field: { display: "grid", gap: vars["--ads-space-8"], fontSize: vars["--ads-font-size-caption"], color: vars["--ads-color-text-muted"] },
  figures: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 160px), 1fr))", gap: vars["--ads-space-16"], paddingBlock: vars["--ads-space-16"],
    borderBlockWidth: vars["--ads-border-width-hairline"], borderBlockStyle: "solid", borderBlockColor: vars["--ads-color-border"] },
  figure: { display: "grid", gap: vars["--ads-space-8"], minInlineSize: 0 },
  value: { margin: 0, fontSize: vars["--ads-font-size-heading"], fontWeight: vars["--ads-font-weight-semibold"], color: vars["--ads-color-text"], fontVariantNumeric: "tabular-nums" },
  columns: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 320px), 1fr))", gap: vars["--ads-space-24"] },
  quotas: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 260px), 1fr))", gap: vars["--ads-space-16"] },
  quota: { display: "grid", gap: vars["--ads-space-8"], minInlineSize: 0, padding: vars["--ads-space-12"], backgroundColor: vars["--ads-color-surface-tint"], borderRadius: vars["--ads-radius-panel"] },
  quotaWindow: { display: "grid", gap: vars["--ads-space-8"], minInlineSize: 0, paddingBlockStart: vars["--ads-space-8"] },
  track: { blockSize: 6, backgroundColor: vars["--ads-color-border"], borderRadius: vars["--ads-radius-full"], overflow: "hidden" },
  fill: { blockSize: "100%", backgroundColor: vars["--ads-color-accent"], borderRadius: vars["--ads-radius-full"] },
  warning: { backgroundColor: vars["--ads-color-warning"] },
  danger: { backgroundColor: vars["--ads-color-danger"] },
  tableScroll: { minInlineSize: 0, overflowX: "auto" },
  number: { fontVariantNumeric: "tabular-nums", whiteSpace: "nowrap" },
  end: { textAlign: "end", fontVariantNumeric: "tabular-nums", whiteSpace: "nowrap" },
  wrap: { overflowWrap: "anywhere", maxInlineSize: "20rem" },
  history: { containerType: "inline-size", containerName: "usageHistory" },
  historyDate: { margin: 0, fontSize: vars["--ads-font-size-body"], fontWeight: vars["--ads-font-weight-medium"] },
  historyList: { listStyle: "none", margin: 0, padding: 0 },
  historyTurn: { borderBlockEndWidth: vars["--ads-border-width-hairline"], borderBlockEndStyle: "solid", borderBlockEndColor: vars["--ads-color-border"],
    "--usageTurnRotation": { default: "0deg", ":is([open])": "90deg" } },
  historySummary: { display: "grid", gridTemplateColumns: { default: "4.5rem minmax(0, 1fr) minmax(12rem, 16rem) 1rem", "@container usageHistory (max-width: 700px)": "3.5rem minmax(0, 1fr) 1rem" },
    gap: vars["--ads-space-12"], alignItems: "center", paddingBlock: vars["--ads-space-12"], paddingInline: vars["--ads-space-8"],
    cursor: "pointer", listStyle: "none", borderRadius: vars["--ads-radius-control"],
    backgroundColor: { default: "transparent", ":hover": vars["--ads-color-overlay-hover"] }, "::-webkit-details-marker": { display: "none" } },
  historyIdentity: { display: "grid", gap: vars["--ads-space-4"], minInlineSize: 0 },
  historyModel: { overflowWrap: "anywhere", fontWeight: vars["--ads-font-weight-medium"] },
  historyAccount: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  historyMetrics: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: vars["--ads-space-12"], minInlineSize: 0,
    gridColumn: { default: "auto", "@container usageHistory (max-width: 700px)": "2" }, gridRow: { default: "auto", "@container usageHistory (max-width: 700px)": "2" } },
  historyMetric: { display: "grid", gap: vars["--ads-space-4"], textAlign: { default: "end", "@container usageHistory (max-width: 700px)": "start" } },
  historyChevron: { inlineSize: 16, blockSize: 16, color: vars["--ads-color-text-muted"], transform: "rotate(var(--usageTurnRotation))",
    gridColumn: { default: "auto", "@container usageHistory (max-width: 700px)": "3" }, gridRow: { default: "auto", "@container usageHistory (max-width: 700px)": "1" } },
  historyDetails: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 180px), 1fr))", gap: vars["--ads-space-16"],
    margin: 0, paddingInline: vars["--ads-space-8"], paddingBlockEnd: vars["--ads-space-16"] },
  historyDetailValue: { margin: 0, overflowWrap: "anywhere", fontVariantNumeric: "tabular-nums" },
  chartScroll: { overflowX: "auto", minInlineSize: 0, paddingBlockEnd: vars["--ads-space-8"] },
  chart: { display: "flex", alignItems: "end", gap: 4, blockSize: 180, minInlineSize: "100%", borderBlockEndWidth: vars["--ads-border-width-hairline"], borderBlockEndStyle: "solid", borderBlockEndColor: vars["--ads-color-border"] },
  bar: { flex: "1 0 12px", minInlineSize: 12, minBlockSize: 3, padding: 0, borderWidth: 0, borderRadius: vars["--ads-radius-mark"], backgroundColor: vars["--ads-color-accent"],
    cursor: "pointer", opacity: { default: 0.85, ":hover": 1, ":focus-visible": 1 } },
  barEmpty: { backgroundColor: vars["--ads-color-border"] },
  chartEnds: { display: "flex", justifyContent: "space-between", gap: vars["--ads-space-12"], fontSize: vars["--ads-font-size-caption"], color: vars["--ads-color-text-muted"] },
  loading: { opacity: 0.55, pointerEvents: "none" },
  svgLabel: { fill: vars["--ads-color-text-muted"], fontSize: vars["--ads-font-size-caption"] },
  svgAxis: { stroke: vars["--ads-color-border"] },
  svgPoint: { fill: vars["--ads-color-accent"] },
});
