import * as stylex from "@stylexjs/stylex";

import { vars } from "../ads/tokens/tokens.stylex";

export const compareRunPanelStyles = stylex.create({
  // Empty state (no compare run selected)
  emptyViewport: {
    alignItems: "center",
    backgroundColor: vars.colorCanvas,
    display: "flex",
    height: "100%",
    justifyContent: "center",
    padding: vars.space24,
  },
  emptyRoot: {
    backgroundColor: "transparent",
    borderStyle: "none",
    padding: 0,
  },
  emptyHeader: {
    gap: vars.space12,
  },
  emptyMedia: {
    backgroundColor: vars.colorAccentSoft,
    borderRadius: vars.radiusFrame,
    color: vars.colorAccent,
    // Logical names, matching the keys ADS `emptyStateStyles.media` declares
    // (`inlineSize: 48` / `minBlockSize: 48`). StyleX treats `width` and
    // `inlineSize` as distinct atomic properties, so overriding with the
    // physical name would leave the medallion 48px on whichever axis ADS still
    // owns and render it non-square.
    blockSize: 56,
    inlineSize: 56,
    minBlockSize: 56,
  },
  emptyTextGroup: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space4,
  },
  emptyTitle: {
    fontSize: vars.fontSizeHeading,
    fontWeight: vars.fontWeightSemibold,
  },
  emptyDescription: {
    fontSize: vars.fontSizeBody,
    maxWidth: "28rem",
  },

  // Root shell
  root: {
    backgroundColor: vars.colorCanvas,
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
  },

  // Header region
  header: {
    backgroundColor: vars.colorSurface,
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    flexShrink: 0,
    paddingBlock: vars.space16,
    paddingInline: vars.space20,
  },
  headerRow: {
    alignItems: "flex-start",
    display: "flex",
    flexWrap: "wrap",
    gap: vars.space16,
    justifyContent: "space-between",
  },
  headerMain: {
    minWidth: 0,
  },
  headerTitleRow: {
    alignItems: "center",
    display: "flex",
    gap: vars.space8,
  },
  headerIcon: {
    color: vars.colorAccent,
    height: 16,
    width: 16,
  },
  headerTitle: {
    color: vars.colorText,
    fontSize: vars.fontSizeLead,
    fontWeight: vars.fontWeightSemibold,
    letterSpacing: "-0.01em",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  promptRow: {
    alignItems: "flex-start",
    display: "flex",
    fontSize: vars.fontSizeCaption,
    gap: vars.space8,
    marginTop: vars.space8,
    maxWidth: "48rem",
  },
  promptLabel: {
    color: vars.colorTextMuted,
    flexShrink: 0,
    fontWeight: vars.fontWeightSemibold,
    letterSpacing: "0.1em",
    textTransform: "uppercase",
  },
  promptText: {
    color: vars.colorText,
    display: "-webkit-box",
    overflow: "hidden",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
  },
  headerActions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: vars.space8,
  },
  actionButton: {
    height: 32,
  },
  actionButtonShrink: {
    flexShrink: 0,
    height: 32,
  },

  // Stepper
  stepper: {
    backgroundColor: vars.colorCanvas,
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    display: "grid",
    flexShrink: 0,
    gridTemplateColumns: "repeat(5, minmax(0, 1fr))",
  },
  step: {
    minWidth: 0,
    paddingBlock: vars.space12,
    paddingInline: vars.space16,
    position: "relative",
  },
  stepDivider: {
    borderRightColor: vars.colorBorder,
    borderRightStyle: "solid",
    borderRightWidth: vars.borderWidthHairline,
  },
  stepActive: {
    backgroundColor: vars.colorAccentSoft,
  },
  stepHeadRow: {
    alignItems: "center",
    display: "flex",
    gap: vars.space8,
  },
  stepBadge: {
    alignItems: "center",
    borderColor: vars.colorBorderStrong,
    borderRadius: vars.radiusFull,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    color: vars.colorTextMuted,
    display: "inline-flex",
    flexShrink: 0,
    fontSize: vars.fontSizeMicro,
    fontVariantNumeric: "tabular-nums",
    fontWeight: vars.fontWeightSemibold,
    height: 20,
    justifyContent: "center",
    width: 20,
  },
  stepBadgeActive: {
    backgroundColor: vars.colorAccent,
    borderColor: vars.colorAccent,
    color: vars.colorAccentText,
  },
  stepBadgeComplete: {
    backgroundColor: vars.colorSuccessSoft,
    borderColor: vars.colorSuccessBorder,
    color: vars.colorSuccessText,
  },
  stepLabel: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightSemibold,
  },
  stepLabelActive: {
    color: vars.colorText,
  },
  stepDescription: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeMicro,
    marginTop: vars.space4,
    overflow: "hidden",
    paddingLeft: "1.75rem",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  stepUnderline: {
    backgroundColor: vars.colorAccent,
    bottom: 0,
    height: 2,
    insetInline: 0,
    position: "absolute",
  },

  // Terminal notice
  notice: {
    alignItems: "flex-start",
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    display: "flex",
    flexShrink: 0,
    gap: vars.space12,
    paddingBlock: vars.space12,
    paddingInline: vars.space20,
  },
  noticeNeutral: {
    backgroundColor: vars.colorSurface,
    borderBottomColor: vars.colorBorder,
  },
  noticeDestructive: {
    backgroundColor: vars.colorDangerSoft,
    borderBottomColor: vars.colorDangerBorder,
  },
  noticeIcon: {
    flexShrink: 0,
    height: 16,
    marginTop: 2,
    width: 16,
  },
  noticeIconNeutral: {
    color: vars.colorTextMuted,
  },
  noticeIconDestructive: {
    color: vars.colorDanger,
  },
  noticeBody: {
    minWidth: 0,
  },
  noticeTitle: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightSemibold,
  },
  noticeDescription: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: "1.25rem",
    marginTop: 2,
  },

  // Judge banner
  judge: {
    alignItems: "flex-start",
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    display: "flex",
    flexShrink: 0,
    gap: vars.space12,
    paddingBlock: vars.space12,
    paddingInline: vars.space20,
  },
  judgeNeutral: {
    backgroundColor: vars.colorSurface,
    borderBottomColor: vars.colorBorder,
  },
  judgeFailed: {
    backgroundColor: vars.colorWarningSoft,
    borderBottomColor: vars.colorWarningBorder,
  },
  judgeCompleted: {
    backgroundColor: vars.colorAccentSoft,
    borderBottomColor: vars.colorBorder,
  },
  judgeMark: {
    alignItems: "center",
    borderRadius: vars.radiusControl,
    display: "flex",
    flexShrink: 0,
    height: 32,
    justifyContent: "center",
    marginTop: 2,
    width: 32,
  },
  judgeMarkNeutral: {
    backgroundColor: vars.colorAccentSoft,
    color: vars.colorAccent,
  },
  judgeMarkFailed: {
    backgroundColor: vars.colorWarningSoft,
    color: vars.colorWarningText,
  },
  judgeBody: {
    flex: 1,
    minWidth: 0,
  },
  judgeHeadRow: {
    alignItems: "center",
    columnGap: vars.space8,
    display: "flex",
    flexWrap: "wrap",
    rowGap: vars.space4,
  },
  judgeTitle: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightSemibold,
  },
  judgeScore: {
    color: vars.colorAccent,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightSemibold,
  },
  judgeMeta: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
  },
  judgeRationale: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: "1.25rem",
    marginTop: vars.space4,
  },

  // Review contract row
  review: {
    alignItems: "center",
    backgroundColor: vars.colorSurface,
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    columnGap: vars.space20,
    display: "flex",
    flexShrink: 0,
    flexWrap: "wrap",
    paddingBlock: vars.space12,
    paddingInline: vars.space20,
    rowGap: vars.space8,
  },
  reviewHead: {
    alignItems: "center",
    display: "flex",
    gap: vars.space8,
  },
  reviewIcon: {
    color: vars.colorAccent,
    height: 16,
    width: 16,
  },
  reviewHeadLabel: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightSemibold,
  },
  reviewCriteria: {
    alignItems: "center",
    columnGap: vars.space16,
    display: "flex",
    flexWrap: "wrap",
    minWidth: 0,
    rowGap: vars.space4,
  },
  reviewCriterion: {
    alignItems: "center",
    color: vars.colorTextMuted,
    display: "inline-flex",
    fontSize: vars.fontSizeCaption,
    gap: 6,
  },
  reviewDot: {
    backgroundColor: vars.colorAccent,
    borderRadius: vars.radiusFull,
    height: 4,
    width: 4,
  },

  // Grid + variant cards
  scroller: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    padding: vars.space16,
  },
  grid: {
    backgroundColor: vars.colorSurface,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    boxShadow: vars.elevationRaised,
    display: "grid",
    minWidth: 760,
    overflow: "hidden",
  },
  variant: {
    display: "flex",
    flexDirection: "column",
    minHeight: "23rem",
    minWidth: 0,
  },
  variantDivider: {
    borderLeftColor: vars.colorBorder,
    borderLeftStyle: "solid",
    borderLeftWidth: vars.borderWidthHairline,
  },
  variantRecommended: {
    backgroundColor: vars.colorAccentSoft,
  },
  variantHeader: {
    backgroundColor: vars.colorSurface,
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    paddingBlock: vars.space12,
    paddingInline: vars.space16,
  },
  variantHeaderRow: {
    alignItems: "flex-start",
    display: "flex",
    gap: vars.space12,
    justifyContent: "space-between",
  },
  variantTitleRow: {
    alignItems: "center",
    display: "flex",
    gap: vars.space8,
  },
  variantIndex: {
    color: vars.colorTextMuted,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeMicro,
  },
  variantTitle: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightSemibold,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  statusChip: {
    alignItems: "center",
    borderRadius: "0.3rem",
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    display: "inline-flex",
    flexShrink: 0,
    fontSize: vars.fontSizeMicro,
    fontWeight: vars.fontWeightMedium,
    gap: vars.space4,
    paddingBlock: 2,
    paddingInline: 6,
  },
  statusFailed: {
    backgroundColor: vars.colorDangerSoft,
    borderColor: vars.colorDangerBorder,
    color: vars.colorDangerText,
  },
  statusMuted: {
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: vars.colorBorder,
    color: vars.colorTextMuted,
  },
  statusKept: {
    backgroundColor: vars.colorSuccessSoft,
    borderColor: vars.colorSuccessBorder,
    color: vars.colorSuccessText,
  },
  statusCompleted: {
    backgroundColor: vars.colorAccentSoft,
    borderColor: vars.colorBorder,
    color: vars.colorAccent,
  },
  statusRunning: {
    backgroundColor: vars.colorWarningSoft,
    borderColor: vars.colorWarningBorder,
    color: vars.colorWarningText,
  },
  statusPending: {
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: vars.colorBorder,
    color: vars.colorTextMuted,
  },
  recommendedTag: {
    alignItems: "center",
    color: vars.colorAccent,
    display: "inline-flex",
    flexShrink: 0,
    fontSize: vars.fontSizeMicro,
    fontWeight: vars.fontWeightSemibold,
    gap: vars.space4,
  },
  variantModelRow: {
    alignItems: "center",
    display: "flex",
    gap: vars.space8,
    marginTop: vars.space4,
    minWidth: 0,
  },
  variantModelText: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  variantScoreInline: {
    color: vars.colorText,
    flexShrink: 0,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightSemibold,
  },
  variantMetaRow: {
    color: vars.colorTextMuted,
    columnGap: vars.space12,
    display: "flex",
    flexWrap: "wrap",
    fontSize: vars.fontSizeMicro,
    marginTop: vars.space12,
    rowGap: vars.space4,
  },
  variantMetaItem: {
    alignItems: "center",
    display: "inline-flex",
    gap: vars.space4,
  },
  variantConflicts: {
    color: vars.colorDanger,
    fontWeight: vars.fontWeightMedium,
  },
  variantBody: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    paddingBlock: vars.space12,
    paddingInline: vars.space16,
  },
  variantError: {
    backgroundColor: vars.colorDangerSoft,
    borderColor: vars.colorDangerBorder,
    borderRadius: vars.radiusMark,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    color: vars.colorDangerText,
    fontSize: vars.fontSizeCaption,
    paddingBlock: vars.space8,
    paddingInline: vars.space8,
  },
  variantLoading: {
    alignItems: "center",
    color: vars.colorTextMuted,
    display: "flex",
    fontSize: vars.fontSizeCaption,
    gap: vars.space8,
    paddingBlock: vars.space24,
  },
  variantWarning: {
    backgroundColor: vars.colorWarningSoft,
    borderColor: vars.colorWarningBorder,
    borderRadius: vars.radiusMark,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    color: vars.colorWarningText,
    fontSize: vars.fontSizeCaption,
    paddingBlock: vars.space8,
    paddingInline: vars.space8,
  },
  variantEmptyFiles: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    paddingBlock: vars.space24,
  },
  fileList: {
    display: "flex",
    flexDirection: "column",
  },
  fileRow: {
    alignItems: "center",
    borderBottomColor: vars.colorBorderSubtle,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    display: "flex",
    gap: vars.space8,
    minWidth: 0,
    paddingBlock: vars.space8,
    paddingInline: vars.space4,
  },
  fileRowLast: {
    borderBottomWidth: 0,
  },
  fileCode: {
    color: vars.colorTextMuted,
    flexShrink: 0,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeMicro,
    fontWeight: vars.fontWeightMedium,
    width: 32,
  },
  filePath: {
    color: vars.colorText,
    fontSize: vars.fontSizeCaption,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  assessment: {
    borderTopColor: vars.colorBorder,
    borderTopStyle: "solid",
    borderTopWidth: vars.borderWidthHairline,
    marginTop: vars.space16,
    paddingTop: vars.space12,
  },
  assessmentHead: {
    alignItems: "center",
    display: "flex",
    gap: vars.space12,
    justifyContent: "space-between",
    marginBottom: vars.space8,
  },
  assessmentHeadLabel: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeMicro,
    fontWeight: vars.fontWeightSemibold,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  assessmentScore: {
    color: vars.colorText,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightSemibold,
  },
  assessmentSummary: {
    color: vars.colorText,
    fontSize: vars.fontSizeCaption,
    lineHeight: "1.25rem",
  },
  criteriaList: {
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    borderTopColor: vars.colorBorder,
    borderTopStyle: "solid",
    borderTopWidth: vars.borderWidthHairline,
    marginTop: vars.space12,
  },
  criteriaRow: {
    borderTopColor: vars.colorBorderSubtle,
    borderTopStyle: "solid",
    borderTopWidth: vars.borderWidthHairline,
    columnGap: vars.space12,
    display: "grid",
    gridTemplateColumns: "minmax(0,1fr) auto",
    paddingBlock: vars.space8,
  },
  criteriaRowFirst: {
    borderTopWidth: 0,
  },
  criteriaMain: {
    minWidth: 0,
  },
  criteriaTerm: {
    color: vars.colorText,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
  },
  criteriaRationale: {
    color: vars.colorTextMuted,
    display: "-webkit-box",
    fontSize: vars.fontSizeMicro,
    lineHeight: "1rem",
    marginTop: 2,
    overflow: "hidden",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
  },
  criteriaScore: {
    color: vars.colorText,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightSemibold,
  },
  risk: {
    color: vars.colorWarningText,
    fontSize: vars.fontSizeMicro,
    lineHeight: "1rem",
    marginTop: vars.space8,
  },
  variantFooter: {
    alignItems: "center",
    backgroundColor: vars.colorCanvas,
    borderTopColor: vars.colorBorder,
    borderTopStyle: "solid",
    borderTopWidth: vars.borderWidthHairline,
    display: "flex",
    gap: vars.space8,
    justifyContent: "flex-end",
    paddingBlock: 10,
    paddingInline: vars.space16,
  },

  // Decorative icon sizes
  icon14: { height: 14, width: 14 },
  icon16: { height: 16, width: 16 },
  icon12: { height: 12, width: 12 },
  icon28: { height: 28, width: 28 },
});
