import * as stylex from "@stylexjs/stylex";

import { vars } from "../ads/tokens/tokens.stylex";

export const compareRunPanelStyles = stylex.create({
  // Empty state (no compare run selected)
  emptyViewport: {
    alignItems: "center",
    backgroundColor: vars["--ads-color-canvas"],
    display: "flex",
    height: "100%",
    justifyContent: "center",
    padding: vars["--ads-space-24"],
  },
  emptyRoot: {
    backgroundColor: "transparent",
    borderStyle: "none",
    padding: 0,
  },
  emptyHeader: {
    gap: vars["--ads-space-12"],
  },
  emptyMedia: {
    // Empty-state medallion: neutral by contract. Accent is reserved for the
    // primary action, active/selected state, and links.
    backgroundColor: vars["--ads-color-surface-tint"],
    borderRadius: vars["--ads-radius-frame"],
    color: vars["--ads-color-text-muted"],
    // Logical names, matching the keys ADS `emptyStateStyles.media` declares
    // (`inlineSize: 48` / `minBlockSize: 48`). StyleX treats `width` and
    // `inlineSize` as distinct atomic properties, so overriding with the
    // physical name would leave the medallion 48px on whichever axis ADS still
    // owns and render it non-square.
    blockSize: 56,
    inlineSize: 56,
    minBlockSize: 56,
  },
  emptyTextGroup: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-4"],
  },
  emptyTitle: {
    fontSize: vars["--ads-font-size-heading"],
    fontWeight: vars["--ads-font-weight-semibold"],
  },
  emptyDescription: {
    fontSize: vars["--ads-font-size-body"],
    maxWidth: "28rem",
  },

  // Root shell
  root: {
    backgroundColor: vars["--ads-color-canvas"],
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
  },

  // Header region
  header: {
    backgroundColor: vars["--ads-color-surface"],
    borderBottomColor: vars["--ads-color-border"],
    borderBottomStyle: "solid",
    borderBottomWidth: vars["--ads-border-width-hairline"],
    flexShrink: 0,
    paddingBlock: vars["--ads-space-16"],
    paddingInline: vars["--ads-space-20"],
  },
  headerRow: {
    alignItems: "flex-start",
    display: "flex",
    flexWrap: "wrap",
    gap: vars["--ads-space-16"],
    justifyContent: "space-between",
  },
  headerMain: {
    minWidth: 0,
  },
  headerTitleRow: {
    alignItems: "center",
    display: "flex",
    gap: vars["--ads-space-8"],
  },
  headerIcon: {
    color: vars["--ads-color-text-muted"],
    height: 16,
    width: 16,
  },
  headerTitle: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-lead"],
    fontWeight: vars["--ads-font-weight-semibold"],
    letterSpacing: "-0.01em",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  promptRow: {
    alignItems: "flex-start",
    display: "flex",
    fontSize: vars["--ads-font-size-caption"],
    gap: vars["--ads-space-8"],
    marginTop: vars["--ads-space-8"],
    maxWidth: "48rem",
  },
  promptLabel: {
    color: vars["--ads-color-text-muted"],
    flexShrink: 0,
    fontWeight: vars["--ads-font-weight-semibold"],
    letterSpacing: "0.1em",
    textTransform: "uppercase",
  },
  promptText: {
    color: vars["--ads-color-text"],
    display: "-webkit-box",
    overflow: "hidden",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
  },
  headerActions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: vars["--ads-space-8"],
  },
  actionButton: {
    height: 32,
  },
  actionButtonShrink: {
    flexShrink: 0,
    height: 32,
  },

  // Stepper
  stepper: {
    backgroundColor: vars["--ads-color-canvas"],
    borderBottomColor: vars["--ads-color-border"],
    borderBottomStyle: "solid",
    borderBottomWidth: vars["--ads-border-width-hairline"],
    display: "grid",
    flexShrink: 0,
    gridTemplateColumns: "repeat(5, minmax(0, 1fr))",
  },
  step: {
    minWidth: 0,
    paddingBlock: vars["--ads-space-12"],
    paddingInline: vars["--ads-space-16"],
    position: "relative",
  },
  stepDivider: {
    borderRightColor: vars["--ads-color-border"],
    borderRightStyle: "solid",
    borderRightWidth: vars["--ads-border-width-hairline"],
  },
  stepActive: {
    backgroundColor: vars["--ads-color-accent-soft"],
  },
  stepHeadRow: {
    alignItems: "center",
    display: "flex",
    gap: vars["--ads-space-8"],
  },
  stepBadge: {
    alignItems: "center",
    borderColor: vars["--ads-color-border-strong"],
    borderRadius: vars["--ads-radius-full"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-text-muted"],
    display: "inline-flex",
    flexShrink: 0,
    fontSize: vars["--ads-font-size-micro"],
    fontVariantNumeric: "tabular-nums",
    fontWeight: vars["--ads-font-weight-semibold"],
    height: 20,
    justifyContent: "center",
    width: 20,
  },
  stepBadgeActive: {
    backgroundColor: vars["--ads-color-accent"],
    borderColor: vars["--ads-color-accent"],
    color: vars["--ads-color-accent-text"],
  },
  stepBadgeComplete: {
    backgroundColor: vars["--ads-color-success-soft"],
    borderColor: vars["--ads-color-success-border"],
    color: vars["--ads-color-success-text"],
  },
  stepLabel: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-semibold"],
  },
  stepLabelActive: {
    color: vars["--ads-color-text"],
  },
  stepDescription: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-micro"],
    marginTop: vars["--ads-space-4"],
    overflow: "hidden",
    paddingLeft: "1.75rem",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  stepUnderline: {
    backgroundColor: vars["--ads-color-accent"],
    bottom: 0,
    height: 2,
    insetInline: 0,
    position: "absolute",
  },

  // Terminal notice
  notice: {
    alignItems: "flex-start",
    borderBottomStyle: "solid",
    borderBottomWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    flexShrink: 0,
    gap: vars["--ads-space-12"],
    paddingBlock: vars["--ads-space-12"],
    paddingInline: vars["--ads-space-20"],
  },
  noticeNeutral: {
    backgroundColor: vars["--ads-color-surface"],
    borderBottomColor: vars["--ads-color-border"],
  },
  noticeDestructive: {
    backgroundColor: vars["--ads-color-danger-soft"],
    borderBottomColor: vars["--ads-color-danger-border"],
  },
  noticeIcon: {
    flexShrink: 0,
    height: 16,
    marginTop: 2,
    width: 16,
  },
  noticeIconNeutral: {
    color: vars["--ads-color-text-muted"],
  },
  noticeIconDestructive: {
    color: vars["--ads-color-danger"],
  },
  noticeBody: {
    minWidth: 0,
  },
  noticeTitle: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-semibold"],
  },
  noticeDescription: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: "1.25rem",
    marginTop: 2,
  },

  // Judge banner
  judge: {
    alignItems: "flex-start",
    borderBottomStyle: "solid",
    borderBottomWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    flexShrink: 0,
    gap: vars["--ads-space-12"],
    paddingBlock: vars["--ads-space-12"],
    paddingInline: vars["--ads-space-20"],
  },
  judgeNeutral: {
    backgroundColor: vars["--ads-color-surface"],
    borderBottomColor: vars["--ads-color-border"],
  },
  judgeFailed: {
    backgroundColor: vars["--ads-color-warning-soft"],
    borderBottomColor: vars["--ads-color-warning-border"],
  },
  judgeCompleted: {
    backgroundColor: vars["--ads-color-accent-soft"],
    borderBottomColor: vars["--ads-color-border"],
  },
  judgeMark: {
    alignItems: "center",
    borderRadius: vars["--ads-radius-control"],
    display: "flex",
    flexShrink: 0,
    height: 32,
    justifyContent: "center",
    marginTop: 2,
    width: 32,
  },
  judgeMarkNeutral: {
    backgroundColor: vars["--ads-color-surface-tint"],
    color: vars["--ads-color-text-muted"],
  },
  judgeMarkFailed: {
    backgroundColor: vars["--ads-color-warning-soft"],
    color: vars["--ads-color-warning-text"],
  },
  judgeBody: {
    flex: 1,
    minWidth: 0,
  },
  judgeHeadRow: {
    alignItems: "center",
    columnGap: vars["--ads-space-8"],
    display: "flex",
    flexWrap: "wrap",
    rowGap: vars["--ads-space-4"],
  },
  judgeTitle: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-semibold"],
  },
  judgeScore: {
    color: vars["--ads-color-text"],
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-semibold"],
  },
  judgeMeta: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
  },
  judgeRationale: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: "1.25rem",
    marginTop: vars["--ads-space-4"],
  },

  // Review contract row
  review: {
    alignItems: "center",
    backgroundColor: vars["--ads-color-surface"],
    borderBottomColor: vars["--ads-color-border"],
    borderBottomStyle: "solid",
    borderBottomWidth: vars["--ads-border-width-hairline"],
    columnGap: vars["--ads-space-20"],
    display: "flex",
    flexShrink: 0,
    flexWrap: "wrap",
    paddingBlock: vars["--ads-space-12"],
    paddingInline: vars["--ads-space-20"],
    rowGap: vars["--ads-space-8"],
  },
  reviewHead: {
    alignItems: "center",
    display: "flex",
    gap: vars["--ads-space-8"],
  },
  reviewIcon: {
    color: vars["--ads-color-text-muted"],
    height: 16,
    width: 16,
  },
  reviewHeadLabel: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-semibold"],
  },
  reviewCriteria: {
    alignItems: "center",
    columnGap: vars["--ads-space-16"],
    display: "flex",
    flexWrap: "wrap",
    minWidth: 0,
    rowGap: vars["--ads-space-4"],
  },
  reviewCriterion: {
    alignItems: "center",
    color: vars["--ads-color-text-muted"],
    display: "inline-flex",
    fontSize: vars["--ads-font-size-caption"],
    gap: 6,
  },
  reviewDot: {
    backgroundColor: vars["--ads-color-accent"],
    borderRadius: vars["--ads-radius-full"],
    height: 4,
    width: 4,
  },

  // Grid + variant cards
  scroller: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    padding: vars["--ads-space-16"],
  },
  grid: {
    backgroundColor: vars["--ads-color-surface"],
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    boxShadow: vars["--ads-elevation-raised"],
    display: "grid",
    minWidth: 760,
    overflow: "hidden",
  },
  variant: {
    display: "flex",
    flexDirection: "column",
    minHeight: "23rem",
    minWidth: 0,
  },
  variantDivider: {
    borderLeftColor: vars["--ads-color-border"],
    borderLeftStyle: "solid",
    borderLeftWidth: vars["--ads-border-width-hairline"],
  },
  variantRecommended: {
    backgroundColor: vars["--ads-color-accent-soft"],
  },
  variantHeader: {
    backgroundColor: vars["--ads-color-surface"],
    borderBottomColor: vars["--ads-color-border"],
    borderBottomStyle: "solid",
    borderBottomWidth: vars["--ads-border-width-hairline"],
    paddingBlock: vars["--ads-space-12"],
    paddingInline: vars["--ads-space-16"],
  },
  variantHeaderRow: {
    alignItems: "flex-start",
    display: "flex",
    gap: vars["--ads-space-12"],
    justifyContent: "space-between",
  },
  variantTitleRow: {
    alignItems: "center",
    display: "flex",
    gap: vars["--ads-space-8"],
  },
  variantIndex: {
    color: vars["--ads-color-text-muted"],
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-micro"],
  },
  variantTitle: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-semibold"],
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  statusChip: {
    alignItems: "center",
    borderRadius: "0.3rem",
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    display: "inline-flex",
    flexShrink: 0,
    fontSize: vars["--ads-font-size-micro"],
    fontWeight: vars["--ads-font-weight-medium"],
    gap: vars["--ads-space-4"],
    paddingBlock: 2,
    paddingInline: 6,
  },
  statusFailed: {
    backgroundColor: vars["--ads-color-danger-soft"],
    borderColor: vars["--ads-color-danger-border"],
    color: vars["--ads-color-danger-text"],
  },
  statusMuted: {
    backgroundColor: vars["--ads-color-canvas-subtle"],
    borderColor: vars["--ads-color-border"],
    color: vars["--ads-color-text-muted"],
  },
  statusKept: {
    backgroundColor: vars["--ads-color-success-soft"],
    borderColor: vars["--ads-color-success-border"],
    color: vars["--ads-color-success-text"],
  },
  statusCompleted: {
    backgroundColor: vars["--ads-color-accent-soft"],
    borderColor: vars["--ads-color-border"],
    color: vars["--ads-color-accent"],
  },
  statusRunning: {
    backgroundColor: vars["--ads-color-warning-soft"],
    borderColor: vars["--ads-color-warning-border"],
    color: vars["--ads-color-warning-text"],
  },
  statusPending: {
    backgroundColor: vars["--ads-color-canvas-subtle"],
    borderColor: vars["--ads-color-border"],
    color: vars["--ads-color-text-muted"],
  },
  recommendedTag: {
    alignItems: "center",
    color: vars["--ads-color-accent"],
    display: "inline-flex",
    flexShrink: 0,
    fontSize: vars["--ads-font-size-micro"],
    fontWeight: vars["--ads-font-weight-semibold"],
    gap: vars["--ads-space-4"],
  },
  variantModelRow: {
    alignItems: "center",
    display: "flex",
    gap: vars["--ads-space-8"],
    marginTop: vars["--ads-space-4"],
    minWidth: 0,
  },
  variantModelText: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  variantScoreInline: {
    color: vars["--ads-color-text"],
    flexShrink: 0,
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-semibold"],
  },
  variantMetaRow: {
    color: vars["--ads-color-text-muted"],
    columnGap: vars["--ads-space-12"],
    display: "flex",
    flexWrap: "wrap",
    fontSize: vars["--ads-font-size-micro"],
    marginTop: vars["--ads-space-12"],
    rowGap: vars["--ads-space-4"],
  },
  variantMetaItem: {
    alignItems: "center",
    display: "inline-flex",
    gap: vars["--ads-space-4"],
  },
  variantConflicts: {
    color: vars["--ads-color-danger"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  variantBody: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    paddingBlock: vars["--ads-space-12"],
    paddingInline: vars["--ads-space-16"],
  },
  variantError: {
    backgroundColor: vars["--ads-color-danger-soft"],
    borderColor: vars["--ads-color-danger-border"],
    borderRadius: vars["--ads-radius-mark"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-danger-text"],
    fontSize: vars["--ads-font-size-caption"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-8"],
  },
  variantLoading: {
    alignItems: "center",
    color: vars["--ads-color-text-muted"],
    display: "flex",
    fontSize: vars["--ads-font-size-caption"],
    gap: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-24"],
  },
  variantWarning: {
    backgroundColor: vars["--ads-color-warning-soft"],
    borderColor: vars["--ads-color-warning-border"],
    borderRadius: vars["--ads-radius-mark"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-warning-text"],
    fontSize: vars["--ads-font-size-caption"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-8"],
  },
  variantEmptyFiles: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    paddingBlock: vars["--ads-space-24"],
  },
  fileList: {
    display: "flex",
    flexDirection: "column",
  },
  fileRow: {
    alignItems: "center",
    borderBottomColor: vars["--ads-color-border-subtle"],
    borderBottomStyle: "solid",
    borderBottomWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    gap: vars["--ads-space-8"],
    minWidth: 0,
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-4"],
  },
  fileRowLast: {
    borderBottomWidth: 0,
  },
  fileCode: {
    color: vars["--ads-color-text-muted"],
    flexShrink: 0,
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-micro"],
    fontWeight: vars["--ads-font-weight-medium"],
    width: 32,
  },
  filePath: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-caption"],
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  assessment: {
    borderTopColor: vars["--ads-color-border"],
    borderTopStyle: "solid",
    borderTopWidth: vars["--ads-border-width-hairline"],
    marginTop: vars["--ads-space-16"],
    paddingTop: vars["--ads-space-12"],
  },
  assessmentHead: {
    alignItems: "center",
    display: "flex",
    gap: vars["--ads-space-12"],
    justifyContent: "space-between",
    marginBottom: vars["--ads-space-8"],
  },
  assessmentHeadLabel: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-micro"],
    fontWeight: vars["--ads-font-weight-semibold"],
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  assessmentScore: {
    color: vars["--ads-color-text"],
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-semibold"],
  },
  assessmentSummary: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: "1.25rem",
  },
  criteriaList: {
    borderBottomColor: vars["--ads-color-border"],
    borderBottomStyle: "solid",
    borderBottomWidth: vars["--ads-border-width-hairline"],
    borderTopColor: vars["--ads-color-border"],
    borderTopStyle: "solid",
    borderTopWidth: vars["--ads-border-width-hairline"],
    marginTop: vars["--ads-space-12"],
  },
  criteriaRow: {
    borderTopColor: vars["--ads-color-border-subtle"],
    borderTopStyle: "solid",
    borderTopWidth: vars["--ads-border-width-hairline"],
    columnGap: vars["--ads-space-12"],
    display: "grid",
    gridTemplateColumns: "minmax(0,1fr) auto",
    paddingBlock: vars["--ads-space-8"],
  },
  criteriaRowFirst: {
    borderTopWidth: 0,
  },
  criteriaMain: {
    minWidth: 0,
  },
  criteriaTerm: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  criteriaRationale: {
    color: vars["--ads-color-text-muted"],
    display: "-webkit-box",
    fontSize: vars["--ads-font-size-micro"],
    lineHeight: "1rem",
    marginTop: 2,
    overflow: "hidden",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
  },
  criteriaScore: {
    color: vars["--ads-color-text"],
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-semibold"],
  },
  risk: {
    color: vars["--ads-color-warning-text"],
    fontSize: vars["--ads-font-size-micro"],
    lineHeight: "1rem",
    marginTop: vars["--ads-space-8"],
  },
  variantFooter: {
    alignItems: "center",
    backgroundColor: vars["--ads-color-canvas"],
    borderTopColor: vars["--ads-color-border"],
    borderTopStyle: "solid",
    borderTopWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    gap: vars["--ads-space-8"],
    justifyContent: "flex-end",
    paddingBlock: 10,
    paddingInline: vars["--ads-space-16"],
  },

  // Decorative icon sizes
  icon14: { height: 14, width: 14 },
  icon16: { height: 16, width: 16 },
  icon12: { height: 12, width: 12 },
  icon28: { height: 28, width: 28 },
});
