import * as stylex from "@stylexjs/stylex";

import { vars } from "../ads/tokens/tokens.stylex";

export const resourceCreatorStyles = stylex.create({
  field: {
    color: vars["--ads-color-text"],
    display: "grid",
    fontSize: vars["--ads-font-size-caption"],
    gap: 6,
  },
  fieldLabel: { fontWeight: vars["--ads-font-weight-medium"] },
  fieldDescription: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-micro"],
    lineHeight: vars["--ads-line-height-control"],
  },
  fieldPair: {
    display: "grid",
    gap: vars["--ads-space-12"],
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
  },
  noteTextarea: { minBlockSize: 80, resize: "vertical" },
  customTextarea: { minBlockSize: 96, resize: "vertical" },
  bodyTextarea: { minBlockSize: 128, resize: "vertical" },
  booleanRow: {
    alignItems: "center",
    blockSize: 36,
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    justifyContent: "space-between",
    paddingInline: vars["--ads-space-12"],
  },
  booleanValue: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
  },

  trigger: {
    blockSize: 32,
    fontSize: vars["--ads-font-size-caption"],
    gap: vars["--ads-space-8"],
    justifyContent: "flex-start",
  },
  triggerIcon: { blockSize: 14, inlineSize: 14 },

  /** Full-bleed shell: header, scrolling body, and footer own their padding. */
  content: {
    maxBlockSize: "84vh",
    maxWidth: {
      default: "28rem",
      "@media (min-width: 640px)": "36rem",
    },
    overflow: "hidden",
    padding: 0,
  },
  header: {
    borderBlockEndColor: vars["--ads-color-border-subtle"],
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: vars["--ads-border-width-hairline"],
    paddingBlockEnd: vars["--ads-space-16"],
    paddingBlockStart: vars["--ads-space-20"],
    paddingInlineEnd: vars["--ads-space-48"],
    paddingInlineStart: vars["--ads-space-20"],
  },
  headerRow: { alignItems: "flex-start", display: "flex", gap: vars["--ads-space-12"] },
  backButton: { blockSize: 32, flexShrink: 0, inlineSize: 32, marginInlineStart: -8 },
  backIcon: {
    blockSize: vars["--ads-control-icon-size-sm"],
    inlineSize: vars["--ads-control-icon-size-sm"],
  },
  headerText: { minInlineSize: 0 },
  headerDescription: { marginBlockStart: vars["--ads-space-4"] },

  body: {
    display: "grid",
    gap: vars["--ads-space-16"],
    maxBlockSize: "60vh",
    overflowY: "auto",
    paddingBlock: vars["--ads-space-16"],
    paddingInline: vars["--ads-space-20"],
  },
  error: {
    backgroundColor: vars["--ads-color-danger-soft"],
    borderColor: vars["--ads-color-danger-border"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-danger-text"],
    fontSize: vars["--ads-font-size-caption"],
    margin: 0,
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
  },
  footer: {
    backgroundColor: vars["--ads-color-canvas-subtle"],
    borderBlockStartColor: vars["--ads-color-border-subtle"],
    borderBlockStartStyle: "solid",
    borderBlockStartWidth: vars["--ads-border-width-hairline"],
    paddingBlock: vars["--ads-space-16"],
    paddingInline: vars["--ads-space-20"],
  },

  typeGrid: {
    display: "grid",
    gap: vars["--ads-space-8"],
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    maxBlockSize: "65vh",
    overflowY: "auto",
    padding: vars["--ads-space-20"],
  },
  typeCard: {
    alignItems: "flex-start",
    backgroundColor: { default: vars["--ads-color-surface"], ":hover": vars["--ads-color-canvas-subtle"] },
    borderColor: {
      default: vars["--ads-color-border-subtle"],
      ":hover": `color-mix(in oklch, ${vars["--ads-color-accent"]} 40%, transparent)`,
    },
    borderRadius: vars["--ads-radius-panel"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    gap: vars["--ads-space-12"],
    minBlockSize: 96,
    padding: vars["--ads-space-12"],
    textAlign: "left",
  },
  typeIconBox: {
    alignItems: "center",
    backgroundColor: vars["--ads-color-canvas-subtle"],
    blockSize: 32,
    borderRadius: vars["--ads-radius-control"],
    color: vars["--ads-color-text-muted"],
    display: "flex",
    flexShrink: 0,
    inlineSize: 32,
    justifyContent: "center",
  },
  typeIcon: {
    blockSize: vars["--ads-control-icon-size-sm"],
    inlineSize: vars["--ads-control-icon-size-sm"],
  },
  typeText: { minInlineSize: 0 },
  typeLabel: {
    color: vars["--ads-color-text"],
    display: "block",
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-semibold"],
  },
  typeDescription: {
    color: vars["--ads-color-text-muted"],
    display: "block",
    fontSize: vars["--ads-font-size-micro"],
    lineHeight: vars["--ads-line-height-control"],
    marginBlockStart: vars["--ads-space-4"],
  },
});
