import * as stylex from "@stylexjs/stylex";

import { vars } from "../ads/tokens/tokens.stylex";

export const cliSessionPanelStyles = stylex.create({
  panel: {
    backgroundColor: vars.colorCanvas,
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
  },
  panelVisible: { display: "flex" },
  panelHidden: { display: "none" },
  column: {
    display: "flex",
    flexDirection: "column",
    flexGrow: 1,
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
  },

  header: {
    backgroundColor: vars.colorSurface,
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    flexShrink: 0,
    paddingBlock: vars.space12,
    paddingInline: vars.space16,
  },
  headerRow: {
    alignItems: "flex-start",
    display: "flex",
    gap: vars.space12,
    justifyContent: "space-between",
  },
  headerMain: { flexGrow: 1, flexShrink: 1, minWidth: 0 },
  titleRow: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: vars.space8,
    minWidth: 0,
  },
  title: {
    alignItems: "center",
    color: vars.colorText,
    display: "inline-flex",
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightSemibold,
    gap: vars.space8,
  },
  providerIcon: {
    blockSize: 16,
    color: vars.colorTextMuted,
    inlineSize: 16,
  },
  truncate: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  badge: {
    borderRadius: vars.radiusMark,
    fontSize: vars.fontSizeMicro,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
  },
  metaRow: {
    alignItems: "center",
    color: vars.colorTextMuted,
    columnGap: vars.space12,
    display: "flex",
    flexWrap: "wrap",
    fontSize: vars.fontSizeCaption,
    marginTop: vars.space8,
    minWidth: 0,
    rowGap: vars.space4,
  },
  exitStatus: { fontWeight: vars.fontWeightMedium },
  exitStatusClean: { color: vars.colorTextMuted },
  exitStatusFailed: { color: vars.colorDanger },
  liveStatus: { color: vars.colorSuccessText },

  actions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: vars.space4,
  },
  handoffButton: { blockSize: 32, gap: vars.space8 },
  iconButton: {
    blockSize: 32,
    borderRadius: vars.radiusControl,
    color: vars.colorTextMuted,
    inlineSize: 32,
    padding: 0,
  },

  errorBanner: {
    backgroundColor: `color-mix(in oklch, ${vars.colorDanger} 10%, transparent)`,
    borderBottomColor: `color-mix(in oklch, ${vars.colorDanger} 30%, transparent)`,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    color: vars.colorDanger,
    fontSize: vars.fontSizeCaption,
    paddingBlock: vars.space8,
    paddingInline: vars.space16,
  },
  degradedBanner: {
    alignItems: "center",
    backgroundColor: `color-mix(in oklch, ${vars.colorWarning} 10%, transparent)`,
    borderBottomColor: `color-mix(in oklch, ${vars.colorWarning} 30%, transparent)`,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    color: vars.colorWarningText,
    display: "flex",
    fontSize: vars.fontSizeCaption,
    gap: vars.space12,
    justifyContent: "space-between",
    paddingBlock: vars.space8,
    paddingInline: vars.space16,
  },
  degradedAction: {
    blockSize: 28,
    color: { default: vars.colorWarningText, ":hover": vars.colorWarning },
    fontSize: vars.fontSizeMicro,
    paddingInline: vars.space8,
  },

  bootOverlay: {
    alignItems: "center",
    backgroundColor: "var(--terminal)",
    display: "flex",
    inset: 0,
    justifyContent: "center",
    position: "absolute",
    zIndex: 10,
  },
  bootLabel: {
    alignItems: "center",
    color: vars.colorTextMuted,
    display: "flex",
    fontSize: vars.fontSizeBody,
    gap: vars.space8,
  },
});
