import * as stylex from "@stylexjs/stylex";

import { vars } from "../ads/tokens/tokens.stylex";

export const cliSessionPanelStyles = stylex.create({
  panel: {
    backgroundColor: vars["--ads-color-canvas"],
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
  },
  panelVisible: { display: "flex" },
  panelHidden: { display: "none" },
  column: {
    display: "flex",
    flexDirection: "column",
    flexGrow: 1,
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
  },

  header: {
    backgroundColor: vars["--ads-color-surface"],
    borderBottomColor: vars["--ads-color-border"],
    borderBottomStyle: "solid",
    borderBottomWidth: vars["--ads-border-width-hairline"],
    flexShrink: 0,
    paddingBlock: vars["--ads-space-12"],
    paddingInline: vars["--ads-space-16"],
  },
  headerRow: {
    alignItems: "flex-start",
    display: "flex",
    gap: vars["--ads-space-12"],
    justifyContent: "space-between",
  },
  headerMain: { flexGrow: 1, flexShrink: 1, minWidth: 0 },
  titleRow: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: vars["--ads-space-8"],
    minWidth: 0,
  },
  title: {
    alignItems: "center",
    color: vars["--ads-color-text"],
    display: "inline-flex",
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-semibold"],
    gap: vars["--ads-space-8"],
  },
  providerIcon: {
    blockSize: 16,
    color: vars["--ads-color-text-muted"],
    inlineSize: 16,
  },
  truncate: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  badge: {
    borderRadius: vars["--ads-radius-mark"],
    fontSize: vars["--ads-font-size-micro"],
    letterSpacing: "0.14em",
    textTransform: "uppercase",
  },
  metaRow: {
    alignItems: "center",
    color: vars["--ads-color-text-muted"],
    columnGap: vars["--ads-space-12"],
    display: "flex",
    flexWrap: "wrap",
    fontSize: vars["--ads-font-size-caption"],
    marginTop: vars["--ads-space-8"],
    minWidth: 0,
    rowGap: vars["--ads-space-4"],
  },
  exitStatus: { fontWeight: vars["--ads-font-weight-medium"] },
  exitStatusClean: { color: vars["--ads-color-text-muted"] },
  exitStatusFailed: { color: vars["--ads-color-danger"] },
  liveStatus: { color: vars["--ads-color-success-text"] },

  actions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: vars["--ads-space-4"],
  },
  handoffButton: { blockSize: 32, gap: vars["--ads-space-8"] },
  iconButton: {
    blockSize: 32,
    borderRadius: vars["--ads-radius-control"],
    color: vars["--ads-color-text-muted"],
    inlineSize: 32,
    padding: 0,
  },

  errorBanner: {
    backgroundColor: `color-mix(in oklch, ${vars["--ads-color-danger"]} 10%, transparent)`,
    borderBottomColor: `color-mix(in oklch, ${vars["--ads-color-danger"]} 30%, transparent)`,
    borderBottomStyle: "solid",
    borderBottomWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-danger"],
    fontSize: vars["--ads-font-size-caption"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-16"],
  },
  degradedBanner: {
    alignItems: "center",
    backgroundColor: `color-mix(in oklch, ${vars["--ads-color-warning"]} 10%, transparent)`,
    borderBottomColor: `color-mix(in oklch, ${vars["--ads-color-warning"]} 30%, transparent)`,
    borderBottomStyle: "solid",
    borderBottomWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-warning-text"],
    display: "flex",
    fontSize: vars["--ads-font-size-caption"],
    gap: vars["--ads-space-12"],
    justifyContent: "space-between",
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-16"],
  },
  degradedAction: {
    blockSize: 28,
    color: { default: vars["--ads-color-warning-text"], ":hover": vars["--ads-color-warning"] },
    fontSize: vars["--ads-font-size-micro"],
    paddingInline: vars["--ads-space-8"],
  },

  bootOverlay: {
    alignItems: "center",
    backgroundColor: "var(--terminal)",
    display: "flex",
    inset: 0,
    justifyContent: "center",
    position: "absolute",
    zIndex: 10,
  },
  bootLabel: {
    alignItems: "center",
    color: vars["--ads-color-text-muted"],
    display: "flex",
    fontSize: vars["--ads-font-size-body"],
    gap: vars["--ads-space-8"],
  },
});
