import * as stylex from "@stylexjs/stylex";

import { vars } from "../ads/tokens/tokens.stylex";

export const craneApprovalStyles = stylex.create({
  /** Full-bleed shell: header, scrolling body, and footer own their padding. */
  content: {
    display: "flex",
    flexDirection: "column",
    gap: 0,
    maxBlockSize: "90vh",
    maxWidth: {
      default: "28rem",
      "@media (min-width: 640px)": "42rem",
    },
    overflow: "hidden",
    padding: 0,
  },
  header: {
    borderBlockEndColor: vars["--ads-color-border-subtle"],
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: vars["--ads-border-width-hairline"],
    flexShrink: 0,
    paddingBlockEnd: vars["--ads-space-20"],
    paddingBlockStart: vars["--ads-space-24"],
    paddingInlineEnd: vars["--ads-space-48"],
    paddingInlineStart: vars["--ads-space-24"],
  },
  headerRow: { alignItems: "flex-start", display: "flex", gap: vars["--ads-space-12"] },
  headerBadge: {
    alignItems: "center",
    backgroundColor: vars["--ads-color-canvas-subtle"],
    blockSize: 40,
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-panel"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    flexShrink: 0,
    inlineSize: 40,
    justifyContent: "center",
  },
  headerIcon: {
    blockSize: vars["--ads-control-icon-size-sm"],
    color: vars["--ads-color-text-muted"],
    inlineSize: vars["--ads-control-icon-size-sm"],
  },
  headerText: { minInlineSize: 0 },
  headerDescription: {
    lineHeight: vars["--ads-line-height-control"],
    marginBlockStart: vars["--ads-space-4"],
  },

  body: {
    display: "flex",
    flexDirection: "column",
    flexGrow: 1,
    gap: vars["--ads-space-20"],
    minBlockSize: 0,
    overflowY: "auto",
    paddingBlock: vars["--ads-space-20"],
    paddingInline: vars["--ads-space-24"],
  },
  panel: {
    backgroundColor: vars["--ads-color-surface-tint"],
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-panel"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-8"],
    padding: vars["--ads-space-16"],
  },
  issueRow: {
    alignItems: "flex-start",
    display: "flex",
    gap: vars["--ads-space-12"],
    justifyContent: "space-between",
  },
  issueText: { minInlineSize: 0 },
  issueTitle: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-semibold"],
    margin: 0,
  },
  issueMeta: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    marginBlockEnd: 0,
    marginBlockStart: vars["--ads-space-4"],
  },
  buttonIcon: { blockSize: 14, inlineSize: 14 },

  instructionGroup: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-4"],
  },
  instructionLabel: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
    margin: 0,
  },
  instruction: {
    fontSize: vars["--ads-font-size-body"],
    lineHeight: vars["--ads-line-height-control"],
    margin: 0,
    whiteSpace: "pre-wrap",
  },

  descriptionAccordion: {
    borderBlockStartColor: vars["--ads-color-border-subtle"],
    borderBlockStartStyle: "solid",
    borderBlockStartWidth: vars["--ads-border-width-hairline"],
  },
  descriptionTrigger: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
    paddingBlock: vars["--ads-space-8"],
  },
  descriptionPanel: { paddingBlockEnd: vars["--ads-space-8"] },
  descriptionBody: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-control"],
    margin: 0,
    maxBlockSize: 160,
    overflowY: "auto",
    whiteSpace: "pre-wrap",
  },

  privacyPanel: {
    alignItems: "flex-start",
    backgroundColor: vars["--ads-color-surface-tint"],
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-panel"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    gap: vars["--ads-space-12"],
    padding: vars["--ads-space-16"],
  },
  privacyIcon: {
    blockSize: vars["--ads-control-icon-size-sm"],
    color: vars["--ads-color-text-muted"],
    flexShrink: 0,
    inlineSize: vars["--ads-control-icon-size-sm"],
    marginBlockStart: 2,
  },
  privacyText: {
    display: "flex",
    flexDirection: "column",
    fontSize: vars["--ads-font-size-caption"],
    gap: vars["--ads-space-4"],
    lineHeight: vars["--ads-line-height-control"],
  },
  privacyHeading: {
    color: vars["--ads-color-text"],
    fontWeight: vars["--ads-font-weight-medium"],
    margin: 0,
  },
  privacyCopy: { color: vars["--ads-color-text-muted"], margin: 0 },

  footer: {
    backgroundColor: vars["--ads-color-canvas-subtle"],
    borderBlockStartColor: vars["--ads-color-border-subtle"],
    borderBlockStartStyle: "solid",
    borderBlockStartWidth: vars["--ads-border-width-hairline"],
    flexShrink: 0,
    paddingBlock: vars["--ads-space-16"],
    paddingInline: vars["--ads-space-24"],
  },
  footerNote: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    marginInlineEnd: "auto",
  },
});
