import * as stylex from "@stylexjs/stylex";

import { vars } from "@/components/ads/tokens/tokens.stylex";

export const branchPickerStyles = stylex.create({
  trigger: {
    display: "flex",
    height: vars.controlHeightMd,
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
    gap: vars.space8,
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: vars.colorBorder,
    backgroundColor: {
      default: vars.colorCanvas,
      ":hover": vars.colorOverlayHover,
      ":active": vars.colorOverlayPressed,
    },
    paddingInline: vars.space12,
    fontSize: vars.fontSizeBody,
    boxShadow: vars.elevationRaised,
    color: {
      default: vars.colorText,
      ":hover": vars.colorText,
      ":active": vars.colorText,
    },
    cursor: { default: "pointer", ":disabled": "not-allowed" },
    opacity: { default: 1, ":disabled": vars.opacityDisabled },
  },
  triggerOpen: {
    borderColor: vars.colorAccent,
    backgroundColor: {
      default: vars.colorSelectionFill,
      ":hover": vars.colorSelectionFill,
      ":active": vars.colorSelectionFill,
    },
  },
  triggerValue: {
    display: "flex",
    minWidth: 0,
    alignItems: "center",
    gap: vars.space8,
  },
  triggerMeta: {
    marginInlineStart: "auto",
    display: "flex",
    alignItems: "center",
    gap: vars.space8,
  },
  branchIcon: {
    width: 14,
    height: 14,
    flexShrink: 0,
    color: vars.colorTextMuted,
  },
  chevronIcon: {
    width: 16,
    height: 16,
    flexShrink: 0,
    color: vars.colorTextMuted,
  },
  truncated: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  scopeBadge: {
    borderRadius: vars.radiusMark,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: vars.colorBorder,
    backgroundColor: vars.colorCanvas,
    paddingInline: 6,
    paddingBlock: 1,
    fontSize: "0.625rem",
    fontWeight: vars.fontWeightMedium,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    color: vars.colorTextMuted,
  },
  popover: {
    maxWidth: "32rem",
    gap: 0,
    overflow: "hidden",
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: vars.colorBorder,
    backgroundColor: vars.colorSurface,
    padding: 0,
  },
  searchBar: {
    borderBottomWidth: vars.borderWidthHairline,
    borderBottomStyle: "solid",
    borderBottomColor: vars.colorBorder,
    padding: vars.space8,
  },
  searchField: {
    position: "relative",
  },
  searchIcon: {
    pointerEvents: "none",
    position: "absolute",
    left: vars.space12,
    top: "50%",
    width: 16,
    height: 16,
    transform: "translateY(-50%)",
    color: vars.colorTextMuted,
  },
  searchInput: {
    height: vars.controlHeightMd,
    borderColor: vars.colorBorder,
    backgroundColor: vars.colorCanvas,
    paddingInlineStart: 36,
  },
  loadingRow: {
    display: "flex",
    alignItems: "center",
    gap: vars.space8,
    paddingInline: vars.space12,
    paddingBlock: vars.space32,
    fontSize: vars.fontSizeBody,
    color: vars.colorTextMuted,
  },
  emptyRow: {
    paddingInline: vars.space12,
    paddingBlock: vars.space32,
    textAlign: "center",
    fontSize: vars.fontSizeBody,
    color: vars.colorTextMuted,
  },
  groupLabel: {
    paddingInline: vars.space12,
    paddingBlockStart: vars.space8,
    paddingBlockEnd: vars.space4,
    fontSize: vars.fontSizeMicro,
    fontWeight: vars.fontWeightSemibold,
    textTransform: "uppercase",
    letterSpacing: "0.12em",
    color: vars.colorTextMuted,
  },
  optionRow: {
    paddingInline: vars.space4,
    paddingBlockEnd: vars.space4,
  },
  option: {
    position: "relative",
    display: "flex",
    width: "100%",
    cursor: "default",
    alignItems: "center",
    gap: vars.space8,
    borderRadius: vars.radiusMark,
    paddingBlock: vars.space8,
    paddingInlineEnd: vars.space8,
    paddingInlineStart: vars.space12,
    textAlign: "left",
    fontSize: vars.fontSizeBody,
    userSelect: "none",
  },
  optionHighlighted: {
    backgroundColor: {
      default: vars.colorSelectionFill,
      ":hover": vars.colorSelectionFill,
    },
    color: { default: vars.colorText, ":hover": vars.colorText },
  },
  optionIdle: {
    backgroundColor: { default: "transparent", ":hover": vars.colorOverlayHover },
    color: { default: vars.colorText, ":hover": vars.colorText },
  },
  optionLabel: {
    minWidth: 0,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  optionCheck: {
    display: "flex",
    width: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
    color: vars.colorText,
  },
  checkIcon: {
    width: 16,
    height: 16,
  },
  loaderInline: {
    flexShrink: 0,
  },
});
