import * as stylex from "@stylexjs/stylex";

import { vars } from "@/components/ads/tokens/tokens.stylex";

export const branchPickerStyles = stylex.create({
  trigger: {
    display: "flex",
    height: vars["--ads-control-height-md"],
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
    gap: vars["--ads-space-8"],
    borderRadius: vars["--ads-radius-control"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
    backgroundColor: {
      default: vars["--ads-color-canvas"],
      ":hover": vars["--ads-color-overlay-hover"],
      ":active": vars["--ads-color-overlay-pressed"],
    },
    paddingInline: vars["--ads-space-12"],
    fontSize: vars["--ads-font-size-body"],
    boxShadow: vars["--ads-elevation-raised"],
    color: {
      default: vars["--ads-color-text"],
      ":hover": vars["--ads-color-text"],
      ":active": vars["--ads-color-text"],
    },
    cursor: { default: "pointer", ":disabled": "not-allowed" },
    opacity: { default: 1, ":disabled": vars["--ads-opacity-disabled"] },
  },
  triggerOpen: {
    borderColor: vars["--ads-color-accent"],
    backgroundColor: {
      default: vars["--ads-color-selection-fill"],
      ":hover": vars["--ads-color-selection-fill"],
      ":active": vars["--ads-color-selection-fill"],
    },
  },
  triggerValue: {
    display: "flex",
    minWidth: 0,
    alignItems: "center",
    gap: vars["--ads-space-8"],
  },
  triggerMeta: {
    marginInlineStart: "auto",
    display: "flex",
    alignItems: "center",
    gap: vars["--ads-space-8"],
  },
  branchIcon: {
    width: 14,
    height: 14,
    flexShrink: 0,
    color: vars["--ads-color-text-muted"],
  },
  chevronIcon: {
    width: 16,
    height: 16,
    flexShrink: 0,
    color: vars["--ads-color-text-muted"],
  },
  truncated: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  scopeBadge: {
    borderRadius: vars["--ads-radius-mark"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-canvas"],
    paddingInline: 6,
    paddingBlock: 1,
    fontSize: vars["--ads-font-size-micro"],
    fontWeight: vars["--ads-font-weight-medium"],
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    color: vars["--ads-color-text-muted"],
  },
  popover: {
    maxWidth: "32rem",
    gap: 0,
    overflow: "hidden",
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface"],
    padding: 0,
  },
  searchBar: {
    borderBottomWidth: vars["--ads-border-width-hairline"],
    borderBottomStyle: "solid",
    borderBottomColor: vars["--ads-color-border"],
    padding: vars["--ads-space-8"],
  },
  searchField: {
    position: "relative",
  },
  searchIcon: {
    pointerEvents: "none",
    position: "absolute",
    left: vars["--ads-space-12"],
    top: "50%",
    width: 16,
    height: 16,
    transform: "translateY(-50%)",
    color: vars["--ads-color-text-muted"],
  },
  searchInput: {
    height: vars["--ads-control-height-md"],
    borderColor: vars["--ads-color-border"],
    paddingInlineStart: 36,
  },
  loadingRow: {
    display: "flex",
    alignItems: "center",
    gap: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
    paddingBlock: vars["--ads-space-32"],
    fontSize: vars["--ads-font-size-body"],
    color: vars["--ads-color-text-muted"],
  },
  emptyRow: {
    paddingInline: vars["--ads-space-12"],
    paddingBlock: vars["--ads-space-32"],
    textAlign: "center",
    fontSize: vars["--ads-font-size-body"],
    color: vars["--ads-color-text-muted"],
  },
  groupLabel: {
    paddingInline: vars["--ads-space-12"],
    paddingBlockStart: vars["--ads-space-8"],
    paddingBlockEnd: vars["--ads-space-4"],
    fontSize: vars["--ads-font-size-micro"],
    fontWeight: vars["--ads-font-weight-semibold"],
    textTransform: "uppercase",
    letterSpacing: "0.12em",
    color: vars["--ads-color-text-muted"],
  },
  optionRow: {
    paddingInline: vars["--ads-space-4"],
    paddingBlockEnd: vars["--ads-space-4"],
  },
  option: {
    position: "relative",
    display: "flex",
    width: "100%",
    cursor: "default",
    alignItems: "center",
    gap: vars["--ads-space-8"],
    borderRadius: vars["--ads-radius-mark"],
    paddingBlock: vars["--ads-space-8"],
    paddingInlineEnd: vars["--ads-space-8"],
    paddingInlineStart: vars["--ads-space-12"],
    textAlign: "left",
    fontSize: vars["--ads-font-size-body"],
    userSelect: "none",
  },
  optionHighlighted: {
    backgroundColor: {
      default: vars["--ads-color-selection-fill"],
      ":hover": vars["--ads-color-selection-fill"],
    },
    color: { default: vars["--ads-color-text"], ":hover": vars["--ads-color-text"] },
  },
  optionIdle: {
    backgroundColor: { default: "transparent", ":hover": vars["--ads-color-overlay-hover"] },
    color: { default: vars["--ads-color-text"], ":hover": vars["--ads-color-text"] },
  },
  optionLabel: {
    minWidth: 0,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  optionCheck: {
    display: "flex",
    width: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
    color: vars["--ads-color-text"],
  },
  checkIcon: {
    width: 16,
    height: 16,
  },
  loaderInline: {
    flexShrink: 0,
  },
});
