import * as stylex from "@stylexjs/stylex";

import { vars } from "../ads/tokens/tokens.stylex";

/** The inbox becomes a real column here; below it is a compact top rail. */
const COLUMN = "@media (min-width: 40rem)";
/** Wide enough to give an open task-control surface room without crowding. */
const ROOMY = "@media (min-width: 64rem)";

export const fleetStyles = stylex.create({
  root: {
    backgroundColor: vars.colorCanvas,
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    overflow: "hidden",
    position: "relative",
  },
  header: {
    alignItems: "center",
    // A single sheen across the chrome: the surface tint fading into the
    // canvas, so the header reads as raised without a second border.
    backgroundImage: `linear-gradient(110deg, color-mix(in oklch, ${vars.colorSurface} 92%, ${vars.colorCanvas}), ${vars.colorCanvas})`,
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    display: "flex",
    flexShrink: 0,
    gap: vars.space16,
    justifyContent: "space-between",
    minHeight: 56,
    paddingBlock: vars.space8,
    paddingInline: vars.space16,
  },
  headerIdentity: {
    alignItems: "center",
    display: "flex",
    gap: vars.space8,
    minWidth: 0,
  },
  headerIcon: {
    color: vars.colorAccent,
    flexShrink: 0,
    height: 16,
    width: 16,
  },
  headerTitle: {
    color: vars.colorText,
    fontFamily: vars.fontSans,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightSemibold,
    letterSpacing: "-0.01em",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerSummary: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeMicro,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerActions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: vars.space8,
  },
  headerAction: {
    height: 28,
  },
  headerIconAction: {
    height: 28,
    padding: 0,
    width: 28,
  },
  actionIcon: {
    height: 14,
    width: 14,
  },
  closeIcon: {
    height: 16,
    width: 16,
  },
  /** Shortcut hint inside the accent button, tinted from its own ink. */
  shortcut: {
    backgroundColor: `color-mix(in oklch, ${vars.colorAccentText} 10%, transparent)`,
    borderColor: `color-mix(in oklch, ${vars.colorAccentText} 20%, transparent)`,
    borderRadius: vars.radiusMark,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    fontFamily: vars.fontMono,
    fontSize: 9,
    marginInlineStart: vars.space4,
    paddingInline: vars.space4,
  },
  notice: {
    alignItems: "center",
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    display: "flex",
    flexWrap: "wrap",
    fontSize: vars.fontSizeCaption,
    gap: vars.space8,
    paddingBlock: vars.space8,
    paddingInline: vars.space16,
  },
  noticeMuted: {
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    paddingBlock: vars.space8,
    paddingInline: vars.space16,
  },
  body: {
    display: "flex",
    flexBasis: 0,
    flexDirection: {
      default: "column",
      [COLUMN]: "row",
    },
    flexGrow: 1,
    minHeight: 0,
  },
  inbox: {
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: {
      default: vars.borderWidthHairline,
      [COLUMN]: 0,
    },
    flexShrink: 0,
    height: {
      default: 160,
      [COLUMN]: "100%",
    },
    minHeight: 0,
    width: "100%",
  },
  inboxRested: {
    width: {
      default: "100%",
      [COLUMN]: 256,
      [ROOMY]: 320,
    },
  },
  inboxExpanded: {
    width: {
      default: "100%",
      [COLUMN]: 320,
      [ROOMY]: 448,
    },
  },
  board: {
    display: "flex",
    flexBasis: 0,
    flexDirection: "column",
    flexGrow: 1,
    minHeight: 0,
    minWidth: 0,
  },
  toolbar: {
    alignItems: "center",
    backgroundColor: vars.colorCanvas,
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    display: "flex",
    flexShrink: 0,
    flexWrap: "wrap",
    gap: vars.space8,
    paddingBlock: vars.space8,
    paddingInline: vars.space16,
  },
  filterGroup: {
    alignItems: "center",
    backgroundColor: vars.colorCanvasSubtle,
    borderRadius: vars.radiusControl,
    display: "flex",
    flexWrap: "wrap",
    gap: vars.space2,
    padding: vars.space2,
  },
  filterChip: {
    fontSize: vars.fontSizeMicro,
    height: 26,
    paddingInline: vars.space8,
  },
  filterChipActive: {
    backgroundColor: vars.colorCanvas,
    borderColor: vars.colorBorder,
    boxShadow: vars.elevationRaised,
  },
  searchField: {
    marginInlineStart: "auto",
    maxWidth: 320,
    minWidth: 192,
    position: "relative",
    width: {
      default: "100%",
      [COLUMN]: 256,
    },
  },
  searchIcon: {
    color: vars.colorTextMuted,
    height: 14,
    insetInlineStart: 10,
    pointerEvents: "none",
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    width: 14,
  },
  searchInput: {
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: {
      default: "transparent",
      ":hover": vars.colorBorder,
    },
    fontSize: vars.fontSizeCaption,
    height: 28,
    paddingInlineEnd: vars.space32,
    paddingInlineStart: vars.space32,
  },
  searchClear: {
    color: {
      default: vars.colorTextMuted,
      ":hover": vars.colorText,
    },
    insetInlineEnd: vars.space4,
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
  },
  scroller: {
    flexBasis: 0,
    flexGrow: 1,
    minHeight: 0,
    overflowY: "auto",
  },
  boardEmpty: {
    paddingBlock: 48,
    paddingInline: vars.space16,
    textAlign: "center",
  },
  boardEmptyTitle: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
  },
  boardEmptyHint: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    marginTop: vars.space4,
  },
  boardEmptyAction: {
    borderRadius: vars.radiusMark,
    marginTop: vars.space12,
  },
  projectSection: {
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: {
      default: vars.borderWidthHairline,
      ":last-child": 0,
    },
  },
  projectHeader: {
    alignItems: "center",
    backdropFilter: "blur(8px)",
    backgroundColor: vars.colorCanvas,
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    display: "flex",
    gap: 6,
    minHeight: 36,
    paddingBlock: 6,
    paddingInline: vars.space16,
    position: "sticky",
    textAlign: "left",
    top: 0,
    width: "100%",
    zIndex: {
      default: vars.zIndexPanel,
      ":focus-visible": vars.zIndexAppChrome,
    },
  },
  projectChevron: {
    color: vars.colorTextMuted,
    flexShrink: 0,
    height: 14,
    width: 14,
  },
  projectName: {
    color: vars.colorText,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightSemibold,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  projectCount: {
    color: vars.colorTextMuted,
    flexShrink: 0,
    fontSize: vars.fontSizeMicro,
    fontVariantNumeric: "tabular-nums",
  },
  projectCurrent: {
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusMark,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    color: vars.colorTextMuted,
    flexShrink: 0,
    fontSize: 9,
    marginInlineStart: vars.space4,
    paddingInline: vars.space4,
  },
  cardGrid: {
    alignItems: "start",
    display: "grid",
    gap: 10,
    gridTemplateColumns:
      "repeat(auto-fill, minmax(min(100%, max(17rem, calc((100% - 2 * 0.625rem) / 3))), 1fr))",
    paddingBlock: vars.space12,
    paddingInline: vars.space16,
  },
  footnote: {
    alignItems: "center",
    color: vars.colorTextMuted,
    display: "flex",
    flexWrap: "wrap",
    fontSize: vars.fontSizeMicro,
    gap: vars.space8,
    paddingBlock: vars.space12,
    paddingInline: vars.space16,
  },
  footnoteIcon: {
    height: 14,
    width: 14,
  },
  footnoteAction: {
    fontSize: vars.fontSizeMicro,
    height: 24,
    paddingInline: vars.space8,
  },
});
