import * as stylex from "@stylexjs/stylex";

import { vars } from "../ads/tokens/tokens.stylex";

export const commandPaletteStyles = stylex.create({
  /** Wider than the default dialog: palette rows carry title + subtitle + keys. */
  dialog: { maxWidth: "44rem" },
  frame: {
    blockSize: "min(74vh, 36rem)",
    display: "flex",
    flexDirection: "column",
    minBlockSize: 0,
  },
  /** The frame owns the height, so the list scrolls instead of capping at 18rem. */
  list: {
    flexGrow: 1,
    maxHeight: "none",
    minBlockSize: 0,
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-8"],
  },
  empty: {
    paddingBlock: vars["--ads-space-40"],
    paddingInline: vars["--ads-space-16"],
    textAlign: "left",
  },
  emptyTitle: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
    margin: 0,
  },
  emptyHint: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-body"],
    marginBlockEnd: 0,
    marginBlockStart: vars["--ads-space-4"],
  },
  group: { paddingBlock: vars["--ads-space-4"] },
  item: {
    alignItems: "flex-start",
    gap: vars["--ads-space-12"],
    paddingBlock: 10,
    paddingInline: vars["--ads-space-12"],
  },
  itemIconBox: {
    alignItems: "center",
    blockSize: vars["--ads-space-20"],
    display: "flex",
    flexShrink: 0,
    inlineSize: vars["--ads-space-20"],
    justifyContent: "center",
    marginBlockStart: 2,
  },
  itemIconBoxMuted: { color: vars["--ads-color-text-muted"] },
  itemIcon: {
    blockSize: vars["--ads-control-icon-size-sm"],
    inlineSize: vars["--ads-control-icon-size-sm"],
  },
  itemBody: { flexGrow: 1, minInlineSize: 0 },
  itemTitleRow: {
    alignItems: "center",
    display: "flex",
    gap: vars["--ads-space-8"],
    minInlineSize: 0,
  },
  itemTitle: {
    color: vars["--ads-color-text"],
    fontWeight: vars["--ads-font-weight-medium"],
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  extBadge: {
    letterSpacing: "0.12em",
    fontSize: vars["--ads-font-size-micro"],
    minBlockSize: 16,
    paddingInline: vars["--ads-space-4"],
    textTransform: "uppercase",
  },
  contextBadge: {
    fontSize: vars["--ads-font-size-micro"],
    fontWeight: vars["--ads-font-weight-medium"],
    letterSpacing: "normal",
    minBlockSize: 16,
    paddingInline: 6,
  },
  itemSubtitle: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    marginBlockEnd: 0,
    marginBlockStart: 2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  footer: {
    alignItems: "center",
    blockSize: 44,
    borderBlockStartColor: vars["--ads-color-border-subtle"],
    borderBlockStartStyle: "solid",
    borderBlockStartWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-text-muted"],
    display: "flex",
    flexShrink: 0,
    fontSize: vars["--ads-font-size-micro"],
    gap: vars["--ads-space-12"],
    justifyContent: "space-between",
    paddingInline: vars["--ads-space-12"],
  },
  footerGroup: {
    alignItems: "center",
    display: "flex",
    gap: vars["--ads-space-12"],
    minInlineSize: 0,
  },
  footerGroupTight: {
    alignItems: "center",
    display: "flex",
    gap: vars["--ads-space-8"],
    minInlineSize: 0,
  },
  footerHint: {
    alignItems: "center",
    display: "inline-flex",
    gap: 6,
  },
  footerIcon: { blockSize: 12, inlineSize: 12 },
  pinButton: {
    blockSize: 28,
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-micro"],
    gap: 6,
    maxInlineSize: 224,
    paddingInline: vars["--ads-space-8"],
  },
  pinLabel: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  resultCount: { flexShrink: 0, fontVariantNumeric: "tabular-nums" },
});
