import * as stylex from "@stylexjs/stylex";

import { vars } from "@/components/ads/tokens/tokens.stylex";

export const kickoffStyles = stylex.create({
  surface: {
    maxHeight: "calc(100dvh - 2rem)",
    width: "calc(100% - 2rem)",
    maxWidth: {
      default: "28rem",
      "@media (min-width: 40rem)": "56rem",
    },
    gridTemplateRows: "auto minmax(0, 1fr) auto",
    gap: 0,
    overflow: "hidden",
    padding: 0,
  },
  busyState: {
    display: "flex",
    minHeight: "20rem",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    paddingInline: vars.space24,
    paddingBlock: 48,
    textAlign: "center",
  },
  busyOrb: {
    display: "grid",
    width: 96,
    height: 96,
    placeItems: "center",
    borderRadius: vars.radiusFull,
    backgroundColor: vars.colorSurfaceTint,
    boxShadow: `0 0 0 1px ${vars.colorBorder}`,
  },
  busyTitle: {
    marginBlock: 0,
    marginBlockStart: vars.space24,
    fontSize: vars.fontSizeLead,
    fontWeight: vars.fontWeightSemibold,
    lineHeight: vars.lineHeightLead,
  },
  busyCopy: {
    marginBlock: 0,
    marginBlockStart: vars.space8,
    maxWidth: "24rem",
    fontSize: vars.fontSizeBody,
    lineHeight: vars.lineHeightRelaxed,
    color: vars.colorTextMuted,
  },
  busyBadge: {
    marginBlockStart: vars.space16,
  },
  header: {
    borderBottomWidth: vars.borderWidthHairline,
    borderBottomStyle: "solid",
    borderBottomColor: vars.colorBorder,
    paddingInlineStart: vars.space24,
    paddingInlineEnd: 56,
    paddingBlockStart: vars.space24,
    paddingBlockEnd: vars.space20,
  },
  headerRow: {
    display: "flex",
    alignItems: "center",
    gap: vars.space12,
  },
  headerMark: {
    display: "grid",
    width: 36,
    height: 36,
    flexShrink: 0,
    placeItems: "center",
    borderRadius: vars.radiusPanel,
    backgroundColor: vars.colorAccentSoft,
    color: vars.colorAccent,
  },
  headerMarkIcon: {
    width: 16,
    height: 16,
  },
  headerCopy: {
    minWidth: 0,
  },
  headerDescription: {
    marginBlockStart: vars.space4,
  },
  steps: {
    marginBlockStart: vars.space16,
    display: "flex",
    alignItems: "center",
    gap: vars.space8,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
  },
  stepActive: {
    color: vars.colorText,
  },
  stepIdle: {
    color: vars.colorTextMuted,
  },
  stepDivider: {
    height: 1,
    width: vars.space32,
    backgroundColor: vars.colorBorder,
  },
  footer: {
    borderTopWidth: vars.borderWidthHairline,
    borderTopStyle: "solid",
    borderTopColor: vars.colorBorder,
    backgroundColor: vars.colorSurfaceTint,
    paddingInline: vars.space24,
    paddingBlock: vars.space16,
  },
  creatingNote: {
    borderTopWidth: vars.borderWidthHairline,
    borderTopStyle: "solid",
    borderTopColor: vars.colorBorder,
    backgroundColor: vars.colorSurfaceTint,
    paddingInline: vars.space24,
    paddingBlock: vars.space16,
    textAlign: "center",
    fontSize: vars.fontSizeCaption,
    color: vars.colorTextMuted,
  },
  scroll: {
    minHeight: 0,
    overflowY: "auto",
    paddingInline: vars.space24,
    paddingBlock: vars.space20,
  },
  sourceStack: {
    display: "grid",
    gap: vars.space20,
  },
  previewStack: {
    display: "grid",
    gap: vars.space16,
  },
  field: {
    display: "grid",
    gap: vars.space8,
  },
  fieldHeaderRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: vars.space12,
  },
  label: {
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
  },
  sourceTextarea: {
    minHeight: 176,
    resize: "vertical",
    backgroundColor: vars.colorCanvas,
    fontSize: vars.fontSizeBody,
    lineHeight: vars.lineHeightRelaxed,
  },
  hint: {
    marginBlock: 0,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightNormal,
    color: vars.colorTextMuted,
  },
  hintSpaced: {
    marginBlock: 0,
    marginBlockStart: vars.space8,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightNormal,
    color: vars.colorTextMuted,
  },
  mcpPanel: {
    borderRadius: vars.radiusPanel,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: vars.colorBorder,
    backgroundColor: vars.colorSurfaceTint,
    paddingInline: vars.space16,
    paddingBlock: vars.space12,
  },
  mcpHeading: {
    display: "flex",
    alignItems: "center",
    gap: vars.space8,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
  },
  successIcon: {
    width: 16,
    height: 16,
    color: vars.colorSuccess,
  },
  warningIcon: {
    width: 16,
    height: 16,
    color: vars.colorWarning,
  },
  mcpBadges: {
    marginBlockStart: vars.space8,
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  error: {
    marginBlock: 0,
    fontSize: vars.fontSizeBody,
    color: vars.colorDangerText,
  },
  errorHint: {
    marginBlock: 0,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightNormal,
    color: vars.colorDangerText,
  },
  buttonIcon: {
    width: 16,
    height: 16,
  },
  smallIcon: {
    width: 14,
    height: 14,
  },
  degradedNote: {
    display: "flex",
    gap: vars.space8,
    borderRadius: vars.radiusPanel,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: vars.colorWarningBorder,
    backgroundColor: vars.colorWarningSoft,
    paddingInline: vars.space16,
    paddingBlock: vars.space12,
    fontSize: vars.fontSizeBody,
  },
  degradedIcon: {
    marginBlockStart: 2,
    width: 16,
    height: 16,
    flexShrink: 0,
    color: vars.colorWarning,
  },
  degradedCopy: {
    marginBlock: 0,
    lineHeight: vars.lineHeightNormal,
  },
  section: {
    display: "grid",
    gap: vars.space16,
    borderRadius: vars.radiusPanel,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: vars.colorBorder,
    backgroundColor: vars.colorSurfaceTint,
    padding: vars.space16,
  },
  sectionTitle: {
    marginBlock: 0,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightSemibold,
  },
  sectionCopy: {
    marginBlock: 0,
    marginBlockStart: vars.space4,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightNormal,
    color: vars.colorTextMuted,
  },
  twoColumn: {
    display: "grid",
    gap: vars.space16,
    gridTemplateColumns: {
      default: "minmax(0, 1fr)",
      "@media (min-width: 40rem)": "repeat(2, minmax(0, 1fr))",
    },
  },
  labeledField: {
    display: "grid",
    gap: vars.space8,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
  },
  labeledFieldTight: {
    display: "grid",
    gap: 6,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
  },
  monoInput: {
    fontFamily: vars.fontMono,
  },
  fieldNote: {
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightRegular,
    color: vars.colorTextMuted,
  },
  summaryTextarea: {
    minHeight: 80,
    lineHeight: vars.lineHeightNormal,
  },
  sectionHeaderRow: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: vars.space12,
  },
  sectionHeaderRowWide: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: vars.space16,
  },
  emptyNote: {
    marginBlock: 0,
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "dashed",
    borderColor: vars.colorBorder,
    paddingInline: vars.space12,
    paddingBlock: vars.space16,
    fontSize: vars.fontSizeBody,
    lineHeight: vars.lineHeightNormal,
    color: vars.colorTextMuted,
  },
  emptyNoteSmall: {
    marginBlock: 0,
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "dashed",
    borderColor: vars.colorBorder,
    paddingInline: vars.space12,
    paddingBlock: vars.space16,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightNormal,
    color: vars.colorTextMuted,
  },
  entryItem: {
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: vars.colorBorder,
  },
  entryHeaderRow: {
    display: "flex",
    alignItems: "center",
    gap: vars.space8,
    paddingInlineEnd: vars.space12,
  },
  entryTriggerLabel: {
    display: "flex",
    minWidth: 0,
    alignItems: "center",
    gap: vars.space8,
    paddingInlineEnd: vars.space12,
  },
  entryBadge: {
    flexShrink: 0,
  },
  entryText: {
    minWidth: 0,
  },
  entryTitle: {
    display: "block",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
  },
  entryMeta: {
    display: "block",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightRegular,
    color: vars.colorTextMuted,
  },
  entryRemove: {
    flexShrink: 0,
  },
  entryPanel: {
    display: "grid",
    gap: vars.space12,
    paddingInline: vars.space12,
    paddingBlockEnd: vars.space12,
  },
  entryPanelGrid: {
    display: "grid",
    gap: vars.space12,
    gridTemplateColumns: {
      default: "minmax(0, 1fr)",
      "@media (min-width: 40rem)": "repeat(2, minmax(0, 1fr))",
    },
  },
  noteTextarea: {
    minHeight: 64,
  },
  notesTextarea: {
    minHeight: 112,
  },
  promptTextarea: {
    minHeight: 144,
    lineHeight: vars.lineHeightRelaxed,
  },
  instructionsTextarea: {
    minHeight: 80,
  },
  splitSection: {
    display: "grid",
    gap: vars.space16,
    borderTopWidth: vars.borderWidthHairline,
    borderTopStyle: "solid",
    borderTopColor: vars.colorBorder,
    paddingBlockStart: vars.space16,
    gridTemplateColumns: {
      default: "minmax(0, 1fr)",
      "@media (min-width: 40rem)": "repeat(2, minmax(0, 1fr))",
    },
  },
  todoHeaderRow: {
    display: "flex",
    minHeight: 36,
    alignItems: "center",
    justifyContent: "space-between",
    gap: vars.space8,
  },
  todoAddButton: {
    fontSize: vars.fontSizeCaption,
  },
  todoList: {
    display: "grid",
    gap: vars.space8,
  },
  todoRow: {
    display: "flex",
    gap: vars.space8,
  },
  startToggle: {
    display: "flex",
    flexShrink: 0,
    alignItems: "center",
    gap: vars.space8,
    borderRadius: vars.radiusControl,
    backgroundColor: vars.colorSurfaceTint,
    paddingInline: vars.space12,
    paddingBlock: vars.space8,
  },
  runtimeGrid: {
    display: "grid",
    gap: vars.space16,
    gridTemplateColumns: {
      default: "minmax(0, 1fr)",
      "@media (min-width: 40rem)": "minmax(0, 1fr) 10rem",
    },
  },
  runtimeGridWithFast: {
    display: "grid",
    gap: vars.space16,
    gridTemplateColumns: {
      default: "minmax(0, 1fr)",
      "@media (min-width: 40rem)": "minmax(0, 1fr) 10rem 10rem",
    },
  },
  fullWidth: {
    width: "100%",
  },
  modelSelectorTrigger: {
    height: 36,
    width: "100%",
    maxWidth: "none",
    borderColor: vars.colorBorder,
    backgroundColor: vars.colorCanvas,
    paddingInline: vars.space12,
  },
  modelSelectorMenu: {
    maxWidth: {
      default: null,
      "@media (min-width: 40rem)": "32rem",
    },
  },
});
