import * as stylex from "@stylexjs/stylex";

import { vars } from "@/components/ads/tokens/tokens.stylex";

export const kickoffStyles = stylex.create({
  surface: {
    maxHeight: "calc(100dvh - 2rem)",
    width: "calc(100% - 2rem)",
    maxWidth: {
      default: "28rem",
      "@media (min-width: 40rem)": "56rem",
    },
    gridTemplateRows: "auto minmax(0, 1fr) auto",
    gap: 0,
    overflow: "hidden",
    padding: 0,
  },
  busyState: {
    display: "flex",
    minHeight: "20rem",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    paddingInline: vars["--ads-space-24"],
    paddingBlock: 48,
    textAlign: "center",
  },
  busyOrb: {
    display: "grid",
    width: 96,
    height: 96,
    placeItems: "center",
    borderRadius: vars["--ads-radius-full"],
    backgroundColor: vars["--ads-color-surface-tint"],
    boxShadow: `0 0 0 1px ${vars["--ads-color-border"]}`,
  },
  busyTitle: {
    marginBlock: 0,
    marginBlockStart: vars["--ads-space-24"],
    fontSize: vars["--ads-font-size-lead"],
    fontWeight: vars["--ads-font-weight-semibold"],
    lineHeight: vars["--ads-line-height-lead"],
  },
  busyCopy: {
    marginBlock: 0,
    marginBlockStart: vars["--ads-space-8"],
    maxWidth: "24rem",
    fontSize: vars["--ads-font-size-body"],
    lineHeight: vars["--ads-line-height-relaxed"],
    color: vars["--ads-color-text-muted"],
  },
  busyBadge: {
    marginBlockStart: vars["--ads-space-16"],
  },
  header: {
    borderBottomWidth: vars["--ads-border-width-hairline"],
    borderBottomStyle: "solid",
    borderBottomColor: vars["--ads-color-border"],
    paddingInlineStart: vars["--ads-space-24"],
    paddingInlineEnd: 56,
    paddingBlockStart: vars["--ads-space-24"],
    paddingBlockEnd: vars["--ads-space-20"],
  },
  headerRow: {
    display: "flex",
    alignItems: "center",
    gap: vars["--ads-space-12"],
  },
  headerMark: {
    display: "grid",
    width: 36,
    height: 36,
    flexShrink: 0,
    placeItems: "center",
    borderRadius: vars["--ads-radius-panel"],
    backgroundColor: vars["--ads-color-surface-tint"],
    color: vars["--ads-color-text-muted"],
  },
  headerMarkIcon: {
    width: 16,
    height: 16,
  },
  headerCopy: {
    minWidth: 0,
  },
  headerDescription: {
    marginBlockStart: vars["--ads-space-4"],
  },
  steps: {
    marginBlockStart: vars["--ads-space-16"],
    display: "flex",
    alignItems: "center",
    gap: vars["--ads-space-8"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  stepActive: {
    color: vars["--ads-color-text"],
  },
  stepIdle: {
    color: vars["--ads-color-text-muted"],
  },
  stepDivider: {
    height: 1,
    width: vars["--ads-space-32"],
    backgroundColor: vars["--ads-color-border"],
  },
  footer: {
    borderTopWidth: vars["--ads-border-width-hairline"],
    borderTopStyle: "solid",
    borderTopColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface-tint"],
    paddingInline: vars["--ads-space-24"],
    paddingBlock: vars["--ads-space-16"],
  },
  creatingNote: {
    borderTopWidth: vars["--ads-border-width-hairline"],
    borderTopStyle: "solid",
    borderTopColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface-tint"],
    paddingInline: vars["--ads-space-24"],
    paddingBlock: vars["--ads-space-16"],
    textAlign: "center",
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text-muted"],
  },
  scroll: {
    minHeight: 0,
    overflowY: "auto",
    paddingInline: vars["--ads-space-24"],
    paddingBlock: vars["--ads-space-20"],
  },
  sourceStack: {
    display: "grid",
    gap: vars["--ads-space-20"],
  },
  previewStack: {
    display: "grid",
    gap: vars["--ads-space-16"],
  },
  field: {
    display: "grid",
    gap: vars["--ads-space-8"],
  },
  fieldHeaderRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: vars["--ads-space-12"],
  },
  label: {
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  sourceTextarea: {
    minHeight: 176,
    resize: "vertical",
    backgroundColor: vars["--ads-color-canvas"],
    fontSize: vars["--ads-font-size-body"],
    lineHeight: vars["--ads-line-height-relaxed"],
  },
  hint: {
    marginBlock: 0,
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
    color: vars["--ads-color-text-muted"],
  },
  hintSpaced: {
    marginBlock: 0,
    marginBlockStart: vars["--ads-space-8"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
    color: vars["--ads-color-text-muted"],
  },
  mcpPanel: {
    borderRadius: vars["--ads-radius-panel"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface-tint"],
    paddingInline: vars["--ads-space-16"],
    paddingBlock: vars["--ads-space-12"],
  },
  mcpHeading: {
    display: "flex",
    alignItems: "center",
    gap: vars["--ads-space-8"],
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  successIcon: {
    width: 16,
    height: 16,
    color: vars["--ads-color-success"],
  },
  warningIcon: {
    width: 16,
    height: 16,
    color: vars["--ads-color-warning"],
  },
  mcpBadges: {
    marginBlockStart: vars["--ads-space-8"],
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  error: {
    marginBlock: 0,
    fontSize: vars["--ads-font-size-body"],
    color: vars["--ads-color-danger-text"],
  },
  errorHint: {
    marginBlock: 0,
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
    color: vars["--ads-color-danger-text"],
  },
  buttonIcon: {
    width: 16,
    height: 16,
  },
  smallIcon: {
    width: 14,
    height: 14,
  },
  degradedNote: {
    display: "flex",
    gap: vars["--ads-space-8"],
    borderRadius: vars["--ads-radius-panel"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-warning-border"],
    backgroundColor: vars["--ads-color-warning-soft"],
    paddingInline: vars["--ads-space-16"],
    paddingBlock: vars["--ads-space-12"],
    fontSize: vars["--ads-font-size-body"],
  },
  degradedIcon: {
    marginBlockStart: 2,
    width: 16,
    height: 16,
    flexShrink: 0,
    color: vars["--ads-color-warning"],
  },
  degradedCopy: {
    marginBlock: 0,
    lineHeight: vars["--ads-line-height-normal"],
  },
  section: {
    display: "grid",
    gap: vars["--ads-space-16"],
    borderRadius: vars["--ads-radius-panel"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface-tint"],
    padding: vars["--ads-space-16"],
  },
  sectionTitle: {
    marginBlock: 0,
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-semibold"],
  },
  sectionCopy: {
    marginBlock: 0,
    marginBlockStart: vars["--ads-space-4"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
    color: vars["--ads-color-text-muted"],
  },
  twoColumn: {
    display: "grid",
    gap: vars["--ads-space-16"],
    gridTemplateColumns: {
      default: "minmax(0, 1fr)",
      "@media (min-width: 40rem)": "repeat(2, minmax(0, 1fr))",
    },
  },
  labeledField: {
    display: "grid",
    gap: vars["--ads-space-8"],
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  labeledFieldTight: {
    display: "grid",
    gap: 6,
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  monoInput: {
    fontFamily: vars["--ads-font-mono"],
  },
  fieldNote: {
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-regular"],
    color: vars["--ads-color-text-muted"],
  },
  summaryTextarea: {
    minHeight: 80,
    lineHeight: vars["--ads-line-height-normal"],
  },
  sectionHeaderRow: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: vars["--ads-space-12"],
  },
  sectionHeaderRowWide: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: vars["--ads-space-16"],
  },
  emptyNote: {
    marginBlock: 0,
    borderRadius: vars["--ads-radius-control"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "dashed",
    borderColor: vars["--ads-color-border"],
    paddingInline: vars["--ads-space-12"],
    paddingBlock: vars["--ads-space-16"],
    fontSize: vars["--ads-font-size-body"],
    lineHeight: vars["--ads-line-height-normal"],
    color: vars["--ads-color-text-muted"],
  },
  emptyNoteSmall: {
    marginBlock: 0,
    borderRadius: vars["--ads-radius-control"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "dashed",
    borderColor: vars["--ads-color-border"],
    paddingInline: vars["--ads-space-12"],
    paddingBlock: vars["--ads-space-16"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
    color: vars["--ads-color-text-muted"],
  },
  entryItem: {
    borderRadius: vars["--ads-radius-control"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
  },
  entryHeaderRow: {
    display: "flex",
    alignItems: "center",
    gap: vars["--ads-space-8"],
    paddingInlineEnd: vars["--ads-space-12"],
  },
  entryTriggerLabel: {
    display: "flex",
    minWidth: 0,
    alignItems: "center",
    gap: vars["--ads-space-8"],
    paddingInlineEnd: vars["--ads-space-12"],
  },
  entryBadge: {
    flexShrink: 0,
  },
  entryText: {
    minWidth: 0,
  },
  entryTitle: {
    display: "block",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  entryMeta: {
    display: "block",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-regular"],
    color: vars["--ads-color-text-muted"],
  },
  entryRemove: {
    flexShrink: 0,
  },
  entryPanel: {
    display: "grid",
    gap: vars["--ads-space-12"],
    paddingInline: vars["--ads-space-12"],
    paddingBlockEnd: vars["--ads-space-12"],
  },
  entryPanelGrid: {
    display: "grid",
    gap: vars["--ads-space-12"],
    gridTemplateColumns: {
      default: "minmax(0, 1fr)",
      "@media (min-width: 40rem)": "repeat(2, minmax(0, 1fr))",
    },
  },
  noteTextarea: {
    minHeight: 64,
  },
  notesTextarea: {
    minHeight: 112,
  },
  promptTextarea: {
    minHeight: 144,
    lineHeight: vars["--ads-line-height-relaxed"],
  },
  instructionsTextarea: {
    minHeight: 80,
  },
  splitSection: {
    display: "grid",
    gap: vars["--ads-space-16"],
    borderTopWidth: vars["--ads-border-width-hairline"],
    borderTopStyle: "solid",
    borderTopColor: vars["--ads-color-border"],
    paddingBlockStart: vars["--ads-space-16"],
    gridTemplateColumns: {
      default: "minmax(0, 1fr)",
      "@media (min-width: 40rem)": "repeat(2, minmax(0, 1fr))",
    },
  },
  todoHeaderRow: {
    display: "flex",
    minHeight: 36,
    alignItems: "center",
    justifyContent: "space-between",
    gap: vars["--ads-space-8"],
  },
  todoAddButton: {
    fontSize: vars["--ads-font-size-caption"],
  },
  todoList: {
    display: "grid",
    gap: vars["--ads-space-8"],
  },
  todoRow: {
    display: "flex",
    gap: vars["--ads-space-8"],
  },
  startToggle: {
    display: "flex",
    flexShrink: 0,
    alignItems: "center",
    gap: vars["--ads-space-8"],
    borderRadius: vars["--ads-radius-control"],
    backgroundColor: vars["--ads-color-surface-tint"],
    paddingInline: vars["--ads-space-12"],
    paddingBlock: vars["--ads-space-8"],
  },
  runtimeGrid: {
    display: "grid",
    gap: vars["--ads-space-16"],
    gridTemplateColumns: {
      default: "minmax(0, 1fr)",
      "@media (min-width: 40rem)": "minmax(0, 1fr) 10rem",
    },
  },
  runtimeGridWithFast: {
    display: "grid",
    gap: vars["--ads-space-16"],
    gridTemplateColumns: {
      default: "minmax(0, 1fr)",
      "@media (min-width: 40rem)": "minmax(0, 1fr) 10rem 10rem",
    },
  },
  fullWidth: {
    width: "100%",
  },
  modelSelectorTrigger: {
    height: 36,
    width: "100%",
    maxWidth: "none",
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-canvas"],
    paddingInline: vars["--ads-space-12"],
  },
  modelSelectorMenu: {
    maxWidth: {
      default: null,
      "@media (min-width: 40rem)": "32rem",
    },
  },
});
