import * as stylex from "@stylexjs/stylex";

import { vars } from "@/components/ads/tokens/tokens.stylex";

export const layoutShellStyles = stylex.create({
  editorPanel: { height: "100%", minWidth: 0, overflow: "hidden", width: "100%" },
  editorPanelBody: {
    backgroundColor: vars.colorSurface,
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
  },
  statusBar: {
    alignItems: "center",
    backgroundColor: vars.colorSurface,
    borderTopColor: vars.colorBorder,
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "flex",
    flexShrink: 0,
    fontSize: vars.fontSizeCaption,
    height: 28,
    justifyContent: "space-between",
    paddingInline: vars.space4,
  },
  statusGroup: { alignItems: "center", display: "flex", gap: 2 },
  shortcut: {
    borderRadius: vars.radiusMark,
    fontSize: vars.fontSizeMicro,
    fontVariantNumeric: "tabular-nums",
    gap: 2,
    height: 20,
    minWidth: 0,
    paddingInline: vars.space8,
  },
  shortcutSeparator: { color: vars.colorTextMuted },
  identityMark: {
    alignItems: "center",
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusMark,
    borderStyle: "solid",
    borderWidth: 1,
    display: "inline-flex",
    flexShrink: 0,
    height: 20,
    justifyContent: "center",
    width: 20,
  },
  workspaceIcon: { height: 12, width: 12 },
  projectIdentityMark: {
    alignItems: "center",
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: 1,
    display: "inline-flex",
    flexShrink: 0,
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  projectIcon: { height: 14, width: 14 },
  projectColorSwatch: {
    borderColor: vars.colorBorder,
    borderStyle: "solid",
    borderWidth: 1,
    borderRadius: 9999,
    display: "inline-flex",
    height: 20,
    width: 20,
  },
  diffReview: { paddingBlock: vars.space4, width: "100%" },
  topBarButton: {
    borderRadius: vars.radiusControl,
    color: vars.colorTextMuted,
    flexShrink: 0,
    height: 32,
    padding: 0,
    position: "relative",
    width: 32,
    ':hover': { backgroundColor: vars.colorOverlayHover, color: vars.colorText },
  },
  topBarButtonActive: { backgroundColor: vars.colorOverlayHover, color: vars.colorText },
  topBarButtonWarning: { color: vars.colorWarningText },
  topBarAttentionBadge: {
    alignItems: "center",
    backgroundColor: vars.colorWarning,
    borderColor: vars.colorSurface,
    borderRadius: vars.radiusFull,
    borderStyle: "solid",
    borderWidth: 1,
    color: vars.colorText,
    display: "flex",
    fontSize: vars.fontSizeMicro,
    fontWeight: vars.fontWeightSemibold,
    height: 16,
    justifyContent: "center",
    lineHeight: 1,
    minWidth: 16,
    paddingInline: vars.space4,
    position: "absolute",
    right: -4,
    top: -4,
  },
  inlineFlex: { display: "inline-flex" },
  icon16: { height: 16, width: 16 },
  windowControls: { alignItems: "center", display: "flex", flexShrink: 0, gap: 6 },
  windowDivider: { backgroundColor: vars.colorBorder, height: 16, marginInline: vars.space4, width: 1 },
  windowButton: { borderRadius: vars.radiusControl, height: 36, padding: 0, width: 36 },
  closeWindowButton: {
    ':hover': { backgroundColor: vars.colorDanger, color: vars.colorTextInverted },
  },
  icon14: { height: 14, width: 14 },
  subdued: { opacity: 0.8 },
});
