import * as stylex from "@stylexjs/stylex";

import { vars } from "@/components/ads/tokens/tokens.stylex";

export const prContextStyles = stylex.create({
  content: {
    display: "flex",
    flexDirection: "column",
    maxHeight: "80vh",
    maxWidth: { default: null, "@media (min-width: 40rem)": "42rem" },
  },
  loading: {
    alignItems: "center",
    color: vars.colorTextMuted,
    display: "flex",
    fontSize: vars.fontSizeBody,
    gap: vars.space8,
    paddingBlock: vars.space32,
  },
  error: {
    alignItems: "flex-start",
    backgroundColor: vars.colorDangerSoft,
    borderColor: vars.colorDangerBorder,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    color: vars.colorDangerText,
    display: "flex",
    fontSize: vars.fontSizeCaption,
    gap: vars.space8,
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
  },
  errorIcon: { flexShrink: 0, height: 14, marginTop: vars.space2, width: 14 },
  body: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: vars.space16,
    minHeight: 0,
    overflowY: "auto",
    paddingRight: vars.space4,
  },
  meta: { color: vars.colorTextMuted, fontSize: vars.fontSizeCaption },
  sectionHeading: {
    alignItems: "center",
    color: vars.colorText,
    display: "flex",
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
    gap: vars.space4,
    marginBottom: 6,
  },
  sectionHeadingIcon: { color: vars.colorTextMuted, height: 14, width: 14 },
  emptyNote: { color: vars.colorTextMuted, fontSize: vars.fontSizeCaption },
  list: { display: "flex", flexDirection: "column", gap: vars.space4 },
  row: {
    alignItems: "flex-start",
    borderRadius: vars.radiusControl,
    display: "flex",
    gap: vars.space8,
    minWidth: 0,
    paddingBlock: 6,
    paddingInline: 6,
  },
  rowEnabled: {
    backgroundColor: { default: "transparent", ":hover": vars.colorOverlayHover },
    cursor: "pointer",
  },
  rowDisabled: { cursor: "not-allowed", opacity: vars.opacityDisabled },
  // Only the offset the row needs; the painted box keeps its canonical size.
  rowCheckbox: { marginTop: vars.space2 },
  rowText: { flex: 1, minWidth: 0 },
  rowTitleLine: { alignItems: "baseline", display: "flex", gap: vars.space8 },
  rowTitle: {
    color: vars.colorText,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowStatus: {
    color: vars.colorTextMuted,
    flexShrink: 0,
    fontSize: vars.fontSizeMicro,
  },
  rowExcerpt: {
    color: vars.colorTextMuted,
    display: "-webkit-box",
    fontSize: vars.fontSizeCaption,
    overflow: "hidden",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
  },
  rowSubtitle: {
    color: vars.colorTextMuted,
    display: "block",
    fontSize: vars.fontSizeMicro,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  footnote: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeMicro,
    marginTop: vars.space4,
  },
});
