import * as stylex from "@stylexjs/stylex";

import { vars } from "@/components/ads/tokens/tokens.stylex";

export const prContextStyles = stylex.create({
  content: {
    display: "flex",
    flexDirection: "column",
    maxHeight: "80vh",
    maxWidth: { default: null, "@media (min-width: 40rem)": "42rem" },
  },
  loading: {
    alignItems: "center",
    color: vars["--ads-color-text-muted"],
    display: "flex",
    fontSize: vars["--ads-font-size-body"],
    gap: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-32"],
  },
  error: {
    alignItems: "flex-start",
    backgroundColor: vars["--ads-color-danger-soft"],
    borderColor: vars["--ads-color-danger-border"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-danger-text"],
    display: "flex",
    fontSize: vars["--ads-font-size-caption"],
    gap: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
  },
  errorIcon: { flexShrink: 0, height: 14, marginTop: vars["--ads-space-2"], width: 14 },
  body: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: vars["--ads-space-16"],
    minHeight: 0,
    overflowY: "auto",
    paddingRight: vars["--ads-space-4"],
  },
  meta: { color: vars["--ads-color-text-muted"], fontSize: vars["--ads-font-size-caption"] },
  sectionHeading: {
    alignItems: "center",
    color: vars["--ads-color-text"],
    display: "flex",
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
    gap: vars["--ads-space-4"],
    marginBottom: 6,
  },
  sectionHeadingIcon: { color: vars["--ads-color-text-muted"], height: 14, width: 14 },
  emptyNote: { color: vars["--ads-color-text-muted"], fontSize: vars["--ads-font-size-caption"] },
  list: { display: "flex", flexDirection: "column", gap: vars["--ads-space-4"] },
  row: {
    alignItems: "flex-start",
    borderRadius: vars["--ads-radius-control"],
    display: "flex",
    gap: vars["--ads-space-8"],
    minWidth: 0,
    paddingBlock: 6,
    paddingInline: 6,
  },
  rowEnabled: {
    backgroundColor: { default: "transparent", ":hover": vars["--ads-color-overlay-hover"] },
    cursor: "pointer",
  },
  rowDisabled: { cursor: "not-allowed", opacity: vars["--ads-opacity-disabled"] },
  // Only the offset the row needs; the painted box keeps its canonical size.
  rowCheckbox: { marginTop: vars["--ads-space-2"] },
  rowText: { flex: 1, minWidth: 0 },
  rowTitleLine: { alignItems: "baseline", display: "flex", gap: vars["--ads-space-8"] },
  rowTitle: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowStatus: {
    color: vars["--ads-color-text-muted"],
    flexShrink: 0,
    fontSize: vars["--ads-font-size-micro"],
  },
  rowExcerpt: {
    color: vars["--ads-color-text-muted"],
    display: "-webkit-box",
    fontSize: vars["--ads-font-size-caption"],
    overflow: "hidden",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
  },
  rowSubtitle: {
    color: vars["--ads-color-text-muted"],
    display: "block",
    fontSize: vars["--ads-font-size-micro"],
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  footnote: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-micro"],
    marginTop: vars["--ads-space-4"],
  },
});
