import * as stylex from "@stylexjs/stylex";

import { vars } from "@/components/ads/tokens/tokens.stylex";

export const quitDialogStyles = stylex.create({
  surface: {
    maxWidth: "min(30rem, calc(100vw - 2rem))",
    gap: 0,
    padding: 0,
    overflow: "hidden",
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-canvas"],
  },
  headerBand: {
    borderBottomWidth: vars["--ads-border-width-hairline"],
    borderBottomStyle: "solid",
    borderBottomColor: vars["--ads-color-border"],
    backgroundImage: `linear-gradient(to bottom, ${vars["--ads-color-surface-tint"]}, transparent)`,
    paddingInline: vars["--ads-space-20"],
    paddingBlock: vars["--ads-space-20"],
  },
  headerRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: vars["--ads-space-16"],
  },
  headerMark: {
    display: "flex",
    width: 44,
    height: 44,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: vars["--ads-radius-shell"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-danger-border"],
    backgroundColor: vars["--ads-color-danger-soft"],
    boxShadow: vars["--ads-elevation-raised"],
    color: vars["--ads-color-danger-text"],
  },
  headerMarkIcon: {
    width: 20,
    height: 20,
  },
  headerCopy: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-8"],
  },
  eyebrow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: vars["--ads-space-8"],
    fontSize: vars["--ads-font-size-micro"],
    fontWeight: vars["--ads-font-weight-semibold"],
    textTransform: "uppercase",
    letterSpacing: "0.14em",
    color: vars["--ads-color-text-muted"],
  },
  shortcutChip: {
    borderRadius: vars["--ads-radius-control"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-canvas"],
    paddingInline: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-4"],
    fontSize: vars["--ads-font-size-micro"],
    fontWeight: vars["--ads-font-weight-medium"],
    letterSpacing: "normal",
    color: vars["--ads-color-text"],
  },
  description: {
    maxWidth: "26rem",
  },
  body: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-16"],
    paddingInline: vars["--ads-space-20"],
    paddingBlock: vars["--ads-space-16"],
  },
  factList: {
    display: "grid",
    gap: vars["--ads-space-8"],
    borderRadius: vars["--ads-radius-frame"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface-tint"],
    padding: vars["--ads-space-12"],
  },
  factRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
  },
  factIcon: {
    marginBlockStart: 2,
    width: 16,
    height: 16,
    flexShrink: 0,
    color: vars["--ads-color-text-muted"],
  },
  factText: {
    margin: 0,
    fontSize: vars["--ads-font-size-body"],
    color: vars["--ads-color-text"],
  },
  footer: {
    display: "flex",
    flexDirection: { default: "column", "@media (min-width: 40rem)": "row" },
    alignItems: { default: "stretch", "@media (min-width: 40rem)": "center" },
    justifyContent: {
      default: "flex-start",
      "@media (min-width: 40rem)": "space-between",
    },
    gap: vars["--ads-space-12"],
    borderTopWidth: vars["--ads-border-width-hairline"],
    borderTopStyle: "solid",
    borderTopColor: vars["--ads-color-border"],
    paddingBlockStart: vars["--ads-space-16"],
  },
  hintRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: vars["--ads-space-12"],
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text-muted"],
  },
  hint: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
  },
  actions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: vars["--ads-space-8"],
  },
});
