import * as stylex from "@stylexjs/stylex";

import { vars } from "@/components/ads/tokens/tokens.stylex";

export const quitDialogStyles = stylex.create({
  surface: {
    maxWidth: "min(30rem, calc(100vw - 2rem))",
    gap: 0,
    padding: 0,
    overflow: "hidden",
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: vars.colorBorder,
    backgroundColor: vars.colorCanvas,
  },
  headerBand: {
    borderBottomWidth: vars.borderWidthHairline,
    borderBottomStyle: "solid",
    borderBottomColor: vars.colorBorder,
    backgroundImage: `linear-gradient(to bottom, ${vars.colorSurfaceTint}, transparent)`,
    paddingInline: vars.space20,
    paddingBlock: vars.space20,
  },
  headerRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: vars.space16,
  },
  headerMark: {
    display: "flex",
    width: 44,
    height: 44,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: vars.radiusShell,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: vars.colorDangerBorder,
    backgroundColor: vars.colorDangerSoft,
    boxShadow: vars.elevationRaised,
    color: vars.colorDangerText,
  },
  headerMarkIcon: {
    width: 20,
    height: 20,
  },
  headerCopy: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space8,
  },
  eyebrow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: vars.space8,
    fontSize: vars.fontSizeMicro,
    fontWeight: vars.fontWeightSemibold,
    textTransform: "uppercase",
    letterSpacing: "0.14em",
    color: vars.colorTextMuted,
  },
  shortcutChip: {
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: vars.colorBorder,
    backgroundColor: vars.colorCanvas,
    paddingInline: vars.space8,
    paddingBlock: vars.space4,
    fontSize: "0.625rem",
    fontWeight: vars.fontWeightMedium,
    letterSpacing: "normal",
    color: vars.colorText,
  },
  description: {
    maxWidth: "26rem",
  },
  body: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space16,
    paddingInline: vars.space20,
    paddingBlock: vars.space16,
  },
  factList: {
    display: "grid",
    gap: vars.space8,
    borderRadius: vars.radiusFrame,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: vars.colorBorder,
    backgroundColor: vars.colorSurfaceTint,
    padding: vars.space12,
  },
  factRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
  },
  factIcon: {
    marginBlockStart: 2,
    width: 16,
    height: 16,
    flexShrink: 0,
    color: vars.colorTextMuted,
  },
  factText: {
    margin: 0,
    fontSize: vars.fontSizeBody,
    color: vars.colorText,
  },
  footer: {
    display: "flex",
    flexDirection: { default: "column", "@media (min-width: 40rem)": "row" },
    alignItems: { default: "stretch", "@media (min-width: 40rem)": "center" },
    justifyContent: {
      default: "flex-start",
      "@media (min-width: 40rem)": "space-between",
    },
    gap: vars.space12,
    borderTopWidth: vars.borderWidthHairline,
    borderTopStyle: "solid",
    borderTopColor: vars.colorBorder,
    paddingBlockStart: vars.space16,
  },
  hintRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: vars.space12,
    fontSize: vars.fontSizeCaption,
    color: vars.colorTextMuted,
  },
  hint: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
  },
  actions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: vars.space8,
  },
});
