import * as stylex from "@stylexjs/stylex";
import { vars } from "@/components/ads/tokens/tokens.stylex";

export const managerStyles = stylex.create({
  tableScroll: { overflowX: "auto", minWidth: 0 },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: vars["--ads-font-size-caption"],
  },
  columnHeading: {
    textAlign: "start",
    fontWeight: 500,
    color: vars["--ads-color-text-muted"],
    paddingBlock: 8,
    paddingInline: 10,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: vars["--ads-color-border"],
  },
  numericHeading: {
    textAlign: "end",
    fontWeight: 500,
    color: vars["--ads-color-text-muted"],
    paddingBlock: 8,
    paddingInline: 10,
    whiteSpace: "nowrap",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: vars["--ads-color-border"],
  },
  identityCell: {
    textAlign: "start",
    fontWeight: 400,
    paddingBlock: 12,
    paddingInline: 10,
    overflowWrap: "anywhere",
    minWidth: 160,
    verticalAlign: "top",
  },
  numericCell: {
    textAlign: "end",
    fontFamily: vars["--ads-font-mono"],
    fontVariantNumeric: "tabular-nums",
    whiteSpace: "nowrap",
    width: "1%",
    paddingBlock: 12,
    paddingInline: 10,
    verticalAlign: "top",
  },
  dataRow: {
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: vars["--ads-color-border"],
    ":last-child": { borderBottomWidth: 0 },
  },
  processTitle: {
    display: "flex",
    alignItems: "baseline",
    gap: 10,
    flexWrap: "wrap",
    fontWeight: 500,
  },
  pageRow: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: 8,
    padding: 10,
    alignItems: "center",
    "@media (max-width: 720px)": { gridTemplateColumns: "minmax(0, 1fr)" },
  },
  pageMeta: {
    gridColumn: "1 / -1",
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
  },
  groupHeading: {
    display: "flex",
    flex: 1,
    minWidth: 0,
    alignItems: "center",
    gap: 12,
    paddingBlock: 10,
    fontWeight: 500,
  },
  resourceDialog: { padding: 12, gap: 8, overflow: "hidden" },
  heading: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    paddingBlock: 10,
    fontWeight: 500,
  },
  processIdentity: {
    display: "grid",
    gap: 4,
    minWidth: 0,
    overflowWrap: "anywhere",
  },
  section: { display: "grid", gap: 10 },
  toolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
  },
  /**
   * The view switcher's track. Without it the selected view and the actions
   * beside it were the same filled button, so "Workspaces and processes" and
   * "Clean up workspaces" read as two items of one kind. The track says the
   * buttons inside it pick a view; the actions outside it stay `outline`, so
   * "which one changes what I am looking at" is answered by the container
   * rather than by reading the labels.
   */
  segmented: {
    display: "flex",
    alignItems: "center",
    gap: 2,
    padding: 2,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-control"],
    backgroundColor: vars["--ads-color-surface-tint"],
  },
  /** Flat inside the track: an elevated tab would fight the track's own edge. */
  segment: { boxShadow: "none" },
  muted: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
  },
  list: {
    overflowY: "auto",
    minHeight: 0,
    maxHeight: "min(52vh, 32rem)",
    borderBlockWidth: 1,
    borderBlockStyle: "solid",
    borderBlockColor: vars["--ads-color-border"],
  },
  row: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    paddingBlock: 10,
    paddingInline: 4,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: vars["--ads-color-border"],
  },
  identity: { flex: 1, minWidth: 0, display: "grid", gap: 4 },
  truncate: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  value: {
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-caption"],
    whiteSpace: "nowrap",
  },
  actions: { display: "flex", gap: 8, flexWrap: "wrap", alignItems: "center" },
  dialog: {
    width: "min(64rem, calc(100vw - 2rem))",
    maxWidth: "calc(100vw - 2rem)",
    maxHeight: "85vh",
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  filters: { display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" },
  search: { flex: 1, minWidth: 180 },
  name: {
    fontWeight: 500,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  message: {
    fontSize: vars["--ads-font-size-caption"],
    overflowWrap: "anywhere",
  },
  summary: { cursor: "pointer", paddingBlock: 10, fontWeight: 500 },
  groupName: {
    display: "inline-block",
    maxWidth: "calc(100% - 7rem)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    verticalAlign: "bottom",
  },
  group: {
    paddingBlock: 4,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: vars["--ads-color-border"],
  },
  detail: { display: "grid", gap: 8, paddingBlock: 8 },
  process: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    fontSize: vars["--ads-font-size-caption"],
  },
});
