import * as stylex from "@stylexjs/stylex";

import { vars } from "../ads/tokens/tokens.stylex";

const spin = stylex.keyframes({
  from: { transform: "rotate(0deg)" },
  to: { transform: "rotate(360deg)" },
});

export const craneConnectorStyles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space20,
  },
  card: {
    backgroundColor: vars.colorSurface,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusFrame,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    outline: "none",
  },
  header: {
    alignItems: "flex-start",
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    display: "flex",
    gap: vars.space12,
    paddingBlock: vars.space16,
    paddingInline: vars.space20,
  },
  headerMark: {
    alignItems: "center",
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    display: "flex",
    flexShrink: 0,
    height: vars.controlHeightMd,
    justifyContent: "center",
    width: vars.controlHeightMd,
  },
  headerMarkIcon: {
    color: vars.colorTextMuted,
    height: vars.controlIconSizeMd,
    width: vars.controlIconSizeMd,
  },
  headerBody: {
    flex: 1,
    minWidth: 0,
  },
  headerTitleLine: {
    alignItems: "center",
    columnGap: vars.space8,
    display: "flex",
    flexWrap: "wrap",
    rowGap: vars.space8,
  },
  headerTitle: {
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightSemibold,
  },
  headerDescription: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightControl,
    marginTop: vars.space4,
  },
  guideButton: {
    height: "auto",
    marginTop: vars.space4,
    paddingInline: 0,
  },
  guideIcon: {
    height: 12,
    width: 12,
  },
  refreshIcon: {
    height: vars.controlIconSizeMd,
    width: vars.controlIconSizeMd,
  },
  refreshIconSpinning: {
    animationDuration: vars.motionDurationLoop,
    animationIterationCount: "infinite",
    animationName: spin,
    animationTimingFunction: "linear",
    "@media (prefers-reduced-motion: reduce)": {
      animationName: "none",
    },
  },
  body: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space20,
    paddingBlock: vars.space16,
    paddingInline: vars.space20,
  },
  enableRow: {
    alignItems: "center",
    display: "flex",
    gap: vars.space16,
    justifyContent: "space-between",
  },
  enableLabel: {
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
  },
  enableHint: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    marginTop: vars.space4,
  },
  field: {
    display: "grid",
    gap: vars.space8,
  },
  fieldLabel: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
  },
  urlRow: {
    display: "flex",
    gap: vars.space8,
  },
  fieldHint: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
  },
  actionIcon: {
    height: vars.controlIconSizeMd,
    width: vars.controlIconSizeMd,
  },
  pollTrigger: {
    width: "12rem",
  },
  pairPanel: {
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    display: "flex",
    flexDirection: "column",
    gap: vars.space12,
    padding: vars.space16,
  },
  panelTitle: {
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
  },
  panelHint: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightControl,
    marginTop: vars.space4,
  },
  pairGrid: {
    display: "grid",
    gap: vars.space12,
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 640px)": "repeat(2, minmax(0, 1fr))",
    },
  },
  pairedPanel: {
    alignItems: "center",
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    columnGap: vars.space12,
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    padding: vars.space16,
    rowGap: vars.space12,
  },
  pairedMeta: {
    minWidth: 0,
  },
  pairedName: {
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  pairedId: {
    color: vars.colorTextMuted,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeMicro,
    marginTop: vars.space4,
  },
  infoNote: {
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightControl,
    paddingBlock: vars.space12,
    paddingInline: vars.space16,
  },
  warning: {
    backgroundColor: vars.colorDangerSoft,
    borderColor: vars.colorDangerBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    color: vars.colorDangerText,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightControl,
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
  },
  mappings: {
    borderTopColor: vars.colorBorder,
    borderTopStyle: "solid",
    borderTopWidth: vars.borderWidthHairline,
    display: "flex",
    flexDirection: "column",
    gap: vars.space12,
    paddingTop: vars.space16,
  },
  mappingsList: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space8,
  },
  mappingRow: {
    alignItems: "center",
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    display: "flex",
    gap: vars.space12,
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
  },
  mappingBody: {
    flex: 1,
    minWidth: 0,
  },
  mappingName: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  mappingPath: {
    color: vars.colorTextMuted,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeMicro,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  outboundCard: {
    backgroundColor: vars.colorSurface,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusFrame,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    paddingBlock: vars.space16,
    paddingInline: vars.space20,
  },
  outboundTitle: {
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightSemibold,
  },
  outboundText: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightControl,
    marginTop: vars.space4,
  },
});
