import * as stylex from "@stylexjs/stylex";

import { vars } from "../ads/tokens/tokens.stylex";

export const mcpConfigEditorStyles = stylex.create({
  dialogSurface: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-0"],
    maxBlockSize: "88vh",
    maxInlineSize: "42rem",
    overflow: "hidden",
    padding: 0,
  },
  shareSurface: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-0"],
    maxBlockSize: "88vh",
    maxInlineSize: "36rem",
    overflow: "hidden",
    padding: 0,
  },
  deleteSurface: {
    maxInlineSize: "28rem",
  },
  headerBlock: {
    borderBottomColor: vars["--ads-color-border"],
    borderBottomStyle: "solid",
    borderBottomWidth: vars["--ads-border-width-hairline"],
    paddingBlock: vars["--ads-space-20"],
    paddingInlineStart: vars["--ads-space-24"],
    paddingInlineEnd: 56,
  },
  headerTitle: {
    fontSize: vars["--ads-font-size-lead"],
  },
  headerDescription: {
    lineHeight: vars["--ads-line-height-control"],
  },
  scrollArea: {
    flex: 1,
    minBlockSize: 0,
    overflowY: "auto",
    paddingBlock: vars["--ads-space-20"],
    paddingInline: vars["--ads-space-24"],
  },
  reviewStack: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-16"],
  },
  reviewCard: {
    backgroundColor: vars["--ads-color-canvas-subtle"],
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-panel"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    padding: vars["--ads-space-16"],
  },
  reviewTitle: {
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  reviewList: {
    color: vars["--ads-color-text-muted"],
    display: "flex",
    flexDirection: "column",
    fontSize: vars["--ads-font-size-body"],
    gap: vars["--ads-space-8"],
    marginBlockStart: vars["--ads-space-12"],
  },
  warningCard: {
    backgroundColor: vars["--ads-color-warning-soft"],
    borderColor: vars["--ads-color-warning-border"],
    borderRadius: vars["--ads-radius-panel"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    fontSize: vars["--ads-font-size-body"],
    padding: vars["--ads-space-12"],
  },
  warningTitle: {
    color: vars["--ads-color-warning-text"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  warningList: {
    color: vars["--ads-color-text-muted"],
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-4"],
    marginBlockStart: vars["--ads-space-8"],
  },
  reviewNote: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-control"],
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-20"],
  },
  fieldStack: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-8"],
  },
  fieldLabel: {
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  fieldDescription: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-space-20"],
  },
  columns: {
    display: "grid",
    gap: vars["--ads-space-16"],
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 640px)": "repeat(2, minmax(0, 1fr))",
    },
  },
  fullWidth: {
    inlineSize: "100%",
  },
  providerToggles: {
    backgroundColor: vars["--ads-color-canvas-subtle"],
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-panel"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-8"],
    padding: vars["--ads-space-12"],
  },
  providerRow: {
    alignItems: "center",
    display: "flex",
    gap: vars["--ads-space-12"],
    justifyContent: "space-between",
  },
  providerLabel: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-body"],
  },
  toggleRow: {
    alignItems: "start",
    backgroundColor: vars["--ads-color-canvas-subtle"],
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-panel"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    gap: vars["--ads-space-16"],
    justifyContent: "space-between",
    padding: vars["--ads-space-12"],
  },
  toggleRowPlain: {
    alignItems: "start",
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-panel"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    gap: vars["--ads-space-16"],
    justifyContent: "space-between",
    padding: vars["--ads-space-12"],
  },
  toggleTitle: {
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  toggleHint: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-space-20"],
    marginBlockStart: vars["--ads-space-4"],
  },
  toggleHintTight: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    marginBlockStart: vars["--ads-space-4"],
  },
  monoArea: {
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-caption"],
  },
  monoAreaTall: {
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-caption"],
    minBlockSize: "6rem",
  },
  monoAreaShort: {
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-caption"],
    minBlockSize: "5rem",
  },
  protectedNote: {
    backgroundColor: vars["--ads-color-warning-soft"],
    borderColor: vars["--ads-color-warning-border"],
    borderRadius: vars["--ads-radius-panel"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-space-20"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
  },
  protectedStrong: {
    color: vars["--ads-color-warning-text"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  errorText: {
    backgroundColor: vars["--ads-color-danger-soft"],
    borderColor: vars["--ads-color-danger-border"],
    borderRadius: vars["--ads-radius-panel"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-danger-text"],
    fontSize: vars["--ads-font-size-body"],
    marginBlockStart: vars["--ads-space-16"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
  },
  footer: {
    backgroundColor: vars["--ads-color-canvas-subtle"],
    borderTopColor: vars["--ads-color-border"],
    borderTopStyle: "solid",
    borderBlockStartWidth: vars["--ads-border-width-hairline"],
    paddingBlock: vars["--ads-space-16"],
    paddingInline: vars["--ads-space-24"],
  },
  deleteTitleLine: {
    alignItems: "center",
    display: "flex",
    gap: vars["--ads-space-8"],
  },
  deleteTitle: {
    color: vars["--ads-color-danger-text"],
  },
  statusText: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-body"],
  },
  deleteWarning: {
    backgroundColor: vars["--ads-color-warning-soft"],
    borderColor: vars["--ads-color-warning-border"],
    borderRadius: vars["--ads-radius-panel"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-space-20"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
  },
});
