import * as stylex from "@stylexjs/stylex";

import { vars } from "../ads/tokens/tokens.stylex";

export const jiraConnectorStyles = stylex.create({
  root: {
    backgroundColor: vars.colorSurface,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusFrame,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    outline: "none",
  },
  header: {
    alignItems: "start",
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    display: "flex",
    gap: vars.space12,
    paddingBlock: vars.space16,
    paddingInline: vars.space20,
  },
  headerBody: {
    flex: 1,
    minInlineSize: 0,
  },
  headerTitleLine: {
    alignItems: "center",
    columnGap: vars.space8,
    display: "flex",
    flexWrap: "wrap",
    rowGap: vars.space8,
  },
  headerTitle: {
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightSemibold,
  },
  hint: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightControl,
  },
  hintError: {
    color: vars.colorDangerText,
  },
  headerHint: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightControl,
    marginBlockStart: vars.space4,
  },
  body: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space20,
    paddingBlock: vars.space16,
    paddingInline: vars.space20,
  },
  field: {
    display: "grid",
    gap: vars.space8,
  },
  fieldLabel: {
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
  },
  tokenPanel: {
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    display: "flex",
    flexDirection: "column",
    gap: vars.space12,
    padding: vars.space16,
  },
  panelTitle: {
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
  },
  accountRow: {
    alignItems: "center",
    columnGap: vars.space12,
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: vars.space12,
  },
  accountMeta: {
    minInlineSize: 0,
  },
  accountName: {
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  accountId: {
    color: vars.colorTextMuted,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeMicro,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  accountActions: {
    alignItems: "center",
    display: "flex",
    gap: vars.space8,
  },
  credentialGrid: {
    display: "grid",
    gap: vars.space12,
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 640px)": "1fr 1fr auto",
    },
  },
  warning: {
    backgroundColor: vars.colorDangerSoft,
    borderColor: vars.colorDangerBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    color: vars.colorDangerText,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightControl,
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
  },
  jqlArea: {
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeCaption,
  },
  jqlFooter: {
    alignItems: "center",
    display: "flex",
    gap: vars.space12,
    justifyContent: "space-between",
  },
  resetButton: {
    flexShrink: 0,
    blockSize: "auto",
    paddingBlock: vars.space4,
  },
  resetIcon: {
    blockSize: vars.space12,
    inlineSize: vars.space12,
  },
  refreshRow: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: vars.space12,
  },
  maxResultsTrigger: {
    inlineSize: "11rem",
  },
  actionIcon: {
    blockSize: vars.controlIconSizeMd,
    inlineSize: vars.controlIconSizeMd,
  },
  mappings: {
    borderTopColor: vars.colorBorder,
    borderTopStyle: "solid",
    borderBlockStartWidth: vars.borderWidthHairline,
    display: "flex",
    flexDirection: "column",
    gap: vars.space12,
    paddingBlockStart: vars.space16,
  },
  mappingRow: {
    alignItems: "center",
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    display: "flex",
    gap: vars.space12,
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
  },
  mappingBody: {
    flex: 1,
    minInlineSize: 0,
  },
  mappingName: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  mappingPath: {
    color: vars.colorTextMuted,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeMicro,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  mappingForm: {
    display: "grid",
    gap: vars.space8,
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 640px)": "8rem 1fr auto",
    },
  },
});
