import * as stylex from "@stylexjs/stylex";

import { vars } from "../ads/tokens/tokens.stylex";

export const mcpSectionStyles = stylex.create({
  titleActions: {
    alignItems: "center",
    display: "flex",
    gap: vars.space8,
  },
  providerCard: {
    backgroundColor: vars.colorCanvas,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    minWidth: 0,
    padding: vars.space12,
  },
  providerHead: {
    alignItems: "center",
    columnGap: vars.space8,
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: vars.space8,
  },
  providerName: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
  },
  providerMeta: {
    color: vars.colorTextMuted,
    columnGap: vars.space12,
    display: "flex",
    flexWrap: "wrap",
    fontSize: vars.fontSizeCaption,
    marginTop: vars.space8,
    rowGap: vars.space4,
  },
  errorBox: {
    backgroundColor: vars.colorDangerSoft,
    borderColor: vars.colorDangerBorder,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    fontSize: vars.fontSizeCaption,
    marginTop: vars.space8,
    paddingBlock: vars.space8,
    paddingInline: 10,
  },
  errorTitle: {
    color: vars.colorDangerText,
    fontWeight: vars.fontWeightMedium,
  },
  errorDetail: {
    color: vars.colorTextMuted,
    marginTop: vars.space4,
    overflowWrap: "break-word",
  },
  signInButton: {
    marginTop: vars.space12,
  },
  statsGrid: {
    display: "grid",
    gap: vars.space8,
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 640px)": "repeat(3, minmax(0, 1fr))",
    },
  },
  statCard: {
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
  },
  statLabel: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
  },
  statValue: {
    color: vars.colorText,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    marginTop: vars.space4,
  },
  availabilityBox: {
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
  },
  availabilityText: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
  },
  availabilityChips: {
    display: "flex",
    flexWrap: "wrap",
    gap: vars.space8,
    marginTop: vars.space8,
  },
  mutedText: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeBody,
  },
  emptyBox: {
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeBody,
    paddingBlock: vars.space12,
    paddingInline: vars.space12,
  },
  serverList: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space12,
  },
  serverArticle: {
    backgroundColor: vars.colorSurfaceTint,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    padding: vars.space12,
  },
  serverHead: {
    alignItems: "flex-start",
    columnGap: vars.space12,
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: vars.space12,
  },
  serverName: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightSemibold,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  serverSources: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    marginTop: vars.space4,
  },
  serverBadges: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    justifyContent: "flex-end",
  },
  serverAvailability: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    marginTop: vars.space8,
  },
  providerGrid: {
    display: "grid",
    gap: vars.space8,
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 768px)": "repeat(2, minmax(0, 1fr))",
      "@media (min-width: 1280px)": "repeat(4, minmax(0, 1fr))",
    },
    marginTop: vars.space12,
  },
  shareActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: vars.space8,
    marginTop: vars.space12,
  },
  configSection: {
    borderTopColor: vars.colorBorder,
    borderTopStyle: "solid",
    borderTopWidth: vars.borderWidthHairline,
    marginTop: vars.space12,
    paddingTop: vars.space12,
  },
  configHeading: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
  },
  configList: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space8,
    marginTop: vars.space8,
  },
  configRow: {
    alignItems: "center",
    backgroundColor: vars.colorCanvas,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    columnGap: vars.space8,
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
    rowGap: vars.space8,
  },
  configMeta: {
    minWidth: 0,
  },
  configLabelLine: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  configLabel: {
    color: vars.colorText,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
  },
  configHidden: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    marginTop: vars.space4,
  },
  configActions: {
    alignItems: "center",
    display: "flex",
    gap: 6,
  },
  noticeSuccess: {
    backgroundColor: vars.colorSuccessSoft,
    borderColor: vars.colorSuccessBorder,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    color: vars.colorSuccessText,
    fontSize: vars.fontSizeBody,
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
  },
  noticePartial: {
    backgroundColor: vars.colorWarningSoft,
    borderColor: vars.colorWarningBorder,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    color: vars.colorWarningText,
    fontSize: vars.fontSizeBody,
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
  },
  authNotice: {
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeBody,
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
  },
  errorList: {
    backgroundColor: vars.colorDangerSoft,
    borderColor: vars.colorDangerBorder,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    color: vars.colorDangerText,
    display: "flex",
    flexDirection: "column",
    fontSize: vars.fontSizeCaption,
    gap: vars.space4,
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
  },
});
