import * as stylex from "@stylexjs/stylex";

import { vars } from "@/components/ads/tokens/tokens.stylex";

const spin = stylex.keyframes({
  from: { transform: "rotate(0deg)" },
  to: { transform: "rotate(360deg)" },
});

export const toolingStyles = stylex.create({
  authBadge: {
    blockSize: vars["--ads-space-24"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    paddingInline: vars["--ads-space-8"],
    fontWeight: vars["--ads-font-weight-medium"],
    letterSpacing: "normal",
  },
  authBadgeAuthenticated: {
    borderColor: vars["--ads-color-success-border"],
    backgroundColor: vars["--ads-color-success-soft"],
    color: vars["--ads-color-success-text"],
  },
  authBadgeUnauthenticated: {
    borderColor: vars["--ads-color-warning-border"],
    backgroundColor: vars["--ads-color-warning-soft"],
    color: vars["--ads-color-warning-text"],
  },
  authBadgeNeutral: {
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface-tint"],
    color: vars["--ads-color-text-muted"],
  },
  versionBadge: {
    blockSize: vars["--ads-space-24"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface-tint"],
    paddingInline: vars["--ads-space-8"],
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-regular"],
    letterSpacing: "normal",
    color: vars["--ads-color-text-muted"],
  },
  toolIcon: {
    inlineSize: vars["--ads-control-icon-size-md"],
    blockSize: vars["--ads-control-icon-size-md"],
  },
  pathRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: vars["--ads-space-8"],
    fontSize: vars["--ads-font-size-body"],
  },
  pathRowEmpty: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: vars["--ads-space-12"],
    fontSize: vars["--ads-font-size-body"],
  },
  pathLabel: {
    color: vars["--ads-color-text-muted"],
  },
  pathLabelShrink: {
    flexShrink: 0,
    color: vars["--ads-color-text-muted"],
  },
  pathValueDash: {
    color: vars["--ads-color-text"],
  },
  pathValueGroup: {
    display: "flex",
    minInlineSize: 0,
    alignItems: "center",
    gap: vars["--ads-space-4"],
  },
  pathValue: {
    minInlineSize: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text"],
  },
  copyButton: {
    flexShrink: 0,
    color: {
      default: vars["--ads-color-text-subtle"],
      ":hover": vars["--ads-color-text-muted"],
    },
  },
  copyIcon: {
    inlineSize: vars["--ads-space-12"],
    blockSize: vars["--ads-space-12"],
  },
  card: {
    borderRadius: vars["--ads-radius-frame"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface"],
    padding: vars["--ads-space-16"],
  },
  cardHeaderRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "start",
    justifyContent: "space-between",
    gap: vars["--ads-space-12"],
  },
  cardHeaderInfo: {
    minInlineSize: 0,
    display: "grid",
    gap: vars["--ads-space-4"],
  },
  cardTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: vars["--ads-space-8"],
  },
  iconPlate: {
    display: "flex",
    inlineSize: vars["--ads-space-32"],
    blockSize: vars["--ads-control-height-sm"],
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: vars["--ads-radius-control"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface-tint"],
    color: vars["--ads-color-text-muted"],
  },
  cardTitleText: {
    minInlineSize: 0,
    display: "grid",
    gap: vars["--ads-space-4"],
  },
  toolLabel: {
    marginBlock: 0,
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-semibold"],
    color: vars["--ads-color-text"],
  },
  toolPurpose: {
    marginBlock: 0,
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text-muted"],
  },
  badgeGroup: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: vars["--ads-space-8"],
  },
  cardBody: {
    marginBlockStart: vars["--ads-space-16"],
    display: "grid",
    gap: vars["--ads-space-8"],
  },
  detailBox: {
    marginBlockStart: vars["--ads-space-16"],
    borderRadius: vars["--ads-radius-control"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface-tint"],
    paddingInline: vars["--ads-space-12"],
    paddingBlock: vars["--ads-space-8"],
  },
  detailText: {
    marginBlock: 0,
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-control"],
    color: vars["--ads-color-text-muted"],
    whiteSpace: "pre-wrap",
  },
  cardActions: {
    marginBlockStart: vars["--ads-space-16"],
    display: "flex",
    flexWrap: "wrap",
    gap: vars["--ads-space-8"],
  },
  actionIcon: {
    inlineSize: vars["--ads-control-icon-size-md"],
    blockSize: vars["--ads-control-icon-size-md"],
  },
  toolsGrid: {
    display: "grid",
    gap: vars["--ads-space-12"],
  },
  emptyState: {
    borderRadius: vars["--ads-radius-frame"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface-tint"],
    paddingInline: vars["--ads-space-16"],
    paddingBlock: vars["--ads-space-12"],
    fontSize: vars["--ads-font-size-body"],
    color: vars["--ads-color-text-muted"],
  },
  refreshIcon: {
    inlineSize: vars["--ads-control-icon-size-md"],
    blockSize: vars["--ads-control-icon-size-md"],
  },
  refreshIconSpinning: {
    inlineSize: vars["--ads-control-icon-size-md"],
    blockSize: vars["--ads-control-icon-size-md"],
    animationName: spin,
    animationDuration: "1s",
    animationTimingFunction: "linear",
    animationIterationCount: "infinite",
    "@media (prefers-reduced-motion: reduce)": {
      animationName: "none",
    },
  },
});
