import * as stylex from "@stylexjs/stylex";

import { vars } from "../ads/tokens/tokens.stylex";

export const mcpConfigEditorStyles = stylex.create({
  dialogSurface: {
    display: "flex",
    flexDirection: "column",
    gap: 0,
    maxHeight: "88vh",
    maxWidth: "42rem",
    overflow: "hidden",
    padding: 0,
  },
  shareSurface: {
    display: "flex",
    flexDirection: "column",
    gap: 0,
    maxHeight: "88vh",
    maxWidth: "36rem",
    overflow: "hidden",
    padding: 0,
  },
  deleteSurface: {
    maxWidth: "28rem",
  },
  headerBlock: {
    borderBottomColor: vars.colorBorder,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    paddingBlock: vars.space20,
    paddingLeft: vars.space24,
    paddingRight: 56,
  },
  headerTitle: {
    fontSize: vars.fontSizeLead,
  },
  headerDescription: {
    lineHeight: vars.lineHeightControl,
  },
  scrollArea: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    paddingBlock: vars.space20,
    paddingInline: vars.space24,
  },
  reviewStack: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space16,
  },
  reviewCard: {
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    padding: vars.space16,
  },
  reviewTitle: {
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
  },
  reviewList: {
    color: vars.colorTextMuted,
    display: "flex",
    flexDirection: "column",
    fontSize: vars.fontSizeBody,
    gap: 6,
    marginTop: vars.space12,
  },
  warningCard: {
    backgroundColor: vars.colorWarningSoft,
    borderColor: vars.colorWarningBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    fontSize: vars.fontSizeBody,
    padding: vars.space12,
  },
  warningTitle: {
    color: vars.colorWarningText,
    fontWeight: vars.fontWeightMedium,
  },
  warningList: {
    color: vars.colorTextMuted,
    display: "flex",
    flexDirection: "column",
    gap: vars.space4,
    marginTop: vars.space8,
  },
  reviewNote: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightControl,
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space20,
  },
  fieldStack: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  fieldLabel: {
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
  },
  fieldDescription: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.space20,
  },
  columns: {
    display: "grid",
    gap: vars.space16,
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 640px)": "repeat(2, minmax(0, 1fr))",
    },
  },
  fullWidth: {
    width: "100%",
  },
  providerToggles: {
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    display: "flex",
    flexDirection: "column",
    gap: vars.space8,
    padding: vars.space12,
  },
  providerRow: {
    alignItems: "center",
    display: "flex",
    gap: vars.space12,
    justifyContent: "space-between",
  },
  providerLabel: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
  },
  toggleRow: {
    alignItems: "flex-start",
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    display: "flex",
    gap: vars.space16,
    justifyContent: "space-between",
    padding: vars.space12,
  },
  toggleRowPlain: {
    alignItems: "flex-start",
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    display: "flex",
    gap: vars.space16,
    justifyContent: "space-between",
    padding: vars.space12,
  },
  toggleTitle: {
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
  },
  toggleHint: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.space20,
    marginTop: vars.space4,
  },
  toggleHintTight: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    marginTop: vars.space4,
  },
  monoArea: {
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeCaption,
  },
  monoAreaTall: {
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeCaption,
    minHeight: "6rem",
  },
  monoAreaShort: {
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeCaption,
    minHeight: "5rem",
  },
  protectedNote: {
    backgroundColor: vars.colorWarningSoft,
    borderColor: vars.colorWarningBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.space20,
    paddingBlock: 10,
    paddingInline: vars.space12,
  },
  protectedStrong: {
    color: vars.colorWarningText,
    fontWeight: vars.fontWeightMedium,
  },
  errorText: {
    backgroundColor: vars.colorDangerSoft,
    borderColor: vars.colorDangerBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    color: vars.colorDangerText,
    fontSize: vars.fontSizeBody,
    marginTop: vars.space16,
    paddingBlock: 10,
    paddingInline: vars.space12,
  },
  footer: {
    backgroundColor: vars.colorCanvasSubtle,
    borderTopColor: vars.colorBorder,
    borderTopStyle: "solid",
    borderTopWidth: vars.borderWidthHairline,
    paddingBlock: vars.space16,
    paddingInline: vars.space24,
  },
  deleteTitleLine: {
    alignItems: "center",
    display: "flex",
    gap: vars.space8,
  },
  deleteTitle: {
    color: vars.colorDangerText,
  },
  statusText: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeBody,
  },
  deleteWarning: {
    backgroundColor: vars.colorWarningSoft,
    borderColor: vars.colorWarningBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.space20,
    paddingBlock: 10,
    paddingInline: vars.space12,
  },
});
