import * as stylex from "@stylexjs/stylex";

import { vars } from "../ads/tokens/tokens.stylex";

export const mcpSectionStyles = stylex.create({
  titleActions: {
    alignItems: "center",
    display: "flex",
    gap: vars["--ads-space-8"],
  },
  providerCard: {
    backgroundColor: vars["--ads-color-canvas"],
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    minInlineSize: 0,
    padding: vars["--ads-space-12"],
  },
  providerHead: {
    alignItems: "center",
    columnGap: vars["--ads-space-8"],
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: vars["--ads-space-8"],
  },
  providerName: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  providerMeta: {
    color: vars["--ads-color-text-muted"],
    columnGap: vars["--ads-space-12"],
    display: "flex",
    flexWrap: "wrap",
    fontSize: vars["--ads-font-size-caption"],
    marginBlockStart: vars["--ads-space-8"],
    rowGap: vars["--ads-space-4"],
  },
  errorBox: {
    backgroundColor: vars["--ads-color-danger-soft"],
    borderColor: vars["--ads-color-danger-border"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    fontSize: vars["--ads-font-size-caption"],
    marginBlockStart: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-8"],
  },
  errorTitle: {
    color: vars["--ads-color-danger-text"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  errorDetail: {
    color: vars["--ads-color-text-muted"],
    marginBlockStart: vars["--ads-space-4"],
    overflowWrap: "break-word",
  },
  signInButton: {
    marginBlockStart: vars["--ads-space-12"],
  },
  // Three counts in a row, unboxed: the section is already a card, and a
  // tile per integer made each one look like a dashboard widget.
  statsGrid: {
    columnGap: vars["--ads-space-16"],
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
  },
  statCard: {
    minWidth: 0,
  },
  statLabel: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
  },
  statValue: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-body"],
    fontVariantNumeric: "tabular-nums",
    fontWeight: vars["--ads-font-weight-medium"],
    marginBlockStart: vars["--ads-space-2"],
  },
  availabilityBox: {
    backgroundColor: vars["--ads-color-canvas-subtle"],
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
  },
  availabilityText: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
  },
  availabilityChips: {
    display: "flex",
    flexWrap: "wrap",
    gap: vars["--ads-space-8"],
    marginBlockStart: vars["--ads-space-8"],
  },
  mutedText: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-body"],
  },
  emptyBox: {
    backgroundColor: vars["--ads-color-canvas-subtle"],
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-body"],
    paddingBlock: vars["--ads-space-12"],
    paddingInline: vars["--ads-space-12"],
  },
  serverList: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-12"],
  },
  serverArticle: {
    backgroundColor: vars["--ads-color-surface-tint"],
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-panel"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    padding: vars["--ads-space-12"],
  },
  serverHead: {
    alignItems: "start",
    columnGap: vars["--ads-space-12"],
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: vars["--ads-space-12"],
  },
  serverName: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-semibold"],
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  serverSources: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    marginBlockStart: vars["--ads-space-4"],
  },
  serverBadges: {
    display: "flex",
    flexWrap: "wrap",
    gap: vars["--ads-space-8"],
    justifyContent: "flex-end",
  },
  serverAvailability: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    marginBlockStart: vars["--ads-space-8"],
  },
  providerGrid: {
    display: "grid",
    gap: vars["--ads-space-8"],
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 768px)": "repeat(2, minmax(0, 1fr))",
      "@media (min-width: 1280px)": "repeat(4, minmax(0, 1fr))",
    },
    marginBlockStart: vars["--ads-space-12"],
  },
  shareActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: vars["--ads-space-8"],
    marginBlockStart: vars["--ads-space-12"],
  },
  configSection: {
    borderTopColor: vars["--ads-color-border"],
    borderTopStyle: "solid",
    borderBlockStartWidth: vars["--ads-border-width-hairline"],
    marginBlockStart: vars["--ads-space-12"],
    paddingBlockStart: vars["--ads-space-12"],
  },
  configHeading: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  configList: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-8"],
    marginBlockStart: vars["--ads-space-8"],
  },
  configRow: {
    alignItems: "center",
    backgroundColor: vars["--ads-color-canvas"],
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    columnGap: vars["--ads-space-8"],
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
    rowGap: vars["--ads-space-8"],
  },
  configMeta: {
    minInlineSize: 0,
  },
  configLabelLine: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: vars["--ads-space-8"],
  },
  configLabel: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  configHidden: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    marginBlockStart: vars["--ads-space-4"],
  },
  configActions: {
    alignItems: "center",
    display: "flex",
    gap: vars["--ads-space-8"],
  },
  noticeSuccess: {
    backgroundColor: vars["--ads-color-success-soft"],
    borderColor: vars["--ads-color-success-border"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-success-text"],
    fontSize: vars["--ads-font-size-body"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
  },
  noticePartial: {
    backgroundColor: vars["--ads-color-warning-soft"],
    borderColor: vars["--ads-color-warning-border"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-warning-text"],
    fontSize: vars["--ads-font-size-body"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
  },
  authNotice: {
    backgroundColor: vars["--ads-color-canvas-subtle"],
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-body"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
  },
  errorList: {
    backgroundColor: vars["--ads-color-danger-soft"],
    borderColor: vars["--ads-color-danger-border"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-danger-text"],
    display: "flex",
    flexDirection: "column",
    fontSize: vars["--ads-font-size-caption"],
    gap: vars["--ads-space-4"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
  },
});
