import * as stylex from "@stylexjs/stylex";

import { vars } from "@/components/ads/tokens/tokens.stylex";

const spin = stylex.keyframes({
  from: { transform: "rotate(0deg)" },
  to: { transform: "rotate(360deg)" },
});

export const reviewsStyles = stylex.create({
  // --- inbox rows ---------------------------------------------------------
  inboxRow: {
    alignItems: "flex-start",
    backgroundColor: {
      default: "transparent",
      ":hover": vars.colorOverlayHover,
      ":focus-visible": vars.colorOverlayHover,
    },
    borderRadius: vars.radiusPanel,
    // The lead glyph inherits this so it brightens with the row, replacing the
    // `group-hover:` pair StyleX has no cross-element selector for.
    color: { default: vars.colorTextMuted, ":hover": vars.colorText },
    display: "flex",
    gap: vars.space12,
    minHeight: 64,
    minWidth: 0,
    paddingBlock: 10,
    paddingInline: vars.space12,
    textAlign: "start",
    width: "100%",
  },
  inboxRowMark: {
    alignItems: "center",
    backgroundColor: vars.colorCanvasSubtle,
    borderRadius: vars.radiusControl,
    color: "inherit",
    display: "flex",
    flexShrink: 0,
    height: 28,
    justifyContent: "center",
    marginTop: vars.space2,
    width: 28,
  },
  inboxRowBody: { flex: 1, minWidth: 0 },
  inboxRowRepo: {
    alignItems: "center",
    color: vars.colorTextMuted,
    display: "flex",
    fontSize: vars.fontSizeCaption,
    gap: vars.space4,
    minWidth: 0,
  },
  inboxRowTitle: {
    color: vars.colorText,
    display: "-webkit-box",
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    lineHeight: "1.25rem",
    marginTop: vars.space4,
    overflow: "hidden",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
  },
  inboxRowMeta: {
    alignItems: "center",
    color: vars.colorTextMuted,
    columnGap: vars.space8,
    display: "flex",
    flexWrap: "wrap",
    fontSize: vars.fontSizeMicro,
    lineHeight: "1rem",
    marginTop: vars.space4,
    rowGap: vars.space4,
  },
  inboxList: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space2,
    padding: 6,
  },

  // --- shared states ------------------------------------------------------
  centeredStatus: {
    alignItems: "center",
    color: vars.colorTextMuted,
    display: "flex",
    fontSize: vars.fontSizeBody,
    gap: vars.space8,
    justifyContent: "center",
    minHeight: 160,
  },
  fillStatus: {
    alignItems: "center",
    color: vars.colorTextMuted,
    display: "flex",
    flex: 1,
    fontSize: vars.fontSizeBody,
    gap: vars.space8,
    justifyContent: "center",
  },
  errorBox: {
    backgroundColor: vars.colorDangerSoft,
    borderColor: vars.colorDangerBorder,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    margin: vars.space12,
    paddingBlock: vars.space12,
    paddingInline: vars.space12,
  },
  errorRow: { alignItems: "flex-start", display: "flex", gap: vars.space8 },
  errorIcon: {
    color: vars.colorDangerText,
    flexShrink: 0,
    height: 16,
    marginTop: vars.space2,
    width: 16,
  },
  errorTitle: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
  },
  errorDetail: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: "1.25rem",
    marginTop: vars.space4,
    overflowWrap: "break-word",
  },
  emptyState: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    minHeight: 192,
    paddingInline: vars.space24,
    textAlign: "center",
  },
  emptyMark: {
    alignItems: "center",
    backgroundColor: vars.colorCanvasSubtle,
    borderRadius: vars.radiusPanel,
    color: vars.colorTextMuted,
    display: "flex",
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  emptyMarkIcon: { height: 20, width: 20 },
  emptyTitle: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    marginTop: vars.space12,
  },
  emptyBody: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: "1.25rem",
    marginTop: vars.space4,
    maxWidth: "16rem",
  },

  // --- files tab ----------------------------------------------------------
  filesPane: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space8,
    padding: vars.space8,
  },
  filesWarning: {
    backgroundColor: vars.colorWarningSoft,
    borderRadius: vars.radiusPanel,
    color: vars.colorWarningText,
    fontSize: vars.fontSizeCaption,
    lineHeight: "1.25rem",
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
  },
  fileRow: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":hover": vars.colorOverlayHover,
      ":focus-visible": vars.colorOverlayHover,
    },
    borderRadius: vars.radiusPanel,
    cursor: { default: null, ":disabled": "not-allowed" },
    display: "flex",
    gap: vars.space8,
    minHeight: 44,
    minWidth: 0,
    opacity: { default: null, ":disabled": vars.opacityDisabled },
    paddingBlock: vars.space8,
    paddingInline: 10,
    textAlign: "start",
    width: "100%",
  },
  fileIcon: { color: vars.colorTextMuted, flexShrink: 0, height: 16, width: 16 },
  fileName: {
    color: vars.colorText,
    flex: 1,
    fontSize: vars.fontSizeCaption,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  fileDiffStat: {
    flexShrink: 0,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeMicro,
  },
  additions: { color: vars.colorSuccessText },
  deletions: { color: vars.colorDangerText },
  filesFootnote: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: "1.25rem",
    paddingBlock: vars.space8,
    paddingInline: vars.space8,
  },

  // --- conversation tab ---------------------------------------------------
  conversationPane: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space16,
    paddingBlock: vars.space12,
    paddingInline: vars.space12,
  },
  conversationSection: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space8,
  },
  sectionLabel: {
    color: vars.colorText,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
  },
  bodyText: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: "1.25rem",
    overflowWrap: "break-word",
    whiteSpace: "pre-wrap",
  },
  mutedText: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: "1.25rem",
  },
  timeline: { display: "flex", flexDirection: "column", gap: vars.space12 },
  timelineItem: {
    backgroundColor: vars.colorSurfaceTint,
    borderRadius: vars.radiusPanel,
    paddingBlock: 10,
    paddingInline: vars.space12,
  },
  timelineMeta: {
    alignItems: "center",
    color: vars.colorTextMuted,
    columnGap: vars.space8,
    display: "flex",
    flexWrap: "wrap",
    fontSize: vars.fontSizeMicro,
    rowGap: vars.space4,
  },
  timelineAuthor: { color: vars.colorText, fontWeight: vars.fontWeightMedium },
  timelineBody: {
    color: vars.colorText,
    fontSize: vars.fontSizeCaption,
    lineHeight: "1.25rem",
    marginTop: vars.space8,
    overflowWrap: "break-word",
    whiteSpace: "pre-wrap",
  },

  // --- checks tab ---------------------------------------------------------
  checksEmpty: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: "1.25rem",
    paddingBlock: vars.space32,
    paddingInline: vars.space16,
    textAlign: "center",
  },
  checksList: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space4,
    padding: vars.space8,
  },
  checkRow: {
    alignItems: "center",
    borderRadius: vars.radiusPanel,
    display: "flex",
    gap: vars.space8,
    minHeight: 44,
    paddingBlock: vars.space8,
    paddingInline: 10,
  },
  checkIcon: { flexShrink: 0, height: 16, width: 16 },
  checkIconSuccess: { color: vars.colorSuccessText },
  checkIconFail: { color: vars.colorDangerText },
  checkIconPending: { color: vars.colorWarningText },
  checkName: {
    color: vars.colorText,
    flex: 1,
    fontSize: vars.fontSizeCaption,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  checkStatus: {
    color: vars.colorTextMuted,
    flexShrink: 0,
    fontSize: vars.fontSizeMicro,
    letterSpacing: "0.025em",
    textTransform: "uppercase",
  },

  // --- shell --------------------------------------------------------------
  shell: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
  },
  detailHeader: {
    alignItems: "center",
    borderBlockEndColor: vars.colorBorder,
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: vars.borderWidthHairline,
    display: "flex",
    gap: vars.space8,
    minHeight: 48,
    paddingBlock: 6,
    paddingInline: vars.space8,
  },
  detailHeaderText: { flex: 1, minWidth: 0 },
  breadcrumb: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeMicro,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  detailTitle: {
    color: vars.colorText,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  iconMd: { height: 16, width: 16 },
  iconSm: { height: 14, width: 14 },
  iconXs: { height: 12, width: 12 },
  spinning: { animationDuration: "1s", animationIterationCount: "infinite", animationName: { default: spin, "@media (prefers-reduced-motion: reduce)": "none" }, animationTimingFunction: "linear" },
  summaryStrip: {
    borderBlockEndColor: vars.colorBorder,
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: vars.borderWidthHairline,
    display: "flex",
    flexDirection: "column",
    gap: vars.space8,
    paddingBlock: 10,
    paddingInline: vars.space12,
  },
  badgeRow: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: vars.space4,
  },
  monoBadge: { fontFamily: vars.fontMono },
  summaryLine: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeMicro,
    lineHeight: "1rem",
  },
  tabs: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: 0,
    minHeight: 0,
  },
  tabStrip: {
    borderBlockEndColor: vars.colorBorder,
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: vars.borderWidthHairline,
    paddingBlock: 6,
    paddingInline: vars.space8,
  },
  inboxStrip: {
    alignItems: "center",
    borderBlockEndColor: vars.colorBorder,
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: vars.borderWidthHairline,
    display: "flex",
    gap: vars.space8,
    paddingBlock: 6,
    paddingInline: vars.space8,
  },
  tabList: { flex: 1, minWidth: 0, width: "100%" },
  tabTrigger: { flex: 1 },
  tabPanel: { flex: 1, minHeight: 0, overflow: "auto" },
  detailFooter: {
    backgroundColor: vars.colorSurface,
    borderBlockStartColor: vars.colorBorder,
    borderBlockStartStyle: "solid",
    borderBlockStartWidth: vars.borderWidthHairline,
    flexShrink: 0,
    paddingBlock: 10,
    paddingInline: vars.space12,
  },
  footerNote: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeMicro,
    marginTop: 6,
    textAlign: "center",
  },
  inboxFooter: {
    borderBlockStartColor: vars.colorBorder,
    borderBlockStartStyle: "solid",
    borderBlockStartWidth: vars.borderWidthHairline,
    flexShrink: 0,
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
  },
  inboxFooterText: {
    alignItems: "center",
    color: vars.colorTextMuted,
    display: "flex",
    fontSize: vars.fontSizeMicro,
    gap: vars.space4,
  },
  truncate: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  shrink0: { flexShrink: 0 },
});
