import * as stylex from "@stylexjs/stylex";

import { vars } from "../ads/tokens/tokens.stylex";

/** Chrome for the top-bar PR trigger and the Create PR dialog. */
export const openPrStyles = stylex.create({
  truncate: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  flexNone: { flexShrink: 0 },
  minWidthZero: { minWidth: 0 },

  // --- Top-bar triggers ---------------------------------------------------
  // Composed after `topBarControlStyles.control`, which owns the 32px height,
  // `space8` gutter/gap, and the caption/medium label shared by the whole top
  // bar row. Only the border and the disabled fade are local here, because a
  // colored PR tone repaints the fill. The neutral Draft trigger does not: it
  // composes `topBarControlStyles.surface` so it matches the row.
  trigger: {
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    opacity: { default: 1, ":disabled": vars["--ads-opacity-disabled"] },
  },
  triggerGroup: { alignItems: "center", display: "flex", gap: vars["--ads-space-8"] },
  continueTrigger: {
    backgroundColor: {
      default: vars["--ads-color-canvas"],
      ":hover": vars["--ads-color-overlay-hover"],
    },
    borderColor: vars["--ads-color-border-subtle"],
    color: vars["--ads-color-text"],
  },
  statusIcon: {
    blockSize: vars["--ads-control-icon-size-sm"],
    flexShrink: 0,
    inlineSize: vars["--ads-control-icon-size-sm"],
  },
  /**
   * The 16px box is the same value the shared glyph rule in `ads/styles.css`
   * now resolves for this host-layout Button's default `md` rung, and the box
   * `Loader size="xs"` occupies — so the idle and busy states of the trigger
   * stay optically equal whichever rule paints the glyph.
   */
  triggerIcon: {
    blockSize: vars["--ads-control-icon-size-sm"],
    flexShrink: 0,
    inlineSize: vars["--ads-control-icon-size-sm"],
  },
  statusMenu: { width: 256 },
  statusMenuLabel: { display: "flex", flexDirection: "column", gap: 2 },
  statusMenuTitle: {
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  statusMenuSubtitle: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-micro"],
    fontWeight: vars["--ads-font-weight-regular"],
  },
  menuItemStrong: { fontWeight: vars["--ads-font-weight-medium"] },
  menuItemRow: { alignItems: "center", display: "flex", gap: vars["--ads-space-8"] },
  menuItemIcon: { color: vars["--ads-color-text-muted"], height: 14, width: 14 },

  // --- Inline notice ------------------------------------------------------
  notice: {
    alignItems: "flex-start",
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    fontSize: vars["--ads-font-size-body"],
    gap: vars["--ads-space-12"],
    paddingBlock: "0.625rem",
    paddingInline: vars["--ads-space-12"],
  },
  noticeInfo: {
    backgroundColor: vars["--ads-color-canvas-subtle"],
    borderColor: vars["--ads-color-border-subtle"],
    color: vars["--ads-color-text"],
  },
  noticeSuccess: {
    backgroundColor: vars["--ads-color-success-soft"],
    borderColor: vars["--ads-color-success-border"],
    color: vars["--ads-color-success-text"],
  },
  noticeWarning: {
    backgroundColor: vars["--ads-color-warning-soft"],
    borderColor: vars["--ads-color-warning-border"],
    color: vars["--ads-color-warning-text"],
  },
  noticeError: {
    backgroundColor: vars["--ads-color-danger-soft"],
    borderColor: vars["--ads-color-danger-border"],
    color: vars["--ads-color-danger-text"],
  },
  noticeIcon: {
    flexShrink: 0,
    height: 16,
    marginTop: vars["--ads-space-2"],
    width: 16,
  },
  noticeBody: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-4"],
    minWidth: 0,
  },
  noticeTitle: {
    fontWeight: vars["--ads-font-weight-medium"],
    overflowWrap: "break-word",
  },
  noticeDescription: {
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-relaxed"],
    opacity: 0.8,
    overflowWrap: "break-word",
  },

  // --- Loading splash -----------------------------------------------------
  splash: { display: "flex", flexDirection: "column", gap: vars["--ads-space-16"] },
  splashCard: {
    backgroundColor: vars["--ads-color-canvas-subtle"],
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-frame"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    padding: vars["--ads-space-16"],
  },
  splashRow: { alignItems: "flex-start", display: "flex", gap: vars["--ads-space-12"] },
  splashMark: {
    alignItems: "center",
    backgroundColor: vars["--ads-color-canvas"],
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-full"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    flexShrink: 0,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  splashLoader: { color: vars["--ads-color-accent"] },
  splashCopy: { display: "flex", flexDirection: "column", gap: 6 },
  splashTitle: { fontSize: vars["--ads-font-size-body"], fontWeight: vars["--ads-font-weight-medium"] },
  splashText: { color: vars["--ads-color-text-muted"], fontSize: vars["--ads-font-size-body"] },
  skeletonCard: {
    backgroundColor: vars["--ads-color-canvas"],
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-frame"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-12"],
    padding: vars["--ads-space-16"],
  },
  skeletonGroup: { display: "flex", flexDirection: "column", gap: vars["--ads-space-8"] },
  skeletonBlock: {
    backgroundColor: vars["--ads-color-canvas-subtle"],
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-8"],
    padding: vars["--ads-space-12"],
  },

  // --- Findings / verification panels -------------------------------------
  panel: {
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-8"],
    padding: vars["--ads-space-12"],
  },
  panelWarning: {
    backgroundColor: vars["--ads-color-warning-soft"],
    borderColor: vars["--ads-color-warning-border"],
  },
  panelDanger: {
    backgroundColor: vars["--ads-color-danger-soft"],
    borderColor: vars["--ads-color-danger-border"],
  },
  panelHead: { alignItems: "flex-start", display: "flex", gap: vars["--ads-space-8"] },
  panelIcon: { flexShrink: 0, height: 16, marginTop: vars["--ads-space-2"], width: 16 },
  panelIconWarning: { color: vars["--ads-color-warning-text"] },
  panelIconDanger: { color: vars["--ads-color-danger-text"] },
  panelCopy: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-4"],
    minWidth: 0,
  },
  panelTitle: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  panelText: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-relaxed"],
  },
  panelList: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-8"],
    maxHeight: "13rem",
    overflowY: "auto",
    paddingInlineEnd: vars["--ads-space-4"],
  },
  panelItem: {
    backgroundColor: vars["--ads-color-canvas"],
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    padding: vars["--ads-space-8"],
  },
  panelItemTags: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    minWidth: 0,
  },
  tag: {
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-mark"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    fontSize: vars["--ads-font-size-micro"],
    fontWeight: vars["--ads-font-weight-medium"],
    paddingBlock: vars["--ads-space-2"],
    paddingInline: 6,
    textTransform: "uppercase",
  },
  tagNeutral: {
    backgroundColor: vars["--ads-color-canvas-subtle"],
    color: vars["--ads-color-text-muted"],
  },
  tagWarning: {
    backgroundColor: vars["--ads-color-warning-soft"],
    borderColor: vars["--ads-color-warning-border"],
    color: vars["--ads-color-warning-text"],
  },
  tagDanger: {
    backgroundColor: vars["--ads-color-danger-soft"],
    borderColor: vars["--ads-color-danger-border"],
    color: vars["--ads-color-danger-text"],
  },
  tagOutlineWarning: {
    borderColor: vars["--ads-color-warning-border"],
    color: vars["--ads-color-warning-text"],
  },
  tagOutlineDanger: {
    borderColor: vars["--ads-color-danger-border"],
    color: vars["--ads-color-danger-text"],
  },
  tagLocation: {
    color: vars["--ads-color-text-muted"],
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-micro"],
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  panelItemMessage: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-relaxed"],
    marginTop: 6,
    overflowWrap: "break-word",
  },

  // --- Branch fields ------------------------------------------------------
  branchCard: {
    backgroundColor: vars["--ads-color-canvas-subtle"],
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-frame"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    minWidth: 0,
    padding: vars["--ads-space-12"],
  },
  branchGrid: {
    alignItems: { default: null, "@media (min-width: 40rem)": "end" },
    display: "grid",
    gap: vars["--ads-space-12"],
    gridTemplateColumns: {
      default: null,
      "@media (min-width: 40rem)":
        "minmax(0, 1fr) auto minmax(0, 1fr)",
    },
    minWidth: 0,
  },
  branchField: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    minWidth: 0,
  },
  branchReadout: {
    alignItems: "center",
    backgroundColor: vars["--ads-color-canvas"],
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    boxShadow: vars["--ads-elevation-raised"],
    display: "flex",
    fontSize: vars["--ads-font-size-body"],
    gap: vars["--ads-space-8"],
    height: 36,
    paddingInline: vars["--ads-space-12"],
    width: "100%",
  },
  branchReadoutIcon: {
    color: vars["--ads-color-text-muted"],
    flexShrink: 0,
    height: 14,
    width: 14,
  },
  branchArrow: {
    color: vars["--ads-color-text-muted"],
    display: { default: "none", "@media (min-width: 40rem)": "block" },
    flexShrink: 0,
    height: 16,
    marginBottom: { default: null, "@media (min-width: 40rem)": "0.625rem" },
    width: 16,
  },
  fieldLabel: {
    color: vars["--ads-color-text-muted"],
    display: "block",
    fontSize: vars["--ads-font-size-micro"],
    fontWeight: vars["--ads-font-weight-semibold"],
    letterSpacing: "0.12em",
    textTransform: "uppercase",
  },

  // --- Dialog body --------------------------------------------------------
  dialogSurface: {
    display: "flex",
    flexDirection: "column",
    maxBlockSize: "calc(100dvh - 2rem)",
    maxWidth: { default: null, "@media (min-width: 40rem)": "32rem" },
    minWidth: 0,
    overflow: "hidden",
  },
  loadingSlot: {
    minBlockSize: 0,
    minWidth: 0,
    overflowY: "auto",
    paddingInlineEnd: vars["--ads-space-4"],
  },
  form: {
    display: "flex",
    flex: "1 1 auto",
    flexDirection: "column",
    gap: vars["--ads-space-16"],
    minBlockSize: 0,
    minWidth: 0,
  },
  formBody: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-16"],
    minWidth: 0,
    paddingInlineEnd: vars["--ads-space-4"],
  },
  createFormBodyScroll: {
    flex: "1 1 auto",
    minBlockSize: 0,
    overflowY: "auto",
  },
  mergeCard: {
    backgroundColor: vars["--ads-color-canvas-subtle"],
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-frame"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-12"],
    minWidth: 0,
    padding: vars["--ads-space-12"],
  },
  settingRow: {
    alignItems: "center",
    display: "grid",
    gap: vars["--ads-space-12"],
    gridTemplateColumns: "minmax(0, 1fr) auto",
    minWidth: 0,
  },
  settingLabel: {
    display: "block",
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
    lineHeight: vars["--ads-line-height-relaxed"],
  },
  settingHint: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: "1rem",
  },
  mergeMethodTrigger: {
    flexShrink: 0,
    justifySelf: "end",
    width: 160,
  },
  autoMergeSwitch: { flexShrink: 0, justifySelf: "end" },
  divider: { backgroundColor: vars["--ads-color-border-subtle"], height: 1 },
  field: { display: "flex", flexDirection: "column", gap: vars["--ads-space-8"] },
  fieldMinWidthZero: { minWidth: 0 },
  textInput: { fontSize: vars["--ads-font-size-body"], height: 36 },
  bodyTextarea: {
    fieldSizing: "fixed",
    fontSize: vars["--ads-font-size-body"],
    maxHeight: "20rem",
    minHeight: "6rem",
    minWidth: 0,
    overflowWrap: "anywhere",
    resize: "vertical",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  fieldError: { color: vars["--ads-color-danger-text"], fontSize: vars["--ads-font-size-caption"] },
  fieldErrorTight: {
    color: vars["--ads-color-danger-text"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: "1rem",
  },
  fieldHint: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: "1rem",
  },

  // --- Uncommitted changes ------------------------------------------------
  changesToggle: {
    alignItems: "center",
    color: vars["--ads-color-warning-text"],
    display: "flex",
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
    gap: 6,
    lineHeight: vars["--ads-line-height-relaxed"],
    minWidth: 0,
    textAlign: "left",
    width: "100%",
  },
  /* Rotation only; `transition.transform` at the call site owns the timing. */
  changesChevronOpen: { transform: "rotate(90deg)" },
  changesCountLabel: { flexShrink: 0 },
  changesHint: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-regular"],
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  changesList: {
    backgroundColor: vars["--ads-color-canvas-subtle"],
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    fontSize: vars["--ads-font-size-caption"],
    maxHeight: "10rem",
    minWidth: 0,
    overflowY: "auto",
    padding: vars["--ads-space-8"],
  },
  changesRow: {
    alignItems: "center",
    backgroundColor: { default: "transparent", ":hover": vars["--ads-color-overlay-hover"] },
    borderRadius: vars["--ads-radius-mark"],
    display: "flex",
    gap: vars["--ads-space-8"],
    minWidth: 0,
    paddingBlock: vars["--ads-space-4"],
    paddingInline: vars["--ads-space-4"],
  },
  changesCode: {
    color: vars["--ads-color-text-muted"],
    flexShrink: 0,
    fontFamily: vars["--ads-font-mono"],
    fontWeight: vars["--ads-font-weight-medium"],
    textAlign: "center",
    width: 20,
  },
  changesPath: {
    fontFamily: vars["--ads-font-mono"],
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  dialogFooter: { flexShrink: 0 },
});
