import * as stylex from "@stylexjs/stylex";

import { vars } from "../ads/tokens/tokens.stylex";

/** Chrome for the top-bar PR trigger and the Create PR dialog. */
export const openPrStyles = stylex.create({
  truncate: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  flexNone: { flexShrink: 0 },
  minWidthZero: { minWidth: 0 },

  // --- Top-bar triggers ---------------------------------------------------
  trigger: {
    alignItems: "center",
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    display: "inline-flex",
    fontSize: vars.fontSizeCaption,
    gap: 6,
    height: 28,
    opacity: { default: 1, ":disabled": vars.opacityDisabled },
    paddingInline: "0.625rem",
  },
  triggerGroup: { alignItems: "center", display: "flex", gap: 6 },
  continueTrigger: {
    backgroundColor: {
      default: vars.colorCanvas,
      ":hover": vars.colorOverlayHover,
    },
    borderColor: vars.colorBorderSubtle,
    color: vars.colorText,
  },
  statusIcon: { flexShrink: 0, height: 14, width: 14 },
  statusMenu: { width: 256 },
  statusMenuLabel: { display: "flex", flexDirection: "column", gap: 2 },
  statusMenuTitle: {
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  statusMenuSubtitle: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeMicro,
    fontWeight: vars.fontWeightRegular,
  },
  menuItemStrong: { fontWeight: vars.fontWeightMedium },
  menuItemRow: { alignItems: "center", display: "flex", gap: vars.space8 },
  menuItemIcon: { color: vars.colorTextMuted, height: 14, width: 14 },

  // --- Inline notice ------------------------------------------------------
  notice: {
    alignItems: "flex-start",
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    display: "flex",
    fontSize: vars.fontSizeBody,
    gap: vars.space12,
    paddingBlock: "0.625rem",
    paddingInline: vars.space12,
  },
  noticeInfo: {
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: vars.colorBorderSubtle,
    color: vars.colorText,
  },
  noticeSuccess: {
    backgroundColor: vars.colorSuccessSoft,
    borderColor: vars.colorSuccessBorder,
    color: vars.colorSuccessText,
  },
  noticeWarning: {
    backgroundColor: vars.colorWarningSoft,
    borderColor: vars.colorWarningBorder,
    color: vars.colorWarningText,
  },
  noticeError: {
    backgroundColor: vars.colorDangerSoft,
    borderColor: vars.colorDangerBorder,
    color: vars.colorDangerText,
  },
  noticeIcon: {
    flexShrink: 0,
    height: 16,
    marginTop: vars.space2,
    width: 16,
  },
  noticeBody: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space4,
    minWidth: 0,
  },
  noticeTitle: {
    fontWeight: vars.fontWeightMedium,
    overflowWrap: "break-word",
  },
  noticeDescription: {
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightRelaxed,
    opacity: 0.8,
    overflowWrap: "break-word",
  },

  // --- Loading splash -----------------------------------------------------
  splash: { display: "flex", flexDirection: "column", gap: vars.space16 },
  splashCard: {
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusFrame,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    padding: vars.space16,
  },
  splashRow: { alignItems: "flex-start", display: "flex", gap: vars.space12 },
  splashMark: {
    alignItems: "center",
    backgroundColor: vars.colorCanvas,
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusFull,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    display: "flex",
    flexShrink: 0,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  splashLoader: { color: vars.colorAccent },
  splashCopy: { display: "flex", flexDirection: "column", gap: 6 },
  splashTitle: { fontSize: vars.fontSizeBody, fontWeight: vars.fontWeightMedium },
  splashText: { color: vars.colorTextMuted, fontSize: vars.fontSizeBody },
  skeletonCard: {
    backgroundColor: vars.colorCanvas,
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusFrame,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    display: "flex",
    flexDirection: "column",
    gap: vars.space12,
    padding: vars.space16,
  },
  skeletonGroup: { display: "flex", flexDirection: "column", gap: vars.space8 },
  skeletonBlock: {
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    display: "flex",
    flexDirection: "column",
    gap: vars.space8,
    padding: vars.space12,
  },

  // --- Findings / verification panels -------------------------------------
  panel: {
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    display: "flex",
    flexDirection: "column",
    gap: vars.space8,
    padding: vars.space12,
  },
  panelWarning: {
    backgroundColor: vars.colorWarningSoft,
    borderColor: vars.colorWarningBorder,
  },
  panelDanger: {
    backgroundColor: vars.colorDangerSoft,
    borderColor: vars.colorDangerBorder,
  },
  panelHead: { alignItems: "flex-start", display: "flex", gap: vars.space8 },
  panelIcon: { flexShrink: 0, height: 16, marginTop: vars.space2, width: 16 },
  panelIconWarning: { color: vars.colorWarningText },
  panelIconDanger: { color: vars.colorDangerText },
  panelCopy: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space4,
    minWidth: 0,
  },
  panelTitle: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
  },
  panelText: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightRelaxed,
  },
  panelList: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space8,
    maxHeight: "13rem",
    overflowY: "auto",
    paddingInlineEnd: vars.space4,
  },
  panelItem: {
    backgroundColor: vars.colorCanvas,
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    padding: vars.space8,
  },
  panelItemTags: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    minWidth: 0,
  },
  tag: {
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusMark,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    fontSize: vars.fontSizeMicro,
    fontWeight: vars.fontWeightMedium,
    paddingBlock: vars.space2,
    paddingInline: 6,
    textTransform: "uppercase",
  },
  tagNeutral: {
    backgroundColor: vars.colorCanvasSubtle,
    color: vars.colorTextMuted,
  },
  tagWarning: {
    backgroundColor: vars.colorWarningSoft,
    borderColor: vars.colorWarningBorder,
    color: vars.colorWarningText,
  },
  tagDanger: {
    backgroundColor: vars.colorDangerSoft,
    borderColor: vars.colorDangerBorder,
    color: vars.colorDangerText,
  },
  tagOutlineWarning: {
    borderColor: vars.colorWarningBorder,
    color: vars.colorWarningText,
  },
  tagOutlineDanger: {
    borderColor: vars.colorDangerBorder,
    color: vars.colorDangerText,
  },
  tagLocation: {
    color: vars.colorTextMuted,
    fontFamily: vars.fontMono,
    fontSize: 11,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  panelItemMessage: {
    color: vars.colorText,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightRelaxed,
    marginTop: 6,
    overflowWrap: "break-word",
  },

  // --- Branch fields ------------------------------------------------------
  branchCard: {
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusFrame,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    minWidth: 0,
    padding: vars.space12,
  },
  branchGrid: {
    alignItems: { default: null, "@media (min-width: 40rem)": "end" },
    display: "grid",
    gap: vars.space12,
    gridTemplateColumns: {
      default: null,
      "@media (min-width: 40rem)":
        "minmax(0, 1fr) auto minmax(0, 1fr)",
    },
    minWidth: 0,
  },
  branchField: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    minWidth: 0,
  },
  branchReadout: {
    alignItems: "center",
    backgroundColor: vars.colorCanvas,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    boxShadow: vars.elevationRaised,
    display: "flex",
    fontSize: vars.fontSizeBody,
    gap: vars.space8,
    height: 36,
    paddingInline: vars.space12,
    width: "100%",
  },
  branchReadoutIcon: {
    color: vars.colorTextMuted,
    flexShrink: 0,
    height: 14,
    width: 14,
  },
  branchArrow: {
    color: vars.colorTextMuted,
    display: { default: "none", "@media (min-width: 40rem)": "block" },
    flexShrink: 0,
    height: 16,
    marginBottom: { default: null, "@media (min-width: 40rem)": "0.625rem" },
    width: 16,
  },
  fieldLabel: {
    color: vars.colorTextMuted,
    display: "block",
    fontSize: 11,
    fontWeight: vars.fontWeightSemibold,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
  },

  // --- Dialog body --------------------------------------------------------
  dialogSurface: {
    maxWidth: { default: null, "@media (min-width: 40rem)": "32rem" },
    minWidth: 0,
  },
  loadingSlot: { minWidth: 0, paddingInlineEnd: vars.space4 },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space16,
    minWidth: 0,
  },
  formBody: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space16,
    minWidth: 0,
    paddingInlineEnd: vars.space4,
  },
  mergeCard: {
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusFrame,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    display: "flex",
    flexDirection: "column",
    gap: vars.space12,
    minWidth: 0,
    padding: vars.space12,
  },
  settingRow: {
    alignItems: "center",
    display: "grid",
    gap: vars.space12,
    gridTemplateColumns: "minmax(0, 1fr) auto",
    minWidth: 0,
  },
  settingLabel: {
    display: "block",
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    lineHeight: vars.lineHeightRelaxed,
  },
  settingHint: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: "1rem",
  },
  mergeMethodTrigger: {
    flexShrink: 0,
    justifySelf: "end",
    width: 160,
  },
  autoMergeSwitch: { flexShrink: 0, justifySelf: "end" },
  divider: { backgroundColor: vars.colorBorderSubtle, height: 1 },
  field: { display: "flex", flexDirection: "column", gap: vars.space8 },
  fieldMinWidthZero: { minWidth: 0 },
  textInput: { fontSize: vars.fontSizeBody, height: 36 },
  bodyTextarea: {
    fieldSizing: "fixed",
    fontSize: vars.fontSizeBody,
    maxHeight: "20rem",
    minHeight: "6rem",
    minWidth: 0,
    overflowWrap: "anywhere",
    resize: "vertical",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  fieldError: { color: vars.colorDangerText, fontSize: vars.fontSizeCaption },
  fieldErrorTight: {
    color: vars.colorDangerText,
    fontSize: vars.fontSizeCaption,
    lineHeight: "1rem",
  },
  fieldHint: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: "1rem",
  },

  // --- Uncommitted changes ------------------------------------------------
  changesToggle: {
    alignItems: "center",
    color: vars.colorWarningText,
    display: "flex",
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    gap: 6,
    lineHeight: vars.lineHeightRelaxed,
    minWidth: 0,
    textAlign: "left",
    width: "100%",
  },
  changesCountLabel: { flexShrink: 0 },
  changesHint: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightRegular,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  changesList: {
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    fontSize: vars.fontSizeCaption,
    maxHeight: "10rem",
    minWidth: 0,
    overflowY: "auto",
    padding: vars.space8,
  },
  changesRow: {
    alignItems: "center",
    backgroundColor: { default: null, ":hover": vars.colorOverlayHover },
    borderRadius: vars.radiusMark,
    display: "flex",
    gap: vars.space8,
    minWidth: 0,
    paddingBlock: vars.space4,
    paddingInline: vars.space4,
  },
  changesCode: {
    color: vars.colorTextMuted,
    flexShrink: 0,
    fontFamily: vars.fontMono,
    fontWeight: vars.fontWeightMedium,
    textAlign: "center",
    width: 20,
  },
  changesPath: {
    fontFamily: vars.fontMono,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  dialogFooter: { flexShrink: 0 },
});
