import * as stylex from "@stylexjs/stylex";

import { vars } from "../ads/tokens/tokens.stylex";

const spin = stylex.keyframes({
  from: { transform: "rotate(0deg)" },
  to: { transform: "rotate(360deg)" },
});

export const updateStyles = stylex.create({
  trigger: {
    backgroundColor: {
      default: "transparent",
      ":hover": vars.colorOverlayHover,
    },
    borderRadius: vars.radiusControl,
    color: { default: vars.colorTextMuted, ":hover": vars.colorText },
    flexShrink: 0,
    height: 32,
    padding: 0,
    position: "relative",
    width: 32,
  },
  triggerHasUpdate: { color: vars.colorAccent },
  // Corner pip on the trigger square; it deliberately overhangs the control box.
  pip: {
    borderRadius: vars.radiusFull,
    display: "inline-flex",
    height: 10,
    insetBlockStart: -2,
    insetInlineEnd: -2,
    position: "absolute",
    width: 10,
  },
  pipUpdate: { backgroundColor: vars.colorAccent },
  pipIssue: { backgroundColor: vars.colorWarning },
  panel: {
    backgroundColor: vars.colorSurface,
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusFrame,
    gap: 0,
    padding: 0,
    width: "min(24rem, calc(100vw - 1rem))",
  },
  panelHeader: {
    borderBottomColor: vars.colorBorderSubtle,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    paddingBlock: vars.space12,
    paddingInline: vars.space16,
  },
  panelHeaderRow: {
    alignItems: "flex-start",
    display: "flex",
    gap: vars.space12,
    justifyContent: "space-between",
  },
  panelHeaderText: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space4,
  },
  panelSummary: { color: vars.colorTextMuted, fontSize: vars.fontSizeCaption },
  stateBadge: { flexShrink: 0 },
  panelBody: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space12,
    paddingBlock: vars.space12,
    paddingInline: vars.space16,
  },
  infoList: { display: "flex", flexDirection: "column", gap: vars.space8 },
  infoRow: {
    alignItems: "flex-start",
    display: "flex",
    fontSize: vars.fontSizeBody,
    gap: vars.space12,
    justifyContent: "space-between",
  },
  infoLabel: { color: vars.colorTextMuted },
  infoValue: {
    color: vars.colorText,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeCaption,
    maxWidth: "70%",
    overflowWrap: "break-word",
    textAlign: "right",
    wordBreak: "break-all",
  },
  detailBox: {
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
  },
  detailText: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightRelaxed,
    whiteSpace: "pre-wrap",
  },
  actions: { display: "flex", flexWrap: "wrap", gap: vars.space8 },
  spinning: {
    animationDuration: {
      default: vars.motionDurationLoop,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    animationIterationCount: "infinite",
    animationName: spin,
    animationTimingFunction: "linear",
  },
  confirmSurface: { maxWidth: { default: null, "@media (min-width: 40rem)": "32rem" } },
  confirmBody: { display: "flex", flexDirection: "column", gap: vars.space12 },
  warningNote: {
    backgroundColor: vars.colorWarningSoft,
    borderColor: vars.colorWarningBorder,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    color: vars.colorWarningText,
    fontSize: vars.fontSizeBody,
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
  },
  taskListEyebrow: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
  },
  taskList: {
    color: vars.colorText,
    display: "flex",
    flexDirection: "column",
    fontSize: vars.fontSizeBody,
    gap: vars.space4,
    marginTop: vars.space8,
  },
  taskListItem: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  taskListOverflow: { color: vars.colorTextMuted },
});
