import * as stylex from "@stylexjs/stylex";

import { vars } from "../ads/tokens/tokens.stylex";

const spin = stylex.keyframes({
  from: { transform: "rotate(0deg)" },
  to: { transform: "rotate(360deg)" },
});

export const branchDropdownStyles = stylex.create({
  truncate: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  flexNone: { flexShrink: 0 },

  // --- Trigger ------------------------------------------------------------
  trigger: {
    alignItems: "center",
    backgroundColor: {
      default: vars.colorCanvas,
      ":hover": vars.colorOverlayHover,
    },
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    color: vars.colorTextMuted,
    display: "inline-flex",
    fontSize: vars.fontSizeCaption,
    gap: 6,
    height: 28,
    maxWidth: 224,
    paddingInline: "0.625rem",
  },
  triggerOpen: {
    backgroundColor: vars.colorOverlayPressed,
    borderColor: vars.colorAccent,
    color: vars.colorText,
  },
  triggerDrift: {
    backgroundColor: vars.colorWarningSoft,
    borderColor: vars.colorWarningBorder,
    color: vars.colorWarningText,
  },
  dirtyCount: {
    alignItems: "center",
    borderRadius: vars.radiusFull,
    display: "inline-flex",
    flexShrink: 0,
    fontSize: vars.fontSizeMicro,
    fontWeight: vars.fontWeightMedium,
    justifyContent: "center",
    lineHeight: "1rem",
    minWidth: 16,
    paddingInline: vars.space4,
  },
  dirtyCountConflict: {
    backgroundColor: vars.colorDangerSoft,
    color: vars.colorDangerText,
  },
  dirtyCountDirty: {
    backgroundColor: vars.colorWarningSoft,
    color: vars.colorWarningText,
  },
  chevron: { transitionProperty: "transform" },
  chevronOpen: { transform: "rotate(180deg)" },

  // --- Menu shell ---------------------------------------------------------
  menu: {
    display: "flex",
    flexDirection: "column",
    maxHeight: "min(34rem, calc(100vh - 5rem))",
    overflow: "hidden",
    padding: 0,
    width: "min(30rem, calc(100vw - 2rem))",
  },
  header: {
    backgroundColor: vars.colorCanvas,
    borderBottomColor: vars.colorBorderSubtle,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    padding: vars.space8,
  },
  headerRow: { alignItems: "center", display: "flex", gap: vars.space8 },
  searchField: { flex: 1, minWidth: 0, position: "relative" },
  searchIcon: {
    color: vars.colorTextMuted,
    height: 14,
    insetInlineStart: "0.625rem",
    pointerEvents: "none",
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    width: 14,
  },
  searchInput: {
    borderRadius: vars.radiusControl,
    fontSize: vars.fontSizeBody,
    height: 32,
    paddingInlineStart: vars.space32,
  },
  spinning: {
    animationDuration: {
      default: vars.motionDurationLoop,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    animationIterationCount: "infinite",
    animationName: spin,
    animationTimingFunction: "linear",
  },

  // --- Drift banner -------------------------------------------------------
  driftNote: {
    alignItems: "flex-start",
    backgroundColor: vars.colorWarningSoft,
    borderColor: vars.colorWarningBorder,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    display: "flex",
    gap: vars.space8,
    marginTop: vars.space8,
    padding: "0.625rem",
  },
  driftIcon: {
    color: vars.colorWarningText,
    flexShrink: 0,
    height: 16,
    marginTop: vars.space2,
    width: 16,
  },
  driftBody: { flex: 1, minWidth: 0 },
  driftTitle: {
    color: vars.colorText,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
  },
  driftText: {
    color: vars.colorTextMuted,
    fontSize: 11,
    lineHeight: "1rem",
    marginTop: vars.space2,
  },
  driftAction: {
    flexShrink: 0,
    fontSize: 11,
    height: 28,
    paddingInline: vars.space8,
  },

  // --- Current-branch card ------------------------------------------------
  statusCard: {
    backgroundColor: vars.colorCanvasSubtle,
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    marginTop: vars.space8,
    paddingBlock: vars.space8,
    paddingInline: "0.625rem",
  },
  statusRow: {
    alignItems: "center",
    display: "flex",
    fontSize: vars.fontSizeCaption,
    gap: vars.space12,
    justifyContent: "space-between",
  },
  statusBranch: {
    color: vars.colorText,
    fontWeight: vars.fontWeightMedium,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  statusPill: {
    borderRadius: vars.radiusMark,
    flexShrink: 0,
    fontSize: 11,
    paddingBlock: vars.space2,
    paddingInline: 6,
  },
  statusPillConflict: {
    backgroundColor: vars.colorDangerSoft,
    color: vars.colorDangerText,
  },
  statusPillDirty: {
    backgroundColor: vars.colorWarningSoft,
    color: vars.colorWarningText,
  },
  statusPillClean: {
    backgroundColor: vars.colorSuccessSoft,
    color: vars.colorSuccessText,
  },
  statusHint: {
    color: vars.colorTextMuted,
    fontSize: 11,
    lineHeight: "1rem",
    marginTop: vars.space4,
  },
  actionGrid: {
    display: "grid",
    gap: vars.space8,
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    marginTop: vars.space8,
  },
  actionButton: {
    borderRadius: vars.radiusMark,
    fontSize: vars.fontSizeCaption,
    gap: 6,
    height: 28,
    paddingInline: vars.space8,
  },
  detachSlot: { display: "flex", marginTop: vars.space8 },
  detachButton: {
    borderRadius: vars.radiusMark,
    fontSize: vars.fontSizeCaption,
    gap: 6,
    height: 28,
    paddingInline: vars.space8,
    width: "100%",
  },

  // --- Create branch ------------------------------------------------------
  createRow: { display: "flex", gap: vars.space8, marginTop: vars.space8 },
  createInput: {
    borderRadius: vars.radiusControl,
    fontSize: vars.fontSizeBody,
    height: 32,
  },
  createButton: {
    fontSize: vars.fontSizeCaption,
    gap: 6,
    height: 32,
    paddingInline: "0.625rem",
  },
  createError: {
    color: vars.colorDangerText,
    fontSize: 11,
    marginTop: 6,
    paddingInline: vars.space2,
  },
  branchError: {
    backgroundColor: vars.colorDangerSoft,
    borderColor: vars.colorDangerBorder,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    color: vars.colorDangerText,
    fontSize: vars.fontSizeCaption,
    marginTop: vars.space8,
    overflowWrap: "break-word",
    paddingBlock: 6,
    paddingInline: vars.space8,
    whiteSpace: "pre-wrap",
  },

  // --- Branch list --------------------------------------------------------
  list: { flex: 1, minHeight: 0, overflowY: "auto", padding: vars.space8 },
  groups: { display: "flex", flexDirection: "column", gap: vars.space12 },
  groupHeader: {
    alignItems: "center",
    color: vars.colorTextMuted,
    display: "flex",
    fontSize: 11,
    fontWeight: vars.fontWeightMedium,
    justifyContent: "space-between",
    letterSpacing: "normal",
    marginBottom: vars.space4,
    paddingInline: 6,
    textTransform: "uppercase",
  },
  groupOptions: { display: "flex", flexDirection: "column", gap: vars.space4 },
  option: {
    alignItems: "center",
    borderRadius: vars.radiusControl,
    display: "flex",
    gap: vars.space8,
    paddingBlock: vars.space8,
    paddingInline: vars.space8,
    textAlign: "left",
    width: "100%",
  },
  optionCurrent: {
    backgroundColor: vars.colorSelectionFill,
    borderColor: vars.colorBorder,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
  },
  optionSelectable: {
    backgroundColor: { default: null, ":hover": vars.colorOverlayHover },
  },
  optionDisabled: { cursor: "not-allowed", opacity: 0.7 },
  optionIcon: { color: vars.colorTextMuted },
  optionText: { flex: 1, minWidth: 0 },
  optionName: {
    color: vars.colorText,
    display: "block",
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  optionDescription: {
    color: vars.colorTextMuted,
    display: "block",
    fontSize: vars.fontSizeCaption,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  optionCheck: { color: vars.colorSuccess },
  emptyState: {
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeBody,
    paddingBlock: vars.space24,
    paddingInline: vars.space12,
    textAlign: "center",
  },

  // --- Read-only chip (worktree-managed branch) ---------------------------
  staticChip: {
    alignItems: "center",
    backgroundColor: vars.colorCanvas,
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    color: vars.colorTextMuted,
    display: "inline-flex",
    fontSize: vars.fontSizeCaption,
    gap: 6,
    height: 28,
    maxWidth: 224,
    paddingInline: "0.625rem",
  },
  staticChipIcon: { flexShrink: 0, height: 14, width: 14 },
});
