import * as stylex from "@stylexjs/stylex";

import { vars } from "../ads/tokens/tokens.stylex";

const spin = stylex.keyframes({
  from: { transform: "rotate(0deg)" },
  to: { transform: "rotate(360deg)" },
});

export const updateStyles = stylex.create({
  trigger: {
    backgroundColor: {
      default: "transparent",
      ":hover": vars["--ads-color-overlay-hover"],
    },
    borderRadius: vars["--ads-radius-control"],
    color: { default: vars["--ads-color-text-muted"], ":hover": vars["--ads-color-text"] },
    flexShrink: 0,
    height: 32,
    padding: 0,
    position: "relative",
    width: 32,
  },
  triggerHasUpdate: { color: vars["--ads-color-accent"] },
  // Corner pip on the trigger square; it deliberately overhangs the control box.
  pip: {
    borderRadius: vars["--ads-radius-full"],
    display: "inline-flex",
    height: 10,
    insetBlockStart: -2,
    insetInlineEnd: -2,
    position: "absolute",
    width: 10,
  },
  pipUpdate: { backgroundColor: vars["--ads-color-accent"] },
  pipIssue: { backgroundColor: vars["--ads-color-warning"] },
  panel: {
    backgroundColor: vars["--ads-color-surface"],
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-frame"],
    gap: 0,
    padding: 0,
    width: "min(24rem, calc(100vw - 1rem))",
  },
  panelHeader: {
    borderBottomColor: vars["--ads-color-border-subtle"],
    borderBottomStyle: "solid",
    borderBottomWidth: vars["--ads-border-width-hairline"],
    paddingBlock: vars["--ads-space-12"],
    paddingInline: vars["--ads-space-16"],
  },
  panelHeaderRow: {
    alignItems: "flex-start",
    display: "flex",
    gap: vars["--ads-space-12"],
    justifyContent: "space-between",
  },
  panelHeaderText: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-4"],
  },
  panelSummary: { color: vars["--ads-color-text-muted"], fontSize: vars["--ads-font-size-caption"] },
  stateBadge: { flexShrink: 0 },
  panelBody: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-12"],
    paddingBlock: vars["--ads-space-12"],
    paddingInline: vars["--ads-space-16"],
  },
  infoList: { display: "flex", flexDirection: "column", gap: vars["--ads-space-8"] },
  infoRow: {
    alignItems: "flex-start",
    display: "flex",
    fontSize: vars["--ads-font-size-body"],
    gap: vars["--ads-space-12"],
    justifyContent: "space-between",
  },
  infoLabel: { color: vars["--ads-color-text-muted"] },
  infoValue: {
    color: vars["--ads-color-text"],
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-caption"],
    maxWidth: "70%",
    overflowWrap: "break-word",
    textAlign: "right",
    wordBreak: "break-all",
  },
  detailBox: {
    backgroundColor: vars["--ads-color-canvas-subtle"],
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
  },
  detailText: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-relaxed"],
    whiteSpace: "pre-wrap",
  },
  actions: { display: "flex", flexWrap: "wrap", gap: vars["--ads-space-8"] },
  spinning: {
    animationDuration: {
      default: vars["--ads-motion-duration-loop"],
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    animationIterationCount: "infinite",
    animationName: spin,
    animationTimingFunction: "linear",
  },
  confirmSurface: { maxWidth: { default: null, "@media (min-width: 40rem)": "32rem" } },
  confirmBody: { display: "flex", flexDirection: "column", gap: vars["--ads-space-12"] },
  warningNote: {
    backgroundColor: vars["--ads-color-warning-soft"],
    borderColor: vars["--ads-color-warning-border"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-warning-text"],
    fontSize: vars["--ads-font-size-body"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
  },
  taskListEyebrow: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
    letterSpacing: "0.12em",
    textTransform: "uppercase",
  },
  taskList: {
    color: vars["--ads-color-text"],
    display: "flex",
    flexDirection: "column",
    fontSize: vars["--ads-font-size-body"],
    gap: vars["--ads-space-4"],
    marginTop: vars["--ads-space-8"],
  },
  taskListItem: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  taskListOverflow: { color: vars["--ads-color-text-muted"] },
});
