import * as stylex from "@stylexjs/stylex";

import { vars } from "../ads/tokens/tokens.stylex";

/** Warning hue held back to a wash so the match reads as a highlight, not a fill. */
const matchHighlight = `color-mix(in oklch, ${vars["--ads-color-warning"]} 32%, transparent)`;

/** Explorer rail: file tree, inline create form, and the in-files search view. */
export const explorerStyles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
  },
  header: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: vars["--ads-space-8"],
    justifyContent: "space-between",
    marginBottom: vars["--ads-space-4"],
  },
  projectName: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-body"],
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerActions: { alignItems: "center", display: "flex", gap: vars["--ads-space-4"] },
  toolButton: {
    borderRadius: vars["--ads-radius-mark"],
    color: vars["--ads-color-text-muted"],
    height: 28,
    padding: 0,
    width: 28,
  },
  toolButtonActive: {
    backgroundColor: vars["--ads-color-surface-tint"],
    color: vars["--ads-color-text"],
  },
  toolIcon: { height: 16, width: 16 },
  searchSlot: { flex: 1, marginBottom: vars["--ads-space-8"], minHeight: 0 },
  panelError: {
    color: vars["--ads-color-danger-text"],
    flexShrink: 0,
    fontSize: vars["--ads-font-size-body"],
    marginBottom: vars["--ads-space-4"],
  },
  tree: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: vars["--ads-space-4"],
    minHeight: 0,
    overflow: "auto",
  },
  createForm: {
    backgroundColor: vars["--ads-color-surface-tint"],
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-mark"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-8"],
  },
  createRow: { alignItems: "center", display: "flex", gap: vars["--ads-space-8"] },
  createIcon: { color: vars["--ads-color-text-muted"], flexShrink: 0, height: 16, width: 16 },
  createInput: {
    backgroundColor: vars["--ads-color-canvas"],
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-mark"],
    fontSize: vars["--ads-font-size-body"],
    height: 32,
    paddingInline: vars["--ads-space-8"],
  },
  createSubmit: { borderRadius: vars["--ads-radius-mark"], height: 32 },
  createCancel: {
    borderRadius: vars["--ads-radius-mark"],
    color: vars["--ads-color-text-muted"],
    height: 32,
    paddingInline: vars["--ads-space-8"],
  },
  createHint: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    marginTop: vars["--ads-space-4"],
  },
  statusLine: {
    alignItems: "center",
    color: vars["--ads-color-text-muted"],
    display: "flex",
    fontSize: vars["--ads-font-size-body"],
    gap: vars["--ads-space-8"],
  },
  emptyLine: { color: vars["--ads-color-text-muted"], fontSize: vars["--ads-font-size-body"] },

  // ---- Tree row ----------------------------------------------------------
  treeRow: {
    alignItems: "center",
    backgroundColor: { default: "transparent", ":hover": vars["--ads-color-overlay-hover"] },
    borderRadius: vars["--ads-radius-mark"],
    display: "flex",
    fontSize: vars["--ads-font-size-body"],
    gap: vars["--ads-space-4"],
    minWidth: 0,
    paddingBlock: vars["--ads-space-4"],
    paddingInline: 6,
    textAlign: "start",
    width: "100%",
  },
  chevron: { color: vars["--ads-color-text-muted"], height: 14, width: 14 },
  chevronSpacer: { display: "inline-block", width: 14 },
  entryName: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowLoader: { color: vars["--ads-color-text-muted"], flexShrink: 0 },
  menu: { width: "14rem" },
  menuIcon: { height: 16, width: 16 },
  childError: {
    color: vars["--ads-color-danger-text"],
    fontSize: vars["--ads-font-size-body"],
    paddingBlock: vars["--ads-space-4"],
  },
  childEmpty: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-body"],
    paddingBlock: vars["--ads-space-4"],
  },

  // ---- Search view -------------------------------------------------------
  searchRoot: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
  },
  searchField: { paddingBottom: vars["--ads-space-4"], paddingInline: vars["--ads-space-8"] },
  searchAnchor: { position: "relative" },
  searchIcon: {
    color: vars["--ads-color-text-muted"],
    height: 14,
    insetInlineStart: vars["--ads-space-12"],
    pointerEvents: "none",
    position: "absolute",
    top: vars["--ads-space-12"],
    width: 14,
  },
  searchInput: {
    // Fill comes from the ADS field recipe (`colorSurfaceRaised`); pinning it
    // to the canvas made the field vanish on themes where `--background` and
    // `--popover` are the same colour.
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-mark"],
    fontSize: vars["--ads-font-size-body"],
    lineHeight: "20px",
    minHeight: 0,
    paddingBlock: vars["--ads-space-8"],
    paddingInlineEnd: 36,
    paddingInlineStart: 32,
    resize: "none",
  },
  searchClear: {
    borderRadius: vars["--ads-radius-mark"],
    color: { default: vars["--ads-color-text-muted"], ":hover": vars["--ads-color-text"] },
    height: 24,
    insetInlineEnd: 6,
    padding: 0,
    position: "absolute",
    top: 6,
    width: 24,
  },
  searchClearIcon: { height: 14, width: 14 },
  searchHint: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: "16px",
    paddingInline: vars["--ads-space-2"],
    paddingTop: vars["--ads-space-4"],
  },
  searchStatus: {
    alignItems: "center",
    color: vars["--ads-color-text-muted"],
    display: "flex",
    fontSize: vars["--ads-font-size-body"],
    gap: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-8"],
  },
  searchEmpty: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-body"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-8"],
  },
  searchError: {
    color: vars["--ads-color-danger-text"],
    fontSize: vars["--ads-font-size-body"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-8"],
  },
  searchCount: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    paddingBottom: vars["--ads-space-4"],
    paddingInline: vars["--ads-space-8"],
  },
  searchResults: {
    backgroundColor: vars["--ads-color-ground"],
    flex: 1,
    minHeight: 0,
  },
  /**
   * The scroller root carries the ground fill directly. It used to be reached
   * through the viewport `react-virtuoso` renders inside it; painting the root
   * covers the same area without a descendant selector.
   */
  searchScroller: { backgroundColor: vars["--ads-color-ground"] },
  resultFileRow: {
    alignItems: "center",
    backgroundColor: { default: "transparent", ":hover": vars["--ads-color-overlay-hover"] },
    borderRadius: vars["--ads-radius-mark"],
    display: "flex",
    fontSize: vars["--ads-font-size-body"],
    gap: 6,
    height: 28,
    minWidth: 0,
    paddingInline: 6,
    textAlign: "start",
    width: "100%",
  },
  resultIcon: { color: vars["--ads-color-text-muted"], flexShrink: 0, height: 14, width: 14 },
  resultFileName: {
    flex: 1,
    fontWeight: vars["--ads-font-weight-medium"],
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  resultDirPath: {
    color: vars["--ads-color-text-muted"],
    flexShrink: 0,
    fontSize: vars["--ads-font-size-caption"],
  },
  resultCount: {
    backgroundColor: vars["--ads-color-canvas-subtle"],
    borderRadius: vars["--ads-radius-full"],
    color: vars["--ads-color-text-muted"],
    flexShrink: 0,
    fontSize: vars["--ads-font-size-caption"],
    marginInlineStart: vars["--ads-space-4"],
    paddingInline: 6,
  },
  resultMatchRow: {
    alignItems: "flex-start",
    backgroundColor: { default: "transparent", ":hover": vars["--ads-color-overlay-hover"] },
    borderRadius: vars["--ads-radius-mark"],
    display: "flex",
    gap: vars["--ads-space-8"],
    minWidth: 0,
    paddingBlock: 6,
    paddingInline: 6,
    textAlign: "start",
    width: "100%",
  },
  resultLineNumber: {
    backgroundColor: vars["--ads-color-canvas-subtle"],
    borderRadius: vars["--ads-radius-mark"],
    color: vars["--ads-color-text-muted"],
    flexShrink: 0,
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-caption"],
    marginTop: 2,
    paddingBlock: vars["--ads-space-2"],
    paddingInline: 6,
  },
  // The matched source line — the whole result, not a caption on one — so it
  // reads at the body step while its line number stays metadata.
  resultText: {
    color: vars["--ads-color-text-muted"],
    flex: 1,
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-body"],
    lineHeight: "20px",
    minWidth: 0,
    overflowWrap: "break-word",
    whiteSpace: "pre-wrap",
  },
  matchHit: {
    backgroundColor: matchHighlight,
    color: vars["--ads-color-text"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
});
