import * as stylex from "@stylexjs/stylex";

import { vars } from "../ads/tokens/tokens.stylex";

/** Warning hue held back to a wash so the match reads as a highlight, not a fill. */
const matchHighlight = `color-mix(in oklch, ${vars.colorWarning} 32%, transparent)`;

/** Explorer rail: file tree, inline create form, and the in-files search view. */
export const explorerStyles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
  },
  header: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: vars.space8,
    justifyContent: "space-between",
    marginBottom: vars.space4,
  },
  projectName: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeBody,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerActions: { alignItems: "center", display: "flex", gap: vars.space4 },
  toolButton: {
    borderRadius: vars.radiusMark,
    color: vars.colorTextMuted,
    height: 28,
    padding: 0,
    width: 28,
  },
  toolButtonActive: {
    backgroundColor: vars.colorSurfaceTint,
    color: vars.colorText,
  },
  toolIcon: { height: 16, width: 16 },
  searchSlot: { flex: 1, marginBottom: vars.space8, minHeight: 0 },
  panelError: {
    color: vars.colorDangerText,
    flexShrink: 0,
    fontSize: vars.fontSizeBody,
    marginBottom: vars.space4,
  },
  tree: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: vars.space4,
    minHeight: 0,
    overflow: "auto",
  },
  createForm: {
    backgroundColor: vars.colorSurfaceTint,
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusMark,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    paddingBlock: vars.space8,
    paddingInline: vars.space8,
  },
  createRow: { alignItems: "center", display: "flex", gap: vars.space8 },
  createIcon: { color: vars.colorTextMuted, flexShrink: 0, height: 16, width: 16 },
  createInput: {
    backgroundColor: vars.colorCanvas,
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusMark,
    fontSize: vars.fontSizeBody,
    height: 32,
    paddingInline: vars.space8,
  },
  createSubmit: { borderRadius: vars.radiusMark, height: 32 },
  createCancel: {
    borderRadius: vars.radiusMark,
    color: vars.colorTextMuted,
    height: 32,
    paddingInline: vars.space8,
  },
  createHint: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    marginTop: vars.space4,
  },
  statusLine: {
    alignItems: "center",
    color: vars.colorTextMuted,
    display: "flex",
    fontSize: vars.fontSizeBody,
    gap: vars.space8,
  },
  emptyLine: { color: vars.colorTextMuted, fontSize: vars.fontSizeBody },

  // ---- Tree row ----------------------------------------------------------
  treeRow: {
    alignItems: "center",
    backgroundColor: { default: "transparent", ":hover": vars.colorOverlayHover },
    borderRadius: vars.radiusMark,
    display: "flex",
    fontSize: vars.fontSizeBody,
    gap: vars.space4,
    minWidth: 0,
    paddingBlock: vars.space4,
    paddingInline: 6,
    textAlign: "start",
    width: "100%",
  },
  chevron: { color: vars.colorTextMuted, height: 14, width: 14 },
  chevronSpacer: { display: "inline-block", width: 14 },
  entryName: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowLoader: { color: vars.colorTextMuted, flexShrink: 0 },
  menu: { width: "14rem" },
  menuIcon: { height: 16, width: 16 },
  childError: {
    color: vars.colorDangerText,
    fontSize: vars.fontSizeBody,
    paddingBlock: vars.space4,
  },
  childEmpty: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeBody,
    paddingBlock: vars.space4,
  },

  // ---- Search view -------------------------------------------------------
  searchRoot: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
  },
  searchField: { paddingBottom: vars.space4, paddingInline: vars.space8 },
  searchAnchor: { position: "relative" },
  searchIcon: {
    color: vars.colorTextMuted,
    height: 14,
    insetInlineStart: vars.space12,
    pointerEvents: "none",
    position: "absolute",
    top: vars.space12,
    width: 14,
  },
  searchInput: {
    backgroundColor: vars.colorCanvas,
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusMark,
    fontSize: vars.fontSizeBody,
    lineHeight: "20px",
    minHeight: 0,
    paddingBlock: vars.space8,
    paddingInlineEnd: 36,
    paddingInlineStart: 32,
    resize: "none",
  },
  searchClear: {
    borderRadius: vars.radiusMark,
    color: { default: vars.colorTextMuted, ":hover": vars.colorText },
    height: 24,
    insetInlineEnd: 6,
    padding: 0,
    position: "absolute",
    top: 6,
    width: 24,
  },
  searchClearIcon: { height: 14, width: 14 },
  searchHint: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeMicro,
    lineHeight: "16px",
    paddingInline: vars.space2,
    paddingTop: vars.space4,
  },
  searchStatus: {
    alignItems: "center",
    color: vars.colorTextMuted,
    display: "flex",
    fontSize: vars.fontSizeBody,
    gap: vars.space8,
    paddingBlock: vars.space8,
    paddingInline: vars.space8,
  },
  searchEmpty: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeBody,
    paddingBlock: vars.space8,
    paddingInline: vars.space8,
  },
  searchError: {
    color: vars.colorDangerText,
    fontSize: vars.fontSizeBody,
    paddingBlock: vars.space8,
    paddingInline: vars.space8,
  },
  searchCount: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    paddingBottom: vars.space4,
    paddingInline: vars.space8,
  },
  searchResults: {
    backgroundColor: vars.colorGround,
    flex: 1,
    minHeight: 0,
  },
  /**
   * The scroller root carries the ground fill directly. It used to be reached
   * through the viewport `react-virtuoso` renders inside it; painting the root
   * covers the same area without a descendant selector.
   */
  searchScroller: { backgroundColor: vars.colorGround },
  resultFileRow: {
    alignItems: "center",
    backgroundColor: { default: "transparent", ":hover": vars.colorOverlayHover },
    borderRadius: vars.radiusMark,
    display: "flex",
    fontSize: vars.fontSizeBody,
    gap: 6,
    height: 28,
    minWidth: 0,
    paddingInline: 6,
    textAlign: "start",
    width: "100%",
  },
  resultIcon: { color: vars.colorTextMuted, flexShrink: 0, height: 14, width: 14 },
  resultFileName: {
    flex: 1,
    fontWeight: vars.fontWeightMedium,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  resultDirPath: {
    color: vars.colorTextMuted,
    flexShrink: 0,
    fontSize: vars.fontSizeCaption,
  },
  resultCount: {
    backgroundColor: vars.colorCanvasSubtle,
    borderRadius: vars.radiusFull,
    color: vars.colorTextMuted,
    flexShrink: 0,
    fontSize: vars.fontSizeCaption,
    marginInlineStart: vars.space4,
    paddingInline: 6,
  },
  resultMatchRow: {
    alignItems: "flex-start",
    backgroundColor: { default: "transparent", ":hover": vars.colorOverlayHover },
    borderRadius: vars.radiusMark,
    display: "flex",
    gap: vars.space8,
    minWidth: 0,
    paddingBlock: 6,
    paddingInline: 6,
    textAlign: "start",
    width: "100%",
  },
  resultLineNumber: {
    backgroundColor: vars.colorCanvasSubtle,
    borderRadius: vars.radiusMark,
    color: vars.colorTextMuted,
    flexShrink: 0,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeMicro,
    marginTop: 2,
    paddingBlock: vars.space2,
    paddingInline: 6,
  },
  resultText: {
    color: vars.colorTextMuted,
    flex: 1,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeMicro,
    lineHeight: "20px",
    minWidth: 0,
    overflowWrap: "break-word",
    whiteSpace: "pre-wrap",
  },
  matchHit: {
    backgroundColor: matchHighlight,
    color: vars.colorText,
    fontWeight: vars.fontWeightMedium,
  },
});
