import * as stylex from "@stylexjs/stylex";
import { vars } from "../ads/tokens/tokens.stylex";

const spin = stylex.keyframes({ to: { transform: "rotate(360deg)" } });
export const toolStyles = stylex.create({
  quickAddClosed: { display: "flex", flexDirection: "column", gap: vars.space8 },
  quickAddForm: { display: "grid", gap: vars.space12, padding: vars.space12, color: vars.colorText },
  fieldLabel: { display: "block", fontSize: vars.fontSizeCaption, fontWeight: vars.fontWeightMedium },
  commandInput: { minHeight: 80, width: "100%", resize: "vertical", fontFamily: vars.fontMono, fontSize: vars.fontSizeCaption },
  formActions: { display: "flex", flexWrap: "wrap", justifyContent: "flex-end", gap: vars.space8 },
  duration: { fontVariantNumeric: "tabular-nums" },
  url: { marginTop: vars.space4, display: "inline-flex", maxWidth: "100%", alignItems: "center", gap: 6, borderRadius: vars.radiusControl, backgroundColor: { default: vars.colorSurfaceTint, ":hover": vars.colorSelectionFill, ":active": vars.colorSurfaceTint }, paddingInline: vars.space8, paddingBlock: vars.space4, fontSize: vars.fontSizeCaption, fontWeight: vars.fontWeightMedium, color: vars.colorText },
  smallIcon: { width: 12, height: 12, flexShrink: 0 },
  externalIcon: { width: 12, height: 12, flexShrink: 0, opacity: 0.6 },
  truncated: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  hint: { fontSize: vars.fontSizeMicro, color: vars.colorTextMuted },
  urlHint: { flexShrink: 0, fontSize: vars.fontSizeMicro, lineHeight: "16px", color: vars.colorTextMuted },
  section: { borderTopWidth: { default: 1, ":first-child": 0 }, borderTopStyle: "solid", borderTopColor: vars.colorBorder },
  sectionHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", paddingBlock: 10 },
  sectionTitle: { fontSize: vars.fontSizeCaption, fontWeight: vars.fontWeightSemibold, color: vars.colorTextMuted },
  sectionCount: { fontSize: vars.fontSizeMicro, fontVariantNumeric: "tabular-nums", color: vars.colorTextMuted },
  compactEmpty: { flex: "none", gap: vars.space8, paddingInline: vars.space16, paddingBlock: vars.space20 },
  compactHeader: { gap: vars.space4 },
  compactMedia: { marginBottom: 0 },
  compactTitle: { fontSize: vars.fontSizeBody },
  description: { fontSize: vars.fontSizeCaption, lineHeight: 1.625, color: vars.colorTextMuted },
  hook: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: vars.space12, borderBottomWidth: { default: 1, ":last-child": 0 }, borderBottomStyle: "solid", borderBottomColor: vars.colorBorder, paddingBlock: vars.space12 },
  hookText: { minWidth: 0, display: "flex", flexDirection: "column", gap: vars.space4 },
  title: { fontSize: vars.fontSizeBody, fontWeight: vars.fontWeightMedium, color: vars.colorText },
  muted: { fontSize: vars.fontSizeCaption, color: vars.colorTextMuted },
  truncatedHint: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", fontSize: vars.fontSizeMicro, color: vars.colorTextMuted },
  runButton: { height: 32, borderRadius: vars.radiusControl, paddingInline: 10 },
  loader: { marginRight: vars.space4 },
  runIcon: { marginRight: vars.space4, width: 14, height: 14 },
  entry: { borderBottomWidth: { default: 1, ":last-child": 0 }, borderBottomStyle: "solid", borderBottomColor: vars.colorBorder, paddingBlock: vars.space12 },
  selected: { backgroundColor: vars.colorSelectionFill },
  entryHeader: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: vars.space12 },
  entryBody: { minWidth: 0, flex: 1, display: "flex", flexDirection: "column", gap: vars.space2 },
  entryTitleRow: { display: "flex", flexWrap: "wrap", alignItems: "baseline", columnGap: vars.space8, rowGap: vars.space2 },
  inspect: { textAlign: "start", fontSize: vars.fontSizeBody, fontWeight: vars.fontWeightMedium, color: vars.colorText, textDecorationLine: { default: "none", ":hover": "underline" } },
  stateRow: { display: "flex", alignItems: "center", gap: 6, fontSize: vars.fontSizeMicro },
  running: { display: "inline-flex", alignItems: "center", gap: vars.space4, fontWeight: vars.fontWeightMedium, color: vars.colorAccent },
  runningMark: { width: 6, height: 6, borderRadius: 9999, backgroundColor: vars.colorAccent },
  separator: { color: vars.colorTextSubtle },
  metadata: { color: vars.colorTextMuted },
  finished: { display: "inline-flex", alignItems: "center", gap: vars.space4, color: vars.colorTextMuted },
  failed: { fontWeight: vars.fontWeightMedium, color: vars.colorDangerText },
  success: { fontWeight: vars.fontWeightMedium, color: vars.colorSuccessText },
  detail: { fontSize: vars.fontSizeMicro, color: vars.colorTextSubtle },
  actions: { display: "flex", alignItems: "center", gap: 6 },
  iconButton: { width: 28, height: 28, borderRadius: vars.radiusControl },
  icon: { width: 14, height: 14 },
  sectionIcon: { width: 16, height: 16 },
  view: { paddingInline: vars.space12, paddingBlock: vars.space8 },
  loading: { paddingInline: vars.space4, paddingBlock: vars.space16, fontSize: vars.fontSizeCaption, color: vars.colorTextMuted },
  quickAdd: { marginTop: vars.space4, width: "100%", maxWidth: "24rem" },
  setup: { paddingInline: vars.space8, paddingBlock: vars.space32, textAlign: "center" },
  setupAction: { marginTop: vars.space16 },
  addForm: { marginBottom: vars.space12 },
  viewDescription: { paddingInline: vars.space4, paddingBottom: vars.space12, fontSize: vars.fontSizeCaption, lineHeight: "20px", color: vars.colorTextMuted },
  inactive: { borderTopWidth: 1, borderTopStyle: "solid", borderTopColor: vars.colorBorder, paddingInline: vars.space8, paddingBlock: vars.space24, textAlign: "center" },
  inactiveHint: { marginTop: vars.space4, fontSize: vars.fontSizeCaption, lineHeight: "20px", color: vars.colorTextMuted },
  settingsButton: { marginTop: vars.space4, height: 32, borderRadius: vars.radiusControl },
  settingsIcon: { marginRight: vars.space4, width: 16, height: 16 },
  panel: { display: "flex", height: "100%", minHeight: 0, flexDirection: "column", overflow: "hidden" },
  header: { flexShrink: 0, display: "flex", flexDirection: "column", gap: vars.space8, borderBottomWidth: 1, borderBottomStyle: "solid", borderBottomColor: vars.colorBorder, padding: vars.space12 },
  headingRow: { display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: vars.space8 },
  heading: { minWidth: 0 },
  panelTitle: { fontSize: vars.fontSizeBody, fontWeight: vars.fontWeightSemibold },
  workspaceName: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", fontSize: vars.fontSizeCaption, color: vars.colorTextMuted },
  headerActions: { display: "flex", alignItems: "center", gap: vars.space4 },
  refreshing: { animationName: { default: spin, "@media (prefers-reduced-motion: reduce)": "none" }, animationDuration: "1s", animationTimingFunction: "linear", animationIterationCount: "infinite" },
  configError: { flexShrink: 0, borderBottomWidth: 1, borderBottomStyle: "solid", borderBottomColor: vars.colorDangerBorder, paddingInline: vars.space12, paddingBlock: vars.space8, fontSize: vars.fontSizeCaption, color: vars.colorDangerText },
  search: { minHeight: 0, flex: 1, overflow: "auto", padding: vars.space12 },
  noResults: { paddingBlock: vars.space8, fontSize: vars.fontSizeCaption, color: vars.colorTextMuted },
  views: { display: "flex", minHeight: 0, flex: 1, flexDirection: "column" },
  hidden: { display: "none" },
  output: { maxHeight: "45%", flexShrink: 0, overflow: "auto", borderTopWidth: 1, borderTopStyle: "solid", borderTopColor: vars.colorBorder, backgroundColor: vars.colorCanvas, padding: vars.space12 },
  outputHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: vars.space8 },
  outputTitle: { minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", fontSize: vars.fontSizeBody, fontWeight: vars.fontWeightSemibold },
  noOutput: { paddingBlock: vars.space12, fontSize: vars.fontSizeCaption, color: vars.colorTextMuted },
});
