import * as stylex from "@stylexjs/stylex";

import { vars } from "../ads/tokens/tokens.stylex";

const spin = stylex.keyframes({ to: { transform: "rotate(360deg)" } });

/** Saved-plan list: header, empty state, and the per-plan row cluster. */
export const planStyles = stylex.create({
  root: { display: "flex", flexDirection: "column", gap: vars.space12 },
  headerRow: {
    alignItems: "flex-start",
    display: "flex",
    gap: vars.space12,
    justifyContent: "space-between",
  },
  headerText: { display: "flex", flexDirection: "column", gap: vars.space2 },
  headerTitle: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
  },
  headerHint: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: "16px",
  },
  headerActions: {
    alignItems: "center",
    display: "flex",
    gap: vars.space8,
  },
  headerBadge: { borderRadius: vars.radiusMark },
  refreshButton: { borderRadius: vars.radiusMark, height: 32 },
  refreshIcon: { height: 16, marginRight: vars.space4, width: 16 },
  spinning: {
    animationDuration: {
      default: vars.motionDurationLoop,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    animationIterationCount: "infinite",
    animationName: spin,
    animationTimingFunction: "linear",
  },
  unavailable: {
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusPanel,
    borderStyle: "dashed",
    borderWidth: vars.borderWidthHairline,
    backgroundColor: vars.colorSurfaceTint,
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: "20px",
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
  },
  loading: {
    alignItems: "center",
    color: vars.colorTextMuted,
    display: "flex",
    fontSize: vars.fontSizeCaption,
    gap: vars.space8,
    paddingBlock: vars.space16,
    paddingInline: vars.space8,
  },
  smallIcon: { height: 14, width: 14 },
  empty: {
    backgroundColor: vars.colorSurfaceTint,
    paddingBlock: vars.space16,
    paddingInline: vars.space12,
  },
  emptyLead: { display: "flex", alignItems: "flex-start", gap: vars.space12 },
  emptyMark: {
    backgroundColor: vars.colorCanvas,
    borderRadius: vars.radiusPanel,
    boxShadow: vars.elevationRaised,
    color: vars.colorAccent,
    display: "grid",
    flexShrink: 0,
    height: 36,
    outlineColor: vars.colorBorderSubtle,
    outlineOffset: 0,
    outlineStyle: "solid",
    outlineWidth: 1,
    placeItems: "center",
    width: 36,
  },
  emptyIcon: { height: 16, width: 16 },
  emptyText: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space4,
    minWidth: 0,
  },
  emptyTitle: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    lineHeight: "20px",
  },
  emptyDescription: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: "16px",
  },
  emptyActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: vars.space8,
    marginTop: vars.space12,
  },
  emptyButton: { height: 32 },
  list: { display: "flex", flexDirection: "column", gap: vars.space8 },
  row: {
    alignItems: "stretch",
    backgroundColor: {
      default: vars.colorSurfaceTint,
      ":hover": vars.colorCanvasSubtle,
    },
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusPanel,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    display: "flex",
    gap: vars.space4,
    overflow: "hidden",
    width: "100%",
  },
  rowOpen: {
    alignItems: "flex-start",
    display: "flex",
    flex: 1,
    gap: vars.space12,
    minWidth: 0,
    paddingBlock: 10,
    paddingInline: vars.space12,
    textAlign: "start",
  },
  rowIcon: {
    color: vars.colorAccent,
    flexShrink: 0,
    height: 16,
    marginTop: 2,
    width: 16,
  },
  rowBody: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: vars.space4,
    minWidth: 0,
  },
  rowTitleLine: { alignItems: "center", display: "flex", gap: vars.space8 },
  rowTitle: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowBadge: {
    borderRadius: vars.radiusMark,
    fontSize: vars.fontSizeMicro,
    paddingBlock: 0,
    paddingInline: 6,
  },
  rowMeta: {
    color: vars.colorTextSubtle,
    fontSize: vars.fontSizeMicro,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowAction: {
    alignItems: "center",
    color: {
      default: vars.colorTextSubtle,
      ":hover": vars.colorText,
    },
    backgroundColor: { default: "transparent", ":hover": vars.colorOverlayHover },
    display: "flex",
    flexShrink: 0,
    justifyContent: "center",
    width: 36,
  },
  rowActionDanger: {
    backgroundColor: {
      default: "transparent",
      ":hover": vars.colorDangerSoft,
    },
    color: {
      default: vars.colorTextSubtle,
      ":focus-visible": vars.colorDangerText,
      ":hover": vars.colorDangerText,
    },
  },
  rowActionIcon: { height: 16, width: 16 },
  card: {
    backgroundColor: vars.colorCanvas,
    borderColor: vars.colorBorderSubtle,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
  },
  cardContent: { paddingTop: vars.space16 },
});
