import * as stylex from "@stylexjs/stylex";

import { vars } from "../ads/tokens/tokens.stylex";

const spin = stylex.keyframes({ to: { transform: "rotate(360deg)" } });

/**
 * A row reveals its actions on hover/focus, but the trigger is the ROW and the
 * target is a descendant — which StyleX has no selector for. The row publishes
 * its state as custom properties and the children read them, the same
 * parent-publishes/child-reads shape the markdown preview uses for paragraph
 * margins.
 */
const ROW_ACTION_OPACITY = "--stave-skill-row-actions";
const ROW_CHEVRON_NUDGE = "--stave-skill-row-nudge";

const hairlineRing = `0 0 0 1px ${vars.colorBorderSubtle}`;

export const skillStyles = stylex.create({
  // ---- Instructions surface ---------------------------------------------
  instructionsSource: {
    backgroundColor: vars.colorSurfaceTint,
    borderRadius: vars.radiusPanel,
    boxShadow: hairlineRing,
    color: vars.colorText,
    fontFamily: vars.fontMono,
    // 13px: the reading step between caption and body this pane has always used.
    fontSize: 13,
    lineHeight: "24px",
    minHeight: 0,
    overflowWrap: "break-word",
    paddingBlock: vars.space12,
    paddingInline: vars.space16,
    whiteSpace: "pre-wrap",
  },
  instructionsRendered: {
    backgroundColor: vars.colorSurfaceTint,
    borderRadius: vars.radiusPanel,
    boxShadow: hairlineRing,
    color: vars.colorText,
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    paddingBlock: vars.space12,
    paddingInline: vars.space16,
  },
  instructionsPreview: {
    backgroundColor: "transparent",
    flex: 1,
    minHeight: 0,
    overflow: "visible",
  },
  instructionsFill: { flex: 1, height: "100%", minHeight: "100%" },
  instructionsPreviewPane: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    paddingBlock: 10,
    paddingInline: vars.space12,
  },

  // ---- Instructions dialog ----------------------------------------------
  dialog: {
    display: "flex",
    flexDirection: "column",
    gap: 0,
    height: "min(88vh, 56rem)",
    maxHeight: "88vh",
    maxWidth: "64rem",
    overflow: "hidden",
    padding: 0,
  },
  dialogHeader: {
    borderBottomColor: vars.colorBorderSubtle,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    flexShrink: 0,
    paddingBlock: vars.space20,
    paddingInlineEnd: 56,
    paddingInlineStart: 28,
  },
  dialogTabs: { flex: 1, gap: 0, height: "100%", minHeight: 0 },
  dialogTabBar: {
    borderBottomColor: vars.colorBorderSubtle,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    flexShrink: 0,
    paddingInline: 28,
  },
  dialogTabList: {
    borderRadius: 0,
    gap: vars.space20,
    height: 44,
    padding: 0,
  },
  dialogTab: { flex: "none", fontSize: 13, height: 44, paddingInline: 0 },
  dialogPanel: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    overflow: "auto",
    paddingBlock: vars.space20,
    paddingInline: vars.space20,
    "@media (min-width: 40rem)": { paddingInline: 28 },
  },
  dialogEmpty: {
    alignItems: "center",
    color: vars.colorTextMuted,
    display: "flex",
    flex: 1,
    fontSize: vars.fontSizeBody,
    justifyContent: "center",
    minHeight: 0,
    paddingBlock: vars.space32,
    paddingInline: 28,
  },

  // ---- Section header ----------------------------------------------------
  sectionHeader: {
    alignItems: "center",
    borderBottomColor: vars.colorBorderSubtle,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    display: "flex",
    gap: vars.space8,
    justifyContent: "space-between",
    paddingBottom: vars.space8,
    paddingInline: vars.space4,
    paddingTop: vars.space16,
  },
  sectionTitle: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeMicro,
    fontWeight: vars.fontWeightSemibold,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
  },
  sectionCount: {
    color: vars.colorTextMuted,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeMicro,
    fontVariantNumeric: "tabular-nums",
  },

  // ---- Skill row ---------------------------------------------------------
  row: {
    [ROW_ACTION_OPACITY]: {
      default: "0",
      ":focus-within": "1",
      ":hover": "1",
    },
    [ROW_CHEVRON_NUDGE]: { default: "0px", ":hover": "2px" },
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":focus-within": vars.colorOverlayHover,
      ":hover": vars.colorOverlayHover,
    },
    borderBottomColor: vars.colorBorderSubtle,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    display: "flex",
    gap: vars.space12,
    paddingBlock: vars.space12,
    paddingInline: vars.space4,
    textAlign: "start",
    width: "100%",
  },
  rowOpen: {
    alignItems: "center",
    display: "flex",
    flex: 1,
    gap: vars.space12,
    minWidth: 0,
  },
  rowScope: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    paddingTop: vars.space2,
  },
  rowScopeIcon: { color: vars.colorTextMuted, height: 14, width: 14 },
  rowBody: { flex: 1, minWidth: 0 },
  rowTitleLine: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  rowTitle: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
  },
  rowBadge: {
    borderRadius: vars.radiusMark,
    fontSize: vars.fontSizeMicro,
    height: 18,
    letterSpacing: "0.025em",
    paddingBlock: 0,
    paddingInline: 6,
    textTransform: "uppercase",
  },
  rowDescription: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    marginTop: vars.space2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowActions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: vars.space4,
    opacity: `var(${ROW_ACTION_OPACITY})`,
  },
  rowChevron: {
    color: vars.colorTextSubtle,
    flexShrink: 0,
    height: 14,
    transform: `translateX(var(${ROW_CHEVRON_NUDGE}))`,
    width: 14,
  },
  iconButtonSm: { borderRadius: vars.radiusControl, height: 24, width: 24 },
  iconButtonMd: { borderRadius: vars.radiusControl, height: 28, width: 28 },
  glyphXs: { height: 12, width: 12 },
  glyphSm: { height: 14, width: 14 },
  glyphMd: { height: 16, width: 16 },
  spinning: {
    animationDuration: {
      default: vars.motionDurationLoop,
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    animationIterationCount: "infinite",
    animationName: spin,
    animationTimingFunction: "linear",
  },

  // ---- Metadata disclosure ----------------------------------------------
  details: {
    backgroundColor: vars.colorSurfaceTint,
    borderRadius: vars.radiusPanel,
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
  },
  summary: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":hover": vars.colorCanvasSubtle,
    },
    borderRadius: vars.radiusPanel,
    color: { default: vars.colorTextMuted, ":hover": vars.colorText },
    cursor: "pointer",
    display: "flex",
    fontSize: vars.fontSizeMicro,
    fontWeight: vars.fontWeightMedium,
    gap: vars.space8,
    letterSpacing: "0.16em",
    listStyleType: "none",
    paddingBlock: vars.space8,
    paddingInline: 10,
    textTransform: "uppercase",
    "::-webkit-details-marker": { display: "none" },
  },
  summaryChevron: {
    flexShrink: 0,
    height: 12,
    transform: "rotate(0deg)",
    transitionDuration: {
      default: vars.motionDurationQuick,
      "@media (prefers-reduced-motion: reduce)": "0ms",
    },
    transitionProperty: "transform",
    transitionTimingFunction: vars.motionEaseStandard,
    width: 12,
  },
  summaryChevronOpen: { transform: "rotate(90deg)" },
  detailsList: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    paddingBottom: 10,
    paddingInline: 10,
    paddingTop: vars.space4,
  },
  detailsRow: { display: "flex", gap: vars.space8 },
  detailsTerm: {
    color: vars.colorTextMuted,
    flexShrink: 0,
    fontWeight: vars.fontWeightMedium,
  },
  detailsValue: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },

  // ---- Detail view -------------------------------------------------------
  detail: { display: "flex", flexDirection: "column", height: "100%" },
  detailHeader: {
    alignItems: "center",
    borderBottomColor: vars.colorBorderSubtle,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    display: "flex",
    flexShrink: 0,
    gap: vars.space8,
    paddingBlock: vars.space8,
    paddingInline: vars.space8,
  },
  detailTitle: {
    flex: 1,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  detailMenu: { width: "13rem" },
  detailBody: {
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
    paddingBlock: vars.space12,
    paddingInline: vars.space12,
  },
  detailColumn: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space16,
    height: "100%",
    minHeight: 0,
  },
  overview: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space16,
    minHeight: 0,
    paddingInlineEnd: vars.space4,
  },
  overviewScrolled: {
    flexShrink: 0,
    maxHeight: "42%",
    overflowY: "auto",
    overscrollBehavior: "contain",
    paddingBottom: vars.space4,
  },
  overviewFull: { flex: 1, overflowY: "auto" },
  badgeRow: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  detailBadge: {
    borderRadius: vars.radiusMark,
    fontSize: vars.fontSizeMicro,
    letterSpacing: "0.025em",
    paddingBlock: vars.space2,
    paddingInline: vars.space8,
    textTransform: "uppercase",
  },
  field: { display: "flex", flexDirection: "column", gap: vars.space4 },
  fieldLabel: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeMicro,
    fontWeight: vars.fontWeightMedium,
    letterSpacing: "0.16em",
    textTransform: "uppercase",
  },
  fieldText: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    lineHeight: vars.lineHeightRelaxed,
  },
  tokenRow: { alignItems: "center", display: "flex", gap: vars.space8 },
  tokenCode: {
    backgroundColor: vars.colorCanvas,
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeBody,
    paddingBlock: vars.space4,
    paddingInline: vars.space8,
  },
  insertButton: {
    borderRadius: vars.radiusControl,
    gap: 6,
    height: 28,
    paddingInline: vars.space8,
  },
  instructionsBlock: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: vars.space4,
    minHeight: 0,
  },
  instructionsHead: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
  },

  // ---- Panel shell -------------------------------------------------------
  disabled: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    height: "100%",
    justifyContent: "center",
    paddingInline: vars.space16,
  },
  disabledEmpty: {
    backgroundColor: vars.colorSurfaceTint,
    borderColor: vars.colorBorderSubtle,
    borderStyle: "dashed",
    borderWidth: vars.borderWidthHairline,
  },
  disabledAction: {
    borderRadius: vars.radiusControl,
    height: 32,
    marginTop: vars.space4,
  },
  disabledActionIcon: { height: 16, marginRight: vars.space4, width: 16 },
  panel: { display: "flex", flexDirection: "column", height: "100%" },
  panelHeader: {
    alignItems: "center",
    borderBottomColor: vars.colorBorderSubtle,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    display: "flex",
    flexShrink: 0,
    gap: vars.space8,
    justifyContent: "space-between",
    paddingBlock: 10,
    paddingInline: vars.space12,
  },
  panelHeaderText: { minWidth: 0 },
  panelCount: {
    color: vars.colorText,
    display: "block",
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightSemibold,
  },
  panelHint: {
    color: vars.colorTextMuted,
    display: "block",
    fontSize: vars.fontSizeMicro,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  panelActions: { alignItems: "center", display: "flex", gap: 6 },
  searchSlot: {
    flexShrink: 0,
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
  },
  searchAnchor: { position: "relative" },
  searchIcon: {
    color: vars.colorTextMuted,
    height: 14,
    insetInlineStart: 14,
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    width: 14,
  },
  searchInput: {
    backgroundColor: vars.colorSurfaceTint,
    borderColor: { default: "transparent", ":hover": vars.colorBorderSubtle },
    fontSize: vars.fontSizeBody,
    height: 32,
    paddingInlineEnd: 28,
    paddingInlineStart: 28,
  },
  searchClear: {
    color: { default: vars.colorTextMuted, ":hover": vars.colorText },
    insetInlineEnd: 14,
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
  },
  list: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    paddingBottom: vars.space8,
    paddingInline: vars.space12,
  },
  listStatus: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    paddingBlock: vars.space16,
    paddingInline: vars.space4,
  },
  listEmpty: {
    paddingBlock: vars.space16,
    paddingInline: vars.space4,
    textAlign: "center",
  },
  listEmptyText: { color: vars.colorTextMuted, fontSize: vars.fontSizeBody },
});
