import * as stylex from "@stylexjs/stylex";

import { vars } from "@/components/ads/tokens/tokens.stylex";

const spin = stylex.keyframes({
  from: { transform: "rotate(0deg)" },
  to: { transform: "rotate(360deg)" },
});

/**
 * Workspace Information panel.
 *
 * Two reveal-on-hover patterns here used to be Tailwind `group/*` variants.
 * StyleX has no ancestor selector, so each hovered container publishes an
 * inherited custom property (`--info-*`) that its descendants read. The parent
 * still owns the `:hover` condition, so the behaviour is unchanged; only the
 * transport differs.
 */
export const workspaceInformationPanelStyles = stylex.create({
  // ---- shell -------------------------------------------------------------
  root: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    overflow: "auto",
    transformOrigin: "top left",
  },
  body: { paddingBlock: vars.space8, paddingInline: vars.space12 },
  topCards: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space8,
    marginBlockEnd: vars.space8,
  },

  // ---- section header ----------------------------------------------------
  sectionItem: {
    borderBottomColor: vars.colorBorderSubtle,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    position: "relative",
  },
  sectionItemFirst: { borderTopWidth: 0 },
  sectionItemDragging: { opacity: vars.opacityDisabled },
  sectionRow: {
    // Hover hand-off for the icon -> chevron cross-fade below.
    "--info-section-chevron-opacity": { default: "0", ":hover": "1" },
    "--info-section-chevron-scale": { default: "0.75", ":hover": "1" },
    "--info-section-icon-opacity": { default: "1", ":hover": "0" },
    "--info-section-icon-scale": { default: "1", ":hover": "0.75" },
    alignItems: "center",
    display: "flex",
  },
  sectionTrigger: {
    flex: 1,
    gap: vars.space8,
    paddingBlock: 10,
    paddingInlineEnd: vars.space4,
    paddingInlineStart: 0,
    textDecorationLine: { default: "none", ":hover": "none" },
  },
  sectionTriggerDraggable: {
    cursor: { default: "grab", ":active": "grabbing" },
  },
  sectionTitleRow: {
    alignItems: "center",
    display: "flex",
    gap: vars.space8,
    textAlign: "start",
  },
  sectionMark: {
    alignItems: "center",
    color: vars.colorTextMuted,
    display: "flex",
    flexShrink: 0,
    height: 18,
    justifyContent: "center",
    position: "relative",
    width: 18,
  },
  sectionMarkIcon: {
    alignItems: "center",
    display: "flex",
    justifyContent: "center",
    opacity: "var(--info-section-icon-opacity)",
    transform: "scale(var(--info-section-icon-scale))",
    transitionDuration: {
      default: vars.motionDurationQuick,
      "@media (prefers-reduced-motion: reduce)": "0ms",
    },
    transitionProperty: "opacity, transform",
    transitionTimingFunction: vars.motionEaseStandard,
  },
  sectionMarkChevronSlot: {
    alignItems: "center",
    display: "flex",
    inset: 0,
    justifyContent: "center",
    pointerEvents: "none",
    position: "absolute",
  },
  sectionMarkChevron: {
    height: 18,
    opacity: "var(--info-section-chevron-opacity)",
    transform: "scale(var(--info-section-chevron-scale))",
    transitionDuration: {
      default: vars.motionDurationQuick,
      "@media (prefers-reduced-motion: reduce)": "0ms",
    },
    transitionProperty: "opacity, transform",
    transitionTimingFunction: vars.motionEaseStandard,
    width: 18,
  },
  sectionTitle: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
  },
  sectionCount: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    fontVariantNumeric: "tabular-nums",
  },
  sectionAction: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    marginInlineStart: "auto",
  },
  sectionActionGroup: {
    alignItems: "center",
    display: "flex",
    gap: vars.space2,
  },
  sectionPanel: {
    paddingBlockEnd: vars.space12,
    paddingBlockStart: 0,
    paddingInlineStart: vars.space8,
  },
  sectionStamp: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeMicro,
    paddingInlineEnd: vars.space4,
  },

  // ---- inline link row ---------------------------------------------------
  linkRow: {
    "--info-row-action-opacity": { default: "0", ":hover": "1" },
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":hover": vars.colorOverlayHover,
      ":focus-within": vars.colorOverlayHover,
    },
    borderRadius: vars.radiusControl,
    display: "flex",
    gap: 10,
    paddingBlock: vars.space8,
    paddingInline: 6,
  },
  linkRowMark: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  linkRowBody: { flex: 1, minWidth: 0 },
  linkRowTitleLine: {
    alignItems: "center",
    display: "flex",
    gap: vars.space8,
  },
  linkRowTitle: {
    color: { default: vars.colorText, ":hover": vars.colorAccent },
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    minWidth: 0,
    overflow: "hidden",
    textDecorationLine: { default: "none", ":hover": "underline" },
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  linkRowSublabel: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  linkRowTrail: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: vars.space2,
  },
  linkRowTrailReveal: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: vars.space2,
    opacity: "var(--info-row-action-opacity)",
    transitionDuration: {
      default: vars.motionDurationFast,
      "@media (prefers-reduced-motion: reduce)": vars.motionDurationMicro,
    },
    transitionProperty: "opacity",
    transitionTimingFunction: vars.motionEaseStandard,
  },

  // ---- icon buttons ------------------------------------------------------
  iconButton: {
    alignItems: "center",
    borderRadius: vars.radiusMark,
    color: { default: vars.colorTextMuted, ":hover": vars.colorText },
    display: "flex",
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  iconButtonQuiet: {
    alignItems: "center",
    borderRadius: vars.radiusMark,
    color: { default: vars.colorTextSubtle, ":hover": vars.colorText },
    display: "flex",
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  iconButtonDanger: {
    backgroundColor: {
      default: "transparent",
      ":hover": vars.colorDangerSoft,
    },
    color: { default: vars.colorTextMuted, ":hover": vars.colorDangerText },
  },
  iconButtonDisabledQuiet: {
    opacity: { default: 1, ":disabled": 0.4 },
    pointerEvents: { default: "auto", ":disabled": "none" },
  },
  iconButtonShrink0: { flexShrink: 0 },
  iconButtonPinned: { color: vars.colorAccent, opacity: 1 },
  iconButtonPinReveal: {
    color: { default: vars.colorTextMuted, ":hover": vars.colorText },
    opacity: "var(--info-row-action-opacity)",
  },
  iconButtonPinBase: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":hover": vars.colorOverlayHover,
    },
    borderRadius: vars.radiusMark,
    display: "flex",
    height: 28,
    justifyContent: "center",
    transitionDuration: {
      default: vars.motionDurationFast,
      "@media (prefers-reduced-motion: reduce)": vars.motionDurationMicro,
    },
    transitionProperty: "opacity",
    transitionTimingFunction: vars.motionEaseStandard,
    width: 28,
  },
  iconButtonHoverSurface: {
    backgroundColor: {
      default: "transparent",
      ":hover": vars.colorOverlayHover,
    },
  },
  glyphSm: { height: 14, width: 14 },
  glyphMd: { height: 16, width: 16 },
  glyphFilled: { fill: "currentColor" },
  glyphSpinning: {
    animationDuration: {
      default: "1s",
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    animationIterationCount: "infinite",
    animationName: spin,
    animationTimingFunction: "linear",
  },
  brandGlyph: { height: 16, width: 16 },
  amplifyGlyph: { height: 16, flexShrink: 0, width: "auto" },
  mutedGlyph: { color: vars.colorTextMuted, height: 16, width: 16 },

  // ---- pin tooltip -------------------------------------------------------
  pinTooltip: {
    alignItems: "flex-start",
    flexDirection: "column",
    gap: vars.space2,
    maxWidth: "15rem",
    overflowWrap: "normal",
    textAlign: "start",
    whiteSpace: "normal",
    wordBreak: "normal",
  },
  pinTooltipTitle: { fontWeight: vars.fontWeightMedium },
  pinTooltipBody: { color: vars.colorTextInverted },

  // ---- inline url input --------------------------------------------------
  urlInputRow: {
    alignItems: "center",
    display: "flex",
    gap: vars.space8,
    paddingBlock: 6,
    paddingInline: 6,
  },
  urlInputMark: {
    alignItems: "center",
    color: vars.colorTextSubtle,
    display: "flex",
    flexShrink: 0,
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  bareInput: {
    backgroundColor: "transparent",
    borderWidth: 0,
    boxShadow: "none",
    flex: 1,
    fontSize: vars.fontSizeBody,
    height: 32,
    outlineWidth: { default: 0, ":focus-visible": 0 },
    paddingInline: 0,
  },
  bareInputPadded: {
    backgroundColor: "transparent",
    borderWidth: 0,
    boxShadow: "none",
    flex: 1,
    fontSize: vars.fontSizeBody,
    height: 32,
    outlineWidth: { default: 0, ":focus-visible": 0 },
    paddingInline: vars.space4,
  },
  bareInputStrong: { fontWeight: vars.fontWeightMedium },
  bareInputDone: {
    color: vars.colorTextSubtle,
    textDecorationLine: "line-through",
  },

  // ---- github pr row -----------------------------------------------------
  prRow: {
    "--info-row-action-opacity": { default: "0", ":hover": "1" },
    alignItems: "flex-start",
    backgroundColor: {
      default: "transparent",
      ":hover": vars.colorOverlayHover,
    },
    borderRadius: vars.radiusControl,
    display: "flex",
    gap: 10,
    paddingBlock: 10,
    paddingInline: 6,
  },
  prRowMark: { flexShrink: 0, height: 16, marginBlockStart: 2, width: 16 },
  prStatusGlyph: { flexShrink: 0, height: 18, width: 18 },
  prStatusMerged: { color: vars.colorAccent },
  prStatusClosed: { color: vars.colorDangerText },
  prStatusDraft: { color: vars.colorTextMuted },
  prStatusOpen: { color: vars.colorSuccessText },
  prRowBody: { flex: 1, minWidth: 0 },
  prRowTitleLine: {
    alignItems: "flex-start",
    display: "flex",
    gap: vars.space8,
  },
  prRowTitle: {
    color: { default: vars.colorText, ":hover": vars.colorAccent },
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    lineHeight: 1.375,
    minWidth: 0,
    textAlign: "start",
    textDecorationLine: { default: "none", ":hover": "underline" },
  },
  prRowMeta: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    marginBlockStart: vars.space4,
  },
  prRowNumber: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    fontVariantNumeric: "tabular-nums",
  },
  prRowRepo: { color: vars.colorTextMuted, fontSize: vars.fontSizeCaption },
  prRowBranch: {
    color: vars.colorTextSubtle,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeMicro,
  },
  prRowTrail: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: vars.space2,
    opacity: "var(--info-row-action-opacity)",
    paddingBlockStart: 2,
    transitionDuration: {
      default: vars.motionDurationFast,
      "@media (prefers-reduced-motion: reduce)": vars.motionDurationMicro,
    },
    transitionProperty: "opacity",
    transitionTimingFunction: vars.motionEaseStandard,
  },

  // ---- badges / chips ----------------------------------------------------
  chip: {
    borderRadius: vars.radiusFull,
    fontSize: vars.fontSizeMicro,
    fontWeight: vars.fontWeightRegular,
    height: 20,
    lineHeight: 1,
    paddingBlock: 0,
    paddingInline: vars.space8,
  },
  chipTight: {
    borderRadius: vars.radiusFull,
    fontSize: vars.fontSizeMicro,
    fontWeight: vars.fontWeightRegular,
    height: 20,
    lineHeight: 1,
    paddingBlock: 0,
    paddingInline: 6,
  },
  chipStatus: {
    borderRadius: vars.radiusFull,
    fontSize: vars.fontSizeMicro,
    fontWeight: vars.fontWeightMedium,
    height: 20,
    lineHeight: 1,
    paddingBlock: 0,
    paddingInline: 6,
  },
  chipRepo: { maxWidth: "9rem" },
  chipRepoLabel: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },

  // ---- custom fields -----------------------------------------------------
  fieldStack: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  control: { fontSize: vars.fontSizeBody, height: 36 },
  controlBlock: { fontSize: vars.fontSizeBody, height: 36, width: "100%" },
  controlFlex: { flex: 1, fontSize: vars.fontSizeBody, height: 36 },
  controlTextarea: { fontSize: vars.fontSizeBody, minHeight: 80 },
  datePickerTrigger: {
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightRegular,
    height: 36,
    justifyContent: "flex-start",
    textAlign: "start",
    width: "100%",
  },
  datePickerTriggerEmpty: { color: vars.colorTextMuted },
  datePickerIcon: { height: 16, marginInlineEnd: vars.space8, width: 16 },
  datePickerPopover: { padding: 0, width: "auto" },
  switchRow: {
    alignItems: "center",
    display: "flex",
    gap: vars.space8,
  },
  switchLabel: { color: vars.colorTextMuted, fontSize: vars.fontSizeBody },
  urlFieldRow: {
    alignItems: "center",
    display: "flex",
    gap: 6,
  },
  urlFieldOpen: {
    alignItems: "center",
    borderRadius: vars.radiusMark,
    color: { default: vars.colorTextMuted, ":hover": vars.colorText },
    display: "flex",
    flexShrink: 0,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  customField: {
    "--info-row-action-opacity": { default: "0", ":hover": "1" },
    display: "flex",
    flexDirection: "column",
    gap: 6,
    paddingInline: 6,
  },
  customFieldHead: {
    alignItems: "center",
    display: "flex",
    gap: 6,
  },
  customFieldType: {
    backgroundColor: "transparent",
    borderWidth: 0,
    boxShadow: "none",
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    height: 32,
    minWidth: "5.5rem",
    width: "auto",
  },
  rowRemove: {
    alignItems: "center",
    borderRadius: vars.radiusMark,
    color: { default: vars.colorTextSubtle, ":hover": vars.colorDangerText },
    display: "flex",
    flexShrink: 0,
    height: 28,
    justifyContent: "center",
    opacity: "var(--info-row-action-opacity)",
    transitionDuration: {
      default: vars.motionDurationFast,
      "@media (prefers-reduced-motion: reduce)": vars.motionDurationMicro,
    },
    transitionProperty: "opacity",
    transitionTimingFunction: vars.motionEaseStandard,
    width: 28,
  },
  rowRemoveSm: { height: 24, width: 24 },

  // ---- empty state / notes ----------------------------------------------
  emptyHint: {
    color: vars.colorTextSubtle,
    fontSize: vars.fontSizeBody,
    paddingBlock: 6,
    paddingInline: vars.space8,
  },
  notesEditor: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space8,
  },
  notesTextarea: {
    fontSize: vars.fontSizeBody,
    lineHeight: vars.lineHeightRelaxed,
    minHeight: 160,
    resize: "vertical",
  },
  notesFooter: {
    alignItems: "center",
    display: "flex",
    gap: vars.space12,
    justifyContent: "space-between",
  },
  notesHint: { color: vars.colorTextMuted, fontSize: vars.fontSizeMicro },
  notesActions: {
    alignItems: "center",
    display: "flex",
    gap: 6,
  },
  notesButton: { height: 32 },
  notesPlaceholder: {
    backgroundColor: {
      default: "transparent",
      ":hover": vars.colorOverlayHover,
    },
    borderRadius: vars.radiusControl,
    color: vars.colorTextSubtle,
    fontSize: vars.fontSizeBody,
    paddingBlock: vars.space12,
    paddingInline: vars.space8,
    textAlign: "start",
    width: "100%",
  },
  notesPreview: {
    backgroundColor: {
      default: "transparent",
      ":hover": vars.colorOverlayHover,
    },
    borderRadius: vars.radiusControl,
    cursor: "text",
    paddingBlock: 6,
    paddingInline: vars.space8,
    textAlign: "start",
    width: "100%",
  },

  // ---- summary / todo ----------------------------------------------------
  summaryEmpty: {
    backgroundColor: vars.colorSurfaceTint,
    paddingBlock: vars.space16,
    paddingInline: vars.space12,
  },
  summaryEmptyTitle: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
  },
  summaryEmptyBody: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightRelaxed,
    marginBlockStart: vars.space4,
  },
  todoProgressRow: {
    alignItems: "center",
    display: "flex",
    gap: vars.space8,
    marginBlockEnd: 6,
    paddingInline: 2,
  },
  todoProgressTrack: {
    backgroundColor: vars.colorSurfaceTint,
    borderRadius: vars.radiusFull,
    flex: 1,
    height: 4,
    overflow: "hidden",
  },
  todoProgressFill: {
    backgroundColor: vars.colorAccent,
    borderRadius: vars.radiusFull,
    height: "100%",
    transitionDuration: {
      default: vars.motionDurationFast,
      "@media (prefers-reduced-motion: reduce)": "0ms",
    },
    transitionProperty: "width",
    transitionTimingFunction: vars.motionEaseStandard,
  },
  todoProgressCount: {
    color: vars.colorTextMuted,
    flexShrink: 0,
    fontSize: vars.fontSizeMicro,
    fontVariantNumeric: "tabular-nums",
  },
  itemList: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space2,
    marginInline: -8,
  },
  itemListLoose: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space12,
    marginInline: -8,
  },
  todoRow: {
    "--info-row-action-opacity": { default: "0", ":hover": "1" },
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":hover": vars.colorOverlayHover,
    },
    borderRadius: vars.radiusControl,
    display: "flex",
    gap: vars.space8,
    paddingBlock: vars.space4,
    paddingInline: vars.space8,
  },
  todoStatus: {
    alignItems: "center",
    borderRadius: vars.radiusMark,
    display: "flex",
    flexShrink: 0,
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  todoStatusPending: {
    color: { default: vars.colorTextSubtle, ":hover": vars.colorTextMuted },
  },
  todoStatusActive: { color: vars.colorAccent },
});
