import * as stylex from "@stylexjs/stylex";

import { vars } from "@/components/ads/tokens/tokens.stylex";

/** Turn summary block inside the Information panel. */
export const workspaceTurnSummaryStyles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-12"],
  },
  head: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  taskTitle: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-micro"],
    fontWeight: vars["--ads-font-weight-semibold"],
    letterSpacing: "0.08em",
    overflow: "hidden",
    textOverflow: "ellipsis",
    textTransform: "uppercase",
    whiteSpace: "nowrap",
  },
  workSummary: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
    lineHeight: vars["--ads-line-height-relaxed"],
  },
  summary: {
    alignItems: "center",
    borderRadius: vars["--ads-radius-control"],
    color: { default: vars["--ads-color-text-muted"], ":hover": vars["--ads-color-text"] },
    cursor: "pointer",
    display: "flex",
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
    gap: 6,
    listStyle: "none",
    paddingBlock: vars["--ads-space-4"],
    paddingInlineEnd: vars["--ads-space-4"],
    width: "fit-content",
    "::-webkit-details-marker": { display: "none" },
  },
  summaryChevron: {
    height: vars["--ads-control-icon-size-sm"],
    transform: "rotate(0deg)",
    transitionDuration: {
      default: vars["--ads-motion-duration-quick"],
      "@media (prefers-reduced-motion: reduce)": "0ms",
    },
    transitionProperty: "transform",
    transitionTimingFunction: vars["--ads-motion-ease-standard"],
    width: vars["--ads-control-icon-size-sm"],
  },
  summaryChevronOpen: { transform: "rotate(180deg)" },
  details: {
    borderInlineStartColor: vars["--ads-color-border-subtle"],
    borderInlineStartStyle: "solid",
    borderInlineStartWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-12"],
    marginBlockStart: vars["--ads-space-8"],
    paddingInlineStart: vars["--ads-space-12"],
  },
  entry: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  entryLabel: {
    alignItems: "center",
    color: vars["--ads-color-text-muted"],
    display: "flex",
    fontSize: vars["--ads-font-size-micro"],
    fontWeight: vars["--ads-font-weight-semibold"],
    gap: 6,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  entryIcon: {
    alignItems: "center",
    color: vars["--ads-color-text-subtle"],
    display: "flex",
    flexShrink: 0,
    height: 16,
    justifyContent: "center",
    width: 16,
  },
  entryIconGlyph: { height: vars["--ads-control-icon-size-sm"], width: vars["--ads-control-icon-size-sm"] },
  entryBody: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-body"],
    lineHeight: vars["--ads-line-height-normal"],
    paddingInlineStart: 22,
  },
  modelRow: {
    alignItems: "center",
    color: vars["--ads-color-text-muted"],
    display: "flex",
    fontSize: vars["--ads-font-size-micro"],
    gap: vars["--ads-space-8"],
    paddingInlineStart: 22,
  },
});
