import * as stylex from "@stylexjs/stylex";

import { vars } from "@/components/ads/tokens/tokens.stylex";

/** Turn summary block inside the Information panel. */
export const workspaceTurnSummaryStyles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space12,
  },
  head: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  taskTitle: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeMicro,
    fontWeight: vars.fontWeightSemibold,
    letterSpacing: "0.08em",
    overflow: "hidden",
    textOverflow: "ellipsis",
    textTransform: "uppercase",
    whiteSpace: "nowrap",
  },
  workSummary: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    lineHeight: vars.lineHeightRelaxed,
  },
  summary: {
    alignItems: "center",
    borderRadius: vars.radiusControl,
    color: { default: vars.colorTextMuted, ":hover": vars.colorText },
    cursor: "pointer",
    display: "flex",
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
    gap: 6,
    listStyle: "none",
    paddingBlock: vars.space4,
    paddingInlineEnd: vars.space4,
    width: "fit-content",
    "::-webkit-details-marker": { display: "none" },
  },
  summaryChevron: {
    height: vars.controlIconSizeSm,
    transform: "rotate(0deg)",
    transitionDuration: {
      default: vars.motionDurationQuick,
      "@media (prefers-reduced-motion: reduce)": "0ms",
    },
    transitionProperty: "transform",
    transitionTimingFunction: vars.motionEaseStandard,
    width: vars.controlIconSizeSm,
  },
  summaryChevronOpen: { transform: "rotate(180deg)" },
  details: {
    borderInlineStartColor: vars.colorBorderSubtle,
    borderInlineStartStyle: "solid",
    borderInlineStartWidth: vars.borderWidthHairline,
    display: "flex",
    flexDirection: "column",
    gap: vars.space12,
    marginBlockStart: vars.space8,
    paddingInlineStart: vars.space12,
  },
  entry: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  entryLabel: {
    alignItems: "center",
    color: vars.colorTextMuted,
    display: "flex",
    fontSize: vars.fontSizeMicro,
    fontWeight: vars.fontWeightSemibold,
    gap: 6,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  entryIcon: {
    alignItems: "center",
    color: vars.colorTextSubtle,
    display: "flex",
    flexShrink: 0,
    height: 16,
    justifyContent: "center",
    width: 16,
  },
  entryIconGlyph: { height: vars.controlIconSizeSm, width: vars.controlIconSizeSm },
  entryBody: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    lineHeight: vars.lineHeightNormal,
    paddingInlineStart: 22,
  },
  modelRow: {
    alignItems: "center",
    color: vars.colorTextMuted,
    display: "flex",
    fontSize: vars.fontSizeMicro,
    gap: vars.space8,
    paddingInlineStart: 22,
  },
});
