import * as stylex from "@stylexjs/stylex";

import { vars } from "../../ads/tokens/tokens.stylex";

const mutedSurface = (percent: number) =>
  `color-mix(in oklch, ${vars["--ads-color-canvas-subtle"]} ${percent}%, transparent)`;
const panelSurface = (percent: number) =>
  `color-mix(in oklch, ${vars["--ads-color-surface"]} ${percent}%, transparent)`;
const accent = (percent: number) =>
  `color-mix(in oklch, ${vars["--ads-color-accent"]} ${percent}%, transparent)`;

export const editorStyles = stylex.create({
  sectionHeading: { display: "grid", gap: vars["--ads-space-4"] },
  sectionHeadingRow: {
    alignItems: "center",
    display: "flex",
    gap: vars["--ads-space-12"],
    justifyContent: "space-between",
  },
  sectionTitle: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-semibold"],
    letterSpacing: "0.12em",
    margin: 0,
    textTransform: "uppercase",
  },
  sectionDetail: { color: vars["--ads-color-text-muted"], fontSize: vars["--ads-font-size-micro"] },
  sectionDescription: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-micro"],
    lineHeight: "16px",
    margin: 0,
  },

  formLabel: { display: "grid", gap: 6 },
  formLabelText: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  formLabelDescription: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-micro"],
    lineHeight: "16px",
  },

  runtimeSwitch: {
    alignItems: "center",
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    gap: vars["--ads-space-12"],
    justifyContent: "space-between",
    paddingBlock: vars["--ads-space-8"],
    paddingInline: 10,
  },
  runtimeSwitchWarning: {
    backgroundColor: vars["--ads-color-warning-soft"],
    borderColor: vars["--ads-color-warning-border"],
  },
  runtimeSwitchText: { minInlineSize: 0 },
  runtimeSwitchLabel: {
    color: vars["--ads-color-text"],
    display: "block",
    fontSize: vars["--ads-font-size-caption"],
  },
  runtimeSwitchDescription: {
    color: vars["--ads-color-text-muted"],
    display: "block",
    fontSize: vars["--ads-font-size-micro"],
    lineHeight: "16px",
    marginBlockStart: 2,
  },

  section: { display: "grid", gap: vars["--ads-space-12"] },
  chipRow: { display: "flex", flexWrap: "wrap", gap: 6 },
  cadenceChip: {
    blockSize: 28,
    borderRadius: vars["--ads-radius-full"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    fontSize: vars["--ads-font-size-micro"],
    paddingInline: 10,
  },
  cadenceChipActive: {
    backgroundColor: accent(8),
    borderColor: accent(45),
    color: vars["--ads-color-text"],
  },
  cadenceChipIdle: {
    borderColor: vars["--ads-color-border-subtle"],
    color: { default: vars["--ads-color-text-muted"], ":hover": vars["--ads-color-text"] },
  },
  checkIcon: { blockSize: 12, inlineSize: 12 },

  intervalGrid: {
    display: "grid",
    gap: vars["--ads-space-8"],
    gridTemplateColumns: "minmax(0,1fr) minmax(0,1.5fr)",
  },
  compactControl: { blockSize: 32, fontSize: vars["--ads-font-size-caption"] },
  timeControl: {
    blockSize: 32,
    fontSize: vars["--ads-font-size-caption"],
    inlineSize: 160,
  },
  concurrencyControl: {
    blockSize: 32,
    fontSize: vars["--ads-font-size-caption"],
    inlineSize: 112,
  },
  promptControl: {
    fontSize: vars["--ads-font-size-caption"],
    minBlockSize: 112,
    resize: "vertical",
  },
  repositorySelect: { blockSize: 36, fontSize: vars["--ads-font-size-caption"] },

  weekdayGroup: { display: "grid", gap: 6 },
  weekdayRow: { display: "flex", flexWrap: "wrap", gap: vars["--ads-space-4"] },
  weekdayChip: {
    blockSize: 28,
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    fontSize: vars["--ads-font-size-micro"],
    inlineSize: 40,
    paddingInline: 0,
  },

  summaryRow: {
    alignItems: "flex-start",
    backgroundColor: panelSurface(40),
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-text-muted"],
    display: "flex",
    fontSize: vars["--ads-font-size-micro"],
    gap: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: 10,
  },
  summaryIcon: {
    blockSize: 14,
    flexShrink: 0,
    inlineSize: 14,
    marginBlockStart: 2,
  },
  summaryStrong: { color: vars["--ads-color-text"] },

  modeList: { display: "grid", gap: 6 },
  modeOption: {
    alignItems: "flex-start",
    backgroundColor: { default: "transparent", ":hover": vars["--ads-color-overlay-hover"] },
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    gap: 10,
    inlineSize: "100%",
    padding: 10,
    textAlign: "left",
  },
  modeOptionActive: {
    backgroundColor: accent(8),
    borderColor: accent(50),
  },
  modeIcon: {
    blockSize: vars["--ads-control-icon-size-sm"],
    flexShrink: 0,
    inlineSize: vars["--ads-control-icon-size-sm"],
    marginBlockStart: 2,
  },
  modeIconActive: { color: vars["--ads-color-accent"] },
  modeIconIdle: { color: vars["--ads-color-text-muted"] },
  modeBody: { flexGrow: 1, minInlineSize: 0 },
  modeTitleRow: { alignItems: "center", display: "flex", gap: vars["--ads-space-8"] },
  modeTitle: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-semibold"],
  },
  modeBadge: {
    borderColor: vars["--ads-color-border-subtle"],
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-micro"],
    fontWeight: vars["--ads-font-weight-regular"],
    minBlockSize: 16,
    paddingInline: vars["--ads-space-4"],
  },
  modeRecommended: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-micro"],
    letterSpacing: "0.025em",
    textTransform: "uppercase",
  },
  modeDescription: {
    color: vars["--ads-color-text-muted"],
    display: "block",
    fontSize: vars["--ads-font-size-micro"],
    lineHeight: "16px",
    marginBlockStart: vars["--ads-space-4"],
  },

  manualPanel: {
    backgroundColor: panelSurface(30),
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    display: "grid",
    gap: vars["--ads-space-8"],
    padding: 10,
  },
  optionPair: {
    display: "grid",
    gap: vars["--ads-space-8"],
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
  },
  permissionSummary: {
    backgroundColor: mutedSurface(40),
    borderRadius: vars["--ads-radius-control"],
    color: vars["--ads-color-text-muted"],
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-micro"],
    lineHeight: "16px",
    margin: 0,
    paddingBlock: vars["--ads-space-8"],
    paddingInline: 10,
  },

  root: {
    blockSize: "100%",
    display: "flex",
    flexDirection: "column",
    minBlockSize: 0,
  },
  header: {
    alignItems: "center",
    borderBlockEndColor: vars["--ads-color-border-subtle"],
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    flexShrink: 0,
    gap: vars["--ads-space-12"],
    justifyContent: "space-between",
    paddingBlock: vars["--ads-space-12"],
    paddingInline: vars["--ads-space-20"],
  },
  headerText: { minInlineSize: 0 },
  headerTitle: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-semibold"],
  },
  headerSubtitle: { color: vars["--ads-color-text-muted"], fontSize: vars["--ads-font-size-micro"] },
  headerActions: { alignItems: "center", display: "flex", gap: 6 },
  headerButtonQuiet: {
    blockSize: 32,
    fontSize: vars["--ads-font-size-caption"],
    paddingInline: vars["--ads-space-8"],
  },
  headerButton: {
    blockSize: 32,
    fontSize: vars["--ads-font-size-caption"],
    paddingInline: vars["--ads-space-12"],
  },

  body: {
    flexGrow: 1,
    minBlockSize: 0,
    overflowY: "auto",
    paddingBlock: vars["--ads-space-16"],
    paddingInline: vars["--ads-space-20"],
  },
  bodyColumn: {
    display: "grid",
    gap: vars["--ads-space-24"],
    marginInline: "auto",
    maxInlineSize: "48rem",
  },

  providerSelect: { flexShrink: 0, inlineSize: 118 },
  effortGroup: { display: "grid", gap: 6 },

  environmentPath: {
    backgroundColor: mutedSurface(60),
    borderRadius: vars["--ads-radius-control"],
    color: vars["--ads-color-text-muted"],
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-micro"],
    overflow: "hidden",
    paddingBlock: vars["--ads-space-8"],
    paddingInline: 10,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  emptyPanel: {
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "dashed",
    borderWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    padding: vars["--ads-space-12"],
  },
  loadingNote: { color: vars["--ads-color-text-muted"], fontSize: vars["--ads-font-size-micro"] },
  referenceList: { display: "grid", gap: vars["--ads-space-8"] },
  referenceCard: {
    backgroundColor: mutedSurface(20),
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    padding: 10,
  },
  referenceDescription: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-micro"],
    lineHeight: "16px",
    marginBlockEnd: 0,
    marginBlockStart: vars["--ads-space-8"],
    overflowWrap: "break-word",
  },
  referenceToken: {
    color: vars["--ads-color-text-subtle"],
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-micro"],
    marginBlockStart: vars["--ads-space-4"],
    wordBreak: "break-all",
  },
});
