import * as stylex from "@stylexjs/stylex";

import { vars } from "../../ads/tokens/tokens.stylex";

const spin = stylex.keyframes({ to: { transform: "rotate(360deg)" } });

const mutedSurface = (percent: number) =>
  `color-mix(in oklch, ${vars["--ads-color-canvas-subtle"]} ${percent}%, transparent)`;
const canvasSurface = (percent: number) =>
  `color-mix(in oklch, ${vars["--ads-color-canvas"]} ${percent}%, transparent)`;
const accent = (percent: number) =>
  `color-mix(in oklch, ${vars["--ads-color-accent"]} ${percent}%, transparent)`;

export const centerStyles = stylex.create({
  detail: { minInlineSize: 0 },
  detailTerm: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-micro"],
    letterSpacing: "0.12em",
    textTransform: "uppercase",
  },
  detailValue: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-micro"],
    marginBlockStart: 2,
    marginInlineStart: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },

  root: {
    backgroundColor: vars["--ads-color-canvas"],
    blockSize: "100%",
    display: "flex",
    flexDirection: "column",
    minBlockSize: 0,
    overflow: "hidden",
    position: "relative",
  },

  header: {
    alignItems: "center",
    backgroundImage: `linear-gradient(110deg, color-mix(in oklch, ${vars["--ads-color-surface"]} 92%, ${vars["--ads-color-canvas"]}), ${vars["--ads-color-canvas"]})`,
    borderBlockEndColor: vars["--ads-color-border-subtle"],
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    flexShrink: 0,
    gap: vars["--ads-space-16"],
    justifyContent: "space-between",
    minBlockSize: 72,
    paddingBlock: vars["--ads-space-12"],
    paddingInline: vars["--ads-space-20"],
  },
  headerText: { minInlineSize: 0 },
  headerTitleRow: {
    alignItems: "center",
    display: "flex",
    gap: vars["--ads-space-8"],
    minInlineSize: 0,
  },
  headerIcon: {
    blockSize: 18,
    color: vars["--ads-color-text-muted"],
    flexShrink: 0,
    inlineSize: 18,
  },
  headerTitle: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-semibold"],
    letterSpacing: "-0.01em",
    margin: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerSubtitle: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    marginBlockEnd: 0,
    marginBlockStart: vars["--ads-space-4"],
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerActions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: 6,
  },
  headerButton: { blockSize: 32, fontSize: vars["--ads-font-size-caption"], gap: 6 },
  iconButton: { blockSize: 32, inlineSize: 32, padding: 0 },
  buttonIcon: { blockSize: 14, inlineSize: 14 },
  actionIcon: {
    blockSize: vars["--ads-control-icon-size-sm"],
    inlineSize: vars["--ads-control-icon-size-sm"],
  },
  actionIconSpinning: {
    animationDuration: "1s",
    animationIterationCount: "infinite",
    animationName: { default: spin, "@media (prefers-reduced-motion: reduce)": "none" },
    animationTimingFunction: "linear",
  },

  toolbar: {
    alignItems: "center",
    backgroundColor: canvasSurface(85),
    borderBlockEndColor: vars["--ads-color-border-subtle"],
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    flexShrink: 0,
    flexWrap: "wrap",
    gap: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-16"],
  },
  tabNav: { display: "flex", flexWrap: "wrap", gap: vars["--ads-space-4"] },
  toolbarNote: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    margin: 0,
  },
  filterGroup: {
    alignItems: "center",
    backgroundColor: mutedSurface(45),
    borderRadius: vars["--ads-radius-control"],
    display: "flex",
    gap: 2,
    padding: 2,
  },
  filterChip: { blockSize: 26, fontSize: vars["--ads-font-size-micro"], paddingInline: vars["--ads-space-8"] },
  filterChipActive: {
    backgroundColor: canvasSurface(85),
    borderColor: `color-mix(in oklch, ${vars["--ads-color-border"]} 55%, transparent)`,
    boxShadow: vars["--ads-elevation-raised"],
  },
  runSelect: { blockSize: 28, fontSize: vars["--ads-font-size-micro"], inlineSize: 224 },
  shownCount: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-micro"],
    marginInlineStart: "auto",
  },

  errorBanner: {
    alignItems: "flex-start",
    backgroundColor: vars["--ads-color-danger-soft"],
    borderColor: vars["--ads-color-danger-border"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-danger-text"],
    display: "flex",
    flexShrink: 0,
    fontSize: vars["--ads-font-size-caption"],
    gap: vars["--ads-space-8"],
    marginBlockStart: vars["--ads-space-12"],
    marginInline: vars["--ads-space-16"],
    padding: vars["--ads-space-12"],
  },
  errorIcon: {
    blockSize: 14,
    flexShrink: 0,
    inlineSize: 14,
    marginBlockStart: 2,
  },

  loadingPane: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    flexGrow: 1,
    gap: vars["--ads-space-16"],
    justifyContent: "center",
    minBlockSize: 0,
    paddingBlock: vars["--ads-space-40"],
    paddingInline: vars["--ads-space-24"],
    textAlign: "center",
  },
  loadingOrb: {
    backgroundColor: mutedSurface(45),
    blockSize: 80,
    borderRadius: vars["--ads-radius-full"],
    boxShadow: `0 0 0 1px ${vars["--ads-color-border-subtle"]}`,
    display: "grid",
    inlineSize: 80,
    placeItems: "center",
  },
  loadingTitle: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-semibold"],
    margin: 0,
  },
  loadingHint: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    marginBlockEnd: 0,
    marginBlockStart: vars["--ads-space-4"],
  },

  emptyPane: { borderWidth: 0, flexGrow: 1, minBlockSize: 0 },
  emptyPaneFull: { blockSize: "100%", borderWidth: 0 },

  masterDetail: {
    display: "grid",
    flexGrow: 1,
    gridTemplateColumns: {
      default: "repeat(1, minmax(0, 1fr))",
      "@media (min-width: 48rem)": "minmax(240px, 300px) minmax(0, 1fr)",
    },
    minBlockSize: 0,
    overflow: "hidden",
  },
  runsMasterDetail: {
    display: "grid",
    flexGrow: 1,
    gridTemplateColumns: {
      default: "repeat(1, minmax(0, 1fr))",
      "@media (min-width: 48rem)": "minmax(260px, 340px) minmax(0, 1fr)",
    },
    minBlockSize: 0,
    overflow: "hidden",
  },
  masterColumn: {
    borderInlineEndColor: vars["--ads-color-border-subtle"],
    borderInlineEndStyle: "solid",
    borderInlineEndWidth: vars["--ads-border-width-hairline"],
    display: { default: "none", "@media (min-width: 48rem)": "flex" },
    flexDirection: "column",
    minBlockSize: 0,
    overflowY: "auto",
    padding: vars["--ads-space-12"],
  },
  runsMasterColumn: {
    borderBlockEndColor: vars["--ads-color-border-subtle"],
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: {
      default: vars["--ads-border-width-hairline"],
      "@media (min-width: 48rem)": 0,
    },
    borderInlineEndColor: vars["--ads-color-border-subtle"],
    borderInlineEndStyle: "solid",
    borderInlineEndWidth: {
      default: 0,
      "@media (min-width: 48rem)": vars["--ads-border-width-hairline"],
    },
    minBlockSize: 0,
    overflowY: "auto",
    padding: vars["--ads-space-12"],
  },
  cardList: { display: "grid", gap: vars["--ads-space-8"] },
  routineCard: {
    backgroundColor: { default: "transparent", ":hover": vars["--ads-color-overlay-hover"] },
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    inlineSize: "100%",
    padding: 10,
    textAlign: "left",
  },
  routineCardActive: {
    backgroundColor: accent(8),
    borderColor: accent(50),
  },
  routineCardHead: { alignItems: "center", display: "flex", gap: vars["--ads-space-8"] },
  routineDot: {
    blockSize: 8,
    borderRadius: vars["--ads-radius-full"],
    flexShrink: 0,
    inlineSize: 8,
  },
  routineDotOn: { backgroundColor: vars["--ads-color-success"] },
  routineDotOff: { backgroundColor: vars["--ads-color-text-muted"] },
  routineName: {
    color: vars["--ads-color-text"],
    flexGrow: 1,
    flexShrink: 1,
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-semibold"],
    minInlineSize: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  routineMeta: {
    alignItems: "center",
    color: vars["--ads-color-text-muted"],
    display: "flex",
    fontSize: vars["--ads-font-size-micro"],
    gap: vars["--ads-space-8"],
    justifyContent: "space-between",
    marginBlockStart: vars["--ads-space-4"],
  },
  routineMetaText: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  routineMetaModel: {
    flexShrink: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },

  detailColumn: { minBlockSize: 0, overflowY: "auto" },
  compactPicker: {
    borderBlockEndColor: vars["--ads-color-border-subtle"],
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: vars["--ads-border-width-hairline"],
    display: { default: "block", "@media (min-width: 48rem)": "none" },
    padding: vars["--ads-space-12"],
  },
  compactSelect: { blockSize: 32, fontSize: vars["--ads-font-size-caption"] },

  detailBody: {
    display: "grid",
    gap: vars["--ads-space-16"],
    paddingBlock: vars["--ads-space-16"],
    paddingInline: vars["--ads-space-20"],
  },
  detailHeadRow: {
    alignItems: "flex-start",
    display: "flex",
    gap: vars["--ads-space-12"],
    justifyContent: "space-between",
  },
  detailHeadText: { minInlineSize: 0 },
  detailTitle: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-semibold"],
    margin: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  detailPrompt: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-control"],
    marginBlockEnd: 0,
    marginBlockStart: vars["--ads-space-4"],
    whiteSpace: "pre-wrap",
  },
  detailActions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: 6,
  },
  facts: {
    backgroundColor: `color-mix(in oklch, ${vars["--ads-color-surface"]} 30%, transparent)`,
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    columnGap: vars["--ads-space-16"],
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (min-width: 40rem)": "repeat(4, minmax(0, 1fr))",
    },
    margin: 0,
    padding: vars["--ads-space-12"],
    rowGap: vars["--ads-space-12"],
  },
  footerActions: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: vars["--ads-space-8"],
  },
  runCount: {
    color: vars["--ads-color-text-muted"],
    fontVariantNumeric: "tabular-nums",
  },
  deleteButton: {
    blockSize: 32,
    color: { default: vars["--ads-color-danger-text"], ":hover": vars["--ads-color-danger-text"] },
    fontSize: vars["--ads-font-size-caption"],
    gap: 6,
    marginInlineStart: "auto",
  },
  placeholder: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-caption"],
    padding: vars["--ads-space-24"],
  },
  runsDetailColumn: { minBlockSize: 0, overflow: "hidden" },
});
