import * as stylex from "@stylexjs/stylex";

import { vars } from "../../ads/tokens/tokens.stylex";

export const runDetailStyles = stylex.create({
  row: {
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    inlineSize: "100%",
    padding: 10,
    textAlign: "left",
    backgroundColor: { default: "transparent", ":hover": vars["--ads-color-overlay-hover"] },
  },
  rowActive: {
    backgroundColor: vars["--ads-color-selection-fill"],
    borderColor: vars["--ads-color-accent"],
  },
  rowHead: { alignItems: "center", display: "flex", gap: vars["--ads-space-8"] },
  rowName: {
    color: vars["--ads-color-text"],
    flexGrow: 1,
    flexShrink: 1,
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-semibold"],
    minInlineSize: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowMeta: {
    alignItems: "center",
    color: vars["--ads-color-text-muted"],
    display: "flex",
    fontSize: vars["--ads-font-size-micro"],
    gap: vars["--ads-space-8"],
    justifyContent: "space-between",
    marginBlockStart: vars["--ads-space-4"],
  },

  detailCell: { minInlineSize: 0 },
  detailTerm: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-micro"],
    letterSpacing: "0.12em",
    textTransform: "uppercase",
  },
  detailValue: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-micro"],
    marginBlockStart: 2,
    marginInlineStart: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  detailValueMono: { fontFamily: vars["--ads-font-mono"] },

  root: {
    blockSize: "100%",
    display: "flex",
    flexDirection: "column",
    minBlockSize: 0,
  },
  header: {
    borderBlockEndColor: vars["--ads-color-border-subtle"],
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: vars["--ads-border-width-hairline"],
    flexShrink: 0,
    paddingBlock: vars["--ads-space-12"],
    paddingInline: vars["--ads-space-20"],
  },
  headerRow: {
    alignItems: "flex-start",
    display: "flex",
    gap: vars["--ads-space-12"],
    justifyContent: "space-between",
  },
  headerMain: { minInlineSize: 0 },
  headerTitleRow: {
    alignItems: "center",
    display: "flex",
    gap: vars["--ads-space-8"],
    minInlineSize: 0,
  },
  headerTitle: {
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-semibold"],
    margin: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerSub: {
    color: vars["--ads-color-text-muted"],
    fontSize: vars["--ads-font-size-micro"],
    marginBlockEnd: 0,
    marginBlockStart: vars["--ads-space-4"],
  },
  headerActions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: 6,
  },
  headerButton: {
    blockSize: 32,
    fontSize: vars["--ads-font-size-caption"],
    gap: 6,
  },
  buttonIcon: { blockSize: 14, inlineSize: 14 },

  body: {
    flexGrow: 1,
    minBlockSize: 0,
    overflowY: "auto",
    paddingBlock: vars["--ads-space-16"],
    paddingInline: vars["--ads-space-20"],
  },
  bodyGrid: { display: "grid", gap: vars["--ads-space-16"] },
  facts: {
    backgroundColor: vars["--ads-color-surface-tint"],
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    columnGap: vars["--ads-space-16"],
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (min-width: 40rem)": "repeat(3, minmax(0, 1fr))",
    },
    margin: 0,
    padding: vars["--ads-space-12"],
    rowGap: vars["--ads-space-12"],
  },
  executionRow: {
    alignItems: "center",
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    display: "flex",
    gap: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
  },
  executionId: {
    color: vars["--ads-color-text"],
    flexGrow: 1,
    flexShrink: 1,
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-micro"],
    minInlineSize: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  section: { display: "grid", gap: vars["--ads-space-8"] },
  prose: {
    borderColor: vars["--ads-color-border-subtle"],
    borderRadius: vars["--ads-radius-control"],
    borderStyle: "solid",
    borderWidth: vars["--ads-border-width-hairline"],
    fontSize: vars["--ads-font-size-micro"],
    lineHeight: vars["--ads-line-height-control"],
    margin: 0,
    padding: vars["--ads-space-12"],
    whiteSpace: "pre-wrap",
  },
  proseSkipped: {
    backgroundColor: vars["--ads-color-canvas-subtle"],
    color: vars["--ads-color-text-muted"],
  },
  proseError: {
    backgroundColor: vars["--ads-color-danger-soft"],
    borderColor: vars["--ads-color-danger-border"],
    color: vars["--ads-color-danger-text"],
  },
  proseResult: {
    backgroundColor: vars["--ads-color-canvas"],
    color: vars["--ads-color-text"],
  },
  proseInstructions: {
    backgroundColor: vars["--ads-color-surface-tint"],
    color: vars["--ads-color-text-muted"],
  },
  proseEmpty: {
    borderColor: vars["--ads-color-border"],
    borderStyle: "dashed",
    color: vars["--ads-color-text-muted"],
    whiteSpace: "normal",
  },
});
