import * as stylex from "@stylexjs/stylex";

import { vars } from "../../ads/tokens/tokens.stylex";

const spin = stylex.keyframes({ to: { transform: "rotate(360deg)" } });

const mutedSurface = (percent: number) =>
  `color-mix(in oklch, ${vars.colorCanvasSubtle} ${percent}%, transparent)`;
const canvasSurface = (percent: number) =>
  `color-mix(in oklch, ${vars.colorCanvas} ${percent}%, transparent)`;
const accent = (percent: number) =>
  `color-mix(in oklch, ${vars.colorAccent} ${percent}%, transparent)`;

export const centerStyles = stylex.create({
  detail: { minInlineSize: 0 },
  detailTerm: {
    color: vars.colorTextMuted,
    fontSize: 9,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
  },
  detailValue: {
    color: vars.colorText,
    fontSize: 11,
    marginBlockStart: 2,
    marginInlineStart: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },

  root: {
    backgroundColor: vars.colorCanvas,
    blockSize: "100%",
    display: "flex",
    flexDirection: "column",
    minBlockSize: 0,
    overflow: "hidden",
    position: "relative",
  },

  header: {
    alignItems: "center",
    backgroundImage: `linear-gradient(110deg, color-mix(in oklch, ${vars.colorSurface} 92%, ${vars.colorCanvas}), ${vars.colorCanvas})`,
    borderBlockEndColor: vars.colorBorderSubtle,
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: vars.borderWidthHairline,
    display: "flex",
    flexShrink: 0,
    gap: vars.space16,
    justifyContent: "space-between",
    minBlockSize: 72,
    paddingBlock: vars.space12,
    paddingInline: vars.space20,
  },
  headerText: { minInlineSize: 0 },
  headerTitleRow: {
    alignItems: "center",
    display: "flex",
    gap: vars.space8,
    minInlineSize: 0,
  },
  headerIcon: {
    blockSize: 18,
    color: vars.colorAccent,
    flexShrink: 0,
    inlineSize: 18,
  },
  headerTitle: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightSemibold,
    letterSpacing: "-0.01em",
    margin: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerSubtitle: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    marginBlockEnd: 0,
    marginBlockStart: vars.space4,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerActions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: 6,
  },
  headerButton: { blockSize: 32, fontSize: vars.fontSizeCaption, gap: 6 },
  iconButton: { blockSize: 32, inlineSize: 32, padding: 0 },
  buttonIcon: { blockSize: 14, inlineSize: 14 },
  actionIcon: {
    blockSize: vars.controlIconSizeSm,
    inlineSize: vars.controlIconSizeSm,
  },
  actionIconSpinning: {
    animationDuration: "1s",
    animationIterationCount: "infinite",
    animationName: { default: spin, "@media (prefers-reduced-motion: reduce)": "none" },
    animationTimingFunction: "linear",
  },

  toolbar: {
    alignItems: "center",
    backgroundColor: canvasSurface(85),
    borderBlockEndColor: vars.colorBorderSubtle,
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: vars.borderWidthHairline,
    display: "flex",
    flexShrink: 0,
    flexWrap: "wrap",
    gap: vars.space8,
    paddingBlock: vars.space8,
    paddingInline: vars.space16,
  },
  tabNav: { display: "flex", flexWrap: "wrap", gap: vars.space4 },
  toolbarNote: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    margin: 0,
  },
  filterGroup: {
    alignItems: "center",
    backgroundColor: mutedSurface(45),
    borderRadius: vars.radiusControl,
    display: "flex",
    gap: 2,
    padding: 2,
  },
  filterChip: { blockSize: 26, fontSize: 11, paddingInline: vars.space8 },
  filterChipActive: {
    backgroundColor: canvasSurface(85),
    borderColor: `color-mix(in oklch, ${vars.colorBorder} 55%, transparent)`,
    boxShadow: vars.elevationRaised,
  },
  runSelect: { blockSize: 28, fontSize: 11, inlineSize: 224 },
  shownCount: {
    color: vars.colorTextMuted,
    fontSize: 11,
    marginInlineStart: "auto",
  },

  errorBanner: {
    alignItems: "flex-start",
    backgroundColor: vars.colorDangerSoft,
    borderColor: vars.colorDangerBorder,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    color: vars.colorDangerText,
    display: "flex",
    flexShrink: 0,
    fontSize: vars.fontSizeCaption,
    gap: vars.space8,
    marginBlockStart: vars.space12,
    marginInline: vars.space16,
    padding: vars.space12,
  },
  errorIcon: {
    blockSize: 14,
    flexShrink: 0,
    inlineSize: 14,
    marginBlockStart: 2,
  },

  libraryPane: {
    flexGrow: 1,
    minBlockSize: 0,
    overflowY: "auto",
    padding: vars.space20,
  },
  libraryColumn: { marginInline: "auto", maxInlineSize: "48rem" },

  loadingPane: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    flexGrow: 1,
    gap: vars.space16,
    justifyContent: "center",
    minBlockSize: 0,
    paddingBlock: vars.space40,
    paddingInline: vars.space24,
    textAlign: "center",
  },
  loadingOrb: {
    backgroundColor: mutedSurface(45),
    blockSize: 80,
    borderRadius: vars.radiusFull,
    boxShadow: `0 0 0 1px ${vars.colorBorderSubtle}`,
    display: "grid",
    inlineSize: 80,
    placeItems: "center",
  },
  loadingTitle: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightSemibold,
    margin: 0,
  },
  loadingHint: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    marginBlockEnd: 0,
    marginBlockStart: vars.space4,
  },

  emptyPane: { borderWidth: 0, flexGrow: 1, minBlockSize: 0 },
  emptyPaneFull: { blockSize: "100%", borderWidth: 0 },

  masterDetail: {
    display: "grid",
    flexGrow: 1,
    gridTemplateColumns: {
      default: "repeat(1, minmax(0, 1fr))",
      "@media (min-width: 48rem)": "minmax(240px, 300px) minmax(0, 1fr)",
    },
    minBlockSize: 0,
    overflow: "hidden",
  },
  runsMasterDetail: {
    display: "grid",
    flexGrow: 1,
    gridTemplateColumns: {
      default: "repeat(1, minmax(0, 1fr))",
      "@media (min-width: 48rem)": "minmax(260px, 340px) minmax(0, 1fr)",
    },
    minBlockSize: 0,
    overflow: "hidden",
  },
  masterColumn: {
    borderInlineEndColor: vars.colorBorderSubtle,
    borderInlineEndStyle: "solid",
    borderInlineEndWidth: vars.borderWidthHairline,
    display: { default: "none", "@media (min-width: 48rem)": "flex" },
    flexDirection: "column",
    minBlockSize: 0,
    overflowY: "auto",
    padding: vars.space12,
  },
  runsMasterColumn: {
    borderBlockEndColor: vars.colorBorderSubtle,
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: {
      default: vars.borderWidthHairline,
      "@media (min-width: 48rem)": 0,
    },
    borderInlineEndColor: vars.colorBorderSubtle,
    borderInlineEndStyle: "solid",
    borderInlineEndWidth: {
      default: 0,
      "@media (min-width: 48rem)": vars.borderWidthHairline,
    },
    minBlockSize: 0,
    overflowY: "auto",
    padding: vars.space12,
  },
  cardList: { display: "grid", gap: vars.space8 },
  routineCard: {
    backgroundColor: { default: "transparent", ":hover": vars.colorOverlayHover },
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    inlineSize: "100%",
    padding: 10,
    textAlign: "left",
  },
  routineCardActive: {
    backgroundColor: accent(8),
    borderColor: accent(50),
  },
  routineCardHead: { alignItems: "center", display: "flex", gap: vars.space8 },
  routineDot: {
    blockSize: 8,
    borderRadius: vars.radiusFull,
    flexShrink: 0,
    inlineSize: 8,
  },
  routineDotOn: { backgroundColor: vars.colorSuccess },
  routineDotOff: { backgroundColor: vars.colorTextMuted },
  routineName: {
    color: vars.colorText,
    flexGrow: 1,
    flexShrink: 1,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightSemibold,
    minInlineSize: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  routineMeta: {
    alignItems: "center",
    color: vars.colorTextMuted,
    display: "flex",
    fontSize: 10,
    gap: vars.space8,
    justifyContent: "space-between",
    marginBlockStart: vars.space4,
  },
  routineMetaText: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  routineMetaModel: {
    flexShrink: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },

  detailColumn: { minBlockSize: 0, overflowY: "auto" },
  compactPicker: {
    borderBlockEndColor: vars.colorBorderSubtle,
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: vars.borderWidthHairline,
    display: { default: "block", "@media (min-width: 48rem)": "none" },
    padding: vars.space12,
  },
  compactSelect: { blockSize: 32, fontSize: vars.fontSizeCaption },

  detailBody: {
    display: "grid",
    gap: vars.space16,
    paddingBlock: vars.space16,
    paddingInline: vars.space20,
  },
  detailHeadRow: {
    alignItems: "flex-start",
    display: "flex",
    gap: vars.space12,
    justifyContent: "space-between",
  },
  detailHeadText: { minInlineSize: 0 },
  detailTitle: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightSemibold,
    margin: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  detailPrompt: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightControl,
    marginBlockEnd: 0,
    marginBlockStart: vars.space4,
    whiteSpace: "pre-wrap",
  },
  detailActions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: 6,
  },
  facts: {
    backgroundColor: `color-mix(in oklch, ${vars.colorSurface} 30%, transparent)`,
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    columnGap: vars.space16,
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (min-width: 40rem)": "repeat(4, minmax(0, 1fr))",
    },
    margin: 0,
    padding: vars.space12,
    rowGap: vars.space12,
  },
  footerActions: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: vars.space8,
  },
  runCount: {
    color: vars.colorTextMuted,
    fontVariantNumeric: "tabular-nums",
  },
  deleteButton: {
    blockSize: 32,
    color: { default: vars.colorDangerText, ":hover": vars.colorDangerText },
    fontSize: vars.fontSizeCaption,
    gap: 6,
    marginInlineStart: "auto",
  },
  placeholder: {
    color: vars.colorTextMuted,
    fontSize: vars.fontSizeCaption,
    padding: vars.space24,
  },
  runsDetailColumn: { minBlockSize: 0, overflow: "hidden" },
});
