import * as stylex from "@stylexjs/stylex";

import { vars } from "../../ads/tokens/tokens.stylex";

export const runDetailStyles = stylex.create({
  row: {
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    inlineSize: "100%",
    padding: 10,
    textAlign: "left",
    backgroundColor: { default: "transparent", ":hover": vars.colorOverlayHover },
  },
  rowActive: {
    backgroundColor: vars.colorSelectionFill,
    borderColor: vars.colorAccent,
  },
  rowHead: { alignItems: "center", display: "flex", gap: vars.space8 },
  rowName: {
    color: vars.colorText,
    flexGrow: 1,
    flexShrink: 1,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightSemibold,
    minInlineSize: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowMeta: {
    alignItems: "center",
    color: vars.colorTextMuted,
    display: "flex",
    fontSize: 10,
    gap: vars.space8,
    justifyContent: "space-between",
    marginBlockStart: vars.space4,
  },

  detailCell: { minInlineSize: 0 },
  detailTerm: {
    color: vars.colorTextMuted,
    fontSize: 9,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
  },
  detailValue: {
    color: vars.colorText,
    fontSize: 11,
    marginBlockStart: 2,
    marginInlineStart: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  detailValueMono: { fontFamily: vars.fontMono },

  root: {
    blockSize: "100%",
    display: "flex",
    flexDirection: "column",
    minBlockSize: 0,
  },
  header: {
    borderBlockEndColor: vars.colorBorderSubtle,
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: vars.borderWidthHairline,
    flexShrink: 0,
    paddingBlock: vars.space12,
    paddingInline: vars.space20,
  },
  headerRow: {
    alignItems: "flex-start",
    display: "flex",
    gap: vars.space12,
    justifyContent: "space-between",
  },
  headerMain: { minInlineSize: 0 },
  headerTitleRow: {
    alignItems: "center",
    display: "flex",
    gap: vars.space8,
    minInlineSize: 0,
  },
  headerTitle: {
    color: vars.colorText,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightSemibold,
    margin: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerSub: {
    color: vars.colorTextMuted,
    fontSize: 11,
    marginBlockEnd: 0,
    marginBlockStart: vars.space4,
  },
  headerActions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: 6,
  },
  headerButton: {
    blockSize: 32,
    fontSize: vars.fontSizeCaption,
    gap: 6,
  },
  buttonIcon: { blockSize: 14, inlineSize: 14 },

  body: {
    flexGrow: 1,
    minBlockSize: 0,
    overflowY: "auto",
    paddingBlock: vars.space16,
    paddingInline: vars.space20,
  },
  bodyGrid: { display: "grid", gap: vars.space16 },
  facts: {
    backgroundColor: vars.colorSurfaceTint,
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    columnGap: vars.space16,
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (min-width: 40rem)": "repeat(3, minmax(0, 1fr))",
    },
    margin: 0,
    padding: vars.space12,
    rowGap: vars.space12,
  },
  executionRow: {
    alignItems: "center",
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    display: "flex",
    gap: vars.space8,
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
  },
  executionId: {
    color: vars.colorText,
    flexGrow: 1,
    flexShrink: 1,
    fontFamily: vars.fontMono,
    fontSize: 11,
    minInlineSize: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  section: { display: "grid", gap: vars.space8 },
  prose: {
    borderColor: vars.colorBorderSubtle,
    borderRadius: vars.radiusControl,
    borderStyle: "solid",
    borderWidth: vars.borderWidthHairline,
    fontSize: 11,
    lineHeight: vars.lineHeightControl,
    margin: 0,
    padding: vars.space12,
    whiteSpace: "pre-wrap",
  },
  proseSkipped: {
    backgroundColor: vars.colorCanvasSubtle,
    color: vars.colorTextMuted,
  },
  proseError: {
    backgroundColor: vars.colorDangerSoft,
    borderColor: vars.colorDangerBorder,
    color: vars.colorDangerText,
  },
  proseResult: {
    backgroundColor: vars.colorCanvas,
    color: vars.colorText,
  },
  proseInstructions: {
    backgroundColor: vars.colorSurfaceTint,
    color: vars.colorTextMuted,
  },
  proseEmpty: {
    borderColor: vars.colorBorder,
    borderStyle: "dashed",
    color: vars.colorTextMuted,
    whiteSpace: "normal",
  },
});
