import * as stylex from "@stylexjs/stylex";

import { vars } from "@/components/ads/tokens/tokens.stylex";

export const terminalSurfacePanelStyles = stylex.create({
  root: {
    backgroundColor: vars["--ads-color-canvas"],
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
  },
  header: {
    alignItems: "center",
    borderBottomColor: vars["--ads-color-border-subtle"],
    borderBottomStyle: "solid",
    borderBottomWidth: vars["--ads-border-width-hairline"],
    color: vars["--ads-color-text-muted"],
    display: "flex",
    flexShrink: 0,
    fontSize: vars["--ads-font-size-caption"],
    gap: vars["--ads-space-8"],
    height: 32,
    paddingInline: vars["--ads-space-12"],
  },
  headerIcon: { flexShrink: 0, height: 14, width: 14 },
  headerPath: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  status: {
    flexShrink: 0,
    fontSize: vars["--ads-font-size-micro"],
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  statusExited: { color: vars["--ads-color-text-subtle"], fontWeight: vars["--ads-font-weight-medium"] },
  statusExitedFailed: { color: vars["--ads-color-danger"], fontWeight: vars["--ads-font-weight-medium"] },
  statusShell: { color: vars["--ads-color-info-text"] },
  statusLive: { color: vars["--ads-color-success-text"] },
  clearButton: { color: vars["--ads-color-text-muted"], flexShrink: 0 },
  restartButton: { color: vars["--ads-color-warning-text"], fontSize: vars["--ads-font-size-micro"] },
  notice: {
    borderBottomStyle: "solid",
    borderBottomWidth: vars["--ads-border-width-hairline"],
    fontSize: vars["--ads-font-size-caption"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
  },
  noticeDanger: {
    backgroundColor: vars["--ads-color-danger-soft"],
    borderBottomColor: vars["--ads-color-danger-border"],
    color: vars["--ads-color-danger-text"],
  },
  noticeWarning: {
    alignItems: "center",
    backgroundColor: vars["--ads-color-warning-soft"],
    borderBottomColor: vars["--ads-color-warning-border"],
    color: vars["--ads-color-warning-text"],
    display: "flex",
    gap: vars["--ads-space-12"],
    justifyContent: "space-between",
  },
  loadingOverlay: {
    alignItems: "center",
    backgroundColor: "var(--terminal)",
    display: "flex",
    inset: 0,
    justifyContent: "center",
    position: "absolute",
    zIndex: vars["--ads-z-index-panel"],
  },
  loadingLabel: {
    alignItems: "center",
    color: vars["--ads-color-text-muted"],
    display: "flex",
    fontSize: vars["--ads-font-size-body"],
    gap: vars["--ads-space-8"],
  },
});
