import * as stylex from "@stylexjs/stylex";

import { vars } from "@/components/ads/tokens/tokens.stylex";

export const terminalSurfacePanelStyles = stylex.create({
  root: {
    backgroundColor: vars.colorCanvas,
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
  },
  header: {
    alignItems: "center",
    borderBottomColor: vars.colorBorderSubtle,
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    color: vars.colorTextMuted,
    display: "flex",
    flexShrink: 0,
    fontSize: vars.fontSizeCaption,
    gap: vars.space8,
    height: 32,
    paddingInline: vars.space12,
  },
  headerIcon: { flexShrink: 0, height: 14, width: 14 },
  headerPath: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  status: {
    flexShrink: 0,
    fontSize: 11,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  statusExited: { color: vars.colorTextSubtle, fontWeight: vars.fontWeightMedium },
  statusExitedFailed: { color: vars.colorDanger, fontWeight: vars.fontWeightMedium },
  statusShell: { color: vars.colorInfoText },
  statusLive: { color: vars.colorSuccessText },
  clearButton: { color: vars.colorTextMuted, flexShrink: 0 },
  restartButton: { color: vars.colorWarningText, fontSize: 11 },
  notice: {
    borderBottomStyle: "solid",
    borderBottomWidth: vars.borderWidthHairline,
    fontSize: vars.fontSizeCaption,
    paddingBlock: vars.space8,
    paddingInline: vars.space12,
  },
  noticeDanger: {
    backgroundColor: vars.colorDangerSoft,
    borderBottomColor: vars.colorDangerBorder,
    color: vars.colorDangerText,
  },
  noticeWarning: {
    alignItems: "center",
    backgroundColor: vars.colorWarningSoft,
    borderBottomColor: vars.colorWarningBorder,
    color: vars.colorWarningText,
    display: "flex",
    gap: vars.space12,
    justifyContent: "space-between",
  },
  loadingOverlay: {
    alignItems: "center",
    backgroundColor: "var(--terminal)",
    display: "flex",
    inset: 0,
    justifyContent: "center",
    position: "absolute",
    zIndex: vars.zIndexPanel,
  },
  loadingLabel: {
    alignItems: "center",
    color: vars.colorTextMuted,
    display: "flex",
    fontSize: vars.fontSizeBody,
    gap: vars.space8,
  },
});
