import * as stylex from "@stylexjs/stylex";
import { focusRing } from "../../../ads/recipes/focus-ring";
import { transition } from "../../../ads/recipes/transition";
import { vars } from "../../../ads/tokens/tokens.stylex";

export { focusRing, transition };

const diagnosticGrid =
  "4.5rem 4rem 4.5rem minmax(8rem, 1fr) 5.5rem 4.5rem 4.5rem 5rem";

export const workbenchStyles = stylex.create({
  surface: {
    display: "flex",
    height: "100%",
    minHeight: 0,
    flexDirection: "column",
    backgroundColor: vars.colorCanvas,
  },
  toolbar: {
    display: "flex",
    flexShrink: 0,
    flexWrap: "wrap",
    alignItems: "center",
    gap: vars.space8,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: vars.colorBorderSubtle,
    padding: vars.space8,
  },
  search: { position: "relative", minWidth: "9rem", flex: 1 },
  networkSearch: { minWidth: "10rem" },
  searchIcon: {
    pointerEvents: "none",
    position: "absolute",
    left: vars.space8,
    top: "50%",
    width: 14,
    height: 14,
    transform: "translateY(-50%)",
    color: vars.colorTextMuted,
  },
  searchInput: { height: 28, paddingLeft: 28, fontSize: vars.fontSizeCaption },
  filters: {
    display: "flex",
    alignItems: "center",
    gap: vars.space4,
    overflowX: "auto",
  },
  toolbarButton: {
    height: 28,
    paddingInline: vars.space8,
    fontSize: vars.fontSizeMicro,
  },
  icon: { width: 14, height: 14 },
  workbench: {
    display: "flex",
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: "row",
  },
  entryList: {
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    overflow: "auto",
    fontSize: vars.fontSizeCaption,
  },
  consoleList: { fontFamily: vars.fontMono },
  entryRows: { display: "flex", flexDirection: "column" },
  entryRow: {
    display: "grid",
    width: "100%",
    gridTemplateColumns: "4.5rem 4.25rem minmax(0, 1fr)",
    gap: vars.space8,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: vars.colorBorder,
    paddingInline: vars.space12,
    paddingBlock: vars.space8,
    backgroundColor: {
      default: "transparent",
      ":hover": vars.colorSurfaceTint,
    },
    color: vars.colorText,
    textAlign: "left",
  },
  selectedEntryRow: {
    backgroundColor: vars.colorAccentSoft,
    color: vars.colorText,
  },
  time: { fontSize: vars.fontSizeMicro, color: vars.colorTextMuted },
  entryContent: { minWidth: 0 },
  entryText: {
    display: "block",
    overflowWrap: "break-word",
    whiteSpace: "pre-wrap",
    color: vars.colorText,
  },
  entrySource: {
    display: "block",
    marginTop: vars.space4,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "10px",
    color: vars.colorTextMuted,
  },
  empty: {
    display: "flex",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    padding: vars.space16,
    fontSize: vars.fontSizeCaption,
    color: vars.colorTextMuted,
  },
  pre: {
    maxHeight: "16rem",
    overflow: "auto",
    overflowWrap: "break-word",
    whiteSpace: "pre-wrap",
  },
  compactStack: { display: "flex", flexDirection: "column", gap: 6 },
  stack: { display: "flex", flexDirection: "column", gap: vars.space12 },
  stackFrame: {
    borderRadius: vars.radiusControl,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: vars.colorBorderSubtle,
    backgroundColor: vars.colorCanvas,
    paddingInline: vars.space8,
    paddingBlock: 6,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeMicro,
  },
  stackFrameHeader: {
    display: "flex",
    minWidth: 0,
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: vars.space12,
  },
  stackFrameName: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontWeight: vars.fontWeightMedium,
    color: vars.colorText,
  },
  stackFrameDescription: {
    flexShrink: 0,
    fontSize: "10px",
    color: vars.colorTextMuted,
  },
  stackFrameLocation: {
    marginTop: 2,
    overflowWrap: "break-word",
    fontSize: "10px",
    color: vars.colorTextMuted,
  },
  detailsGrid: { display: "grid", gap: vars.space12 },
  networkTable: { minWidth: "700px" },
  networkHeading: {
    display: "grid",
    gridTemplateColumns: diagnosticGrid,
    gap: vars.space8,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: vars.colorBorder,
    paddingInline: vars.space12,
    paddingBlock: vars.space8,
    fontSize: "10px",
    fontWeight: vars.fontWeightMedium,
    textTransform: "uppercase",
    color: vars.colorTextMuted,
  },
  networkRow: {
    display: "grid",
    width: "100%",
    alignItems: "center",
    gridTemplateColumns: diagnosticGrid,
    gap: vars.space8,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: vars.colorBorder,
    paddingInline: vars.space12,
    paddingBlock: vars.space8,
    backgroundColor: {
      default: "transparent",
      ":hover": vars.colorSurfaceTint,
    },
    color: vars.colorText,
    textAlign: "left",
  },
  mono: { fontFamily: vars.fontMono, fontSize: vars.fontSizeMicro },
  monoMuted: {
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeMicro,
    color: vars.colorTextMuted,
  },
  medium: { fontWeight: vars.fontWeightMedium },
  semibold: { fontWeight: vars.fontWeightSemibold },
  truncation: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  statusMuted: { color: vars.colorTextMuted },
  statusDanger: { color: vars.colorDangerText },
  statusWarning: { color: vars.colorWarningText },
  statusInfo: { color: vars.colorInfoText },
  statusSuccess: { color: vars.colorSuccessText },
  breakWords: { overflowWrap: "break-word" },
  definitionList: {
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr)",
    columnGap: vars.space12,
    rowGap: vars.space4,
  },
  definitionTerm: { color: vars.colorTextMuted },
  list: { display: "flex", flexDirection: "column", gap: vars.space4 },
  previewHost: { position: "absolute", inset: 0, padding: vars.space12 },
  runtimeEmpty: {
    height: "100%",
    justifyContent: "center",
    borderRadius: vars.radiusPanel,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: vars.colorBorderSubtle,
    backgroundColor: vars.colorCanvas,
    padding: vars.space24,
  },
  runtimeCopy: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space4,
    fontSize: vars.fontSizeCaption,
    color: vars.colorTextMuted,
  },
  overlay: {
    pointerEvents: "auto",
    position: "absolute",
    inset: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    overflow: "auto",
    backgroundColor: vars.colorCanvas,
    padding: vars.space24,
    color: vars.colorText,
  },
  onboarding: {
    width: "100%",
    maxWidth: "28rem",
    marginBlock: "auto",
    display: "flex",
    flexDirection: "column",
    gap: vars.space16,
  },
  onboardingIcon: { width: 24, height: 24, color: vars.colorAccent },
  onboardingTitle: {
    fontSize: vars.fontSizeHeading,
    fontWeight: vars.fontWeightSemibold,
  },
  onboardingCopy: {
    fontSize: vars.fontSizeBody,
    lineHeight: vars.lineHeightRelaxed,
    color: vars.colorTextMuted,
  },
  actions: { display: "flex", flexWrap: "wrap", gap: vars.space8 },
  onboardingList: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space12,
    margin: 0,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: vars.colorBorder,
    paddingTop: vars.space16,
    paddingLeft: 0,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightRelaxed,
    color: vars.colorTextMuted,
    listStylePosition: "inside",
  },
  strong: { color: vars.colorText },
  loading: {
    pointerEvents: "none",
    position: "absolute",
    left: vars.space12,
    top: vars.space12,
    borderRadius: vars.radiusControl,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: vars.colorBorderSubtle,
    backgroundColor: vars.colorCanvas,
    paddingInline: vars.space8,
    paddingBlock: vars.space4,
    fontSize: vars.fontSizeCaption,
    color: vars.colorTextMuted,
    boxShadow: vars.elevationRaised,
  },
  loadingContent: { display: "inline-flex", alignItems: "center", gap: 6 },
  error: {
    pointerEvents: "auto",
    position: "absolute",
    insetInline: vars.space12,
    bottom: vars.space12,
    display: "flex",
    flexDirection: "column",
    gap: vars.space8,
    borderRadius: vars.radiusControl,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: vars.colorDangerBorder,
    backgroundColor: vars.colorSurfaceRaised,
    paddingInline: vars.space12,
    paddingBlock: vars.space12,
    fontSize: vars.fontSizeCaption,
    color: vars.colorText,
  },
  errorTitle: { fontWeight: vars.fontWeightMedium },
  guestPlaceholder: {
    position: "absolute",
    inset: 0,
    minHeight: 0,
    overflow: "hidden",
    backgroundColor: vars.colorCanvas,
  },
});
