import * as stylex from "@stylexjs/stylex";
import { vars } from "../../../ads/tokens/tokens.stylex";

export const detailStyles = stylex.create({
  label: { fontSize: vars["--ads-font-size-micro"], fontWeight: vars["--ads-font-weight-medium"], color: vars["--ads-color-text-muted"] },
  block: { marginTop: vars["--ads-space-4"], borderRadius: vars["--ads-radius-control"], borderWidth: 1, borderStyle: "solid", borderColor: vars["--ads-color-border"], backgroundColor: vars["--ads-color-canvas"], padding: vars["--ads-space-8"], fontFamily: vars["--ads-font-mono"], fontSize: vars["--ads-font-size-micro"], lineHeight: 1.625, color: vars["--ads-color-text"] },
  object: { borderRadius: vars["--ads-radius-control"], borderWidth: 1, borderStyle: "solid", borderColor: vars["--ads-color-border"], backgroundColor: vars["--ads-color-canvas"] },
  nested: { marginLeft: vars["--ads-space-16"] },
  objectRow: { display: "flex", minWidth: 0, alignItems: "flex-start", gap: 6, paddingInline: vars["--ads-space-8"], paddingBlock: 6 },
  toggle: { marginTop: -2, width: 24, height: 24, flexShrink: 0 },
  chevron: { width: 12, height: 12, transitionProperty: "transform", transitionDuration: { default: vars["--ads-motion-duration-fast"], "@media (prefers-reduced-motion: reduce)": "0s" } },
  expanded: { transform: "rotate(90deg)" },
  spacer: { display: "block", width: 24, height: 24, flexShrink: 0 },
  fill: { minWidth: 0, flex: 1 },
  valueRow: { display: "flex", minWidth: 0, flexWrap: "wrap", alignItems: "baseline", columnGap: vars["--ads-space-8"], rowGap: 2, fontFamily: vars["--ads-font-mono"], fontSize: vars["--ads-font-size-micro"] },
  property: { flexShrink: 0, color: vars["--ads-color-accent"] },
  value: { wordBreak: "break-all", color: vars["--ads-color-text"] },
  muted: { color: vars["--ads-color-text-muted"] },
  hint: { fontSize: vars["--ads-font-size-micro"], color: vars["--ads-color-text-muted"] },
  preview: { marginTop: vars["--ads-space-4"], overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", fontFamily: vars["--ads-font-mono"], fontSize: vars["--ads-font-size-micro"], color: vars["--ads-color-text-muted"] },
  properties: { display: "flex", flexDirection: "column", gap: vars["--ads-space-4"], borderTopWidth: 1, borderTopStyle: "solid", borderTopColor: vars["--ads-color-border"], padding: 6 },
  error: { borderRadius: vars["--ads-radius-control"], backgroundColor: vars["--ads-color-danger-soft"], paddingInline: vars["--ads-space-8"], paddingBlock: 6, fontSize: vars["--ads-font-size-micro"], color: vars["--ads-color-danger-text"] },
  note: { paddingInline: vars["--ads-space-8"], paddingBlock: vars["--ads-space-4"], fontSize: vars["--ads-font-size-micro"], color: vars["--ads-color-text-muted"] },
  state: { display: "flex", alignItems: "center", gap: vars["--ads-space-8"], borderRadius: vars["--ads-radius-control"], borderWidth: 1, borderStyle: "solid", borderColor: vars["--ads-color-border"], backgroundColor: vars["--ads-color-canvas"], paddingInline: vars["--ads-space-12"], paddingBlock: vars["--ads-space-8"], fontSize: vars["--ads-font-size-micro"], color: vars["--ads-color-text-muted"] },
  stateError: { paddingInline: vars["--ads-space-12"], paddingBlock: vars["--ads-space-8"] },
  stack: { display: "flex", flexDirection: "column", gap: vars["--ads-space-8"] },
  spacedStack: { display: "flex", flexDirection: "column", gap: vars["--ads-space-12"] },
  metadata: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: vars["--ads-space-8"], fontSize: vars["--ads-font-size-micro"], color: vars["--ads-color-text-muted"] },
  kind: { borderRadius: vars["--ads-radius-control"], backgroundColor: vars["--ads-color-surface-tint"], paddingInline: vars["--ads-space-8"], paddingBlock: 2, fontWeight: vars["--ads-font-weight-medium"] },
  warning: { borderRadius: vars["--ads-radius-control"], backgroundColor: vars["--ads-color-warning-soft"], paddingInline: vars["--ads-space-8"], paddingBlock: 2, fontWeight: vars["--ads-font-weight-medium"], color: vars["--ads-color-warning-text"] },
  body: { maxHeight: "28rem", overflow: "auto", whiteSpace: "pre-wrap", wordBreak: "break-all" },
  timestamps: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) auto", columnGap: vars["--ads-space-12"], rowGap: vars["--ads-space-4"] },
  table: { overflow: "hidden", borderRadius: vars["--ads-radius-control"], borderWidth: 1, borderStyle: "solid", borderColor: vars["--ads-color-border"], backgroundColor: vars["--ads-color-canvas"] },
  phaseRow: { display: "grid", gridTemplateColumns: "4.5rem 3.5rem 3.5rem minmax(7rem, 1fr)", alignItems: "center", gap: vars["--ads-space-8"], borderBottomWidth: { default: 1, ":last-child": 0 }, borderBottomStyle: "solid", borderBottomColor: vars["--ads-color-border"], paddingInline: vars["--ads-space-8"], paddingBlock: 6, fontSize: vars["--ads-font-size-micro"] },
  phaseHeading: { fontWeight: vars["--ads-font-weight-medium"], color: vars["--ads-color-text-muted"] },
  phaseName: { fontWeight: vars["--ads-font-weight-medium"], color: vars["--ads-color-text"] },
  monoMuted: { fontFamily: vars["--ads-font-mono"], color: vars["--ads-color-text-muted"] },
  track: { position: "relative", height: 8, overflow: "hidden", borderRadius: vars["--ads-radius-full"], backgroundColor: vars["--ads-color-surface-tint"] },
  smallTrack: { height: 6 },
  bar: { position: "absolute", insetBlock: 0, borderRadius: vars["--ads-radius-full"], backgroundColor: vars["--ads-color-accent"] },
  barOrigin: { left: 0 },
  failed: { backgroundColor: vars["--ads-color-danger"] },
  capture: { display: "flex", minWidth: 0, alignItems: "center", gap: vars["--ads-space-4"] },
  captureStatus: { display: "flex", minWidth: 0, alignItems: "center", gap: 6, borderRadius: vars["--ads-radius-control"], backgroundColor: vars["--ads-color-success-soft"], paddingInline: vars["--ads-space-8"], paddingBlock: vars["--ads-space-4"], fontSize: vars["--ads-font-size-micro"], fontWeight: vars["--ads-font-weight-medium"], color: vars["--ads-color-success-text"] },
  dot: { width: 6, height: 6, flexShrink: 0, borderRadius: vars["--ads-radius-full"], backgroundColor: vars["--ads-color-success-text"] },
  truncated: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  captureButton: { height: 28, paddingInline: vars["--ads-space-8"], fontSize: vars["--ads-font-size-micro"] },
  stopIcon: { width: 12, height: 12, fill: "currentColor" },
  icon: { width: 14, height: 14 },
  inspector: { order: 9999, height: "100%", minHeight: 0, width: "min(38%, 34rem)", minWidth: "min(18rem, 48%)", maxWidth: "48%", flexShrink: 0, overflow: "auto", borderLeftWidth: 1, borderLeftStyle: "solid", borderLeftColor: vars["--ads-color-border"], backgroundColor: vars["--ads-color-surface"] },
  sticky: { position: "sticky", top: 0, zIndex: 10, borderBottomWidth: 1, borderBottomStyle: "solid", borderBottomColor: vars["--ads-color-border"], backgroundColor: vars["--ads-color-surface"] },
  header: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: vars["--ads-space-12"], paddingInline: vars["--ads-space-12"], paddingBlock: vars["--ads-space-8"] },
  title: { fontSize: vars["--ads-font-size-caption"], fontWeight: vars["--ads-font-weight-semibold"], color: vars["--ads-color-text"] },
  actions: { display: "flex", alignItems: "center", gap: vars["--ads-space-4"] },
  tablist: { display: "flex", minWidth: 0, alignItems: "center", gap: vars["--ads-space-4"], overflowX: "auto", paddingInline: vars["--ads-space-8"] },
  tab: { position: "relative", height: 32, flexShrink: 0, paddingInline: vars["--ads-space-8"], fontSize: vars["--ads-font-size-micro"], fontWeight: vars["--ads-font-weight-medium"], color: { default: vars["--ads-color-text-muted"], ":hover": vars["--ads-color-text"] }, borderBottomWidth: 1, borderBottomStyle: "solid", borderBottomColor: "transparent" },
  selectedTab: { color: vars["--ads-color-text"], borderBottomColor: vars["--ads-color-accent"] },
  content: { padding: vars["--ads-space-12"] },
  fields: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", columnGap: vars["--ads-space-16"], rowGap: vars["--ads-space-12"] },
  field: { minWidth: 0 },
  fieldValue: { marginTop: 2, overflowWrap: "break-word", fontFamily: vars["--ads-font-mono"], fontSize: vars["--ads-font-size-micro"], color: vars["--ads-color-text"] },
});
