import * as stylex from "@stylexjs/stylex";
import { vars } from "../../../ads/tokens/tokens.stylex";

export const detailStyles = stylex.create({
  label: { fontSize: vars.fontSizeMicro, fontWeight: vars.fontWeightMedium, color: vars.colorTextMuted },
  block: { marginTop: vars.space4, borderRadius: vars.radiusControl, borderWidth: 1, borderStyle: "solid", borderColor: vars.colorBorder, backgroundColor: vars.colorCanvas, padding: vars.space8, fontFamily: vars.fontMono, fontSize: vars.fontSizeMicro, lineHeight: 1.625, color: vars.colorText },
  object: { borderRadius: vars.radiusControl, borderWidth: 1, borderStyle: "solid", borderColor: vars.colorBorder, backgroundColor: vars.colorCanvas },
  nested: { marginLeft: vars.space16 },
  objectRow: { display: "flex", minWidth: 0, alignItems: "flex-start", gap: 6, paddingInline: vars.space8, paddingBlock: 6 },
  toggle: { marginTop: -2, width: 24, height: 24, flexShrink: 0 },
  chevron: { width: 12, height: 12, transitionProperty: "transform", transitionDuration: { default: vars.motionDurationFast, "@media (prefers-reduced-motion: reduce)": "0s" } },
  expanded: { transform: "rotate(90deg)" },
  spacer: { display: "block", width: 24, height: 24, flexShrink: 0 },
  fill: { minWidth: 0, flex: 1 },
  valueRow: { display: "flex", minWidth: 0, flexWrap: "wrap", alignItems: "baseline", columnGap: vars.space8, rowGap: 2, fontFamily: vars.fontMono, fontSize: vars.fontSizeMicro },
  property: { flexShrink: 0, color: vars.colorAccent },
  value: { wordBreak: "break-all", color: vars.colorText },
  muted: { color: vars.colorTextMuted },
  hint: { fontSize: vars.fontSizeMicro, color: vars.colorTextMuted },
  preview: { marginTop: vars.space4, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", fontFamily: vars.fontMono, fontSize: vars.fontSizeMicro, color: vars.colorTextMuted },
  properties: { display: "flex", flexDirection: "column", gap: vars.space4, borderTopWidth: 1, borderTopStyle: "solid", borderTopColor: vars.colorBorder, padding: 6 },
  error: { borderRadius: vars.radiusControl, backgroundColor: vars.colorDangerSoft, paddingInline: vars.space8, paddingBlock: 6, fontSize: vars.fontSizeMicro, color: vars.colorDangerText },
  note: { paddingInline: vars.space8, paddingBlock: vars.space4, fontSize: vars.fontSizeMicro, color: vars.colorTextMuted },
  state: { display: "flex", alignItems: "center", gap: vars.space8, borderRadius: vars.radiusControl, borderWidth: 1, borderStyle: "solid", borderColor: vars.colorBorder, backgroundColor: vars.colorCanvas, paddingInline: vars.space12, paddingBlock: vars.space8, fontSize: vars.fontSizeMicro, color: vars.colorTextMuted },
  stateError: { paddingInline: vars.space12, paddingBlock: vars.space8 },
  stack: { display: "flex", flexDirection: "column", gap: vars.space8 },
  spacedStack: { display: "flex", flexDirection: "column", gap: vars.space12 },
  metadata: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: vars.space8, fontSize: vars.fontSizeMicro, color: vars.colorTextMuted },
  kind: { borderRadius: vars.radiusControl, backgroundColor: vars.colorSurfaceTint, paddingInline: vars.space8, paddingBlock: 2, fontWeight: vars.fontWeightMedium },
  warning: { borderRadius: vars.radiusControl, backgroundColor: vars.colorWarningSoft, paddingInline: vars.space8, paddingBlock: 2, fontWeight: vars.fontWeightMedium, color: vars.colorWarningText },
  body: { maxHeight: "28rem", overflow: "auto", whiteSpace: "pre-wrap", wordBreak: "break-all" },
  timestamps: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) auto", columnGap: vars.space12, rowGap: vars.space4 },
  table: { overflow: "hidden", borderRadius: vars.radiusControl, borderWidth: 1, borderStyle: "solid", borderColor: vars.colorBorder, backgroundColor: vars.colorCanvas },
  phaseRow: { display: "grid", gridTemplateColumns: "4.5rem 3.5rem 3.5rem minmax(7rem, 1fr)", alignItems: "center", gap: vars.space8, borderBottomWidth: { default: 1, ":last-child": 0 }, borderBottomStyle: "solid", borderBottomColor: vars.colorBorder, paddingInline: vars.space8, paddingBlock: 6, fontSize: vars.fontSizeMicro },
  phaseHeading: { fontWeight: vars.fontWeightMedium, color: vars.colorTextMuted },
  phaseName: { fontWeight: vars.fontWeightMedium, color: vars.colorText },
  monoMuted: { fontFamily: vars.fontMono, color: vars.colorTextMuted },
  track: { position: "relative", height: 8, overflow: "hidden", borderRadius: vars.radiusFull, backgroundColor: vars.colorSurfaceTint },
  smallTrack: { height: 6 },
  bar: { position: "absolute", insetBlock: 0, borderRadius: vars.radiusFull, backgroundColor: vars.colorAccent },
  barOrigin: { left: 0 },
  failed: { backgroundColor: vars.colorDanger },
  capture: { display: "flex", minWidth: 0, alignItems: "center", gap: vars.space4 },
  captureStatus: { display: "flex", minWidth: 0, alignItems: "center", gap: 6, borderRadius: vars.radiusControl, backgroundColor: vars.colorSuccessSoft, paddingInline: vars.space8, paddingBlock: vars.space4, fontSize: vars.fontSizeMicro, fontWeight: vars.fontWeightMedium, color: vars.colorSuccessText },
  dot: { width: 6, height: 6, flexShrink: 0, borderRadius: vars.radiusFull, backgroundColor: vars.colorSuccessText },
  truncated: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  captureButton: { height: 28, paddingInline: vars.space8, fontSize: vars.fontSizeMicro },
  stopIcon: { width: 12, height: 12, fill: "currentColor" },
  icon: { width: 14, height: 14 },
  inspector: { order: 9999, height: "100%", minHeight: 0, width: "min(38%, 34rem)", minWidth: "min(18rem, 48%)", maxWidth: "48%", flexShrink: 0, overflow: "auto", borderLeftWidth: 1, borderLeftStyle: "solid", borderLeftColor: vars.colorBorder, backgroundColor: vars.colorSurface },
  sticky: { position: "sticky", top: 0, zIndex: 10, borderBottomWidth: 1, borderBottomStyle: "solid", borderBottomColor: vars.colorBorder, backgroundColor: vars.colorSurface },
  header: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: vars.space12, paddingInline: vars.space12, paddingBlock: vars.space8 },
  title: { fontSize: vars.fontSizeCaption, fontWeight: vars.fontWeightSemibold, color: vars.colorText },
  actions: { display: "flex", alignItems: "center", gap: vars.space4 },
  tablist: { display: "flex", minWidth: 0, alignItems: "center", gap: vars.space4, overflowX: "auto", paddingInline: vars.space8 },
  tab: { position: "relative", height: 32, flexShrink: 0, paddingInline: vars.space8, fontSize: vars.fontSizeMicro, fontWeight: vars.fontWeightMedium, color: { default: vars.colorTextMuted, ":hover": vars.colorText }, borderBottomWidth: 1, borderBottomStyle: "solid", borderBottomColor: "transparent" },
  selectedTab: { color: vars.colorText, borderBottomColor: vars.colorAccent },
  content: { padding: vars.space12 },
  fields: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", columnGap: vars.space16, rowGap: vars.space12 },
  field: { minWidth: 0 },
  fieldValue: { marginTop: 2, overflowWrap: "break-word", fontFamily: vars.fontMono, fontSize: vars.fontSizeMicro, color: vars.colorText },
});
