import * as stylex from "@stylexjs/stylex";
import { focusRing } from "../../../ads/recipes/focus-ring";
import { transition } from "../../../ads/recipes/transition";
import { vars } from "../../../ads/tokens/tokens.stylex";

export { focusRing, transition };

const diagnosticGrid =
  "4.5rem 4rem 4.5rem minmax(8rem, 1fr) 5.5rem 4.5rem 4.5rem 5rem";

export const workbenchStyles = stylex.create({
  surface: {
    display: "flex",
    height: "100%",
    minHeight: 0,
    flexDirection: "column",
    backgroundColor: vars["--ads-color-canvas"],
  },
  toolbar: {
    display: "flex",
    flexShrink: 0,
    flexWrap: "wrap",
    alignItems: "center",
    gap: vars["--ads-space-8"],
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: vars["--ads-color-border-subtle"],
    padding: vars["--ads-space-8"],
  },
  search: { position: "relative", minWidth: "9rem", flex: 1 },
  networkSearch: { minWidth: "10rem" },
  searchIcon: {
    pointerEvents: "none",
    position: "absolute",
    left: vars["--ads-space-8"],
    top: "50%",
    width: 14,
    height: 14,
    transform: "translateY(-50%)",
    color: vars["--ads-color-text-muted"],
  },
  searchInput: { height: 28, paddingLeft: 28, fontSize: vars["--ads-font-size-caption"] },
  filters: {
    display: "flex",
    alignItems: "center",
    gap: vars["--ads-space-4"],
    overflowX: "auto",
  },
  toolbarButton: {
    height: 28,
    paddingInline: vars["--ads-space-8"],
    fontSize: vars["--ads-font-size-micro"],
  },
  icon: { width: 14, height: 14 },
  workbench: {
    display: "flex",
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: "row",
  },
  entryList: {
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    overflow: "auto",
    fontSize: vars["--ads-font-size-caption"],
  },
  consoleList: { fontFamily: vars["--ads-font-mono"] },
  entryRows: { display: "flex", flexDirection: "column" },
  entryRow: {
    display: "grid",
    width: "100%",
    gridTemplateColumns: "4.5rem 4.25rem minmax(0, 1fr)",
    gap: vars["--ads-space-8"],
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: vars["--ads-color-border"],
    paddingInline: vars["--ads-space-12"],
    paddingBlock: vars["--ads-space-8"],
    backgroundColor: {
      default: "transparent",
      ":hover": vars["--ads-color-surface-tint"],
    },
    color: vars["--ads-color-text"],
    textAlign: "left",
  },
  selectedEntryRow: {
    backgroundColor: vars["--ads-color-accent-soft"],
    color: vars["--ads-color-text"],
  },
  time: { fontSize: vars["--ads-font-size-micro"], color: vars["--ads-color-text-muted"] },
  entryContent: { minWidth: 0 },
  entryText: {
    display: "block",
    overflowWrap: "break-word",
    whiteSpace: "pre-wrap",
    color: vars["--ads-color-text"],
  },
  entrySource: {
    display: "block",
    marginTop: vars["--ads-space-4"],
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: vars["--ads-font-size-micro"],
    color: vars["--ads-color-text-muted"],
  },
  empty: {
    display: "flex",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    padding: vars["--ads-space-16"],
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text-muted"],
  },
  pre: {
    maxHeight: "16rem",
    overflow: "auto",
    overflowWrap: "break-word",
    whiteSpace: "pre-wrap",
  },
  compactStack: { display: "flex", flexDirection: "column", gap: 6 },
  stack: { display: "flex", flexDirection: "column", gap: vars["--ads-space-12"] },
  stackFrame: {
    borderRadius: vars["--ads-radius-control"],
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: vars["--ads-color-border-subtle"],
    backgroundColor: vars["--ads-color-canvas"],
    paddingInline: vars["--ads-space-8"],
    paddingBlock: 6,
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-micro"],
  },
  stackFrameHeader: {
    display: "flex",
    minWidth: 0,
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: vars["--ads-space-12"],
  },
  stackFrameName: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontWeight: vars["--ads-font-weight-medium"],
    color: vars["--ads-color-text"],
  },
  stackFrameDescription: {
    flexShrink: 0,
    fontSize: vars["--ads-font-size-micro"],
    color: vars["--ads-color-text-muted"],
  },
  stackFrameLocation: {
    marginTop: 2,
    overflowWrap: "break-word",
    fontSize: vars["--ads-font-size-micro"],
    color: vars["--ads-color-text-muted"],
  },
  detailsGrid: { display: "grid", gap: vars["--ads-space-12"] },
  networkTable: { minWidth: "700px" },
  networkHeading: {
    display: "grid",
    gridTemplateColumns: diagnosticGrid,
    gap: vars["--ads-space-8"],
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: vars["--ads-color-border"],
    paddingInline: vars["--ads-space-12"],
    paddingBlock: vars["--ads-space-8"],
    fontSize: vars["--ads-font-size-micro"],
    fontWeight: vars["--ads-font-weight-medium"],
    textTransform: "uppercase",
    color: vars["--ads-color-text-muted"],
  },
  networkRow: {
    display: "grid",
    width: "100%",
    alignItems: "center",
    gridTemplateColumns: diagnosticGrid,
    gap: vars["--ads-space-8"],
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: vars["--ads-color-border"],
    paddingInline: vars["--ads-space-12"],
    paddingBlock: vars["--ads-space-8"],
    backgroundColor: {
      default: "transparent",
      ":hover": vars["--ads-color-surface-tint"],
    },
    color: vars["--ads-color-text"],
    textAlign: "left",
  },
  mono: { fontFamily: vars["--ads-font-mono"], fontSize: vars["--ads-font-size-micro"] },
  monoMuted: {
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-micro"],
    color: vars["--ads-color-text-muted"],
  },
  medium: { fontWeight: vars["--ads-font-weight-medium"] },
  semibold: { fontWeight: vars["--ads-font-weight-semibold"] },
  truncation: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  statusMuted: { color: vars["--ads-color-text-muted"] },
  statusDanger: { color: vars["--ads-color-danger-text"] },
  statusWarning: { color: vars["--ads-color-warning-text"] },
  statusInfo: { color: vars["--ads-color-info-text"] },
  statusSuccess: { color: vars["--ads-color-success-text"] },
  breakWords: { overflowWrap: "break-word" },
  definitionList: {
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr)",
    columnGap: vars["--ads-space-12"],
    rowGap: vars["--ads-space-4"],
  },
  definitionTerm: { color: vars["--ads-color-text-muted"] },
  list: { display: "flex", flexDirection: "column", gap: vars["--ads-space-4"] },
  previewHost: { position: "absolute", inset: 0, padding: vars["--ads-space-12"] },
  runtimeEmpty: {
    height: "100%",
    justifyContent: "center",
    borderRadius: vars["--ads-radius-panel"],
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: vars["--ads-color-border-subtle"],
    backgroundColor: vars["--ads-color-canvas"],
    padding: vars["--ads-space-24"],
  },
  runtimeCopy: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-4"],
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text-muted"],
  },
  overlay: {
    pointerEvents: "auto",
    position: "absolute",
    inset: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    overflow: "auto",
    backgroundColor: vars["--ads-color-canvas"],
    padding: vars["--ads-space-24"],
    color: vars["--ads-color-text"],
  },
  onboarding: {
    width: "100%",
    maxWidth: "28rem",
    marginBlock: "auto",
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-16"],
  },
  onboardingIcon: { width: 24, height: 24, color: vars["--ads-color-accent"] },
  onboardingTitle: {
    fontSize: vars["--ads-font-size-heading"],
    fontWeight: vars["--ads-font-weight-semibold"],
  },
  onboardingCopy: {
    fontSize: vars["--ads-font-size-body"],
    lineHeight: vars["--ads-line-height-relaxed"],
    color: vars["--ads-color-text-muted"],
  },
  actions: { display: "flex", flexWrap: "wrap", gap: vars["--ads-space-8"] },
  onboardingList: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-12"],
    margin: 0,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: vars["--ads-color-border"],
    paddingTop: vars["--ads-space-16"],
    paddingLeft: 0,
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-relaxed"],
    color: vars["--ads-color-text-muted"],
    listStylePosition: "inside",
  },
  strong: { color: vars["--ads-color-text"] },
  loading: {
    pointerEvents: "none",
    position: "absolute",
    left: vars["--ads-space-12"],
    top: vars["--ads-space-12"],
    borderRadius: vars["--ads-radius-control"],
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: vars["--ads-color-border-subtle"],
    backgroundColor: vars["--ads-color-canvas"],
    paddingInline: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-4"],
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text-muted"],
    boxShadow: vars["--ads-elevation-raised"],
  },
  loadingContent: { display: "inline-flex", alignItems: "center", gap: 6 },
  error: {
    pointerEvents: "auto",
    position: "absolute",
    insetInline: vars["--ads-space-12"],
    bottom: vars["--ads-space-12"],
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-8"],
    borderRadius: vars["--ads-radius-control"],
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: vars["--ads-color-danger-border"],
    backgroundColor: vars["--ads-color-surface-raised"],
    paddingInline: vars["--ads-space-12"],
    paddingBlock: vars["--ads-space-12"],
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text"],
  },
  errorTitle: { fontWeight: vars["--ads-font-weight-medium"] },
  guestPlaceholder: {
    position: "absolute",
    inset: 0,
    minHeight: 0,
    overflow: "hidden",
    backgroundColor: vars["--ads-color-canvas"],
  },
});
