import * as stylex from "@stylexjs/stylex";
import { vars } from "../ads/tokens/tokens.stylex";

/**
 * Playbooks tab and editor. Existing ADS tokens only.
 *
 * Grid: the editor is one reading column; properties are a two-column grid
 * (label 7.5rem, control) so every control starts on one line; stage rows keep
 * a fixed lead (handle, number, kind) so titles align down the list.
 */
const LABEL_COLUMN = "7.5rem";

export const playbookStyles = stylex.create({
  /* Tab ------------------------------------------------------------------ */
  tab: {
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(0, 1fr)",
      "@media (min-width: 56rem)": "minmax(15rem, 18rem) minmax(0, 1fr)",
    },
    flex: "1 1 auto",
    minHeight: 0,
    borderTopWidth: vars["--ads-border-width-hairline"],
    borderTopStyle: "solid",
    borderTopColor: vars["--ads-color-border-subtle"],
  },
  master: {
    display: { default: "none", "@media (min-width: 56rem)": "flex" },
    flexDirection: "column",
    gap: vars["--ads-space-8"],
    minHeight: 0,
    overflowY: "auto",
    padding: vars["--ads-space-12"],
    borderInlineEndWidth: vars["--ads-border-width-hairline"],
    borderInlineEndStyle: "solid",
    borderInlineEndColor: vars["--ads-color-border-subtle"],
  },
  masterHeader: { display: "flex", alignItems: "center", gap: vars["--ads-space-4"] },
  masterSearch: { flex: "1 1 auto", minWidth: 0 },
  list: { display: "flex", flexDirection: "column", gap: 2, margin: 0, padding: 0, listStyle: "none" },
  listLabel: {
    margin: 0,
    marginTop: vars["--ads-space-12"],
    paddingInline: vars["--ads-space-8"],
    fontSize: vars["--ads-font-size-micro"],
    fontWeight: vars["--ads-font-weight-medium"],
    letterSpacing: "0.02em",
    textTransform: "uppercase",
    color: vars["--ads-color-text-subtle"],
  },
  listLabelFlush: { paddingInline: 0, marginTop: 0 },
  card: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    gap: 2,
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-8"],
    borderRadius: vars["--ads-radius-control"],
    textAlign: "start",
    color: vars["--ads-color-text"],
    backgroundColor: {
      default: "transparent",
      ":hover": vars["--ads-color-overlay-hover"],
    },
    cursor: "pointer",
  },
  cardActive: {
    backgroundColor: {
      default: vars["--ads-color-selection-fill"],
      ":hover": vars["--ads-color-selection-fill"],
    },
  },
  cardTitleRow: { display: "flex", alignItems: "center", gap: vars["--ads-space-4"], minWidth: 0 },
  cardTitle: {
    flex: "1 1 auto",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  cardMeta: {
    display: "flex",
    alignItems: "center",
    gap: vars["--ads-space-4"],
    minWidth: 0,
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text-muted"],
    whiteSpace: "nowrap",
    overflow: "hidden",
  },
  unsavedDot: {
    flex: "0 0 auto",
    width: 6,
    height: 6,
    borderRadius: vars["--ads-radius-full"],
    backgroundColor: vars["--ads-color-warning"],
  },
  shortcut: {
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-micro"],
    color: vars["--ads-color-text-muted"],
    paddingInline: 4,
    borderRadius: vars["--ads-radius-mark"],
    backgroundColor: vars["--ads-color-canvas-subtle"],
  },
  detail: { display: "flex", flexDirection: "column", flex: "1 1 auto", minHeight: 0, minWidth: 0 },
  compactPicker: {
    display: { default: "flex", "@media (min-width: 56rem)": "none" },
    gap: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-16"],
    paddingTop: vars["--ads-space-12"],
  },

  /* Editor --------------------------------------------------------------- */
  scroll: { flex: "1 1 auto", minHeight: 0, overflowY: "auto" },
  editor: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-24"],
    width: "100%",
    maxWidth: "48rem",
    marginInline: "auto",
    paddingInline: vars["--ads-space-24"],
    paddingTop: vars["--ads-space-20"],
    paddingBottom: vars["--ads-space-32"],
  },
  heading: { display: "flex", alignItems: "flex-start", gap: vars["--ads-space-12"], minWidth: 0 },
  headingText: { display: "flex", flexDirection: "column", gap: vars["--ads-space-4"], flex: "1 1 auto", minWidth: 0 },
  nameInput: {
    width: "100%",
    margin: 0,
    paddingBlock: 2,
    paddingInline: vars["--ads-space-4"],
    marginInlineStart: `calc(-1 * ${vars["--ads-space-4"]})`,
    borderWidth: 0,
    borderRadius: vars["--ads-radius-control"],
    outline: "none",
    backgroundColor: {
      default: "transparent",
      ":hover": vars["--ads-color-overlay-hover"],
      ":focus-visible": vars["--ads-color-overlay-hover"],
    },
    boxShadow: { default: "none", ":focus-visible": `0 0 0 2px ${vars["--ads-color-border-focus"]}` },
    color: vars["--ads-color-text"],
    fontFamily: "inherit",
    fontSize: vars["--ads-font-size-title"],
    lineHeight: vars["--ads-line-height-title"],
    fontWeight: vars["--ads-font-weight-semibold"],
  },
  purposeInput: {
    width: "100%",
    margin: 0,
    paddingBlock: 2,
    paddingInline: vars["--ads-space-4"],
    marginInlineStart: `calc(-1 * ${vars["--ads-space-4"]})`,
    borderWidth: 0,
    borderRadius: vars["--ads-radius-control"],
    outline: "none",
    resize: "none",
    fieldSizing: "content",
    minHeight: "1.5rem",
    backgroundColor: {
      default: "transparent",
      ":hover": vars["--ads-color-overlay-hover"],
      ":focus-visible": vars["--ads-color-overlay-hover"],
    },
    boxShadow: { default: "none", ":focus-visible": `0 0 0 2px ${vars["--ads-color-border-focus"]}` },
    color: vars["--ads-color-text-muted"],
    fontFamily: "inherit",
    fontSize: vars["--ads-font-size-body"],
    lineHeight: vars["--ads-line-height-relaxed"],
  },
  headingActions: { flex: "0 0 auto", display: "flex", alignItems: "center", gap: vars["--ads-space-4"] },
  banner: {
    display: "flex",
    alignItems: "flex-start",
    gap: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
    borderRadius: vars["--ads-radius-control"],
    backgroundColor: vars["--ads-color-danger-soft"],
    color: vars["--ads-color-text"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
  },
  bannerNeutral: { backgroundColor: vars["--ads-color-canvas-subtle"] },
  bannerIcon: { flex: "0 0 auto", width: 14, height: 14, marginTop: 2, color: vars["--ads-color-danger-text"] },

  /* Properties ------------------------------------------------------------ */
  properties: {
    display: "grid",
    gridTemplateColumns: `${LABEL_COLUMN} minmax(0, 1fr)`,
    columnGap: vars["--ads-space-16"],
    rowGap: vars["--ads-space-16"],
    alignItems: "start",
    margin: 0,
  },
  propertyLabel: {
    paddingTop: 6,
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
    color: vars["--ads-color-text-muted"],
  },
  propertyValue: { display: "flex", flexDirection: "column", gap: vars["--ads-space-4"], margin: 0, minWidth: 0 },
  propertyRow: { display: "flex", alignItems: "center", gap: vars["--ads-space-8"], flexWrap: "wrap", minWidth: 0 },
  hint: {
    margin: 0,
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
    color: vars["--ads-color-text-subtle"],
  },
  fieldError: {
    margin: 0,
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
    color: vars["--ads-color-danger-text"],
  },
  shortcutField: { display: "flex", alignItems: "center", gap: 2, maxWidth: "16rem" },
  shortcutPrefix: { fontFamily: vars["--ads-font-mono"], color: vars["--ads-color-text-muted"] },

  /* Stages ---------------------------------------------------------------- */
  sectionHeader: { display: "flex", alignItems: "baseline", gap: vars["--ads-space-8"] },
  sectionTitle: {
    flex: "1 1 auto",
    margin: 0,
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
    color: vars["--ads-color-text"],
  },
  sectionAside: { fontSize: vars["--ads-font-size-caption"], color: vars["--ads-color-text-subtle"], fontVariantNumeric: "tabular-nums" },
  stages: {
    display: "flex",
    flexDirection: "column",
    margin: 0,
    padding: 0,
    listStyle: "none",
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-panel"],
    backgroundColor: vars["--ads-color-surface"],
    overflow: "hidden",
  },
  stage: {
    position: "relative",
    borderTopWidth: { default: vars["--ads-border-width-hairline"], ":first-child": 0 },
    borderTopStyle: "solid",
    borderTopColor: vars["--ads-color-border-subtle"],
  },
  stageDragging: { opacity: 0.45 },
  dropBefore: { boxShadow: `inset 0 2px 0 ${vars["--ads-color-accent"]}` },
  dropAfter: { boxShadow: `inset 0 -2px 0 ${vars["--ads-color-accent"]}` },
  stageHead: {
    display: "grid",
    gridTemplateColumns: "20px 18px 18px minmax(0, 1fr) auto",
    alignItems: "center",
    columnGap: vars["--ads-space-8"],
    minHeight: 44,
    paddingInlineStart: vars["--ads-space-8"],
    paddingInlineEnd: vars["--ads-space-8"],
  },
  handle: {
    width: 20,
    height: 24,
    paddingInline: 0,
    color: vars["--ads-color-text-subtle"],
    cursor: "grab",
  },
  number: {
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text-subtle"],
    fontVariantNumeric: "tabular-nums",
    textAlign: "center",
  },
  kind: { display: "flex", justifyContent: "center", color: vars["--ads-color-text-muted"] },
  kindAction: { color: vars["--ads-color-accent"] },
  kindIcon: { width: 15, height: 15 },
  titleCell: { display: "flex", flexDirection: "column", minWidth: 0, gap: 0 },
  titleInput: {
    width: "100%",
    margin: 0,
    paddingBlock: 2,
    paddingInline: vars["--ads-space-4"],
    marginInlineStart: `calc(-1 * ${vars["--ads-space-4"]})`,
    borderWidth: 0,
    borderRadius: vars["--ads-radius-mark"],
    outline: "none",
    backgroundColor: {
      default: "transparent",
      ":hover": vars["--ads-color-overlay-hover"],
      ":focus-visible": vars["--ads-color-overlay-hover"],
    },
    boxShadow: { default: "none", ":focus-visible": `0 0 0 2px ${vars["--ads-color-border-focus"]}` },
    color: vars["--ads-color-text"],
    fontFamily: "inherit",
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  preview: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text-subtle"],
  },
  previewMissing: { color: vars["--ads-color-danger-text"] },
  stageActions: { display: "flex", alignItems: "center", gap: 2 },
  askToggle: { color: vars["--ads-color-text-subtle"] },
  askToggleOn: {
    color: vars["--ads-color-warning-text"],
    backgroundColor: vars["--ads-color-warning-soft"],
  },
  chevron: {
    transitionProperty: "transform",
    transitionDuration: vars["--ads-motion-duration-fast"],
  },
  chevronOpen: { transform: "rotate(90deg)" },
  stageBody: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-12"],
    paddingInlineStart: `calc(${vars["--ads-space-8"]} + 20px + 18px + 18px + 3 * ${vars["--ads-space-8"]})`,
    paddingInlineEnd: vars["--ads-space-16"],
    paddingBottom: vars["--ads-space-16"],
  },
  addRow: { display: "flex", alignItems: "center", gap: vars["--ads-space-8"] },

  /* Footer ---------------------------------------------------------------- */
  footer: {
    display: "flex",
    alignItems: "center",
    gap: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-12"],
    paddingInline: vars["--ads-space-24"],
    borderTopWidth: vars["--ads-border-width-hairline"],
    borderTopStyle: "solid",
    borderTopColor: vars["--ads-color-border-subtle"],
    backgroundColor: vars["--ads-color-surface"],
  },
  footerSpacer: { flex: "1 1 auto" },
  footerNote: { fontSize: vars["--ads-font-size-caption"], color: vars["--ads-color-text-muted"] },

  /* Empty and templates ---------------------------------------------------- */
  empty: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-20"],
    width: "100%",
    maxWidth: "52rem",
    marginInline: "auto",
    paddingInline: vars["--ads-space-24"],
    paddingBlock: vars["--ads-space-32"],
  },
  emptyTitle: { margin: 0, fontSize: vars["--ads-font-size-title"], fontWeight: vars["--ads-font-weight-semibold"] },
  emptyText: {
    margin: 0,
    maxWidth: "40rem",
    fontSize: vars["--ads-font-size-body"],
    lineHeight: vars["--ads-line-height-relaxed"],
    color: vars["--ads-color-text-muted"],
  },
  templates: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(15rem, 1fr))",
    gap: vars["--ads-space-12"],
  },
  template: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    gap: vars["--ads-space-8"],
    padding: vars["--ads-space-16"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: {
      default: vars["--ads-color-border"],
      ":hover": vars["--ads-color-border-strong"],
    },
    borderRadius: vars["--ads-radius-panel"],
    backgroundColor: vars["--ads-color-surface"],
    textAlign: "start",
    color: vars["--ads-color-text"],
    cursor: "pointer",
    height: "auto",
    whiteSpace: "normal",
  },
  templateTitle: { fontSize: vars["--ads-font-size-body"], fontWeight: vars["--ads-font-weight-medium"] },
  templateText: {
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
    color: vars["--ads-color-text-muted"],
    fontWeight: vars["--ads-font-weight-regular"],
  },
  chips: { display: "flex", flexWrap: "wrap", gap: 4 },
  chip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    paddingInline: 6,
    height: 20,
    borderRadius: vars["--ads-radius-full"],
    backgroundColor: vars["--ads-color-canvas-subtle"],
    fontSize: vars["--ads-font-size-micro"],
    color: vars["--ads-color-text-muted"],
    fontWeight: vars["--ads-font-weight-regular"],
  },
  chipIcon: { width: 11, height: 11 },
  emptyActions: { display: "flex", alignItems: "center", gap: vars["--ads-space-8"], flexWrap: "wrap" },

  /* Draft with AI --------------------------------------------------------- */
  draftPanel: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-8"],
    padding: vars["--ads-space-16"],
    borderRadius: vars["--ads-radius-panel"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: `color-mix(in oklab, ${vars["--ads-color-accent"]} 35%, ${vars["--ads-color-border"]})`,
    backgroundColor: vars["--ads-color-surface"],
  },
  draftHeader: { display: "flex", alignItems: "center", gap: vars["--ads-space-8"] },
  draftTitle: { margin: 0, fontSize: vars["--ads-font-size-body"], fontWeight: vars["--ads-font-weight-medium"] },
  draftActions: { display: "flex", alignItems: "center", justifyContent: "flex-end", gap: vars["--ads-space-8"] },
  icon: { width: 14, height: 14, flex: "0 0 auto" },
  iconAccent: { color: vars["--ads-color-accent"] },
});
