import * as stylex from "@stylexjs/stylex";
import { vars } from "../ads/tokens/tokens.stylex";

export const collaborationStyles = stylex.create({
  panelStack: { display: "flex", flexDirection: "column", gap: vars.space16 },
  contentStack: { display: "flex", flexDirection: "column", gap: vars.space12 },
  compactStack: { display: "flex", flexDirection: "column", gap: vars.space8 },
  librarySectionStack: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space8,
  },
  sectionStack: { display: "flex", flexDirection: "column", gap: vars.space12 },
  sectionDivider: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space12,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: vars.colorBorder,
    paddingTop: vars.space24,
  },
  article: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space12,
    borderBottomWidth: 1,
    borderBottomStyle: { default: "solid", ":last-of-type": "none" },
    borderBottomColor: vars.colorBorder,
    paddingBottom: vars.space20,
  },
  articleCompact: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space8,
    borderBottomWidth: 1,
    borderBottomStyle: { default: "solid", ":last-of-type": "none" },
    borderBottomColor: vars.colorBorder,
    paddingBottom: vars.space20,
  },
  row: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: vars.space8,
  },
  rowBetween: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: vars.space12,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: vars.colorBorder,
    paddingBottom: vars.space12,
  },
  wrap: { display: "flex", flexWrap: "wrap", gap: vars.space8 },
  body: { fontSize: vars.fontSizeCaption, lineHeight: vars.lineHeightNormal },
  bodyRelaxed: {
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightRelaxed,
  },
  muted: { color: vars.colorTextMuted },
  danger: { color: vars.colorDangerText },
  warning: { color: vars.colorWarningText },
  heading: {
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightNormal,
    fontWeight: vars.fontWeightSemibold,
  },
  headingBody: {
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightSemibold,
  },
  label: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space4,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightNormal,
  },
  field: {
    width: "100%",
    paddingInline: vars.space8,
    paddingBlock: vars.space8,
  },
  searchField: {
    width: "100%",
    paddingInline: vars.space12,
  },
  card: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: vars.colorBorder,
    borderRadius: vars.radiusControl,
    padding: vars.space12,
  },
  details: {
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightNormal,
  },
  detailsMuted: {
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightNormal,
    color: vars.colorTextMuted,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))",
    gap: vars.space12,
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "flex-start",
    gap: vars.space8,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightNormal,
  },
  definitionList: {
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr)",
    columnGap: vars.space12,
    rowGap: 6,
    fontSize: vars.fontSizeCaption,
    lineHeight: vars.lineHeightNormal,
  },
  minZero: { minWidth: 0 },
  breakWords: { overflowWrap: "break-word" },
  breakAll: { overflowWrap: "anywhere" },
  preWrap: { whiteSpace: "pre-wrap" },
  cursor: { cursor: "pointer" },
  selfStart: { alignSelf: "flex-start" },
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    borderWidth: 0,
  },
  marginTop1: { marginTop: vars.space4 },
  marginTop2: { marginTop: vars.space8 },
  marginTop3: { marginTop: vars.space12 },
  marginBottom2: { marginBottom: vars.space8 },
  marginBottom3: { marginBottom: vars.space12 },
  marginY2: { marginBlock: vars.space8 },
  marginY3: { marginBlock: vars.space12 },
});
