import * as stylex from "@stylexjs/stylex";
import { vars } from "@/components/ads/tokens/tokens.stylex";

const mq480 = "@media (min-width: 480px)";
const mq560 = "@media (min-width: 560px)";

const overlayHover = vars.colorOverlayHover;

export const cursorModelConfigStyles = stylex.create({
  fixedChip: {
    display: "flex",
    height: "1.5rem",
    flexShrink: 0,
    alignItems: "center",
    alignSelf: "center",
    borderRadius: vars.radiusMark,
    backgroundColor: `color-mix(in oklch, ${vars.colorCanvasSubtle} 45%, transparent)`,
    paddingInline: "0.375rem",
    fontSize: vars.fontSizeMicro,
    lineHeight: "1rem",
    fontWeight: vars.fontWeightMedium,
    color: `color-mix(in oklch, ${vars.colorTextMuted} 85%, transparent)`,
  },
  configButton: {
    display: "inline-flex",
    minHeight: "2.75rem",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: vars.radiusMark,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: "transparent",
    paddingInline: vars.space8,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
    color: {
      default: vars.colorTextMuted,
      ":hover": vars.colorText,
    },
    backgroundColor: { default: null, ":hover": overlayHover },
  },
  configButtonPressed: {
    borderColor: `color-mix(in oklch, ${vars.colorBorder} 70%, transparent)`,
    backgroundColor: `color-mix(in oklch, ${vars.colorCanvasSubtle} 70%, transparent)`,
    color: vars.colorText,
  },
  configButtonGap: { gap: "0.375rem" },
  configButtonFast: { color: "var(--prompt-role-fast)" },
  configButtonEffort: { width: "2.75rem", height: "2.75rem", paddingInline: 0 },
  row: {
    minWidth: 0,
    borderRadius: vars.radiusControl,
    paddingInline: { default: vars.space4, [mq480]: vars.space8 },
    paddingBlock: vars.space4,
    backgroundColor: {
      default: null,
      ":hover": `color-mix(in oklch, ${overlayHover} 60%, transparent)`,
    },
  },
  rowSelected: {
    backgroundColor: `color-mix(in oklch, ${vars.colorSelectionFill} 70%, transparent)`,
  },
  toolbar: {
    display: "flex",
    minWidth: 0,
    alignItems: "center",
    gap: { default: vars.space4, [mq480]: vars.space8 },
  },
  modelButton: {
    display: "flex",
    minHeight: "2.75rem",
    minWidth: { default: "10rem", [mq480]: "11rem" },
    maxWidth: {
      default: "min(44%, 14rem)",
      [mq480]: "min(42%, 16rem)",
    },
    flexShrink: 0,
    alignItems: "center",
    gap: vars.space8,
    borderRadius: vars.radiusMark,
    paddingInline: vars.space8,
    textAlign: "left",
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    color: vars.colorText,
    backgroundColor: { default: null, ":hover": overlayHover },
  },
  modelIcon: { width: "0.875rem", height: "0.875rem", flexShrink: 0 },
  modelLabel: {
    minWidth: 0,
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  defaultLabel: {
    display: { default: "none", [mq560]: "inline" },
    fontSize: vars.fontSizeMicro,
    color: vars.colorTextMuted,
  },
  controlStrip: {
    display: "flex",
    minWidth: 0,
    flex: 1,
    alignItems: "center",
    gap: vars.space4,
    overflowX: "auto",
    overscrollBehavior: "contain",
  },
  fastIcon: { width: "0.875rem", height: "0.875rem" },
  fastIconFilled: { fill: "currentColor" },
  fastIconFixed: {
    width: "0.75rem",
    height: "0.75rem",
    marginInlineEnd: vars.space4,
    fill: "currentColor",
  },
  effortInner: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "0.125rem",
  },
  effortShortLabel: { fontSize: vars.fontSizeMicro, lineHeight: 1 },
  effortVisual: {
    display: "flex",
    width: "1.25rem",
    height: "1.25rem",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: vars.radiusMark,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: `color-mix(in oklch, ${vars.colorText} 5%, transparent)`,
    boxShadow: vars.elevationRaised,
  },
  effortVisualUnavailable: { opacity: 0.3 },
  effortCheck: { width: "0.75rem", height: "0.75rem" },
  footer: {
    borderTopWidth: vars.borderWidthHairline,
    borderTopStyle: "solid",
    borderTopColor: `color-mix(in oklch, ${vars.colorBorder} 65%, transparent)`,
    paddingInline: vars.space12,
    paddingBlock: vars.space8,
    fontSize: vars.fontSizeCaption,
    color: vars.colorTextMuted,
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space4,
    padding: { default: vars.space4, [mq480]: vars.space8 },
  },
});
