import * as stylex from "@stylexjs/stylex";
import { vars } from "@/components/ads/tokens/tokens.stylex";

const mq480 = "@media (min-width: 480px)";
const mq560 = "@media (min-width: 560px)";

const overlayHover = vars["--ads-color-overlay-hover"];

export const cursorModelConfigStyles = stylex.create({
  fixedChip: {
    display: "flex",
    height: "1.5rem",
    flexShrink: 0,
    alignItems: "center",
    alignSelf: "center",
    borderRadius: vars["--ads-radius-mark"],
    backgroundColor: `color-mix(in oklch, ${vars["--ads-color-canvas-subtle"]} 45%, transparent)`,
    paddingInline: "0.375rem",
    fontSize: vars["--ads-font-size-micro"],
    lineHeight: "1rem",
    fontWeight: vars["--ads-font-weight-medium"],
    color: `color-mix(in oklch, ${vars["--ads-color-text-muted"]} 85%, transparent)`,
  },
  configButton: {
    display: "inline-flex",
    minHeight: "2.75rem",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: vars["--ads-radius-mark"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: "transparent",
    paddingInline: vars["--ads-space-8"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
    color: {
      default: vars["--ads-color-text-muted"],
      ":hover": vars["--ads-color-text"],
    },
    backgroundColor: { default: "transparent", ":hover": overlayHover },
  },
  configButtonPressed: {
    borderColor: `color-mix(in oklch, ${vars["--ads-color-border"]} 70%, transparent)`,
    backgroundColor: `color-mix(in oklch, ${vars["--ads-color-canvas-subtle"]} 70%, transparent)`,
    color: vars["--ads-color-text"],
  },
  configButtonGap: { gap: "0.375rem" },
  configButtonFast: { color: "var(--prompt-role-fast)" },
  configButtonEffort: { width: "2.75rem", height: "2.75rem", paddingInline: 0 },
  row: {
    minWidth: 0,
    borderRadius: vars["--ads-radius-control"],
    paddingInline: { default: vars["--ads-space-4"], [mq480]: vars["--ads-space-8"] },
    paddingBlock: vars["--ads-space-4"],
    backgroundColor: {
      default: "transparent",
      ":hover": `color-mix(in oklch, ${overlayHover} 60%, transparent)`,
    },
  },
  rowSelected: {
    backgroundColor: `color-mix(in oklch, ${vars["--ads-color-selection-fill"]} 70%, transparent)`,
  },
  toolbar: {
    display: "flex",
    minWidth: 0,
    alignItems: "center",
    gap: { default: vars["--ads-space-4"], [mq480]: vars["--ads-space-8"] },
  },
  modelButton: {
    display: "flex",
    minHeight: "2.75rem",
    minWidth: { default: "10rem", [mq480]: "11rem" },
    maxWidth: {
      default: "min(44%, 14rem)",
      [mq480]: "min(42%, 16rem)",
    },
    flexShrink: 0,
    alignItems: "center",
    gap: vars["--ads-space-8"],
    borderRadius: vars["--ads-radius-mark"],
    paddingInline: vars["--ads-space-8"],
    textAlign: "left",
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
    color: vars["--ads-color-text"],
    backgroundColor: { default: "transparent", ":hover": overlayHover },
  },
  modelIcon: { width: "0.875rem", height: "0.875rem", flexShrink: 0 },
  modelLabel: {
    minWidth: 0,
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  defaultLabel: {
    display: { default: "none", [mq560]: "inline" },
    fontSize: vars["--ads-font-size-micro"],
    color: vars["--ads-color-text-muted"],
  },
  controlStrip: {
    display: "flex",
    minWidth: 0,
    flex: 1,
    alignItems: "center",
    gap: vars["--ads-space-4"],
    overflowX: "auto",
    overscrollBehavior: "contain",
  },
  fastIcon: { width: "0.875rem", height: "0.875rem" },
  fastIconFilled: { fill: "currentColor" },
  fastIconFixed: {
    width: "0.75rem",
    height: "0.75rem",
    marginInlineEnd: vars["--ads-space-4"],
    fill: "currentColor",
  },
  effortInner: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "0.125rem",
  },
  effortShortLabel: { fontSize: vars["--ads-font-size-micro"], lineHeight: 1 },
  effortVisual: {
    display: "flex",
    width: "1.25rem",
    height: "1.25rem",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: vars["--ads-radius-mark"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: `color-mix(in oklch, ${vars["--ads-color-text"]} 5%, transparent)`,
    boxShadow: vars["--ads-elevation-raised"],
  },
  effortVisualUnavailable: { opacity: 0.3 },
  effortCheck: { width: "0.75rem", height: "0.75rem" },
  footer: {
    borderTopWidth: vars["--ads-border-width-hairline"],
    borderTopStyle: "solid",
    borderTopColor: `color-mix(in oklch, ${vars["--ads-color-border"]} 65%, transparent)`,
    paddingInline: vars["--ads-space-12"],
    paddingBlock: vars["--ads-space-8"],
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text-muted"],
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-4"],
    padding: { default: vars["--ads-space-4"], [mq480]: vars["--ads-space-8"] },
  },
});
