import * as stylex from "@stylexjs/stylex";
import { vars } from "../ads/tokens/tokens.stylex";

const border70 = `color-mix(in oklch, ${vars.colorBorder} 70%, transparent)`;
const border80 = `color-mix(in oklch, ${vars.colorBorder} 80%, transparent)`;
const mutedHover = `color-mix(in oklch, ${vars.colorCanvasSubtle} 40%, transparent)`;

export const localChangeReviewStyles = stylex.create({
  triggerIcon: { width: 16, height: 16 },

  content: {
    maxHeight: "calc(100vh - 2rem)",
    gridTemplateRows: "auto minmax(0, 1fr) auto",
    gap: 0,
    overflow: "hidden",
    padding: 0,
    maxWidth: { "@media (min-width: 640px)": "42rem" },
  },
  header: {
    borderBottomWidth: vars.borderWidthHairline,
    borderBottomStyle: "solid",
    borderBottomColor: border70,
    paddingInline: vars.space24,
    paddingBlock: vars.space20,
    paddingRight: "3.5rem",
  },
  headerRow: { display: "flex", alignItems: "flex-start", gap: vars.space12 },
  headerBadge: {
    display: "flex",
    width: 40,
    height: 40,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: border70,
    backgroundColor: mutedHover,
    color: vars.colorText,
  },
  iconLg: { width: 20, height: 20 },
  headerText: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: "0.375rem",
  },
  title: { fontSize: vars.fontSizeLead, lineHeight: vars.lineHeightTight },
  description: { lineHeight: "24px" },

  body: {
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    gap: vars.space24,
    overflowY: "auto",
    paddingInline: vars.space24,
    paddingBlock: vars.space20,
  },
  section: { display: "flex", flexDirection: "column", gap: vars.space12 },
  labelStack: { display: "flex", flexDirection: "column", gap: vars.space4 },
  sectionHeaderRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: vars.space8,
  },
  sectionHeading: {
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
  },
  status: {
    display: "flex",
    minHeight: 24,
    alignItems: "center",
    gap: vars.space8,
    fontSize: vars.fontSizeBody,
    color: vars.colorTextMuted,
  },
  iconSm: { width: 14, height: 14 },
  branchName: {
    maxWidth: 192,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },

  cardGrid: {
    display: "grid",
    gap: vars.space8,
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 640px)": "repeat(2, minmax(0, 1fr))",
    },
  },
  scopeCard: {
    display: "flex",
    minHeight: 80,
    alignItems: "flex-start",
    gap: vars.space12,
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    paddingInline: vars.space16,
    paddingBlock: vars.space12,
    textAlign: "start",
  },
  reviewerCard: {
    display: "flex",
    minHeight: 56,
    alignItems: "center",
    gap: vars.space12,
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    paddingInline: vars.space16,
    paddingBlock: vars.space12,
    textAlign: "start",
  },
  focusCard: {
    display: "flex",
    minHeight: 64,
    alignItems: "flex-start",
    gap: "0.625rem",
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    paddingInline: vars.space12,
    paddingBlock: "0.625rem",
    textAlign: "start",
  },
  cardSelected: {
    borderColor: `color-mix(in oklch, ${vars.colorAccent} 50%, transparent)`,
    backgroundColor: `color-mix(in oklch, ${vars.colorAccent} 5%, transparent)`,
  },
  cardUnselected: {
    borderColor: border80,
    backgroundColor: {
      default: vars.colorCanvas,
      ":hover": mutedHover,
    },
  },
  cardUnselectedMuted: {
    borderColor: border80,
    color: { default: vars.colorTextMuted, ":hover": vars.colorText },
    backgroundColor: {
      default: vars.colorCanvas,
      ":hover": mutedHover,
    },
  },
  cardSelectedText: { color: vars.colorText },

  scopeIcon: { marginTop: vars.space2, width: 16, height: 16, flexShrink: 0 },
  scopeIconSelected: { color: vars.colorAccent },
  scopeIconUnselected: { color: vars.colorTextMuted },
  scopeBody: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: vars.space4,
  },
  scopeLabelRow: {
    display: "flex",
    alignItems: "center",
    gap: vars.space8,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    color: vars.colorText,
  },
  defaultTag: {
    borderRadius: vars.radiusMark,
    backgroundColor: vars.colorCanvasSubtle,
    paddingInline: "0.375rem",
    paddingBlock: "0.125rem",
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightRegular,
    color: vars.colorTextMuted,
  },
  scopeDescription: {
    display: "block",
    fontSize: vars.fontSizeBody,
    lineHeight: "20px",
    color: vars.colorTextMuted,
  },
  summaryLine: { fontSize: vars.fontSizeBody, color: vars.colorTextMuted },

  reviewerIcon: { width: 20, height: 20 },
  reviewerLabel: {
    minWidth: 0,
    flex: 1,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
  },
  reviewerCheck: { width: 16, height: 16, color: vars.colorAccent },

  modelSelector: { width: "100%" },
  modelTrigger: {
    height: 44,
    width: "100%",
    maxWidth: "none",
    borderColor: border80,
    backgroundColor: vars.colorCanvas,
    paddingInline: vars.space12,
  },
  modelMenu: { maxWidth: { "@media (min-width: 640px)": "32rem" } },

  focusCheckbox: {
    marginTop: vars.space2,
    display: "flex",
    width: 16,
    height: 16,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: vars.radiusMark,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
  },
  focusCheckboxSelected: {
    borderColor: vars.colorAccent,
    backgroundColor: vars.colorAccent,
    color: vars.colorAccentText,
  },
  focusCheckboxUnselected: { borderColor: vars.colorBorder },
  iconXs: { width: 12, height: 12 },
  focusBody: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: "0.125rem",
  },
  focusLabel: {
    display: "block",
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    color: vars.colorText,
  },
  focusDescription: {
    display: "block",
    fontSize: vars.fontSizeBody,
    lineHeight: "20px",
    color: vars.colorTextMuted,
  },

  instructionsLabel: {
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
  },
  instructionsTextarea: {
    minHeight: 144,
    resize: "vertical",
    fontSize: vars.fontSizeBody,
    lineHeight: "24px",
  },

  footer: {
    alignItems: "center",
    borderTopWidth: vars.borderWidthHairline,
    borderTopStyle: "solid",
    borderTopColor: border70,
    backgroundColor: `color-mix(in oklch, ${vars.colorCanvasSubtle} 20%, transparent)`,
    paddingInline: vars.space24,
    paddingBlock: vars.space16,
    justifyContent: { "@media (min-width: 640px)": "space-between" },
  },
  footerNote: {
    display: "flex",
    alignItems: "center",
    gap: vars.space8,
    fontSize: vars.fontSizeBody,
    color: vars.colorTextMuted,
  },
  footerActions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: vars.space8,
  },
  cancelButton: { height: 44 },
  submitButton: { height: 44, minWidth: 144 },
});
