import * as stylex from "@stylexjs/stylex";
import { vars } from "../ads/tokens/tokens.stylex";

const border70 = `color-mix(in oklch, ${vars["--ads-color-border"]} 70%, transparent)`;
const border80 = `color-mix(in oklch, ${vars["--ads-color-border"]} 80%, transparent)`;
const mutedHover = `color-mix(in oklch, ${vars["--ads-color-canvas-subtle"]} 40%, transparent)`;

export const localChangeReviewStyles = stylex.create({
  triggerIcon: { width: 16, height: 16 },

  content: {
    maxHeight: "calc(100vh - 2rem)",
    gridTemplateRows: "auto minmax(0, 1fr) auto",
    gap: 0,
    overflow: "hidden",
    padding: 0,
    maxWidth: { "@media (min-width: 640px)": "42rem" },
  },
  header: {
    borderBottomWidth: vars["--ads-border-width-hairline"],
    borderBottomStyle: "solid",
    borderBottomColor: border70,
    paddingInline: vars["--ads-space-24"],
    paddingBlock: vars["--ads-space-20"],
    paddingRight: "3.5rem",
  },
  headerRow: { display: "flex", alignItems: "flex-start", gap: vars["--ads-space-12"] },
  headerBadge: {
    display: "flex",
    width: 40,
    height: 40,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: vars["--ads-radius-control"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: border70,
    backgroundColor: mutedHover,
    color: vars["--ads-color-text"],
  },
  iconLg: { width: 20, height: 20 },
  headerText: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: "0.375rem",
  },
  title: { fontSize: vars["--ads-font-size-lead"], lineHeight: vars["--ads-line-height-tight"] },
  description: { lineHeight: "24px" },

  body: {
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-24"],
    overflowY: "auto",
    paddingInline: vars["--ads-space-24"],
    paddingBlock: vars["--ads-space-20"],
  },
  section: { display: "flex", flexDirection: "column", gap: vars["--ads-space-12"] },
  labelStack: { display: "flex", flexDirection: "column", gap: vars["--ads-space-4"] },
  sectionHeaderRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: vars["--ads-space-8"],
  },
  sectionHeading: {
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  status: {
    display: "flex",
    minHeight: 24,
    alignItems: "center",
    gap: vars["--ads-space-8"],
    fontSize: vars["--ads-font-size-body"],
    color: vars["--ads-color-text-muted"],
  },
  iconSm: { width: 14, height: 14 },
  branchName: {
    maxWidth: 192,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },

  cardGrid: {
    display: "grid",
    gap: vars["--ads-space-8"],
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 640px)": "repeat(2, minmax(0, 1fr))",
    },
  },
  scopeCard: {
    display: "flex",
    minHeight: 80,
    alignItems: "flex-start",
    gap: vars["--ads-space-12"],
    borderRadius: vars["--ads-radius-control"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    paddingInline: vars["--ads-space-16"],
    paddingBlock: vars["--ads-space-12"],
    textAlign: "start",
  },
  reviewerCard: {
    display: "flex",
    minHeight: 56,
    alignItems: "center",
    gap: vars["--ads-space-12"],
    borderRadius: vars["--ads-radius-control"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    paddingInline: vars["--ads-space-16"],
    paddingBlock: vars["--ads-space-12"],
    textAlign: "start",
  },
  focusCard: {
    display: "flex",
    minHeight: 64,
    alignItems: "flex-start",
    gap: "0.625rem",
    borderRadius: vars["--ads-radius-control"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    paddingInline: vars["--ads-space-12"],
    paddingBlock: "0.625rem",
    textAlign: "start",
  },
  cardSelected: {
    borderColor: `color-mix(in oklch, ${vars["--ads-color-accent"]} 50%, transparent)`,
    backgroundColor: `color-mix(in oklch, ${vars["--ads-color-accent"]} 5%, transparent)`,
  },
  cardUnselected: {
    borderColor: border80,
    backgroundColor: {
      default: vars["--ads-color-canvas"],
      ":hover": mutedHover,
    },
  },
  cardUnselectedMuted: {
    borderColor: border80,
    color: { default: vars["--ads-color-text-muted"], ":hover": vars["--ads-color-text"] },
    backgroundColor: {
      default: vars["--ads-color-canvas"],
      ":hover": mutedHover,
    },
  },
  cardSelectedText: { color: vars["--ads-color-text"] },

  scopeIcon: { marginTop: vars["--ads-space-2"], width: 16, height: 16, flexShrink: 0 },
  scopeIconSelected: { color: vars["--ads-color-accent"] },
  scopeIconUnselected: { color: vars["--ads-color-text-muted"] },
  scopeBody: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-4"],
  },
  scopeLabelRow: {
    display: "flex",
    alignItems: "center",
    gap: vars["--ads-space-8"],
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
    color: vars["--ads-color-text"],
  },
  defaultTag: {
    borderRadius: vars["--ads-radius-mark"],
    backgroundColor: vars["--ads-color-canvas-subtle"],
    paddingInline: "0.375rem",
    paddingBlock: "0.125rem",
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-regular"],
    color: vars["--ads-color-text-muted"],
  },
  scopeDescription: {
    display: "block",
    fontSize: vars["--ads-font-size-body"],
    lineHeight: "20px",
    color: vars["--ads-color-text-muted"],
  },
  summaryLine: { fontSize: vars["--ads-font-size-body"], color: vars["--ads-color-text-muted"] },

  reviewerIcon: { width: 20, height: 20 },
  reviewerLabel: {
    minWidth: 0,
    flex: 1,
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  reviewerCheck: { width: 16, height: 16, color: vars["--ads-color-accent"] },

  modelSelector: { width: "100%" },
  modelTrigger: {
    height: 44,
    width: "100%",
    maxWidth: "none",
    borderColor: border80,
    backgroundColor: vars["--ads-color-canvas"],
    paddingInline: vars["--ads-space-12"],
  },
  modelMenu: { maxWidth: { "@media (min-width: 640px)": "32rem" } },

  focusCheckbox: {
    marginTop: vars["--ads-space-2"],
    display: "flex",
    width: 16,
    height: 16,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: vars["--ads-radius-mark"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
  },
  focusCheckboxSelected: {
    borderColor: vars["--ads-color-accent"],
    backgroundColor: vars["--ads-color-accent"],
    color: vars["--ads-color-accent-text"],
  },
  focusCheckboxUnselected: { borderColor: vars["--ads-color-border"] },
  iconXs: { width: 12, height: 12 },
  focusBody: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: "0.125rem",
  },
  focusLabel: {
    display: "block",
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
    color: vars["--ads-color-text"],
  },
  focusDescription: {
    display: "block",
    fontSize: vars["--ads-font-size-body"],
    lineHeight: "20px",
    color: vars["--ads-color-text-muted"],
  },

  instructionsLabel: {
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  instructionsTextarea: {
    minHeight: 144,
    resize: "vertical",
    fontSize: vars["--ads-font-size-body"],
    lineHeight: "24px",
  },

  footer: {
    alignItems: "center",
    borderTopWidth: vars["--ads-border-width-hairline"],
    borderTopStyle: "solid",
    borderTopColor: border70,
    backgroundColor: `color-mix(in oklch, ${vars["--ads-color-canvas-subtle"]} 20%, transparent)`,
    paddingInline: vars["--ads-space-24"],
    paddingBlock: vars["--ads-space-16"],
    justifyContent: { "@media (min-width: 640px)": "space-between" },
  },
  footerNote: {
    display: "flex",
    alignItems: "center",
    gap: vars["--ads-space-8"],
    fontSize: vars["--ads-font-size-body"],
    color: vars["--ads-color-text-muted"],
  },
  footerActions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: vars["--ads-space-8"],
  },
  cancelButton: { height: 44 },
  submitButton: { height: 44, minWidth: 144 },
});
