import * as stylex from "@stylexjs/stylex";
import { vars } from "@/components/ads/tokens/tokens.stylex";

const mq480 = "@media (min-width: 480px)";

export const modelEffortGridStyles = stylex.create({
  scroller: {
    minWidth: 0,
    overflowX: "auto",
    overscrollBehaviorX: "contain",
    padding: { default: vars.space4, [mq480]: vars.space8 },
  },
  grid: {
    display: "grid",
    width: "100%",
    alignItems: "center",
    columnGap: { default: 0, [mq480]: vars.space2 },
    rowGap: vars.space4,
    "--model-effort-row-width": { default: "6rem", [mq480]: "6.75rem" },
  },
  columnHeaderModel: {
    paddingInline: vars.space8,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
    color: vars.colorTextMuted,
  },
  columnHeaderEffort: {
    textAlign: "center",
    fontSize: vars.fontSizeMicro,
    fontWeight: vars.fontWeightMedium,
    color: vars.colorTextMuted,
  },
  rowHeader: {
    display: "flex",
    minWidth: 0,
    alignItems: "center",
    gap: vars.space8,
    paddingInline: vars.space8,
  },
  rowHeaderIcon: { width: "0.875rem", height: "0.875rem" },
  rowHeaderLabel: {
    maxWidth: "8rem",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    color: `color-mix(in oklch, ${vars.colorText} 90%, transparent)`,
  },
  defaultBadge: {
    display: { default: "none", [mq480]: "inline-flex" },
    borderRadius: vars.radiusFull,
    backgroundColor: vars.colorCanvasSubtle,
    paddingInline: "0.375rem",
    paddingBlock: "0.125rem",
    fontSize: vars.fontSizeMicro,
    color: vars.colorTextMuted,
  },
  unsupportedCell: {
    display: "flex",
    width: "2.75rem",
    height: "2.75rem",
    alignItems: "center",
    justifyContent: "center",
    color: `color-mix(in oklch, ${vars.colorTextMuted} 45%, transparent)`,
  },
  unsupportedGlyph: {
    display: "flex",
    width: "2rem",
    height: "2rem",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: vars.radiusMark,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "dashed",
    borderColor: `color-mix(in oklch, ${vars.colorBorder} 65%, transparent)`,
    backgroundColor: `color-mix(in oklch, ${vars.colorCanvasSubtle} 25%, transparent)`,
  },
  unsupportedIcon: { width: "0.75rem", height: "0.75rem" },
  cell: {
    display: "flex",
    width: "2.75rem",
    height: "2.75rem",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
    borderRadius: vars.radiusMark,
  },
  cellVisual: {
    display: "flex",
    width: "2rem",
    height: "2rem",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: vars.radiusMark,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: `color-mix(in oklch, ${vars.colorText} 5%, transparent)`,
    color: vars.colorText,
    boxShadow: vars.elevationRaised,
    transitionProperty: "transform",
    transitionDuration: {
      default: vars.motionDurationFast,
      "@media (prefers-reduced-motion: reduce)": "0ms",
    },
  },
  cellVisualSelected: { transform: "scale(1.05)" },
  checkIcon: { width: vars.controlIconSizeMd, height: vars.controlIconSizeMd },
  contents: { display: "contents" },
});
