import * as stylex from "@stylexjs/stylex";
import { vars } from "@/components/ads/tokens/tokens.stylex";

const accent10 = `color-mix(in oklch, ${vars.colorAccent} 10%, transparent)`;

export const modelSelectorStyles = stylex.create({
  root: { position: "relative" },
  trigger: {
    display: "inline-flex",
    height: vars.controlHeight,
    maxWidth: 240,
    alignItems: "center",
    justifyContent: "space-between",
    gap: "0.375rem",
    borderRadius: vars.radiusMark,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: "transparent",
    backgroundColor: {
      default: "transparent",
      ":hover": vars.colorOverlayHover,
    },
    paddingInline: "0.625rem",
    fontSize: vars.fontSizeBody,
    color: vars.colorText,
  },
  triggerOpen: {
    backgroundColor: `color-mix(in oklch, ${vars.colorOverlayHover} 100%, transparent)`,
  },
  triggerLead: {
    display: "flex",
    minWidth: 0,
    alignItems: "center",
    gap: "0.375rem",
  },
  triggerIcon: {
    width: vars.controlIconSizeSm,
    height: vars.controlIconSizeSm,
    flexShrink: 0,
  },
  triggerAccentIcon: {
    width: vars.controlIconSizeSm,
    height: vars.controlIconSizeSm,
    flexShrink: 0,
    color: vars.colorAccent,
  },
  triggerLabel: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  triggerChevron: {
    width: vars.controlIconSizeSm,
    height: vars.controlIconSizeSm,
    color: vars.colorTextMuted,
  },
  dialogContent: {
    overflow: "hidden",
    borderRadius: vars.radiusPanel,
    padding: 0,
    maxWidth: { default: null, "@media (min-width: 640px)": "32rem" },
  },
  command: {
    borderRadius: 0,
    backgroundColor: "transparent",
    padding: 0,
  },
  commandList: {
    maxHeight: "17.5rem",
    paddingInline: vars.space4,
    paddingBottom: vars.space4,
  },
  optionItem: {
    gap: "0.75rem",
    borderRadius: vars.radiusControl,
    paddingInline: vars.space12,
    paddingBlock: "0.625rem",
  },
  optionAccentIcon: {
    width: vars.controlIconSizeMd,
    height: vars.controlIconSizeMd,
    flexShrink: 0,
    color: vars.colorAccent,
  },
  optionIcon: {
    width: vars.controlIconSizeMd,
    height: vars.controlIconSizeMd,
    flexShrink: 0,
  },
  optionBody: {
    display: "flex",
    minWidth: 0,
    flex: 1,
    flexDirection: "column",
  },
  optionTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.375rem",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  optionLabel: { fontWeight: vars.fontWeightMedium },
  optionDefaultBadge: {
    flexShrink: 0,
    borderRadius: vars.radiusMark,
    backgroundColor: accent10,
    paddingInline: vars.space4,
    paddingBlock: "1px",
    fontSize: vars.fontSizeMicro,
    fontWeight: vars.fontWeightMedium,
    lineHeight: vars.lineHeightTight,
    color: vars.colorAccent,
  },
  optionDescription: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: vars.fontSizeCaption,
    color: vars.colorTextMuted,
  },
  groupHeading: {
    display: "flex",
    alignItems: "center",
    gap: "0.375rem",
  },
  groupHeadingIcon: {
    width: vars.controlIconSizeSm,
    height: vars.controlIconSizeSm,
  },
  effortRow: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space8,
    borderTopWidth: vars.borderWidthHairline,
    borderTopStyle: "solid",
    borderTopColor: `color-mix(in oklch, ${vars.colorBorder} 70%, transparent)`,
    paddingInline: vars.space12,
    paddingBlock: vars.space12,
  },
  effortLabel: { fontSize: vars.fontSizeCaption, color: vars.colorTextMuted },
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    borderWidth: 0,
  },
});
