import * as stylex from "@stylexjs/stylex";
import { vars } from "../ads/tokens/tokens.stylex";

const diffStep = "--prompt-diff-step";
const diffIndex = "--prompt-diff-i";

const promptDiffWord = stylex.keyframes({
  from: { opacity: 0, backgroundColor: `color-mix(in oklch, ${vars.colorAccent} 22%, transparent)` },
  to: { opacity: 1, backgroundColor: "transparent" },
});

const pulse = stylex.keyframes({
  "0%, 100%": { opacity: 1 },
  "50%": { opacity: 0.5 },
});

const caretBlink = stylex.keyframes({
  "0%, 49%": { opacity: 1 },
  "50%, 100%": { opacity: 0 },
});

export const promptInputStyles = stylex.create({
  // ---- Editor typography (shared by editor + reveal overlay) ----
  editorTypographyMinimal: {
    fontFamily: vars.fontMono,
    fontSize: "15px",
    lineHeight: "1.75rem",
    letterSpacing: "-0.01em",
  },
  editorTypographyDefault: {
    // Stated, not inherited. The editable is a `contenteditable` div and the
    // placeholder is a sibling `div`; leaving the family to inheritance let
    // whichever ancestor happened to be closest decide, so the placeholder
    // could render in the ADS default stack while the typed text used the
    // app's. `vars.fontSans` resolves to `var(--font-sans)` through
    // `ads-theme.ts`, so both follow the one font setting.
    fontFamily: vars.fontSans,
    fontSize: "18px",
    lineHeight: "2rem",
  },
  enhancementEditorInset: {
    paddingInlineEnd: "2.25rem",
  },

  // ---- Enhancement reveal overlay ----
  revealOverlay: {
    pointerEvents: "none",
    position: "absolute",
    inset: 0,
    userSelect: "none",
    overflow: "hidden",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    overflowWrap: "anywhere",
  },
  revealWord: {
    borderRadius: "3px",
    boxDecorationBreak: "clone",
    WebkitBoxDecorationBreak: "clone",
    animationName: promptDiffWord,
    animationDuration: `var(${diffStep})`,
    animationDelay: `calc(var(${diffStep}) * var(${diffIndex}))`,
    animationTimingFunction: "ease-out",
    animationFillMode: "both",
    "@media (prefers-reduced-motion: reduce)": { animationName: "none" },
  },

  // ---- Runtime trigger icon ----
  runtimeTriggerIcon: {
    position: "relative",
    display: "inline-flex",
    width: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  runtimeTriggerGlyph: { width: 16, height: 16 },
  runtimeTriggerDot: {
    position: "absolute",
    right: -4,
    top: -4,
    width: 8,
    height: 8,
    borderRadius: vars.radiusFull,
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: vars.colorSurface,
  },
  runtimeDotWarning: { backgroundColor: vars.colorWarning },
  runtimeDotCustom: { backgroundColor: vars.colorAccent },
  runtimeDotSuccess: { backgroundColor: vars.colorSuccessBorder },

  // ---- Tone text helpers ----
  toneWarning: { color: vars.colorWarning },
  tonePrimary: { color: vars.colorAccent },
  toneSuccess: { color: vars.colorSuccessText },
  accentThinking: {
    color: {
      default: "var(--prompt-role-thinking)",
      ":hover": "var(--prompt-role-thinking)",
    },
  },
  accentPlan: {
    color: {
      default: "var(--prompt-role-plan)",
      ":hover": "var(--prompt-role-plan)",
    },
  },

  // ---- Shared visually-hidden (sr-only) ----
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    borderWidth: 0,
  },

  // ---- Common icon sizes ----
  // `flexShrink: 0` is not optional on any of these: every composer control is
  // a flex row whose label is `flex: 1`, and in a 3.75rem wing the row is
  // narrower than icon + gap + label. Without it the glyph — not the label —
  // gave up the width and the wing rendered squashed icons.
  icon4: { width: vars.controlIconSizeMd, height: vars.controlIconSizeMd, flexShrink: 0 },
  icon3: { width: 12, height: 12, flexShrink: 0 },
  icon35: { width: vars.controlIconSizeSm, height: vars.controlIconSizeSm, flexShrink: 0 },
  icon35Shrink: { width: vars.controlIconSizeSm, height: vars.controlIconSizeSm, flexShrink: 0 },

  pulseAnimation: {
    animationName: pulse,
    animationDuration: vars.motionDurationLoop,
    animationIterationCount: "infinite",
    "@media (prefers-reduced-motion: reduce)": { animationName: "none" },
  },

  // ---- Surfaces / toolbar buttons ----
  toolbarIconButton: {
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: "transparent",
    backgroundColor: { default: "transparent", ":hover": vars.colorOverlayHover },
    padding: 0,
    color: { default: vars.colorTextMuted, ":hover": vars.colorText },
  },
  floatingSurface: {
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: `color-mix(in oklch, ${vars.colorBorder} 60%, transparent)`,
    backgroundColor: {
      default: `color-mix(in oklch, ${vars.colorCanvas} 90%, transparent)`,
      ":hover": `color-mix(in oklch, ${vars.colorCanvas} 95%, transparent)`,
    },
    color: vars.colorText,
  },
  surfacePrimaryFocus: {
    outline: { default: "none", ":focus-visible": "none" },
    borderColor: { ":focus-visible": "transparent" },
  },

  // ---- Lens annotation popovers ----
  lensPopover72: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space12,
    width: "18rem",
  },
  lensPopover64: {
    display: "flex",
    flexDirection: "column",
    gap: vars.space12,
    width: "16rem",
  },
  fieldGrid: { display: "grid", gap: vars.space8 },
  fieldGridCols2: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: vars.space8,
  },
  fieldLabel: { display: "grid", gap: vars.space4, fontSize: vars.fontSizeCaption },
  fieldLabelText: { fontWeight: vars.fontWeightMedium, color: vars.colorTextMuted },
  inputField: {
    height: 28,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeCaption,
  },
  fullWidth: { width: "100%" },

  scopeIcon: {
    width: "0.875rem",
    height: "0.875rem",
    color: `color-mix(in oklch, ${vars.colorText} 80%, transparent)`,
  },
  cursorDisabled: { cursor: "not-allowed", opacity: 0.6 },
  toneMutedHalf: {
    color: `color-mix(in oklch, ${vars.colorTextMuted} 50%, transparent)`,
  },
  iconThinking: { color: "var(--prompt-role-thinking)" },
  pendingShell: {
    position: "relative",
    zIndex: vars.zIndexPanel,
    borderRadius: vars.radiusPanel,
    backgroundColor: vars.colorSurface,
    outline: "none",
  },

  drawerContent: {
    backgroundColor: vars.colorSurfaceRaised,
    boxShadow: vars.elevationModal,
    maxHeight: "78vh",
  },
  drawerHeader: {
    gap: 6,
    paddingInline: vars.space20,
    paddingBottom: vars.space16,
    paddingTop: vars.space16,
    textAlign: "left",
  },
  rowBaseline: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: vars.space16,
  },
  titleBase: { fontSize: vars.fontSizeLead, fontWeight: vars.fontWeightSemibold },
  toneLabel: { fontSize: vars.fontSizeCaption, fontWeight: vars.fontWeightSemibold },
  drawerScroll: { minHeight: 0, flex: 1, overflowY: "auto" },
  runtimePopover: {
    width: "min(25rem, calc(100vw - 2rem))",
    gap: 0,
    borderRadius: vars.radiusPanel,
    backgroundColor: vars.colorSurfaceRaised,
    padding: 0,
    boxShadow: `${vars.elevationOverlay}, 0 0 0 1px color-mix(in oklch, ${vars.colorText} 10%, transparent)`,
  },
  runtimePopoverHeader: {
    paddingInline: vars.space20,
    paddingBottom: "0.875rem",
    paddingTop: vars.space16,
  },
  mt1: { marginTop: vars.space4 },
  menuSeparator: {
    marginBlock: 6,
    height: 1,
    backgroundColor: `color-mix(in oklch, ${vars.colorBorder} 60%, transparent)`,
  },
  customizeButton: {
    width: "100%",
    justifyContent: "flex-start",
    gap: 6,
    fontSize: vars.fontSizeCaption,
    color: { default: vars.colorTextMuted, ":hover": vars.colorText },
  },

  borderBeamTransition: {
    transitionProperty: "box-shadow",
    transitionDuration: { default: "200ms", "@media (prefers-reduced-motion: reduce)": "0ms" },
    transitionTimingFunction: "ease-out",
  },
  composerShell: {
    position: "relative",
    zIndex: vars.zIndexPanel,
    borderRadius: vars.radiusPanel,
  },
  formBase: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    gap: vars.space12,
    transitionProperty: "border-color, background-color",
    transitionDuration: vars.motionDurationFast,
    transitionTimingFunction: vars.motionEaseStandard,
  },
  formMinimal: {
    gap: vars.space8,
    borderWidth: 0,
    borderTopWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderTopColor: `color-mix(in oklch, ${vars.colorBorder} 60%, transparent)`,
    backgroundColor: "transparent",
    padding: 0,
    paddingTop: vars.space12,
  },
  formDefault: {
    borderRadius: vars.radiusPanel,
    borderWidth: 0,
    backgroundColor: vars.colorSurface,
    padding: vars.space12,
  },
  suggestions: { marginLeft: -6, marginBottom: 2 },
  suggestionChip: {
    height: 28,
    borderRadius: vars.radiusFull,
    backgroundColor: {
      default: `color-mix(in oklch, ${vars.colorSurfaceTint} 40%, transparent)`,
      ":hover": `color-mix(in oklch, ${vars.colorSurfaceTint} 70%, transparent)`,
    },
    paddingInline: "0.875rem",
    fontSize: vars.fontSizeCaption,
    color: { default: vars.colorTextMuted, ":hover": vars.colorText },
  },
  stackSm: { display: "flex", flexDirection: "column", gap: vars.space8 },
  stackMd: { display: "flex", flexDirection: "column", gap: vars.space12 },
  minimalBox: {
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: `color-mix(in oklch, ${vars.colorBorder} 60%, transparent)`,
    backgroundColor: vars.colorCanvas,
    paddingInline: vars.space12,
    paddingBlock: 10,
  },
  minimalRow: { display: "flex", alignItems: "flex-start", gap: vars.space12 },
  promptCaretGlyph: {
    userSelect: "none",
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeLead,
    lineHeight: "1.75rem",
    color: `color-mix(in oklch, ${vars.colorAccent} 90%, transparent)`,
  },
  editorArea: { position: "relative", minWidth: 0, flex: 1 },

  enhanceOverlay: {
    pointerEvents: "none",
    position: "absolute",
    right: 0,
    top: 0,
  },
  enhanceGradientMinimal: {
    paddingLeft: vars.space16,
    backgroundImage: `linear-gradient(to left, ${vars.colorCanvas}, transparent)`,
  },
  enhanceGradientDefault: {
    paddingLeft: vars.space16,
    backgroundImage: `linear-gradient(to left, ${vars.colorSurface}, transparent)`,
  },
  enhanceButtonBase: {
    pointerEvents: "auto",
    opacity: { ":disabled": 1 },
  },
  enhanceBusyMinimal: {
    height: 28,
    gap: 6,
    borderRadius: vars.radiusFull,
    borderColor: `color-mix(in oklch, ${vars.colorAccent} 25%, transparent)`,
    paddingInline: vars.space8,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
    color: vars.colorAccent,
    backgroundColor: vars.colorCanvas,
  },
  enhanceBusyDefault: {
    height: 28,
    gap: 6,
    borderRadius: vars.radiusFull,
    borderColor: `color-mix(in oklch, ${vars.colorAccent} 25%, transparent)`,
    paddingInline: vars.space8,
    fontSize: vars.fontSizeCaption,
    fontWeight: vars.fontWeightMedium,
    color: vars.colorAccent,
    backgroundColor: vars.colorSurface,
  },
  enhanceIdle: {
    width: 28,
    height: 28,
    opacity: { default: 0.7, ":hover": 1 },
  },
  loaderPrimary: { color: vars.colorAccent },
  maxW64: { maxWidth: "16rem" },

  editorReset: {
    resize: "none",
    overflowY: "auto",
    borderRadius: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    paddingInline: 0,
    paddingBlock: 0,
    boxShadow: "none",
    outline: { default: "none", ":focus-visible": "none" },
  },
  editorSizeMinimal: {
    minBlockSize: 32,
    maxBlockSize: 168,
    caretColor: vars.colorAccent,
  },
  editorSizeDefault: {
    minBlockSize: 104,
    maxBlockSize: 240,
  },
  editorProgress: {
    cursor: "progress",
    userSelect: "none",
    color: `color-mix(in oklch, ${vars.colorTextMuted} 70%, transparent)`,
  },
  editorRevealing: {
    cursor: "progress",
    userSelect: "none",
  },
  editorHidden: { opacity: 0 },
  terminalCaret: {
    pointerEvents: "none",
    position: "absolute",
    left: 0,
    top: 6,
    height: 20,
    width: 8,
    borderRadius: 1,
    backgroundColor: `color-mix(in oklch, ${vars.colorText} 85%, transparent)`,
    animationName: caretBlink,
    animationDuration: vars.motionDurationLoop,
    animationIterationCount: "infinite",
    "@media (prefers-reduced-motion: reduce)": { animationName: "none" },
  },
  commandPopover: {
    maxHeight: "min(40rem, var(--available-height))",
    width: "min(44rem, calc(100vw - 2rem))",
    gap: 0,
    overflow: "hidden",
    borderRadius: vars.radiusPanel,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: `color-mix(in oklch, ${vars.colorBorder} 80%, transparent)`,
    backgroundColor: vars.colorSurfaceRaised,
    padding: vars.space4,
    boxShadow: vars.elevationOverlay,
  },
  commandRoot: {
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: `color-mix(in oklch, ${vars.colorBorder} 60%, transparent)`,
    backgroundColor: `color-mix(in oklch, ${vars.colorCanvas} 70%, transparent)`,
    padding: 0,
  },
  commandList: { maxHeight: "32rem", scrollPaddingBlock: vars.space8 },
  itemStandard: {
    minHeight: 56,
    cursor: "pointer",
    alignItems: "flex-start",
    gap: vars.space12,
    borderRadius: vars.radiusControl,
    paddingInline: vars.space12,
    paddingBlock: 10,
  },
  itemTall: {
    height: "4.5rem",
    minHeight: "4.5rem",
    cursor: "pointer",
    alignItems: "flex-start",
    gap: vars.space12,
    overflow: "hidden",
    borderRadius: vars.radiusControl,
    paddingInline: vars.space12,
    paddingBlock: 10,
  },
  /*
   * Icon slots stand next to `minWidth: 0` copy, so they have to opt out of
   * flex shrinking explicitly — a shrinking wrapper squeezes the glyph inside
   * it and the row's leading edge stops lining up.
   */
  iconWrapPrimary: {
    display: "flex",
    flexShrink: 0,
    alignItems: "flex-start",
    paddingBlockStart: vars.space2,
    color: vars.colorAccent,
  },
  iconWrap: {
    display: "flex",
    flexShrink: 0,
    alignItems: "flex-start",
    paddingBlockStart: vars.space2,
  },
  flex1Min: { minWidth: 0, flex: 1 },
  rowCenter: { display: "flex", alignItems: "center", gap: vars.space8 },
  rowCenterMin: {
    display: "flex",
    minWidth: 0,
    alignItems: "center",
    gap: vars.space8,
  },
  fontMedium: { fontWeight: vars.fontWeightMedium },
  truncMedium: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontWeight: vars.fontWeightMedium,
  },
  badgeUpper: {
    height: 20,
    paddingInline: 6,
    fontSize: vars.fontSizeMicro,
    textTransform: "uppercase",
    letterSpacing: "0.025em",
  },
  badgeUpperShrink: {
    height: 20,
    flexShrink: 0,
    paddingInline: 6,
    fontSize: vars.fontSizeMicro,
    textTransform: "uppercase",
    letterSpacing: "0.025em",
  },
  badgeMonoShrink: {
    height: 20,
    flexShrink: 0,
    paddingInline: 6,
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeMicro,
    letterSpacing: "0.025em",
  },
  badgePlain: { height: 20, paddingInline: 6, fontSize: vars.fontSizeMicro },
  itemDesc: {
    marginTop: vars.space2,
    fontSize: vars.fontSizeCaption,
    color: vars.colorTextMuted,
  },
  itemDescClamp: {
    marginTop: vars.space2,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
    fontSize: vars.fontSizeCaption,
    lineHeight: "16px",
    color: vars.colorTextMuted,
  },
  iconMuted: { inlineSize: vars.controlIconSizeMd, blockSize: vars.controlIconSizeMd, flexShrink: 0, color: vars.colorTextMuted },
  paletteFooter: {
    borderTopWidth: vars.borderWidthHairline,
    borderTopStyle: "solid",
    borderTopColor: `color-mix(in oklch, ${vars.colorBorder} 70%, transparent)`,
    paddingInline: vars.space12,
    paddingBlock: 10,
    fontSize: vars.fontSizeCaption,
    color: vars.colorTextMuted,
  },
  paletteFooterTitle: {
    display: "flex",
    alignItems: "center",
    gap: vars.space8,
    fontWeight: vars.fontWeightMedium,
    color: vars.colorText,
  },
  paletteFooterTitlePlain: {
    fontWeight: vars.fontWeightMedium,
    color: vars.colorText,
  },
  mt2: { marginTop: vars.space8 },
  mt2Title: {
    marginTop: vars.space8,
    fontWeight: vars.fontWeightMedium,
    color: vars.colorText,
  },
  mt1Pre: { marginTop: vars.space4, whiteSpace: "pre-line" },

  commentBox: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: `color-mix(in oklch, ${vars.colorBorder} 60%, transparent)`,
    backgroundColor: `color-mix(in oklch, ${vars.colorSurfaceTint} 15%, transparent)`,
    paddingInline: vars.space12,
    paddingBlock: vars.space8,
  },
  captionMuted: { fontSize: vars.fontSizeCaption, color: vars.colorTextMuted },
  flexWrapGap: { display: "flex", flexWrap: "wrap", gap: 6 },
  commentChip: {
    display: "flex",
    maxWidth: "100%",
    alignItems: "center",
    gap: 6,
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: `color-mix(in oklch, ${vars.colorBorder} 70%, transparent)`,
    backgroundColor: `color-mix(in oklch, ${vars.colorCanvas} 75%, transparent)`,
    paddingInline: vars.space8,
    paddingBlock: vars.space4,
    fontSize: vars.fontSizeCaption,
  },
  chipIndex: {
    flexShrink: 0,
    fontWeight: vars.fontWeightMedium,
    color: vars.colorTextMuted,
  },
  chipTrunc: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: vars.colorText,
  },
  chipAttachCount: {
    display: "inline-flex",
    flexShrink: 0,
    alignItems: "center",
    gap: vars.space2,
    color: vars.colorTextMuted,
  },
  chipRemove: {
    borderRadius: vars.radiusMark,
    padding: vars.space2,
    color: { default: vars.colorTextMuted, ":hover": vars.colorText },
  },
  lensChip: {
    display: "flex",
    maxWidth: "100%",
    alignItems: "center",
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: `color-mix(in oklch, ${vars.colorBorder} 70%, transparent)`,
    backgroundColor: `color-mix(in oklch, ${vars.colorSurfaceTint} 50%, transparent)`,
    fontSize: vars.fontSizeCaption,
    color: vars.colorText,
  },
  lensChipTrigger: {
    display: "flex",
    minWidth: 0,
    alignItems: "center",
    gap: 6,
    paddingInline: vars.space8,
    paddingBlock: vars.space4,
    backgroundColor: {
      default: "transparent",
      ":hover": `color-mix(in oklch, ${vars.colorSurfaceTint} 70%, transparent)`,
    },
  },
  truncPlain: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  maxW80: { maxWidth: "20rem" },
  lensPopoverContent: {
    maxHeight: "24rem",
    width: "min(42rem, calc(100vw - 2rem))",
    overflow: "auto",
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: `color-mix(in oklch, ${vars.colorBorder} 80%, transparent)`,
    backgroundColor: vars.colorSurfaceRaised,
    padding: vars.space12,
    boxShadow: vars.elevationOverlay,
  },
  lensPre: {
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeCaption,
    lineHeight: "20px",
    color: vars.colorText,
  },
  lensChipRemove: {
    borderLeftWidth: vars.borderWidthHairline,
    borderLeftStyle: "solid",
    borderLeftColor: `color-mix(in oklch, ${vars.colorBorder} 70%, transparent)`,
    paddingInline: 6,
    paddingBlock: vars.space4,
    color: { default: vars.colorTextMuted, ":hover": vars.colorText },
  },

  annotationChip: {
    display: "flex",
    maxWidth: "100%",
    alignItems: "flex-start",
    gap: vars.space8,
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: `color-mix(in oklch, ${vars.colorBorder} 70%, transparent)`,
    backgroundColor: `color-mix(in oklch, ${vars.colorSurfaceTint} 50%, transparent)`,
    paddingInline: vars.space8,
    paddingBlock: 6,
    fontSize: vars.fontSizeCaption,
    color: vars.colorText,
  },
  annotationPin: {
    marginTop: vars.space2,
    display: "flex",
    width: 20,
    height: 20,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: vars.radiusFull,
    backgroundColor: vars.colorAccent,
    fontSize: vars.fontSizeMicro,
    fontWeight: vars.fontWeightSemibold,
    color: vars.colorAccentText,
  },
  screenshotButton: {
    flexShrink: 0,
    borderRadius: vars.radiusMark,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: {
      default: `color-mix(in oklch, ${vars.colorBorder} 70%, transparent)`,
      ":hover": vars.colorBorder,
    },
    backgroundColor: vars.colorCanvas,
    padding: vars.space2,
  },
  screenshotImage: {
    height: 40,
    width: 64,
    borderRadius: 2,
    objectFit: "cover",
  },
  annotationTextButton: {
    minWidth: 0,
    flex: 1,
    textAlign: "left",
    color: { ":hover": vars.colorText },
  },
  annotationComment: {
    display: "block",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontWeight: vars.fontWeightMedium,
  },
  annotationMeta: {
    display: "block",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: vars.fontSizeMicro,
    color: vars.colorTextMuted,
  },

  attachmentsRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 6,
  },
  attachmentsCount: {
    display: "inline-flex",
    alignItems: "center",
    gap: vars.space4,
    fontSize: vars.fontSizeCaption,
    color: vars.colorTextMuted,
  },
  fileChip: {
    display: "flex",
    maxWidth: "100%",
    alignItems: "center",
    borderRadius: vars.radiusMark,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    padding: vars.space2,
    fontSize: vars.fontSizeBody,
  },
  fileChipMinimal: {
    borderColor: `color-mix(in oklch, ${vars.colorBorder} 60%, transparent)`,
    backgroundColor: "transparent",
    fontFamily: vars.fontMono,
    fontSize: vars.fontSizeCaption,
    color: vars.colorTextMuted,
  },
  fileChipDefault: {
    borderColor: `color-mix(in oklch, ${vars.colorBorder} 80%, transparent)`,
    backgroundColor: `color-mix(in oklch, ${vars.colorSurfaceTint} 50%, transparent)`,
  },
  fileOpenButton: {
    height: 28,
    minWidth: 0,
    justifyContent: "flex-start",
    gap: vars.space4,
    borderRadius: vars.radiusMark,
    paddingInline: 6,
    fontFamily: "inherit",
    fontSize: "inherit",
    color: "inherit",
  },
  fileRemoveButton: {
    flexShrink: 0,
    color: { default: vars.colorTextMuted, ":hover": vars.colorText },
  },
  imageChip: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    gap: vars.space4,
    borderRadius: vars.radiusMark,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    padding: vars.space4,
  },
  imageChipMinimal: {
    borderColor: `color-mix(in oklch, ${vars.colorBorder} 60%, transparent)`,
    backgroundColor: "transparent",
  },
  imageChipDefault: {
    borderColor: `color-mix(in oklch, ${vars.colorBorder} 80%, transparent)`,
    backgroundColor: `color-mix(in oklch, ${vars.colorSurfaceTint} 50%, transparent)`,
  },
  imagePreviewButton: {
    borderRadius: vars.radiusMark,
    outline: "none",
  },
  imagePreview: {
    maxHeight: 64,
    maxWidth: 96,
    cursor: "zoom-in",
    borderRadius: vars.radiusMark,
    objectFit: "cover",
  },
  imageRemoveButton: {
    position: "absolute",
    right: -4,
    top: -4,
    borderRadius: vars.radiusFull,
    backgroundColor: { default: vars.colorCanvas, ":hover": vars.colorCanvas },
    color: { default: vars.colorTextMuted, ":hover": vars.colorText },
    boxShadow: vars.elevationRaised,
  },

  toolbarRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: vars.space8,
  },
  toolbarRowEnd: { justifyContent: "flex-end" },
  actionsRow: { display: "flex", alignItems: "center", gap: vars.space8 },
  controlLane: {
    position: "relative",
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    // The row's own gap, on the space scale, matching `toolbarRow` and
    // `actionsRow` either side of it.
    gap: vars.space8,
  },
  customizeAnchor: {
    pointerEvents: "none",
    position: "absolute",
    left: 0,
    top: 0,
    width: 0,
    height: 0,
  },
  customizePopover: {
    width: "min(30rem, calc(100vw - 2rem))",
    gap: 0,
    borderRadius: vars.radiusPanel,
    backgroundColor: vars.colorSurfaceRaised,
    padding: vars.space8,
    boxShadow: `${vars.elevationOverlay}, 0 0 0 1px color-mix(in oklch, ${vars.colorText} 10%, transparent)`,
  },
  customizeTitle: {
    paddingInline: vars.space8,
    paddingBottom: vars.space4,
    paddingTop: vars.space4,
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightSemibold,
  },
  attachButtonMinimal: {
    height: 32,
    width: 32,
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: `color-mix(in oklch, ${vars.colorBorder} 60%, transparent)`,
    backgroundColor: {
      default: `color-mix(in oklch, ${vars.colorCanvas} 50%, transparent)`,
      ":hover": `color-mix(in oklch, ${vars.colorSurfaceTint} 40%, transparent)`,
    },
    color: vars.colorText,
  },
  stopButton: {
    color: {
      default: vars.colorDanger,
      ":hover": vars.colorDanger,
    },
    backgroundColor: {
      ":hover": `color-mix(in oklch, ${vars.colorDanger} 10%, transparent)`,
    },
  },
  stopButtonMinimal: {
    height: 32,
    width: 32,
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: `color-mix(in oklch, ${vars.colorDanger} 30%, transparent)`,
    backgroundColor: `color-mix(in oklch, ${vars.colorCanvas} 50%, transparent)`,
  },
  inlineGap1: { display: "inline-flex", alignItems: "center", gap: vars.space4 },
  roundedMd: { borderRadius: vars.radiusControl },
  sendButtonMinimal: {
    height: 32,
    width: 32,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: `color-mix(in oklch, ${vars.colorAccent} 40%, transparent)`,
    backgroundColor: {
      default: `color-mix(in oklch, ${vars.colorAccent} 10%, transparent)`,
      ":hover": `color-mix(in oklch, ${vars.colorAccent} 15%, transparent)`,
    },
    color: vars.colorAccent,
  },
  tooltipColStart: {
    flexDirection: "column",
    alignItems: "flex-start",
    gap: vars.space2,
  },
  inlineGapBg70: {
    display: "inline-flex",
    alignItems: "center",
    gap: vars.space4,
    color: `color-mix(in oklch, ${vars.colorTextInverted} 70%, transparent)`,
  },
  // The stop glyph, not a control icon: it is a filled square drawn inside an
  // icon button, so it stays off the `controlIconSizes` ramp on purpose. What
  // it did need is a fixed box that cannot shrink in the actions row.
  iconSquare: { inlineSize: 12, blockSize: 12, flexShrink: 0, fill: "currentColor" },
});