import * as stylex from "@stylexjs/stylex";
import { vars } from "../ads/tokens/tokens.stylex";

const softHover = `color-mix(in oklch, ${vars.colorCanvas} 75%, transparent)`;

export const userInputCardStyles = stylex.create({
  // ── Summary card ─────────────────────────────────────────────
  summary: {
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: `color-mix(in oklch, ${vars.colorBorder} 70%, transparent)`,
    backgroundColor: `color-mix(in oklch, ${vars.colorCanvas} 70%, transparent)`,
    padding: vars.space12,
    fontSize: "0.8125rem",
  },
  summaryRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: "0.625rem",
  },
  summaryBadge: {
    display: "flex",
    width: 28,
    height: 28,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: vars.radiusMark,
    backgroundColor: `color-mix(in oklch, ${vars.colorAccent} 10%, transparent)`,
    color: vars.colorAccent,
  },
  iconSm: { width: 14, height: 14 },
  summaryBody: { minWidth: 0, flex: 1 },
  summaryTitle: { fontWeight: vars.fontWeightMedium, color: vars.colorText },
  summaryDetail: {
    marginTop: vars.space2,
    fontSize: vars.fontSizeCaption,
    lineHeight: "20px",
    color: vars.colorTextMuted,
  },
  summaryFirstQuestion: {
    marginTop: vars.space8,
    color: vars.colorText,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  summaryMoreCount: { color: vars.colorTextMuted },
  answerList: {
    marginTop: vars.space8,
    display: "flex",
    flexDirection: "column",
    gap: "0.375rem",
  },
  answerRow: {
    display: "grid",
    gridTemplateColumns: "minmax(0,0.45fr) minmax(0,1fr)",
    gap: vars.space12,
  },
  answerTerm: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: vars.colorTextMuted,
  },
  answerValue: {
    minWidth: 0,
    color: vars.colorText,
    wordBreak: "break-word",
  },

  // ── Form ─────────────────────────────────────────────────────
  formBase: { fontSize: vars.fontSizeBody },
  formInline: {
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: `color-mix(in oklch, ${vars.colorBorder} 70%, transparent)`,
    backgroundColor: `color-mix(in oklch, ${vars.colorCanvas} 80%, transparent)`,
    padding: vars.space12,
  },
  formComposer: {
    display: "flex",
    maxHeight: "min(60vh, 34rem)",
    flexDirection: "column",
    padding: {
      default: vars.space16,
      "@media (min-width: 640px)": vars.space20,
    },
  },
  header: {
    display: "flex",
    flexShrink: 0,
    alignItems: "flex-start",
    gap: vars.space12,
  },
  headerBadge: {
    display: "flex",
    width: 32,
    height: 32,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: vars.radiusControl,
    backgroundColor: `color-mix(in oklch, ${vars.colorAccent} 10%, transparent)`,
    color: vars.colorAccent,
  },
  iconMd: { width: 16, height: 16 },
  headerBody: { minWidth: 0, flex: 1 },
  headerTitle: {
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightSemibold,
    lineHeight: "20px",
    color: vars.colorText,
  },
  headerDetail: {
    marginTop: vars.space2,
    fontSize: vars.fontSizeCaption,
    lineHeight: "20px",
    color: vars.colorTextMuted,
  },
  questionsWrap: { marginTop: vars.space16 },
  questionsWrapComposer: {
    marginInline: `calc(-1 * ${vars.space4})`,
    minHeight: 0,
    flex: 1,
    overflowY: "auto",
    overscrollBehavior: "contain",
    paddingInline: vars.space4,
  },
  questionBlock: {},
  questionBlockDivided: {
    marginTop: vars.space16,
    borderTopWidth: vars.borderWidthHairline,
    borderTopStyle: "solid",
    borderTopColor: `color-mix(in oklch, ${vars.colorBorder} 60%, transparent)`,
    paddingTop: vars.space16,
  },
  fieldset: { minWidth: 0 },
  legend: { width: "100%" },
  legendHeaderRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: vars.space12,
    fontSize: vars.fontSizeCaption,
    lineHeight: "16px",
    color: vars.colorTextMuted,
  },
  legendHeader: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontWeight: vars.fontWeightMedium,
  },
  legendHint: { flexShrink: 0 },
  legendQuestion: {
    marginTop: "0.375rem",
    display: "block",
    maxWidth: "48rem",
    fontSize: vars.fontSizeBody,
    fontWeight: vars.fontWeightMedium,
    lineHeight: "24px",
    color: vars.colorText,
  },

  optionsGrid: {
    marginTop: vars.space12,
    display: "grid",
    gap: vars.space8,
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 640px)": "repeat(2, minmax(0, 1fr))",
    },
  },
  option: {
    position: "relative",
    display: "flex",
    minHeight: 44,
    minWidth: 0,
    cursor: "pointer",
    alignItems: "flex-start",
    gap: vars.space12,
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: {
      default: `color-mix(in oklch, ${vars.colorBorder} 80%, transparent)`,
      ":hover": `color-mix(in oklch, ${vars.colorText} 20%, transparent)`,
    },
    backgroundColor: {
      default: `color-mix(in oklch, ${vars.colorCanvas} 45%, transparent)`,
      ":hover": softHover,
    },
    paddingInline: vars.space12,
    paddingBlock: "0.625rem",
    transitionProperty: "background-color, border-color, box-shadow",
    transitionDuration: {
      default: "150ms",
      "@media (prefers-reduced-motion: reduce)": "0ms",
    },
    transitionTimingFunction: "cubic-bezier(0.16, 1, 0.3, 1)",
  },
  optionSelected: {
    borderColor: `color-mix(in oklch, ${vars.colorAccent} 45%, transparent)`,
    backgroundColor: `color-mix(in oklch, ${vars.colorAccent} 6%, transparent)`,
    boxShadow: `inset 0 0 0 1px color-mix(in oklch, ${vars.colorAccent} 12%, transparent)`,
  },
  optionDisabled: {
    pointerEvents: "none",
    cursor: "not-allowed",
    opacity: 0.45,
  },
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    borderWidth: 0,
  },
  optionMark: {
    marginTop: vars.space2,
    display: "flex",
    width: 16,
    height: 16,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
  },
  optionMarkCheckbox: { borderRadius: 4 },
  optionMarkRadio: { borderRadius: vars.radiusFull },
  optionMarkSelected: {
    borderColor: vars.colorAccent,
    backgroundColor: vars.colorAccent,
    color: vars.colorAccentText,
  },
  optionMarkUnselected: {
    borderColor: vars.colorBorder,
    backgroundColor: vars.colorCanvas,
  },
  iconXs: { width: 12, height: 12 },
  radioDot: {
    width: 6,
    height: 6,
    borderRadius: vars.radiusFull,
    backgroundColor: vars.colorAccentText,
  },
  optionBody: { minWidth: 0, flex: 1 },
  optionLabelRow: {
    display: "flex",
    minWidth: 0,
    flexWrap: "wrap",
    alignItems: "center",
    gap: "0.375rem",
  },
  optionLabel: {
    fontWeight: vars.fontWeightMedium,
    lineHeight: "20px",
    color: vars.colorText,
  },
  recommendedBadge: {
    height: 16,
    paddingInline: vars.space4,
    fontSize: vars.fontSizeMicro,
  },
  optionDescription: {
    marginTop: vars.space2,
    display: "block",
    fontSize: vars.fontSizeCaption,
    lineHeight: "20px",
    color: vars.colorTextMuted,
  },

  urlNotice: {
    marginTop: vars.space12,
    display: "flex",
    flexDirection: {
      default: "column",
      "@media (min-width: 640px)": "row",
    },
    gap: vars.space8,
    borderRadius: vars.radiusControl,
    borderWidth: vars.borderWidthHairline,
    borderStyle: "solid",
    borderColor: `color-mix(in oklch, ${vars.colorBorder} 70%, transparent)`,
    backgroundColor: `color-mix(in oklch, ${vars.colorCanvasSubtle} 20%, transparent)`,
    padding: vars.space12,
    alignItems: { "@media (min-width: 640px)": "center" },
  },
  urlNoticeText: {
    minWidth: 0,
    flex: 1,
    fontSize: vars.fontSizeCaption,
    lineHeight: "20px",
    color: vars.colorTextMuted,
    wordBreak: "break-all",
  },
  urlNoticeButton: {
    alignSelf: {
      default: "flex-start",
      "@media (min-width: 640px)": "auto",
    },
  },

  customToggle: {
    marginTop: "0.625rem",
    marginLeft: `calc(-1 * ${vars.space8})`,
    fontSize: vars.fontSizeCaption,
  },
  customInputWrap: { marginTop: vars.space8 },
  customTextarea: {
    minHeight: 80,
    maxHeight: 160,
    resize: "vertical",
    fontSize: vars.fontSizeBody,
  },

  footer: {
    marginTop: vars.space16,
    display: "flex",
    flexShrink: 0,
    flexWrap: "wrap",
    alignItems: "center",
    gap: vars.space8,
    borderTopWidth: vars.borderWidthHairline,
    borderTopStyle: "solid",
    borderTopColor: `color-mix(in oklch, ${vars.colorBorder} 60%, transparent)`,
    paddingTop: vars.space16,
  },
  disabledReason: {
    flexBasis: "100%",
    fontSize: vars.fontSizeCaption,
    lineHeight: "20px",
    color: vars.colorTextMuted,
  },
});
