import * as stylex from "@stylexjs/stylex";
import { vars } from "../ads/tokens/tokens.stylex";

const softHover = `color-mix(in oklch, ${vars["--ads-color-canvas"]} 75%, transparent)`;

export const userInputCardStyles = stylex.create({
  // ── Summary card ─────────────────────────────────────────────
  summary: {
    borderRadius: vars["--ads-radius-control"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: `color-mix(in oklch, ${vars["--ads-color-border"]} 70%, transparent)`,
    backgroundColor: `color-mix(in oklch, ${vars["--ads-color-canvas"]} 70%, transparent)`,
    padding: vars["--ads-space-12"],
    fontSize: "0.8125rem",
  },
  summaryRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: "0.625rem",
  },
  summaryBadge: {
    display: "flex",
    width: 28,
    height: 28,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: vars["--ads-radius-mark"],
    backgroundColor: `color-mix(in oklch, ${vars["--ads-color-accent"]} 10%, transparent)`,
    color: vars["--ads-color-accent"],
  },
  iconSm: { width: 14, height: 14 },
  summaryBody: { minWidth: 0, flex: 1 },
  summaryTitle: { fontWeight: vars["--ads-font-weight-medium"], color: vars["--ads-color-text"] },
  summaryDetail: {
    marginTop: vars["--ads-space-2"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: "20px",
    color: vars["--ads-color-text-muted"],
  },
  summaryFirstQuestion: {
    marginTop: vars["--ads-space-8"],
    color: vars["--ads-color-text"],
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  summaryMoreCount: { color: vars["--ads-color-text-muted"] },
  answerList: {
    marginTop: vars["--ads-space-8"],
    display: "flex",
    flexDirection: "column",
    gap: "0.375rem",
  },
  answerRow: {
    display: "grid",
    gridTemplateColumns: "minmax(0,0.45fr) minmax(0,1fr)",
    gap: vars["--ads-space-12"],
  },
  answerTerm: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: vars["--ads-color-text-muted"],
  },
  answerValue: {
    minWidth: 0,
    color: vars["--ads-color-text"],
    wordBreak: "break-word",
  },

  // ── Form ─────────────────────────────────────────────────────
  formBase: { fontSize: vars["--ads-font-size-body"] },
  formInline: {
    borderRadius: vars["--ads-radius-control"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: `color-mix(in oklch, ${vars["--ads-color-border"]} 70%, transparent)`,
    backgroundColor: `color-mix(in oklch, ${vars["--ads-color-canvas"]} 80%, transparent)`,
    padding: vars["--ads-space-12"],
  },
  formComposer: {
    display: "flex",
    maxHeight: "min(60vh, 34rem)",
    flexDirection: "column",
    padding: {
      default: vars["--ads-space-16"],
      "@media (min-width: 640px)": vars["--ads-space-20"],
    },
  },
  header: {
    display: "flex",
    flexShrink: 0,
    alignItems: "flex-start",
    gap: vars["--ads-space-12"],
  },
  headerBadge: {
    display: "flex",
    width: 32,
    height: 32,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: vars["--ads-radius-control"],
    backgroundColor: `color-mix(in oklch, ${vars["--ads-color-accent"]} 10%, transparent)`,
    color: vars["--ads-color-accent"],
  },
  iconMd: { width: 16, height: 16 },
  headerBody: { minWidth: 0, flex: 1 },
  headerTitle: {
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-semibold"],
    lineHeight: "20px",
    color: vars["--ads-color-text"],
  },
  headerDetail: {
    marginTop: vars["--ads-space-2"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: "20px",
    color: vars["--ads-color-text-muted"],
  },
  questionsWrap: { marginTop: vars["--ads-space-16"] },
  questionsWrapComposer: {
    marginInline: `calc(-1 * ${vars["--ads-space-4"]})`,
    minHeight: 0,
    flex: 1,
    overflowY: "auto",
    overscrollBehavior: "contain",
    paddingInline: vars["--ads-space-4"],
  },
  questionBlock: {},
  questionBlockDivided: {
    marginTop: vars["--ads-space-16"],
    borderTopWidth: vars["--ads-border-width-hairline"],
    borderTopStyle: "solid",
    borderTopColor: `color-mix(in oklch, ${vars["--ads-color-border"]} 60%, transparent)`,
    paddingTop: vars["--ads-space-16"],
  },
  fieldset: { minWidth: 0 },
  legend: { width: "100%" },
  legendHeaderRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: vars["--ads-space-12"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: "16px",
    color: vars["--ads-color-text-muted"],
  },
  legendHeader: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontWeight: vars["--ads-font-weight-medium"],
  },
  legendHint: { flexShrink: 0 },
  legendQuestion: {
    marginTop: "0.375rem",
    display: "block",
    maxWidth: "48rem",
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
    lineHeight: "24px",
    color: vars["--ads-color-text"],
  },

  optionsGrid: {
    marginTop: vars["--ads-space-12"],
    display: "grid",
    gap: vars["--ads-space-8"],
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 640px)": "repeat(2, minmax(0, 1fr))",
    },
  },
  option: {
    position: "relative",
    display: "flex",
    minHeight: 44,
    minWidth: 0,
    cursor: "pointer",
    alignItems: "flex-start",
    gap: vars["--ads-space-12"],
    borderRadius: vars["--ads-radius-control"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: {
      default: `color-mix(in oklch, ${vars["--ads-color-border"]} 80%, transparent)`,
      ":hover": `color-mix(in oklch, ${vars["--ads-color-text"]} 20%, transparent)`,
    },
    backgroundColor: {
      default: `color-mix(in oklch, ${vars["--ads-color-canvas"]} 45%, transparent)`,
      ":hover": softHover,
    },
    paddingInline: vars["--ads-space-12"],
    paddingBlock: "0.625rem",
    transitionProperty: "background-color, border-color, box-shadow",
    transitionDuration: {
      default: "150ms",
      "@media (prefers-reduced-motion: reduce)": "0ms",
    },
    transitionTimingFunction: "cubic-bezier(0.16, 1, 0.3, 1)",
  },
  optionSelected: {
    borderColor: `color-mix(in oklch, ${vars["--ads-color-accent"]} 45%, transparent)`,
    backgroundColor: `color-mix(in oklch, ${vars["--ads-color-accent"]} 6%, transparent)`,
    boxShadow: `inset 0 0 0 1px color-mix(in oklch, ${vars["--ads-color-accent"]} 12%, transparent)`,
  },
  optionDisabled: {
    pointerEvents: "none",
    cursor: "not-allowed",
    opacity: 0.45,
  },
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    borderWidth: 0,
  },
  optionMark: {
    marginTop: vars["--ads-space-2"],
    display: "flex",
    width: 16,
    height: 16,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
  },
  optionMarkCheckbox: { borderRadius: 4 },
  optionMarkRadio: { borderRadius: vars["--ads-radius-full"] },
  optionMarkSelected: {
    borderColor: vars["--ads-color-accent"],
    backgroundColor: vars["--ads-color-accent"],
    color: vars["--ads-color-accent-text"],
  },
  optionMarkUnselected: {
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-canvas"],
  },
  iconXs: { width: 12, height: 12 },
  radioDot: {
    width: 6,
    height: 6,
    borderRadius: vars["--ads-radius-full"],
    backgroundColor: vars["--ads-color-accent-text"],
  },
  optionBody: { minWidth: 0, flex: 1 },
  optionLabelRow: {
    display: "flex",
    minWidth: 0,
    flexWrap: "wrap",
    alignItems: "center",
    gap: "0.375rem",
  },
  optionLabel: {
    fontWeight: vars["--ads-font-weight-medium"],
    lineHeight: "20px",
    color: vars["--ads-color-text"],
  },
  recommendedBadge: {
    height: 16,
    paddingInline: vars["--ads-space-4"],
    fontSize: vars["--ads-font-size-micro"],
  },
  optionDescription: {
    marginTop: vars["--ads-space-2"],
    display: "block",
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: "20px",
    color: vars["--ads-color-text-muted"],
  },

  urlNotice: {
    marginTop: vars["--ads-space-12"],
    display: "flex",
    flexDirection: {
      default: "column",
      "@media (min-width: 640px)": "row",
    },
    gap: vars["--ads-space-8"],
    borderRadius: vars["--ads-radius-control"],
    borderWidth: vars["--ads-border-width-hairline"],
    borderStyle: "solid",
    borderColor: `color-mix(in oklch, ${vars["--ads-color-border"]} 70%, transparent)`,
    backgroundColor: `color-mix(in oklch, ${vars["--ads-color-canvas-subtle"]} 20%, transparent)`,
    padding: vars["--ads-space-12"],
    alignItems: { "@media (min-width: 640px)": "center" },
  },
  urlNoticeText: {
    minWidth: 0,
    flex: 1,
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: "20px",
    color: vars["--ads-color-text-muted"],
    wordBreak: "break-all",
  },
  urlNoticeButton: {
    alignSelf: {
      default: "flex-start",
      "@media (min-width: 640px)": "auto",
    },
  },

  customToggle: {
    marginTop: "0.625rem",
    marginLeft: `calc(-1 * ${vars["--ads-space-8"]})`,
    fontSize: vars["--ads-font-size-caption"],
  },
  customInputWrap: { marginTop: vars["--ads-space-8"] },
  customTextarea: {
    minHeight: 80,
    maxHeight: 160,
    resize: "vertical",
    fontSize: vars["--ads-font-size-body"],
  },

  footer: {
    marginTop: vars["--ads-space-16"],
    display: "flex",
    flexShrink: 0,
    flexWrap: "wrap",
    alignItems: "center",
    gap: vars["--ads-space-8"],
    borderTopWidth: vars["--ads-border-width-hairline"],
    borderTopStyle: "solid",
    borderTopColor: `color-mix(in oklch, ${vars["--ads-color-border"]} 60%, transparent)`,
    paddingTop: vars["--ads-space-16"],
  },
  disabledReason: {
    flexBasis: "100%",
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: "20px",
    color: vars["--ads-color-text-muted"],
  },
});
