import * as stylex from "@stylexjs/stylex";
import { vars } from "../ads/tokens/tokens.stylex";

/** Shared mission styles. Existing ADS tokens only; no new theme colors. */
export const missionStyles = stylex.create({
  /* Mission bar ------------------------------------------------------------ */
  bar: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-4"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: vars["--ads-color-border-subtle"],
    backgroundColor: vars["--ads-color-surface"],
    containerType: "inline-size",
    minWidth: 0,
  },
  barHeader: {
    display: "flex",
    alignItems: "baseline",
    gap: vars["--ads-space-8"],
    minWidth: 0,
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
  },
  barTitle: {
    flex: "1 1 auto",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontWeight: vars["--ads-font-weight-medium"],
    color: vars["--ads-color-text"],
  },
  barMeta: {
    flex: "0 0 auto",
    color: vars["--ads-color-text-muted"],
    whiteSpace: "nowrap",
  },
  stepper: {
    display: { default: "flex", "@container (max-width: 30rem)": "none" },
    flexWrap: "wrap",
    alignItems: "center",
    gap: vars["--ads-space-12"],
    margin: 0,
    padding: 0,
    listStyle: "none",
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
  },
  stepperCompact: {
    display: { default: "none", "@container (max-width: 30rem)": "flex" },
    alignItems: "center",
    gap: vars["--ads-space-4"],
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text"],
  },
  step: {
    display: "inline-flex",
    alignItems: "center",
    gap: vars["--ads-space-4"],
    color: vars["--ads-color-text-muted"],
    whiteSpace: "nowrap",
  },
  stepCurrent: {
    color: vars["--ads-color-text"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  nowRow: {
    display: "flex",
    alignItems: "baseline",
    gap: vars["--ads-space-8"],
    minWidth: 0,
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
  },
  nowLabel: {
    flex: "0 0 auto",
    color: vars["--ads-color-text-subtle"],
    fontWeight: vars["--ads-font-weight-medium"],
  },
  nowText: {
    flex: "1 1 auto",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: vars["--ads-color-text"],
  },
  visuallyHidden: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    borderWidth: 0,
  },

  /* Tones ------------------------------------------------------------------ */
  toneDone: { color: vars["--ads-color-success-text"] },
  toneActive: { color: vars["--ads-color-accent"] },
  toneWaiting: { color: vars["--ads-color-warning-text"] },
  toneAttention: { color: vars["--ads-color-danger-text"] },
  toneIdle: { color: vars["--ads-color-text-subtle"] },
  toneSkipped: { color: vars["--ads-color-text-subtle"] },
  icon: { flex: "0 0 auto", width: 14, height: 14 },

  /* Panel ------------------------------------------------------------------ */
  panel: { display: "flex", flexDirection: "column", gap: vars["--ads-space-16"], minWidth: 0 },
  panelHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: vars["--ads-space-8"],
  },
  panelTitle: {
    margin: 0,
    fontSize: vars["--ads-font-size-body"],
    lineHeight: vars["--ads-line-height-normal"],
    fontWeight: vars["--ads-font-weight-medium"],
    color: vars["--ads-color-text"],
  },
  facts: {
    display: "grid",
    gridTemplateColumns: "max-content minmax(0, 1fr)",
    columnGap: vars["--ads-space-12"],
    rowGap: vars["--ads-space-4"],
    margin: 0,
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
  },
  factLabel: { color: vars["--ads-color-text-muted"] },
  factValue: { margin: 0, minWidth: 0, color: vars["--ads-color-text"], overflowWrap: "anywhere" },
  list: { display: "flex", flexDirection: "column", gap: vars["--ads-space-4"], margin: 0, padding: 0, listStyle: "none" },
  actions: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: vars["--ads-space-8"] },
  notice: {
    margin: 0,
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
    color: vars["--ads-color-text-muted"],
  },
  error: {
    margin: 0,
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
    color: vars["--ads-color-danger-text"],
  },
  section: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-12"],
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: vars["--ads-color-border"],
    paddingTop: vars["--ads-space-16"],
  },

  /* Stage card ------------------------------------------------------------- */
  stage: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-8"],
    borderBottomWidth: 1,
    borderBottomStyle: { default: "solid", ":last-of-type": "none" },
    borderBottomColor: vars["--ads-color-border-subtle"],
  },
  stageHeader: {
    width: "100%",
    minWidth: 0,
    justifyContent: "flex-start",
    gap: vars["--ads-space-8"],
    paddingInline: 0,
    textAlign: "start",
  },
  stageTitle: { flex: "1 1 auto", minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  stageMeta: { flex: "0 0 auto", color: vars["--ads-color-text-muted"], fontSize: vars["--ads-font-size-caption"] },
  stageBody: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-8"],
    paddingInlineStart: vars["--ads-space-24"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
    color: vars["--ads-color-text"],
  },
  quote: {
    margin: 0,
    paddingInlineStart: vars["--ads-space-8"],
    borderInlineStartWidth: 2,
    borderInlineStartStyle: "solid",
    borderInlineStartColor: vars["--ads-color-border"],
    color: vars["--ads-color-text-muted"],
    whiteSpace: "pre-wrap",
  },
  subheading: {
    margin: 0,
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-medium"],
    color: vars["--ads-color-text-muted"],
  },

  /* Evidence --------------------------------------------------------------- */
  evidence: {
    display: "flex",
    alignItems: "baseline",
    gap: vars["--ads-space-8"],
    minWidth: 0,
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
  },
  evidenceSource: {
    flex: "0 0 auto",
    display: "inline-flex",
    alignItems: "center",
    gap: vars["--ads-space-4"],
    whiteSpace: "nowrap",
  },
  evidenceLabel: { minWidth: 0, overflowWrap: "anywhere" },
  mono: { fontFamily: vars["--ads-font-mono"] },

  /* Sign-off card ---------------------------------------------------------- */
  signOff: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-8"],
    paddingInline: vars["--ads-space-12"],
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: vars["--ads-color-warning-border"],
    borderRadius: vars["--ads-radius-panel"],
    backgroundColor: vars["--ads-color-warning-soft"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
    color: vars["--ads-color-text"],
  },
  signOffTitle: {
    display: "flex",
    alignItems: "center",
    gap: vars["--ads-space-4"],
    margin: 0,
    fontSize: vars["--ads-font-size-body"],
    fontWeight: vars["--ads-font-weight-medium"],
  },

  /* Transcript divider and composer chip ----------------------------------- */
  divider: {
    display: "flex",
    alignItems: "center",
    gap: vars["--ads-space-8"],
    marginBlock: vars["--ads-space-12"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
    color: vars["--ads-color-text-muted"],
  },
  dividerRule: {
    flex: "1 1 auto",
    height: 1,
    backgroundColor: vars["--ads-color-border-subtle"],
  },
  dividerText: { flex: "0 1 auto", minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  chip: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: vars["--ads-space-8"],
    paddingBlock: vars["--ads-space-4"],
    paddingInline: vars["--ads-space-12"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
    color: vars["--ads-color-text-muted"],
  },
  chipLabel: { display: "inline-flex", alignItems: "center", gap: vars["--ads-space-4"], minWidth: 0 },
  switchLabel: { display: "inline-flex", alignItems: "center", gap: vars["--ads-space-4"], cursor: "pointer" },
});
