import * as stylex from "@stylexjs/stylex";
import { focusRing } from "../../ads/recipes/focus-ring";
import { transition } from "../../ads/recipes/transition";
import { vars } from "../../ads/tokens/tokens.stylex";

export const taskRowStyles = stylex.create({
  row: {
    display: "flex",
    alignItems: "center",
    gap: vars["--ads-space-12"],
    cursor: "default",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: vars["--ads-color-border"],
    paddingInline: vars["--ads-space-16"],
    paddingBlock: 10,
    fontSize: vars["--ads-font-size-body"],
    backgroundColor: {
      default: "transparent",
      ":hover": vars["--ads-color-surface-tint"],
      ":focus-visible": vars["--ads-color-surface-tint"],
    },
  },
  selected: { backgroundColor: vars["--ads-color-selection-fill"] },
  foreground: { color: vars["--ads-color-text"] },
  muted: { color: vars["--ads-color-text-muted"] },
  danger: { color: vars["--ads-color-danger-text"] },
  warning: { color: vars["--ads-color-warning-text"] },
  transparent: { color: "transparent" },
  visible: { opacity: 1 },
  hidden: { opacity: 0 },
  sourceIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    width: 20,
    height: 20,
    color: vars["--ads-color-text-muted"],
  },
  icon15: { width: 15, height: 15 },
  key: {
    flexShrink: 0,
    fontFamily: vars["--ads-font-mono"],
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
    color: vars["--ads-color-text-muted"],
  },
  priority: { flexShrink: 0, width: 16, height: 16 },
  title: {
    minWidth: 0,
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: vars["--ads-font-size-body"],
  },
  finished: { color: vars["--ads-color-text-muted"], textDecorationLine: "line-through" },
  inlineParent: {
    display: "inline",
    width: 14,
    height: 14,
    marginInlineEnd: vars["--ads-space-4"],
    color: vars["--ads-color-text-muted"],
  },
  label: {
    display: { default: "none", "@media (min-width: 64rem)": "inline-flex" },
    alignItems: "center",
    gap: vars["--ads-space-4"],
    flexShrink: 0,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: vars["--ads-color-border"],
    borderRadius: vars["--ads-radius-full"],
    paddingInline: vars["--ads-space-8"],
    paddingBlock: 2,
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text-muted"],
  },
  labelDot: { width: 8, height: 8, borderRadius: vars["--ads-radius-full"] },
  hiddenCount: {
    display: { default: "none", "@media (min-width: 64rem)": "inline" },
    flexShrink: 0,
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text-muted"],
  },
  external: {
    display: { default: "none", "@media (min-width: 48rem)": "inline-flex" },
    alignItems: "center",
    gap: vars["--ads-space-4"],
    flexShrink: 0,
    fontSize: vars["--ads-font-size-caption"],
    color: vars["--ads-color-text-muted"],
  },
  link: {
    display: "flex",
    alignItems: "center",
    gap: vars["--ads-space-4"],
    flexShrink: 0,
    borderRadius: vars["--ads-radius-full"],
    paddingInline: vars["--ads-space-8"],
    paddingBlock: 2,
    fontSize: vars["--ads-font-size-caption"],
  },
  linkIcon: { width: 12, height: 12 },
  status: { flexShrink: 0, fontSize: vars["--ads-font-size-caption"] },
  effort: {
    display: { default: "none", "@media (min-width: 40rem)": "inline" },
    width: 24,
    flexShrink: 0,
    textAlign: "right",
    fontSize: vars["--ads-font-size-caption"],
    fontVariantNumeric: "tabular-nums",
    color: vars["--ads-color-text-muted"],
  },
  due: {
    width: "4.5rem",
    flexShrink: 0,
    textAlign: "right",
    fontSize: vars["--ads-font-size-caption"],
  },
  assignee: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 24,
    height: 24,
    flexShrink: 0,
    borderRadius: vars["--ads-radius-full"],
    backgroundColor: vars["--ads-color-surface-tint"],
    fontSize: vars["--ads-font-size-caption"],
    fontWeight: vars["--ads-font-weight-semibold"],
    color: vars["--ads-color-text-muted"],
  },
  sourceStrip: {
    display: "flex",
    alignItems: "center",
    gap: vars["--ads-space-8"],
    flexShrink: 0,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: vars["--ads-color-border"],
    paddingInline: vars["--ads-space-16"],
    paddingBlock: vars["--ads-space-8"],
    fontSize: vars["--ads-font-size-caption"],
  },
  sourceRow: {
    display: "flex",
    alignItems: "center",
    gap: vars["--ads-space-8"],
    fontSize: vars["--ads-font-size-caption"],
  },
  sourceStripError: {
    color: vars["--ads-color-danger-text"],
    backgroundColor: vars["--ads-color-danger-soft"],
    borderBottomColor: vars["--ads-color-danger-border"],
  },
  sourceStripQuiet: {
    color: vars["--ads-color-text-muted"],
    backgroundColor: vars["--ads-color-surface-tint"],
  },
  stripText: { minWidth: 0, flex: 1 },
  stripLabel: { fontWeight: vars["--ads-font-weight-medium"], color: vars["--ads-color-text"] },
  emptyFull: { height: "100%" },
  summaryList: {
    display: "flex",
    flexDirection: "column",
    gap: vars["--ads-space-8"],
    marginBottom: vars["--ads-space-12"],
    textAlign: "left",
    fontSize: vars["--ads-font-size-body"],
  },
  summaryItem: { display: "flex", gap: vars["--ads-space-8"] },
  summarySource: {
    width: "3.5rem",
    flexShrink: 0,
    fontWeight: vars["--ads-font-weight-medium"],
    color: vars["--ads-color-text"],
  },
  summaryDetail: { color: vars["--ads-color-text-muted"] },
  summaryHeadline: { color: vars["--ads-color-text"] },
  emptyActions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: vars["--ads-space-8"],
  },
  spin: {
    animationName: stylex.keyframes({
      from: { transform: "rotate(0deg)" },
      to: { transform: "rotate(360deg)" },
    }),
    animationDuration: "1s",
    animationPlayState: {
      default: "running",
      "@media (prefers-reduced-motion: reduce)": "paused",
    },
    animationIterationCount: "infinite",
    animationTimingFunction: "linear",
  },
  buttonIcon: { width: 14, height: 14 },
  filterTrigger: {
    height: 32,
    gap: 6,
    paddingInline: 10,
    fontSize: vars["--ads-font-size-caption"],
    lineHeight: vars["--ads-line-height-normal"],
  },
  filterActive: {
    borderColor: vars["--ads-color-border"],
    backgroundColor: vars["--ads-color-surface"],
  },
  filterSummary: {
    maxWidth: "7rem",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: vars["--ads-color-text"],
  },
  filterChevron: { width: 14, height: 14, color: vars["--ads-color-text-muted"] },
  filterPopup: { width: "14rem", padding: 0 },
  commandItem: {
    fontSize: vars["--ads-font-size-body"],
    lineHeight: vars["--ads-line-height-normal"],
  },
  commandCheck: { width: 14, height: 14 },
  commandOption: {
    minWidth: 0,
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  optionCount: {
    fontSize: vars["--ads-font-size-caption"],
    fontVariantNumeric: "tabular-nums",
    color: vars["--ads-color-text-muted"],
  },
});

export const taskRowFocus = focusRing.ring;
export const taskRowTransition = transition.colors;
