import * as stylex from "@stylexjs/stylex";
import { vars } from "../ads/tokens/tokens.stylex";

/** Host geometry; surface, focus and motion recipes belong to ADS. */
export const overlayLayout = stylex.create({
  positioner: { isolation: "isolate" },
  dialog: {
    position: "fixed",
    top: "50%",
    left: "50%",
    display: "grid",
    width: "calc(100% - 2rem)",
    maxWidth: "28rem",
    translate: "-50% -50%",
    gap: vars.space24,
    padding: vars.space24,
    fontSize: vars.fontSizeBody,
    outlineStyle: "none",
  },
  close: { position: "absolute", top: vars.space16, right: vars.space16 },
  header: { display: "flex", flexDirection: "column", gap: vars.space8 },
  footer: {
    display: "flex",
    flexDirection: { default: "column-reverse", "@media (min-width: 640px)": "row" },
    justifyContent: { default: "normal", "@media (min-width: 640px)": "flex-end" },
    gap: vars.space8,
  },
  description: { fontSize: vars.fontSizeBody, color: vars.colorTextMuted },
  popover: {
    display: "flex",
    width: "18rem",
    transformOrigin: "var(--transform-origin)",
    flexDirection: "column",
    gap: vars.space16,
    padding: vars.space16,
    fontSize: vars.fontSizeBody,
    outlineStyle: "none",
  },
  popoverHeader: { display: "flex", flexDirection: "column", gap: vars.space4, fontSize: vars.fontSizeBody },
  muted: { color: vars.colorTextMuted },
  submenuArrow: { marginInlineStart: "auto" },
  menuIndicator: { pointerEvents: "none", position: "absolute", right: vars.space8 },
  menuLabel: { minWidth: 0, flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  selectArrow: { pointerEvents: "none", width: vars.space16, height: vars.space16, color: vars.colorTextMuted },
  selectList: { width: "100%", minWidth: 0, padding: vars.space4 },
  selectLabel: { display: "flex", minWidth: 0, flex: 1, gap: vars.space8, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  selectIndicator: { pointerEvents: "none", position: "absolute", right: vars.space8, display: "flex", width: vars.space16, height: vars.space16, alignItems: "center", justifyContent: "center" },
  decorative: { pointerEvents: "none" },
  tableViewport: { position: "relative", width: "100%", overflowX: "auto", "--atelier-table-cell-padding-block": vars.space8 },
  keyGroup: { display: "inline-flex", alignItems: "center", gap: vars.space4, whiteSpace: "nowrap" },
});
